### ISSUE TITLE
Wrong mode string in v1.71 tiffio.c -> findTiffCompression()

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DanBloomberg/leptonica#103]
```
What steps will reproduce the problem?
1. Download liblept v1.71 code
2. Compile for Windows (I used VS2013)
3. Try to call pixRead() on a TIFF file

What is the expected output? What do you see instead?
Expected TIFF file to load and PIX to be created. Instead, TIFF fails to load 
because the call in findTiffCompression() to fopenTiff is passing "fb" instead 
of "rb".

What version of the product are you using? On what operating system?
v1.71, Windows, VS2013

Please provide any additional information below.


```

Original issue reported on code.google.com by `dcree...@gmail.com` on 20 Aug 2014 at 3:37

**Comment by DanBloomberg** [comment]
fopenTiff() is passing 'r' in 1.73.  Does that work?

**Comment by egorpugin** [comment]
fopen() for reading on any binary file should use only 'rb' option, not 'r'.
On windows you receive problems when '\n' became '\r\n' even in binary data.

**Comment by egorpugin** [comment]
But if the call goes to tiff library, 'r' should be enough as it uses other meaning for 'b'.
http://linux.die.net/man/3/tiffclientopen

**Comment by DanBloomberg** [comment]
We are now opening findTiffCompression() with 'r', so this should be ok.
