### ISSUE TITLE
pdf restriction

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DanBloomberg/leptonica#111]
```
What steps will reproduce the problem?
1. run ./pdfiotest from prog directory
2. check document restriction setting in acrobat reader (e.g. in fourimages.pdf

What is the expected output? What do you see instead?
* There are set 2 restrictions: "Page Extraction" and "Document Assembly" to 
"Not Allowed"
How to generate pdf without this restriction?

What version of the product are you using? On what operating system?
leptonica 1.72 on openSUSE 13.2 64bit




```

Original issue reported on code.google.com by `zde...@gmail.com` on 22 Jul 2015 at 9:03

Attachments:
- [fourimages.pdf](https://storage.googleapis.com/google-code-attachments/leptonica/issue-111/comment-0/fourimages.pdf)
- [DocumentRestrictions.png](https://storage.googleapis.com/google-code-attachments/leptonica/issue-111/comment-0/DocumentRestrictions.png)

**Comment by DanBloomberg** [comment]
Are you still having a problem running pdfiotest with 1.73?

**Comment by amitdo** [comment]
>Original issue reported on code.google.com by zde...@gmail.com on 22 Jul 2015 at 9:03

The OP is probably @zdenop

**Comment by DanBloomberg** [comment]
I'll have another look at this.

**Comment by DanBloomberg** [comment]
These are vanilla pdf files.  No security features have been explicitly enabled.  There is nothing in these pdf files that is meant to restrict any operation on them.  No passwords, nothing.

It may be the case that Adobe treats these two restrictions as defaults on their software, and that commands need to be placed in the pdf file to avoid Adobe's default restrictions.  I was unable to find information about any such default restrictions.

Please let me know if you can find the source of these restrictions.

**Comment by amitdo** [comment]
> > Original issue reported on code.google.com by [zde...@gmail.com](mailto:zde...@gmail.com) on 22 Jul 2015 at 9:03
> 
> The OP is probably @zdenop


@zdenop, was it you who opened this issue 5 years ago?

The 2 attached files are no longer available.

Is this issue still exist with version 1.80 ?

**Comment by zdenop** [comment]
Here is pdf generated with leptonica 1.80 and Document properties from Acrobat reader XI (11.0.23)
[fourimages.pdf](https://github.com/DanBloomberg/leptonica/files/5034985/fourimages.pdf)

![acrobat_doc_properties](https://user-images.githubusercontent.com/574156/89535939-6a632d80-d7f7-11ea-85fb-192d15642040.png)

Interesting is that if I check it with PDF Architect 7 I got different information about restrictions:
![pdf_achitect-doc_properties](https://user-images.githubusercontent.com/574156/89536182-cded5b00-d7f7-11ea-9b36-069f79d57f10.png)

Maybe it is Acrobat Reader issue?

**Comment by amitdo** [comment]
https://stackoverflow.com/questions/51418933/pdfwriter-allow-assembly-does-not-change-the-value-for-document-assembly-in-th

**Comment by zdenop** [comment]
@amitdo : thanks for details.  @DanBloomberg : IMO issue can be closed.

**Comment by DanBloomberg** [comment]
happy to oblige
