### ISSUE TITLE
Add install targets to cmake

### ISSUE THREAD

**Issue by egorpugin** [DanBloomberg/leptonica#117]

**Comment by DanBloomberg** [comment]
There are over 200 targets (programs) in prog.  It is not realistic to install most of these.

For debian releases, we have only installed 13, which are listed in prog/makefile.static (line 272ff):

       convertfilestopdf convertfilestops convertformat \
       convertsegfilestopdf convertsegfilestops \
       converttopdf converttops fileinfo \
       printimage printsplitimage printtiff \
       splitimage2pdf xtractprotos
