### ISSUE TITLE
Remove duplicated xtractprotos.c from src/ and prog/

### ISSUE THREAD

**Issue by egorpugin** [DanBloomberg/leptonica#119]

**Comment by DanBloomberg** [comment]
I believe it's ok to remove xtractprotos.c from src/.  Leave the copy in
prog/

**Comment by egorpugin** [comment]
There is also same endiantest.c in root and in src/ dirs.

**Comment by DanBloomberg** [comment]
endiantest.c has now been removed throughout.

xtractprotos.c has been removed from src, as suggested.
