### ISSUE TITLE
Inconsistent handling of temporary files / filenames

### ISSUE THREAD

**Issue by stweil** [DanBloomberg/leptonica#123]
The current version of Leptonica provides and uses several functions for temporary files, directories and filenames: genTempFilename, makeTempDirname, fopenWriteWinTempfile.

Some of them make assumptions about existence of a `/tmp` directory. That will usually fail on hosts like Windows.

**Comment by DanBloomberg** [comment]
Stefan, all these functions call genPathname, which uses the windows "/tmp"
directory if necessary.

If "/tmp" is specified as an argument, the translation happens.

I just noticed that the documentation in genTempFilename() is wrong
(unchanged from 1.72).  Item 7 should read:

 *      (7) When @dir is /tmp or a subdirectory of /tmp, genPathname()
 *          does a name translation for '/tmp' on windows:
 *            /tmp ==> <Temp>
 *          where <Temp> is a path on windows determined by GenTempPath().

**Comment by DanBloomberg** [comment]
Handling is believed to be consistent in use of a /tmp (or windows equivalent) directory.
