### ISSUE TITLE
configure file missing from latest commits

### ISSUE THREAD

**Issue by jakehuesman** [DanBloomberg/leptonica#125]
Following your readme.html for installing leptonica, it looks like your configure file got deleted somewhere in your latest commits. It's available in the commits from a few weeks ago.

**Comment by egorpugin** [comment]
> README  (1.73: 25 Jan 2016)
> gunzip leptonica-1.73.tar.gz
> tar -xvf leptonica-1.73.tar

Did you download release file from here https://github.com/DanBloomberg/leptonica/releases/tag/v1.73 ?
If not, master is always considered as unstable and you should download release tarball.

**Comment by DanBloomberg** [comment]
I'll modify the README to make that clear.

  -- Dan

**Comment by jakehuesman** [comment]
Completely missed the release, thanks! The note in the README should resolve any future confusion.
