### ISSUE TITLE
src/freetype.h and src/freetype.c are unused

### ISSUE THREAD

**Issue by egorpugin** [DanBloomberg/leptonica#139]
These two files are unused in any build system. So, they should be removed. (They can be restored later from git history.)

I'd like to do this change to apply globbing expressions for sources in cmake build. Now we do not have duplicated xtractprotos and endiantest files, so sources list https://github.com/DanBloomberg/leptonica/blob/master/src/CMakeLists.txt#L11 can be replaced with:
`file(GLOB hdr "*.h")
file(GLOB src "*.c")`

This means that future file additions or removals will be handled automatically in cmake.

**Comment by DanBloomberg** [comment]
Makes sense to me.  Significant simplification in CMakeLists.txt.  Go for it.

**Comment by egorpugin** [comment]
Done. See f42f7b4fb80

**Comment by DanBloomberg** [comment]
Thanks!

For some reason the win32 build failed right at the cloning stage on appveyor.  How do you get it to re-run?

**Comment by egorpugin** [comment]
Don't know actually. You should somehow restart the build or just wait for another commit. Win64 is ok. Win32 failed because of some appveyor failure.

**Comment by DanBloomberg** [comment]
I pushed a small commit -- give appveyor another chance  :-)
