### ISSUE TITLE
Not able to compile leptonica due to lack of src/xtractprotos.c files

### ISSUE THREAD

**Issue by gchehab** [DanBloomberg/leptonica#179]
Dan,

I am not being able to compile leptonica since the removal of src/xtractprotos.c  from source (due to issue #119). 

make gives the follwoing output:
make[2]: *** No rule to make target `xtractprotos.o', needed by `xtractprotos'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CC     zlibmemstub.lo
make[2]: Leaving directory `/tmp/src/leptonica/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/src/leptonica'
make: *** [all] Error 2

Putting the file back from ./prog/xtractprotos.c fixed the error. Perhaps, to avoid the dupplication of the file, it should be enough to adapt the Makefile to compile from ../prog/xtractprotos.c

regards,
Guilherme

**Comment by DanBloomberg** [comment]
Guilherme,

Thank you for reporting this.   I expect we'll have a fix for this soon.

The other two ways of building the library (static makefile and cmake) should be working properly.

  -- Dan

**Comment by chewi** [comment]
See #181.

P.S. @DanBloomberg, you can ping people on GitHub just like this!
