### ISSUE TITLE
Question: book fold detection

### ISSUE THREAD

**Issue by pullmoll** [DanBloomberg/leptonica#180]
I have an issue to solve: detection of a book fold (center seam) in a scanned image.

My initial version uses pixExtractTextLines() and *fills* two boxes l_half and r_half, where each box returned from the function is:
+ combined as a union with l_half, if its right edge is left of width/2
+ combined as a union with r_half, if its left edge is right of width/2

If finally the distance between the right edge of l_half and the left edge of r_half is `>= 0.075` of the pixs width (arbitrary value 7.5%), the image is split at the center between the union boxes.

This works reasonably well for deskewed images where text is on both pages and where the layout is sufficiently symmetric. It fails, for obvious reasons, if one of the pages is empty or contains nothing which is identifiable as text lines.

My question or issue is this: Is there a better way, perhaps independent of first finding text lines, to decide if an image is (probably) a scan of a double page and where it could be split? Perhaps using background brightness (or rather darkness) near the fold?

Any hints are appreciated.

**Comment by DanBloomberg** [comment]
This is an interesting problem.  I will send you by Friday one approach
that you can experiment with.

  -- Dan

**Comment by pullmoll** [comment]
Thank you in advance, Dan!

FWIW I know that [Scantailor](http://github.com/scantailor/scantailor) has an implementation of such an algorithm and is even able to detect the book fold in a skewed image. Unfortunately Scantailor is not based on Leptonica and I have not yet identified the code which actually detects the book fold seam.

This is an [example image](https://cloud.githubusercontent.com/assets/10061347/14691959/697aa484-0754-11e6-9c4a-4fa8e00a0ab1.png) and this is Scantailor's [split preview](https://cloud.githubusercontent.com/assets/10061347/14691910/27cd7b38-0754-11e6-8490-daa9b87198b5.png)... you can see where I want to go :smiley:

**Comment by DanBloomberg** [comment]
Jürgen,

I wrote a little program that shows one way to do this, and pushed it to
the master.

I ran it on your example at 45 ppi, which is very low, and it worked well.
 (It also took only about 10 ms, if you skip the debugging).

Let me know how it works on images of interest to you.

  -- Dan

On Wed, Apr 20, 2016 at 3:06 PM, Jürgen Buchmüller <notifications@github.com

**Comment by pullmoll** [comment]
Hey, you're quick!

I'm looking at the code and willl try your approach in my app to see how it does with a (rather large) number of samples I have here.

Thank you very much.

**Comment by DanBloomberg** [comment]
I suggest you also run the algorithm at 150 ppi, for comparison.  Slower
but likely more accurate.

The window size doesn't matter much, but you might increase it to 7 or 9
for 150 ppi.

On Wed, Apr 20, 2016 at 6:45 PM, Jürgen Buchmüller <notifications@github.com

**Comment by pullmoll** [comment]
Perfect!
It works in my app and is definitely fast enough, especially compared to my approach.
The entire process of finding the skew, deskewing, finding the binding and splitting into two pages takes 1700ms here with the example picture at 150 dpi. And this even includes the conversion from and to QImage - it's a Qt5 application.

I can definitely close this issue.
Thank you again.
