### ISSUE TITLE
Out of bounds threshold in pixMaskedThreshOnBackgroundNorm

### ISSUE THREAD

**Issue by jli416** [DanBloomberg/leptonica#190]
In pixMaskedThreshOnBackgroundNorm() it is possible to generate a "Error in pixThresholdToBinary: 8 bpp thresh not in {0-256}" at line 380 if the Otsu threshold returned in val from line 366 is large enough.

Should val + 30 on line 366 be clipped to <= 255?

    pixOtsuAdaptiveThreshold(pixs, w, h, 0, 0, scorefract, &pixt3, NULL);
    if (pixt3 && pthresh) {
        pixGetPixel(pixt3, 0, 0, &val);
        *pthresh = val;
    }
    pixDestroy(&pixt3);
        /* Threshold the background normalized images differentially,
         * using a high value correlated with the background normalization
         * for the part of the image under the mask (i.e., near the
         * darker, thicker foreground), and a value that depends on the Otsu
         * threshold for the rest of the image.  This gives a solid
         * (high) thresholding for the foreground parts of the image,
         * while allowing the background and light foreground to be
         * reasonably well cleaned using a threshold adapted to the
         * input image. */
    pixd = pixThresholdToBinary(pixn, val + 30);  /* for bg and light fg */`

**Comment by DanBloomberg** [comment]
Thank you for reporting this.
I agree it should be clipped (to 256).  The patch is in; closing.
