### ISSUE TITLE
Include dependent Libraries

### ISSUE THREAD

**Issue by peirick** [DanBloomberg/leptonica#192]
For builds on windows its difficult to get all dependent libraries like libJpeg, libPng, libTiff, zlib. So maybe we can include the basic files of these libraries in this repository. The FreeImage library is already doing this. This should be done only as long as there is no nice way to manage this dependencies for windows builds.

**Comment by DanBloomberg** [comment]
Tobias,

Stubs are provided for ALL functions in the image I/O files.  If the
libraries are not present, autobuild and cmake handle this, and the stubs
allow the library to build.

You can also manually force the stubs to be linked by modifying environ.h
and building the library with the static makefile.

**Comment by peirick** [comment]
Hi Dan,
the problem I try to address is, that it is complicated to build leptonica on windows, that supports more than bmp files. You have to search for the current versions of the libraries and get them compiling and linking with leptonica. 
So It would be nice if you can run cmake on windows and it also generates the project files for libjpeg, libtiff, libzip. And you don't have to search the internet for current source code of that libraries.

**Comment by DanBloomberg** [comment]
Tobias,

I think you're suggesting storing source files here, and having cmake
compile them as well as leptonica.  I don't know if it makes sense (really,
I have no idea).  Hadn't heard of it being done at the github level.

Those libraries are fundamental to any imaging application, whether it uses
leptonica or not -- there must be a more general way to get them.
Certainly we don't want to end up here:
      https://en.wikipedia.org/wiki/Dependency_hell
where leptonica has to worry about the version details of these libraries
(I ran into a problem with giblib, which you can read about at the
beginning of gifio.c.  It can be a real mess.)

As an alternative, is there a way to run a "script" file that will download
the basic I/O libraries and zlib to a windows machine, generate the project
files, and run them apart from leptonica?

**Comment by egorpugin** [comment]
Storing other libs' sources in lept repo is not a right way.
But I have one possible solution. I'll check it and write it here.

**Comment by peirick** [comment]
We could store the other libs' sources in another repository and load them, if needed, when cmake generates the solution.

**Comment by egorpugin** [comment]
@peirick I've sent a PR. At the moment you try to build leptonica from my fork https://github.com/egorpugin/leptonica to see if workflow is smooth enough.
1. Clone it.
2. Download https://cppan.org/client/cppan-0.1.3-win32-client.zip Make sure you have vc2015 redist installed. 
3. Run cppan.exe from leptonica dir
4. Run cmake as usual.

**Comment by egorpugin** [comment]
Now you can try to build it on Windows using this main repository.

**Comment by peirick** [comment]
I have never heard of cppan before. It looks promising. We have to see what the future brings. Finally I did get it working. I did the following: 

Download GIT, CMAKE and CPPAN add them to your PATH.

```
git clone --single-branch https://github.com/DanBloomberg/leptonica.git  --branch="master" "leptonica"
cd leptonica
cppan.exe
mkdir build
cd build
cmake ..
```

Open leptonica.sln and compile.


The following define for for Windows and tiflib should be set: "TIF_PLATFORM_CONSOLE". Otherwise you could get an annoying, blocking, messagebox with some special TIF-images. An other way to solve this problem could be to use TIFFSetWarningHandler and TIFFSetErrorHandler.

**Comment by egorpugin** [comment]
I've added TIF_PLATFORM_CONSOLE with commit c5ed67d

**Comment by egorpugin** [comment]
Ok, I've also updated the client of CPPAN. Please, consider downloading the latest version from https://cppan.org/client/

Later I'll try to add CPPAN support for tesseract.
