### ISSUE TITLE
(Re)move conv2doxy.c

### ISSUE THREAD

**Issue by egorpugin** [DanBloomberg/leptonica#194]
I propose to remove conv2doxy.c file or move it from root dir to some other (tools/conv2doxy.c?).

If this tool was supposed to run once, then it's not needed in leptonica and can be stored in some other repo (author's repo). If new comments will be written in Doxy style from the beginning, probably it's not needed anymore.

If this tool must be applied to each release, it can stay and be moved to its dir from root.

In any case the tool can be found in git history.

pinging @pullmoll as author

**Comment by pullmoll** [comment]
Yes, `conv2doxy.c` can be removed or moved elsewhere. It was to be used only once.

**Comment by DanBloomberg** [comment]
Agreed -- it did the job.

**Comment by egorpugin** [comment]
Commited a936371
