### ISSUE TITLE
Is free() provided for leptonica? (for the sake of memory clear in Java)

### ISSUE THREAD

**Issue by johnny5550822** [DanBloomberg/leptonica#195]
Hi, 

I am using lept4J to use leptonica in Java basis. I am trying to write a pix object into a BufferedImage. There is a function in Lept4JUtils that can convert pix to buffered image, called convertPixToImage: https://github.com/nguyenq/lept4j/blob/master/src/main/java/net/sourceforge/lept4j/util/LeptUtils.java

In that function, pixWriteMem() is called. However, in the original leptonica C code, I think we need to call free(data) explicitly to free up the memory assigned to data. Is there any function that I can call to free up memory of a pointer, so that I can call it in java?

**Something like this to use pixWriteMem() with proper freeing of memory in C**

```
void ImageData::SetPixInternal(Pix* pix, GenericVector<char>* image_data) {
  l_uint8* data;
  size_t size;
  pixWriteMem(&data, &size, pix, IFF_PNG);
  pixDestroy(&pix);
  image_data->init_to_size(size, 0);
  memcpy(&(*image_data)[0], data, size);
  free(data);
}
```

I spend 5 days to figure this out, but still cannot find the solution. Thanks in advance!

**Comment by egorpugin** [comment]
pixDestroy?
Or maybe you need to send a PR to lept4j with your free() implementation?

**Comment by DanBloomberg** [comment]
It's a bit strange to have a function that destroys an input pix, but the function that calls it still has a (now invalid) ptr to the pix after this returns..  Certainly wouldn't do that in C/C++

To free data, use lept_free().  This works with DLLs on windows.

Agree with Egor -- this is an issue for lept4j, not leptonica (which is C based).

**Comment by johnny5550822** [comment]
@DanBloomberg  lept_free() does not work for the "data" in pixWriteMem in Java in Ubuntu. So, there is no solution for ubuntu except changing code in lept4j? But, I thought the leptonica(C-based) need to add the free() function so that lept4j can bind to it (the lept4 author is using JNA). But, I do agree it is strange to destroy the pix, but there is in leptonica. http://search.cpan.org/dist/Image-Leptonica/lib/Image/Leptonica/Func/pix1.pm

@egorpugin the "data" is not a pix, rather, it is the image array that is converted from the pix and holds some memory. That's what I think.

**Comment by johnny5550822** [comment]
According to http://stackoverflow.com/questions/38337195/is-there-any-way-that-i-can-free-up-memory-in-the-java-code-that-is-generated-to/38337278?noredirect=1#comment64115791_38337278,

The possible and straightforward solution is to fix it in the C code? Like a simple function that allow free () and that C functionality to Java to call via JNI.

**Comment by johnny5550822** [comment]
Anyone can help this?

**Comment by amitdo** [comment]
It seems that this issue has been solved.
 https://github.com/nguyenq/lept4j/issues/2#issuecomment-249218044
https://github.com/nguyenq/lept4j/commit/5deeb052c2c78e97612a37cabec6254c9a7a8e14

**Comment by DanBloomberg** [comment]
Yes.  Thank you Amit.
