### ISSUE TITLE
Github source installation issues - make file, or instructions, incorrect ?

### ISSUE THREAD

**Issue by Wikinaut** [DanBloomberg/leptonica#197]
My use case is Leptonica for Tesseract with Debian 8 Jessie, but I cannot get Leptonica compiled from the github source with the current instructions.

> Remark:
> When compiling from 1.72 http://www.leptonica.com/source/leptonica-1.72.tar.gz or 1.73 http://www.leptonica.com/source/leptonica-1.73.tar.gz , everything (Leptonica, Tesseract) compiles fine and works, so apparently there are no dependencies missing.

#### Leptonica compilatopn and installation issue

However, when I try to compile from 
``` 
git clone https://github.com/DanBloomberg/leptonica.git
cd leptonica
```
and when following the instructions in http://www.leptonica.com/source/README.html

```
./make-for-local
cd leptonica/src
make 
sudo cp -i ../lib/nodebug/liblept* /usr/local/lib
```
or
```
./make-for-local
cd leptonica/src
make  make SHARED=yes shared
sudo cp -i ../lib/shared/liblept* /usr/local/lib
```

and copying the resulting *.so or *.a files to /usr/local/lib does not allow to configure Tesseract: because "leptonica is missing".

Apparently the reason is, that Tesseract requires ```/usr/local/lib/liblept.la```. But this not created in the current leptonica ```make``` file. Please can you assist/fix this ?

**Comment by zdenop** [comment]
Why you do not follow [README](https://github.com/DanBloomberg/leptonica/blob/master/README.html)  from git repository when you build git repository?

**Comment by Wikinaut** [comment]
```
./autobuild
./configure
make
```
okay, but then
```
sudo make install
Making install in src
make[1]: Entering directory '/work/usr/local/src/leptonica/src'
make[1]: *** No rule to make target 'install'.  Schluss.
make[1]: Leaving directory '/work/usr/local/src/leptonica/src'
Makefile:456: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

**Comment by zdenop** [comment]
I just check it and it works for me (openSUSE 13.2):
```
git clone https://github.com/DanBloomberg/leptonica.git
cd leptonica
./autobuild
./configure
make
sudo make install
```

Check the configure output if there is any useful information.

**Comment by Wikinaut** [comment]
I deleted the installation directory and made a fresh clone. Works now.

How is the current (github master) leptonica telling me its version ? Is ```leptonica-1.73``` correct  as in the following

tesseract --version says

```
tesseract 3.05.00dev
 leptonica-1.73
  libjpeg 6b (libjpeg-turbo 1.3.1) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8
```


.... or shouldn't it better show something like ```leptonica-1.74-dev``` ? (suggestion)

**Comment by Wikinaut** [comment]
Closing, because the problem has been solved.
