### ISSUE TITLE
best way to reuse raw gray pixel data?

### ISSUE THREAD

**Issue by radioman** [DanBloomberg/leptonica#198]
i have raw 8bit data, no padding, whats the fastest way to reuse this buffer if possible, or do i need to convert it to 4byte alignment for leptonica, is it really necessary?

..Suppose data is 10MB, and performance is time critical, is it possible to use it for leptonica without expanding it to 40MB? How it suppose to be faster ;/ Or i'm missing something? Thanks.

**Comment by DanBloomberg** [comment]
See pix.h for the formatting of leptonica image data.

The data is always packed, for all bpp (1, 2, 4, 8, 16, 32).  Padding is only used for 32 bit alignment on scanlines.

Byte order is described in pix.h.  You may need to do byte rearrangement within 32 bit words, and if so there are functions that do this efficiently.

Your 10MB of image data (say, 10 million 8 bpp pixels) will remain 10MB of data, plus a tiny extra amount for padding if bpl is not divisible by 4.

  -- Dan

**Comment by radioman** [comment]
Thanks for the insight!

So if the picture width would be multiply of 4 (256, 512, 1024, etc) it's already 'packed' and it should just work, no extra alignment needed?

**Comment by DanBloomberg** [comment]
yes.  But you may need to rearrange the 8 bit pixels in each 32-bit word (as per pix.h)

**Comment by radioman** [comment]
excellent!, I've done some testing and it works, not sure but why would i need that 'arrangement'?

**Comment by DanBloomberg** [comment]
see pix.h
