### ISSUE TITLE
Configure script not executable

### ISSUE THREAD

**Issue by mlissner** [DanBloomberg/leptonica#200]
I just downloaded the latest release of Leptonica from Github, and attempted to install it with the usual incantation to `./configure`. That didn't work because `configure` wasn't executable. 

So, I `chmod`'ed it, and was able to proceed. I don't often install programs this way -- in fact it's very seldom, so this kind of catch can definitely slow me down.

**Comment by DanBloomberg** [comment]
Mike, thanks for the report.  I assume this is for 1.72.

We'll try to make sure it's executable for the next autotools release, whenever that is.

**Comment by DanBloomberg** [comment]
oops, I mean 1.73   :-)

**Comment by DanBloomberg** [comment]
You can also get the release from leptonica.org, and configure should be executable there.

**Comment by mlissner** [comment]
Yes, for 1.73. Thanks for your hard work.

**Comment by zdenop** [comment]
This issue could be closed.

**Comment by DanBloomberg** [comment]
yes, thank you.
