### ISSUE TITLE
GIF extract fails if /tmp directory does not exist on root of executing drive in Windows

### ISSUE THREAD

**Issue by LeeBear35** [DanBloomberg/leptonica#205]
When extracting a GIF in windows the extract fails with:
Tesseract Open Source OCR Engine v3.05.00dev with Leptonica
Warning in pixReadMemGif: writing to a temp file, not directly to memory
Error in fopenWriteStream: stream not opened
Error in l_binaryWrite: stream not opened
Error in fopenReadStream: file not found
Error in pixRead: image file not found: /tmp/847554_6112_mem.gif
Error in pixReadMemGif: pix not read
Error in pixReadMem: gif: no pix returned
Error during processing.

If you create a tmp directory on the drive where you are running the application it will work.

**Comment by DanBloomberg** [comment]
Thanks for the notification.  My understanding is that windows has a "temp" directory, which is not "/tmp", and the functions in utils.c can find it.  I don't know why this write function failed.

Unfortunately, the GIF library doesn't allow writing a GIF compressed image to  a memory buffer; hence the temp file when Windows (but not linux) attempts to do this.  (Linux uses some gnu extensions for redirecting output to a file stream to memory.)

  -- Dan

**Comment by LeeBear35** [comment]
In looking through the history the utils.c routine went through an update that appears to have broken the functionality of swapping the /tmp for the windows temporary directory.


Leland Carpenter ♦ Sr. Software Engineer ♦ PRGX USA, Inc.
4904 Hickory Way ♦ Johnsburg, IL 60051-8967
O: 815.307.7634 ♦ Lee.Carpenter@prgx.com<mailto:Lee.Carpenter@prgx.com>
[cid:image001.jpg@01D2035F.5B84EC20]

**Comment by peirick** [comment]
So we should go and fix libgif :-) 
I've had a quick look at the current version of the libra. There are two functions DGifOpen and EGifOpen. Maybe they can be uses instead? I will have closer a look at it

**Comment by DanBloomberg** [comment]
Leland, can you pinpoint that change for me?

Peirick, yes, you are joking.  :-)

**Comment by peirick** [comment]
I've added an in memory decoding of gif using the function "DGifOpen". Thatone won't use the workaround with that temp file. Se merge request: https://github.com/DanBloomberg/leptonica/pull/206.

**Comment by DanBloomberg** [comment]
Thank you, peirick.  I've made some small modifications and submitted your change.

**Comment by DanBloomberg** [comment]
We've closed #206, and I'll close this as well.  If there are still problems with gif reading on Windows, please reopen it.

peririck: if you want to experiment with EGifOpen() for writing a pix to memory as an encoded gif image, be my guest  :-)
