### ISSUE TITLE
Analyse Leptonica source code with Coverity Scan

### ISSUE THREAD

**Issue by stweil** [DanBloomberg/leptonica#208]
The Coverity Scan static analysis is very helpful for improving code quality. It is free for free software projects, and so [many major projects](https://scan.coverity.com/projects), but also a lot of small projects, use it. IMHO it would be good to use it for Leptonica, too. @DanBloomberg, if you agree, I can [add Leptonica](https://scan.coverity.com/projects/new) as a new project to Coverity Scan. I already have some own projects there, and I am member of other projects.

**Comment by DanBloomberg** [comment]
Stefan, thank you, please go ahead and add leptonica as a new Coverity project.

**Comment by stweil** [comment]
Done. We now have to wait until Coverity accepts Leptonica as a free software project. This takes 1-2 business days. Meanwhile Coverity only reports that it has found 859 defects.

**Comment by stweil** [comment]
First scan results are now available, see https://scan.coverity.com/projects/leptonica.

**Comment by DanBloomberg** [comment]
@stweil 

Can this old issue be closed?

**Comment by stweil** [comment]
Yes, sorry – I should have closed it long ago.
