### ISSUE TITLE
Installing leptonica in AIX

### ISSUE THREAD

**Issue by KrishnenduP** [DanBloomberg/leptonica#222]
Hi,
We are trying to install leptonica 1.73 in AIX 7.1 with GCC version 4.8.3.
We are getting following error while running make command:
[impaix1:root:/usr/ocr/leptonica-1.73:] make
make  all-recursive
make[1]: Entering directory '/usr/ocr/leptonica-1.73'
Making all in src
make[2]: Entering directory '/usr/ocr/leptonica-1.73/src'
make -f makefile TARGET= nodebug
make[3]: Entering directory '/usr/ocr/leptonica-1.73/src'
gcc -ansi -D_BSD_SOURCE -DANSI -fPIC -O2  -I./  -DL_BIG_ENDIAN  -c -o ../obj/nodebug/sarray.o sarray.c
sarray.c: In function 'getFilenamesInDirectory':
sarray.c:2283:1: error: unknown type name 'DIR'
DIR            *pdir;
^
sarray.c:2292:10: warning: assignment makes pointer from integer without a cast [enabled by default]
     pdir = opendir(realdir);
          ^
sarray.c:2298:23: warning: assignment makes pointer from integer without a cast [enabled by default]
     while ((pdirentry = readdir(pdir))) {
                       ^
sarray.c:2304:22: error: dereferencing pointer to incomplete type
         if (pdirentry->d_type == DT_DIR)
                      ^
sarray.c:2304:34: error: 'DT_DIR' undeclared (first use in this function)
         if (pdirentry->d_type == DT_DIR)
                                  ^
sarray.c:2304:34: note: each undeclared identifier is reported only once for each function it appears in
sarray.c:2309:25: error: dereferencing pointer to incomplete type
         name = pdirentry->d_name;
                         ^
make[3]: *** [makefile:350: ../obj/nodebug/sarray.o] Error 1
make[3]: Leaving directory '/usr/ocr/leptonica-1.73/src'
make[2]: *** [makefile:244: all] Error 2
make[2]: Leaving directory '/usr/ocr/leptonica-1.73/src'
make[1]: *** [Makefile:466: all-recursive] Error 1
make[1]: Leaving directory '/usr/ocr/leptonica-1.73'
make: *** [Makefile:375: all] Error 2

Please find the attached config log file.
[config.txt](https://github.com/DanBloomberg/leptonica/files/611038/config.txt)

Please let us know how to resolve this.

Thanks,
Krishnendu

**Comment by DanBloomberg** [comment]
I have no experience with AIX.

From your error log, AIX doesn't recognize type DIR, which is defined in dirent.h and is part of the poxix-1-2001 standard.  For example, the man page for readdir (and opendir, etc) says:

CONFORMING TO
       SVr4, 4.3BSD, POSIX.1-2001.

You may want to find out how AIX does directory lookup and patch that file.  (sarray.c is the only file in leptonica that uses it).

**Comment by amitdo** [comment]
https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/com.ibm.aix.files/dirent.h.htm

**Comment by amitdo** [comment]
See Also:
https://www.ibm.com/support/knowledgecenter/en/ssw_aix_71/com.ibm.aix.basetrf1/opendir.htm

**Comment by KrishnenduP** [comment]
This link's doesn't have the full source code of dirnet.h. Can any one tell where the source code can be found for dirnet.h. In my AIX package in "user/include/" the file is there but with out any code.

**Comment by DanBloomberg** [comment]
Krish, can't help you with the AIX include files on your system.  Closing the thread.
