### ISSUE TITLE
Error in pixaGetCount: pixa not defined

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#223]
I am using the latest Leptonica from master (revision 121c644f28d21dbabff00b265f08419e94750492) with tesseract and it produce strange error message (coming from Leptonica) when I tried to OCR tiff image. E.g. 
```
tesseract testing/phototest.tif phototest
Tesseract Open Source OCR Engine v3.05.00dev with Leptonica
Page 1
Error in pixaGetCount: pixa not defined
Error in pixaGetCount: pixa not defined
```
But there expected output is produced... 
Why there is error message (Leptonica version 1.73 does not produce any error message for the same image)?

**Comment by amitdo** [comment]
>Error in pixaGetCount: pixa not defined

>Why there is error message (Leptonica version 1.73 does not produce any error message for the same image)?

The code that triggers this message was added at Leptonica 1.46...
https://github.com/DanBloomberg/leptonica/blame/8a839a254e8d2ed3965ab0ecce7120b05f291993/src/pixabasic.c#L619

The issue comes from Tesseract that calls pixaGetCount() with NULL pixa.

**Comment by zdenop** [comment]
I did not tested it deeply ;-), but:

1. I build the same tesseract code against 1.73 version and there is no message. I build the same tesseract version against master (aka version 1.74) and there is error message.
2. If there is error message I expect something serious is happening. But nothing bad has happened. There is expected output. This will confuse end-users (current version of tesseract hides leptonica warnings, but this error message is there...)

**Comment by DanBloomberg** [comment]
cc'ing Ray on this

The only calls to pixaGetCount() that I could find in a quick search were
in textord/
     imagefind.cpp  -- most likely
     devanagari_processing.cpp

In imagefind.cpp, it is called by ConnCompAndRectangularize(),
    which is called by FindImagePartitions(),
    called by ColumnFinder::ImageBlocks(),
    called by AutoPageSeg() in ccmain/pagesegmain.cpp

Now, the only way we get that error message from this call stack is if
pixConnComp() doesn't generate a pixa of the connected components.  For
that to happen without any other error messages, the input pix must be
empty (i.e., a 1 bpp image with all pixels having a value of 0
(background)).

This function (ConnCompAndRectangularize) should in any event check for
that condition.

  -- Dan

**Comment by DanBloomberg** [comment]
Ray will likely fix the 5.04 version to avoid this error condition and message.

The change between 1.73 and 1.74 behavior is due to some "cleanup" in pixConnCompPixa() that I did for coverity scan errors, which changed the semantics of the return in the case of an empty input pix.  In that case it should return an empty pixa and an empty boxa.  I will restore to 1.73 semantics.

**Comment by DanBloomberg** [comment]
Modified pixConnComp*() to restore 1.73 semantics.
This issue can be closed if someone verifies no more error messages from pixaGetCount()

**Comment by amitdo** [comment]
tesseract 5.0.4 ?

Is this the current internal version?

**Comment by DanBloomberg** [comment]
no, that was a typo.  I believe you are at 3.0.4.

**Comment by amitdo** [comment]
You also have this typo in version-notes.html 

Tesseract versions:
3.04 (not 3.0.4)
3.04.1
4.00 alpha (code in master)

**Comment by DanBloomberg** [comment]
Thanks.  Fixed.

**Comment by zdenop** [comment]
thanks.
