### ISSUE TITLE
compile error with latest release 1.74

### ISSUE THREAD

**Issue by rofl0r** [DanBloomberg/leptonica#226]
```
sel1.c: In function 'create2dIntArray':
sel1.c:536:31: error: expected expression before '/' token
```
the comment used here is apparently not compatible with the option `-ansi` the the makefile.static sets.

**Comment by DanBloomberg** [comment]
thank you for this report.  The bad comment has been fixed.

**Comment by rofl0r** [comment]
i just noticed that it was actually my fault. a previous lepton version required -DANSI to build, so i copied a couple of directives from the makefile, including -ansi, into my externally-set CC variable. however the actual version of the makefile doesn't actually use -ansi anymore. thanks anyway!
