### ISSUE TITLE
Leptonica 1.74+ fail to work correctly sometimes on big-endian arches

### ISSUE THREAD

**Issue by AdamWill** [DanBloomberg/leptonica#232]
I was running the test suite for [os-autoinst](https://github.com/os-autoinst/os-autoinst) as part of a Fedora package build, and noticed that its OCR test was failing on ppc64 (big-endian) but not ppc64le (little-endian). The test suite had also worked fine about a month ago.

os-autoinst uses [tesseract](https://github.com/tesseract-ocr/tesseract) for OCR, which in turn uses Leptonica. I noticed that when the test passed, it had used Leptonica 1.73, but when it failed, it used Leptonica 1.74.1.

So I've isolated the bit of the test that failed to this image:

![ocr](https://cloud.githubusercontent.com/assets/916551/21625804/5d1a4260-d1c2-11e6-9753-04df4d96338c.png)

and managed to get direct shell access to a ppc64 test environment, and can reproduce the issue at will. If I run `tesseract /tmp/ocr.png /tmp/ocr` (which dumps all text OCRed from `/tmp/ocr.png` to `/tmp/ocr.txt`) with leptonica-1.73-2.fc24 installed, I get this:

    [fedora@puiterwijk---adamw-ppc ~]$ tesseract /tmp/ocr.png /tmp/ocr
    Tesseract Open Source OCR Engine v3.04.01 with Leptonica
    [fedora@puiterwijk---adamw-ppc ~]$ cat /tmp/ocr.txt 
    Memory Test

    [fedora@puiterwijk---adamw-ppc ~]$

but if I update to leptonica-1.74.1-1.fc26 and try again, I get this:

    [fedora@puiterwijk---adamw-ppc ~]$ tesseract /tmp/ocr.png /tmp/ocr
    Tesseract Open Source OCR Engine v3.04.01 with Leptonica
    Empty page!!
    Empty page!!
    [fedora@puiterwijk---adamw-ppc ~]$ cat /tmp/ocr.txt 
    [fedora@puiterwijk---adamw-ppc ~]$

1.74 also has the problem, so it appeared between 1.73 and 1.74 (not between 1.74 and 1.74.1).

On a little-endian arch, the same process gives the same (correct) result - a text file with the line 'Memory Test', and no "Empty page!!" errors - for both leptonica 1.73 and 1.74.

**Comment by DanBloomberg** [comment]
Adam, look at src/Makefile.  What is ENDIANNESS defined as?

**Comment by AdamWill** [comment]
[fedora@puiterwijk---adamw-ppc leptonica]$ grep ENDIAN src/Makefile
    ENDIANNESS = L_BIG_ENDIAN

Note, I bisected this, and got fd252ce0a17561b74f8cc02726601e5be121ac58 as the offending commit.

**Comment by AdamWill** [comment]
Other possibly relevant notes: we build with GCC, obviously, and the package build does `autoreconf -i` prior to configuring and building (so I did the same in my bisection test).

**Comment by AdamWill** [comment]
So here's a funny thing: I can actually reproduce the problem on top of bdd10d40652b084708996149338c49c11dcdd63b (the commit before fd252ce) by adding just one change from fd252ce:

    diff --git a/src/alltypes.h b/src/alltypes.h
    index b9512a0..a84c0bf 100644
    --- a/src/alltypes.h
    +++ b/src/alltypes.h
    @@ -33,6 +33,7 @@
     #include <stdarg.h>
     
         /* General and configuration defs */
    +#include "endianness.h"
     #include "environ.h"
     
         /* Generic and non-image-specific containers */

i.e. the change that actually makes sure `endianness.h` is included and thus its setting of `L_BIG_ENDIAN` will be respected. Which sort of suggests to me that we were actually getting the `L_LITTLE_ENDIAN` behaviour on this arch before, and that was actually working better (or at least working better for this specific case). Seems somewhat odd...

Oh! Aha. I have an idea. It may simply be that tesseract needs rebuilding after the leptonica fix - even though the library API didn't technically change, perhaps tesseract is thrown off by the change in leptonica's behaviour on this arch due to the fixed endianness detection...I'll rebuild tesseract against the updated leptonica and see if it behaves better then.

**Comment by DanBloomberg** [comment]
whew!  I'm glad we had this one fixed !

Thanks for tracking it all down.
