### ISSUE TITLE
pixProjective

### ISSUE THREAD

**Issue by radioman** [DanBloomberg/leptonica#233]
i'm doing projective transform, and using matrix from gimp transform tools and right bottom corner suppose to be smaller, but it gets bigger, what can be wrong? Thanks.
```
				l_float32 p[9] =
				{
					1.11888f, 0.0f, 0.0f,
					0.0f,     1.0f, 0.0f,
					0.00016f, 0.0f, 1.0f
				};
				pxOut = pixProjective(px, p, 0);
```

**Comment by DanBloomberg** [comment]
You have 9 coefficients; the projective transform has 8 (2 for each of 4 points).  Trim it down.

**Comment by radioman** [comment]
i know 9th point is not relevant, if i use 0.7 instead 1.118, i get transformation in the same direction, it seems current implementation works in inverse direction ;/

**Comment by DanBloomberg** [comment]
The transformation works in a direction so that every image point in the destination D is set!  That is the key.

So instead of saying "for this point in S, what's the corresponding point in D", we go the other way.

**Comment by radioman** [comment]
ok, so how do i make sense of it? Does description of parameters in [homography_transformation](http://www.corrmap.com/features/homography_transformation.php) apply for leptonica and whats the difference? 

Gimp has nice perspective tool, i can experiment with image and get the parameter matrix, but how to apply it for leptonica?

**Comment by DanBloomberg** [comment]
sorry, I don't know.  If you figure it out, please let me know.
