### ISSUE TITLE
[build error] ./configure line 12977 syntax error near unexpected token 'ZLIB'

### ISSUE THREAD

**Issue by Wikinaut** [DanBloomberg/leptonica#234]
Using the git version on `debian 9` in QubesOS, I got this message during ./configure

```
 ./configure line 12977 syntax error near unexpected token 'ZLIB'
PKG_CHECK_MODULES(ZLIB, zlib.)
```

Pls. can you help ?

On my reference system with `debian 8`, building leptonica works.

**Comment by Wikinaut** [comment]
`zlib` looks to be a strange dependency.

**Comment by amitdo** [comment]
Hi Wikinaut, I'm everywhere :-)

Check that `pkg-config` is installed.

**Comment by Wikinaut** [comment]
@amitdo no change, same message

**Comment by Wikinaut** [comment]
I have no idea why, but after redoing 

```
./autobuild
```
./configure now works

works for me :-)

(closing/invalid)
