### ISSUE TITLE
test of arabic_lines.c and misctest1.c

### ISSUE THREAD

**Issue by Shreeshrii** [DanBloomberg/leptonica#236]
Ref: https://github.com/tesseract-ocr/tesseract/issues/657#issuecomment-274678462

I built leptonica with the latest code and gave it a try for both the sample arabic and devanagari pages using arabic_lines.c and misctest1.c.

What I found is that while the devanagari page was split correctly using arabic_lines.c, the arabic page was split correctly using misctest1.c.

Devanagari line splitting using misctest1.c is missing whole chunks of text.

Arabic line splitting using arabic_lines.c merged one set of two lines.

Files are attached.

![lines2](https://cloud.githubusercontent.com/assets/5095331/22617455/a636c12a-eaeb-11e6-8adc-5c870e61750c.png)
![result](https://cloud.githubusercontent.com/assets/5095331/22617456/a639b696-eaeb-11e6-89e6-0d964ae6a4aa.png)

![lines2](https://cloud.githubusercontent.com/assets/5095331/22617458/b0df53da-eaeb-11e6-84b0-1346ec7b5224.png)
![result](https://cloud.githubusercontent.com/assets/5095331/22617457/b080acea-eaeb-11e6-965f-69608c4383f4.png)

**Comment by Shreeshrii** [comment]
Here is another sample using Telugu - another Indian language.

![lines2](https://cloud.githubusercontent.com/assets/5095331/22617516/2e3f24f8-eaed-11e6-8016-bc746cfd0d3a.png)
![result](https://cloud.githubusercontent.com/assets/5095331/22617517/2e42b00a-eaed-11e6-9fef-0ddef4dd243a.png)

**Comment by DanBloomberg** [comment]
Yes, I am aware that the results from the two similar methods are different, and that the arabic_lines.c method joins those two lines in the first image.

These methods are not intended to be "industrial strength"  line extractors; just illustrations of how binary morphology can be used to do these segmentation tasks.  I believe that pixExtractTextlines() is not used in tesseract.

With respect to the first image (arabic with a few examples of a complex character, single column): (1) what does it say, and (2) would there be any reason not to use this as a test file in leptonica/prog?

  -- Dan

**Comment by Shreeshrii** [comment]
Dan, Thanks for your work on this. I am hoping it will lead to better line detection in tesseract.

I do not know Arabic. The image I used for testing was provided by @bmwmy in issue titled 'Arabic lang. feature request' https://github.com/tesseract-ocr/tesseract/issues/552 

The image is linked at https://drive.google.com/file/d/0B1JdJ8IXNweRcG1mRUpkU1dFMVJPUGV3YVlkT0JxYnBlTGhn/view?usp=sharing
and also provided as part of a triningdata.zip file at https://drive.google.com/file/d/0B1JdJ8IXNweRX3NEMkZfX3gtdlk/view?usp=sharing

**Comment by DanBloomberg** [comment]
I've added another function for extracting textlines, pixExtractRawTextlines(), which is much more aggressive in joining components.  It does not respect different columns of text (i.e., it aggressively joins them!)

It doesn't resolve this issue (actually, goes in the other direction), but is useful in other situations.

Closing.
