### ISSUE TITLE
need steps to build leptonica for VS2010  && VS2015 

### ISSUE THREAD

**Issue by essamzaky** [DanBloomberg/leptonica#237]
is there steps to build leptonica for VS2010 & VS2015 ?

**Comment by DanBloomberg** [comment]
I believe the easiest way now is with cmake

**Comment by essamzaky** [comment]
Thanks DanBloomberg

I'm not familiar with cross plat form tools , so sorry for my beginner question , 
I did the following:

git clone https://github.com/DanBloomberg/leptonica.git
cd leptonica
mkdir build
cd build
cmake ..

now i get some errors while build such as
_Could NOT find GIF (missing:  GIF_LIBRARY GIF_INCLUDE_DIR)
 Could NOT find JPEG (missing:  JPEG_LIBRARY JPEG_INCLUDE_DIR)
 Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
 Could NOT find PNG (missing:  PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
 Could NOT find TIFF (missing:  TIFF_LIBRARY TIFF_INCLUDE_DIR)
 Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
 Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)_

Where i can download the suitable dependency libs for the current leptonica source?, where to copy them , and how to set this paths to be recognized by cmake

also there are dome missing headers such as 

_Looking for include file dlfcn.h - not found
Looking for include file strings.h - not found
Looking for include file unistd.h - not found
Looking for include file openjpeg-2.0/openjpeg.h - not found
Looking for include file openjpeg-2.1/openjpeg.h - not found
Looking for include file openjpeg-2.2/openjpeg.h - not found
Looking for fmemopen - not found_

thanks for help

Best Regards

**Comment by radioman** [comment]
https://github.com/radioman/leptonica_vs2015

**Comment by DanBloomberg** [comment]
@egorpugin   What do you suggest for building in windows from the main branch?

**Comment by egorpugin** [comment]
@essamzaky  You need one more command in your sequence.
Of course, download and put [CPPAN](https://cppan.org/) client to PATH.
```
git clone https://github.com/DanBloomberg/leptonica.git
cd leptonica
cppan # <- this!
mkdir build
cd build
cmake ..
```

**Comment by essamzaky** [comment]
Thanks @Egorpugin i found the solution file for VS2015 it succeed to create the "leptonica-1.74.1d.dll"
I have the following question

1-do i need leptonica library dependencies or are they statically linked inside "leptonica-1.74.1d.dll" ?
2-How i can change the build two VS2010 i have both (VS2010 1nd VS2015) in the same machine.
3-Is it possible to have the dependencies as projects inside the solution ? i need to give same settings for all projects (leptonica + dependencies) also i want to trace and debug both leptonica and dependencies.

thanks

**Comment by egorpugin** [comment]
1. Dependencies (dlls) are copied to `bin` directory (`build/bin`). It is also possible to build & link them statically. (Use `cmake .. -DCPPAN_BUILD_SHARED_LIBS=0`).
2. See cmake doc, generators section. You have to add some invocation parameters to cmake command. cppan and all deps will follow it.
3. Yes, it is possible. Debug build will trace all deps without include deps projects to solution. But for custom settings you must do this.  (Use `cmake .. -DCPPAN_USE_CACHE=0`).

**Comment by essamzaky** [comment]
Hi @egorpugin ,
I did the previous steps for VS2015 and it works to generate the the leptonica DLL + static dependences

But the generattion failed for VS2010 , i did the following
1-delete the following folders "C:\Users\emz\leptonica" , "C:\Users\emz\.cppan".
2-git clone https://github.com/DanBloomberg/leptonica.git
3-cd leptonica
4-cppan
5-mkdir build
6-cd build
7-cmake -G "Visual Studio 10 2010" .. 
8-cmake -DCPPAN_USE_CACHE=0 ..

the solution file and project are added to solution
but when build Build the build log is : 
========== Build: 11 succeeded, 3 failed, 0 up-to-date, 1 skipped ==========

the failed project are:
pvt.cppan.demo.xz_utils.lzma-5.2.2
pvt.cppan.demo.gif-5.1.4
leptonica

some error like

'stdbool.h': No such file or directory in lzma

syntax error : identifier '_Bool'	c:\users\emz\.cppan\storage\src\d6\de\c13d\lib\gif_lib.h	43	pvt.cppan.demo.gif-5.1.4

**Comment by egorpugin** [comment]
VS2010 is known to fail. No fixes will be applied. Please, use the latest build tools.

**Comment by xsacha** [comment]
Using CMake and with #260 fixed, vs 2010 and vs 2015 'just work'
See: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1787

**Comment by DanBloomberg** [comment]
#260 hasn't been applied yet, has it?

**Comment by xsacha** [comment]
No, but the steps work (mkdir build; cd build; cmake ..).

**Comment by egorpugin** [comment]
Looks good to me.
(But I'm not really sure if that could fix vs2010 build.)

**Comment by xsacha** [comment]
vs2010 and even vs2008 are compiling with just 'cmake ..' after that fix.

**Comment by essamzaky** [comment]
Hi @xsacha 
would you write the steps in details to build for VS2010

i did the following steps
git clone https://github.com/DanBloomberg/leptonica.git
cd leptonica
mkdir build
cd build
cmake ..

but it fail because it can not find the dependences such as (zlib , pnglib , jpglib, tifflib,..), how to step the dependences to build with leptonica ?

**Comment by xsacha** [comment]
You just need these dev dependencies installed.

**Comment by essamzaky** [comment]
Would you explain how to step these dependencies to be integrated with leptonica

**Comment by xsacha** [comment]
Well since CMake doesn't contain a package manager, all packages are sourced from origin just like every other CMake project. Otherwise you use a package manager like cppan.

Personally, I use Hunter:
git clone https://github.com/hunter-packages/leptonica.git
cd leptonica
mkdir build
cd build
cmake ..
make

**Comment by LaurentBerger** [comment]
Hi, 
I have spent some hours to build leptonica on windows using vs2015. I want to run this [sample ](https://github.com/opencv/opencv_contrib/blob/master/modules/text/samples/webcam_demo.cpp)in opencv. 

Problem is with tiff libray and jpeg and zlib.

First I have modified cmakelists.txt : 

set(LIBRARY_TYPE SHARED)
if (STATIC)
    set(LIBRARY_TYPE)
endif()
if (JPEG_FOUND)
	include_directories(${JPEG_INCLUDE_DIR})
	message("JPEG   ${JPEG_INCLUDE_DIR}")
endif (JPEG_FOUND)
if (TIFF_FOUND)
	include_directories(${TIFF_INCLUDE_DIR})
	message("TIFF   ${TIFF_INCLUDE_DIR}")
endif (TIFF_FOUND)
if (ZLIB_FOUND)
	include_directories(${ZLIB_INCLUDE_DIR})
	message("ZLIB   ${ZLIB_INCLUDE_DIR}")
endif (ZLIB_FOUND)
if (PNG_FOUND)
	include_directories(${PNG_INCLUDE_DIR})
	message("PNG   ${PNG_INCLUDE_DIR}")
endif (PNG_FOUND)


You can then  clone [zlib](https://github.com/madler/zlib.git)

jpeg and tiff you can try to use 3rdparty lib in opencv. It is possible but you have to move some files, disable int32...

I have try using cppan but I like doing things myself.  

Finally can you give me a shorter way to install leptonica on windows using vs2015 to be used with tesseract and opencv?

thanks for yourd answers

**Comment by egorpugin** [comment]
> I have try using cppan but I like doing things myself.

> Finally can you give me a shorter way

Use cppan. It has opencv also.
Here is a quick guide for your `webcam_demo.cpp`.
1. download `opencv.contrib`
2. cd to `webcam_demo.cpp` dir
2. add to preamble:
```
/*
dependencies:
    - pvt.cppan.demo.intel.opencv.contrib.text: 3
    - pvt.cppan.demo.intel.opencv.highgui: 3
    - pvt.cppan.demo.intel.opencv.features2d: 3
    - pvt.cppan.demo.intel.opencv.videoio: 3
*/
```
2. add missing include `#include "opencv2/videoio.hpp"`
5. copy tess traineddata to current dir
3. run `cppan --build webcam_demo.cpp`
4. run `bin\webcam_demo`

What can be easier?

---

But for manual case feel free to find all those deps, link them and build `webcam_demo`.

**Comment by LaurentBerger** [comment]
@DanBloomberg @egorpugin Building leptonica on windows with vs 2015-2017.

My question how to build leptonica (for tesseract-ocr) on windows using cmake ? Is it possible without using cppan?
You can use cmake first like this (with git-bash) : 

cmake -G"$CMAKE_CONFIG_GENERATOR" -DCMAKE_INSTALL_PREFIX="$myRepo"/Install/leptonica "$myRepo/$RepoSource"

Ok with this no problem. But no png, jpeg zlib, gif  support. Tesseract-ocr needs one of this.

Now you can try (with opencv ): 
cmake -G"$CMAKE_CONFIG_GENERATOR" -DPNG_LIBRARY:FILEPATH="$myRepo"/build/opencv/3rdparty/lib/Release/libpng.lib -DPNG_PNG_INCLUDE_DIR:PATH="$myRepo"/opencv/3rdparty/libpng \
-DZLIB_LIBRARY:FILEPATH="$myRepo"/build/opencv/3rdparty/lib/Release/zlib.lib -DZLIB_INCLUDE_DIR:PATH="$myRepo"/opencv/3rdparty/zlib \
-DCMAKE_INSTALL_PREFIX="$myRepo"/Install/leptonica "$myRepo/$RepoSource"

It does not work because I think some lines are missing in cmakelists.txt. I don't know cmake very well but I think lines given in my previous message are necessary for VS. With these line I can build leptonica with png support. 
Is it possible to add these line ?

**Comment by xsacha** [comment]
Install those libraries and CMake automatically detects them.
Otherwise use a cmake package manager like Hunter.

**Comment by LaurentBerger** [comment]
@xsacha what i understand in cmake syntax it[ is](https://cmake.org/Wiki/CMake:How_To_Find_Libraries) 

```
cmake_minimum_required(VERSION 2.8)
project(helloworld)
add_executable(helloworld hello.c)
find_package (BZip2)
if (BZIP2_FOUND)
  include_directories(${BZIP_INCLUDE_DIRS})
  target_link_libraries (helloworld ${BZIP2_LIBRARIES})
endif (BZIP2_FOUND)
```

**Comment by xsacha** [comment]
You can target include directories too, but yes.

If it is a CMake package with a target you can also just link the target and it will automatically do the include directories.
