### ISSUE TITLE
endianness.h is miss ?

### ISSUE THREAD

**Issue by blacklong617** [DanBloomberg/leptonica#238]
in alltypes.h have do :
#include "endianness.h"
but I don't find endianness.h but just find endianness.h.in .
when I include alltypes.h, I got a error that the endianness.h is not find.
Can you help me?

**Comment by DanBloomberg** [comment]
./configure should make it.

what's your OS and hardware platform?

**Comment by ychwang** [comment]
my OS  is win10 i used VS2015 to compile , always reminder me that endianness.h is miss. how  can i do .

**Comment by chewi** [comment]
Building with Visual Studio is not supported. If you must do this then just create endianness.h with this:

```
#define L_LITTLE_ENDIAN
```
