### ISSUE TITLE
Incorrect output when creating synthetic images

### ISSUE THREAD

**Issue by VojtaFPalaxo** [DanBloomberg/leptonica#239]
I was debugging some output of leptonica and in the process I have created following program to test the it:

    #include <leptonica/allheaders.h>
    
    int main(){
        char arr[] = {0xff, 0xff, 0xff, 0xff};
        PIX* pix_image = pixCreate(2, 2, 8);
        pixSetData(pix_image, (l_uint32 *) arr);
        pixWrite("img", pix_image, IFF_PNM);
        return 0;	
    }

Complied on Ubuntu with GCC 5.4.4 and linked against libleptonica.so.1.74.1

The result should be image that is all white. It is 4 bytes with value 255 and the depth is set to 8, i.e. 8bit per pixel.

The resulting image is not white though, but half white and half black.

    00000000  50 35 0a 23 20 52 61 77  20 50 47 4d 20 66 69 6c  |P5.# Raw PGM fil|
    00000010  65 20 77 72 69 74 74 65  6e 20 62 79 20 6c 65 70  |e written by lep|
    00000020  74 6f 6e 69 63 61 20 28  77 77 77 2e 6c 65 70 74  |tonica (www.lept|
    00000030  6f 6e 69 63 61 2e 63 6f  6d 29 0a 32 20 32 0a 32  |onica.com).2 2.2|
    00000040  35 35 0a ff ff 00 00                              |55.....|

The relevant part is the last 4 bytes, which reads `ff ff 00 00` this represents 2 white pixels and 2 black pixels.

Is this a bug in leptonica?

**Comment by DanBloomberg** [comment]
Vojtěch,

Not a bug in leptonica.  You're debugging your understanding of data padding in the pix.
See pix.h.
Data is padded to 32 bit words on each scanline.
In the first raster line, you set 2 image bytes to ff, and 2 pad bytes to ff.
The second raster lne was initialized to 0 by calloc, which explains the black pixels there.

  -- Dan

**Comment by VojtaFPalaxo** [comment]
> Data is padded to 32 bit words on each raster line.

Duh! Thanks, now it makes sense.
