### ISSUE TITLE
There are utilities for command line?

### ISSUE THREAD

**Issue by uasan** [DanBloomberg/leptonica#247]
As in [GraphicsMagick](http://www.graphicsmagick.org/utilities.html) and [ImageMagick](https://www.imagemagick.org/script/command-line-tools.php)?

Thank.

**Comment by DanBloomberg** [comment]
There are about 250 programs in the prog/ directory.

They show how to use the library to carry out various applications.  Many of them are part of a regression test set.

**Comment by zdenop** [comment]
This could be closed IMO.

**Comment by DanBloomberg** [comment]
yes
