### ISSUE TITLE
CMake compile error (utils.c)

### ISSUE THREAD

**Issue by xsacha** [DanBloomberg/leptonica#252]
When I tried to run the CMake configuration, a utils.c file had been generated with the same functions as utils1.c and the result was that my compiler complained that the functions within this file were all defined multiple times.
By manually removing the file, compilation worked.

I am not sure whether the file generation is intentional but it gets picked up by the CMake globbing. Meanwhile, the Makefile configuration, which does not use globbing, works fine.

What is going wrong here?

Thanks

**Comment by DanBloomberg** [comment]
I don't know.  This hasn't been reported.

What release or version are you using?  What platform?

Is there in fact a third utils*.c file, such as utils.c?  If so, perhaps it's a left-over from an earlier release, before utils.c was split into two files.

**Comment by xsacha** [comment]
You're right. It was from an earlier git commit. When I updated to latest it kept the old utils.c.
