### ISSUE TITLE
CMake target missing linkage

### ISSUE THREAD

**Issue by xsacha** [DanBloomberg/leptonica#255]
When successfully building leptonica without cppan, I get a LeptonicaTargets that contains Leptonica_LIBRARY set to leptonica.
When trying to link the module in a different project it then complains of unknown references (missing png, jpeg and gif libraries) until I link the missing libraries manually.

Is this expected or have I done something wrong?

**Comment by DanBloomberg** [comment]
Don't know.  What's the source?  What platform?

2 other choices to build besides cppan:
* Did you try using autotools?
* Or the local makefile without autotools?

**Comment by egorpugin** [comment]
You can try to use leptonica via cppan.
Without this you still need to manually get and build all deps.

In other words LeptonicaTargets is for pure cmake builds and not for cppan ones.

**Comment by xsacha** [comment]
I think I have worked it out. It should be linked to the library already anyway. The target is fine.
