### ISSUE TITLE
mtiff_reg failure on i686

### ISSUE THREAD

**Issue by manisandro** [DanBloomberg/leptonica#256]
While updating the leptonica Fedora package, i noticed that the `mtiff_reg` test is failing on i686:

    $ autoreconf -ifv
    [...]
    $ ./configure --build=i686-pc-linux-gnu "CFLAGS=-m32" "CXXFLAGS=-m32" "LDFLAGS=-m32"
    [...]
    $ make
    [...]
    $ cd prog
    $ ./mtiff_reg 

    ################   mtiff_reg   ###############
    leptonica-1.74.2
    libjpeg 6b (libjpeg-turbo 1.5.1) : libpng 1.6.28 : libtiff 4.0.8 : zlib 1.2.11

    Info in pixaReadMultipageTiff:  Tiff: 7 pages
    Info in boxaWriteMem: work-around: writing to a temp file
    Info in boxaWriteMem: work-around: writing to a temp file
    Info in boxaWriteMem: work-around: writing to a temp file
    Info in boxaWriteMem: work-around: writing to a temp file
    Info in boxaWriteMem: work-around: writing to a temp file
    Info in pixaReadMultipageTiff:  Tiff: 1000 pages
    Time to read 1000 images and return a pixa:  0.051 sec
    Info in boxaWriteMem: work-around: writing to a temp file
    Info in boxaWriteMem: work-around: writing to a temp file
    Writing to: /tmp/lept/tiff/weasel4.ps
    Writing to: /tmp/lept/tiff/weasel4.pdf
    Info in pixaReadMultipageTiff:  Tiff: 4 pages
    Failure in mtiff_reg, index 18: comparing /tmp/lept/tiff/weasel_orig.tif with /tmp/lept/golden/mtiff_golden.18.tif
    Tiff: 4 page
    Failure in mtiff_reg, index 21: comparing /tmp/lept/tiff/weasel_rev.tif with /tmp/lept/golden/mtiff_golden.21.tif
    Failure in mtiff_reg, index 22: comparing /tmp/lept/tiff/weasel_rev_rev.tif with /tmp/lept/golden/mtiff_golden.22.tif
    Time:   0.365 sec
    ################################################

Above is on Fedora Rawhide with gcc version 7.1.1 20170526 (Red Hat 7.1.1-2).

**Comment by DanBloomberg** [comment]
Thanks for reporting this.  See #250, which is now closed and the problem has been fixed on the master.

**Comment by manisandro** [comment]
Cool, thanks.
