### ISSUE TITLE
CMake: Use a namespaced target

### ISSUE THREAD

**Issue by xsacha** [DanBloomberg/leptonica#257]
Use a namespaced CMake target such as Leptonica::leptonica instead of requiring ${Leptonica_LIBRARIES} to be linked and ${Leptonica_INCLUDEDIRS} to be included.

Not submitting as a pull request as I won't assume a name for you.
See: https://github.com/xsacha/leptonica/commit/fc164a0709d40d8791896354ee6c4a927ed9a0af#diff-95e351a3805a1dafa85bf20b81d086e6R60

**Comment by DanBloomberg** [comment]
@egorpugin 

Anything to be done here (he added "REQUIRED" to libraries and namespace for target)?

**Comment by egorpugin** [comment]
REQUIRED - probably not needed.
Namespaces is not very common yet in cmake world.
I'd like to leave everything as is at (least for some time).

**Comment by DanBloomberg** [comment]
ok, up to you to close or leave open

**Comment by amitdo** [comment]
Almost 5 years later...

@egorpugin, is it more common now?

**Comment by egorpugin** [comment]
I did not use cmake for 6 years already, so i cant say whether namespaces are common.

@xsacha Feel free to reopen.
