### ISSUE TITLE
CMake: Set target include path in install export

### ISSUE THREAD

**Issue by xsacha** [DanBloomberg/leptonica#258]
The current method was not giving the correct include path when importing leptonica in to another CMake project. By setting the includes path in the install export to the 'include' dir (relative), you avoid any issues with setting an incorrect directory.
See: https://github.com/xsacha/leptonica/commit/3c7b0cd0594014a7a89a8abfb118c78567b8164c#diff-95e351a3805a1dafa85bf20b81d086e6R70

It also means there is no reason to export the target to a file.
See: https://github.com/xsacha/leptonica/commit/3c7b0cd0594014a7a89a8abfb118c78567b8164c#diff-95e351a3805a1dafa85bf20b81d086e6R56

**Comment by DanBloomberg** [comment]
@egorpugin 

Is there anything to be done on this issue?

**Comment by egorpugin** [comment]
Need more info here. Why export directive was commented out?

**Comment by DanBloomberg** [comment]
@egorpugin 

Any reason to leave this open?

**Comment by egorpugin** [comment]
I think no.
