### ISSUE TITLE
regTestWritePixAndCheck/Error in fopenReadStream: file not found

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#263]
I just tried several leptonica programs (e.g. prog/enhance_reg) on openSUSE 42.2 64 bit and I got these error messages:
################   enhance_reg   ###############
leptonica-1.74.3
libgif 5.0.5 : libjpeg 8d (libjpeg-turbo 1.3.1) : libpng 1.6.8 : libtiff 4.0.7 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0

Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 0: comparing /tmp/lept/regout/enhance.00.png with /tmp/lept/golden/enhance_golden.00.png
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 1: comparing /tmp/lept/regout/enhance.01.png with /tmp/lept/golden/enhance_golden.01.png
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 2: comparing /tmp/lept/regout/enhance.02.png with /tmp/lept/golden/enhance_golden.02.png
Warning in pixModifySaturation: no change requested in saturation
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 3: comparing /tmp/lept/regout/enhance.03.png with /tmp/lept/golden/enhance_golden.03.png
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 4: comparing /tmp/lept/regout/enhance.04.png with /tmp/lept/golden/enhance_golden.04.png
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 5: comparing /tmp/lept/regout/enhance.05.png with /tmp/lept/golden/enhance_golden.05.png
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 6: comparing /tmp/lept/regout/enhance.06.jpg with /tmp/lept/golden/enhance_golden.06.jpg
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 7: comparing /tmp/lept/regout/enhance.7.png with /tmp/lept/golden/enhance_golden.07.png
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 8: comparing /tmp/lept/regout/enhance.08.jpg with /tmp/lept/golden/enhance_golden.08.jpg
Info in pixWriteStreamJpeg: removing colormap; may be better to compress losslessly
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in enhance_reg, index 13: comparing /tmp/lept/regout/enhance.13.jpg with /tmp/lept/golden/enhance_golden.13.jpg
Time:   1.952 sec
################################################
It seam to be produced by regTestWritePixAndCheck function.

**Comment by DanBloomberg** [comment]
That's one of an automated regression set of tests.

You have to do:
   enhance_reg generate  (to generate the golden files)
   enhance_reg [compare]   (to test against the golden files)

There are about 96 of them in alltests_reg.

For the entire set:
      alltests_reg generate
      alltests_reg compare

Nothing should fail.

With autotools, after you 'make' you can do
   make check
which runs each of these 96 programs twice, once to generate the golden files and the second time to check against them.
