### ISSUE TITLE
1.74.3 source package contains a spurious binary object

### ISSUE THREAD

**Issue by matzeri** [DanBloomberg/leptonica#264]
In
https://github.com/DanBloomberg/leptonica/releases/download/1.74.3/leptonica-1.74.3.tar.gz

$ file  leptonica-1.74.3/prog/xtractprotos.o
leptonica-1.74.3/prog/xtractprotos.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped, with debug_info

this causes build to fail.

**Comment by stweil** [comment]
@DanBloomberg, I can confirm that report. There are some more files which don't seem to right:

    Only in leptonica-1.74.3/prog: xtractprotos
    Only in leptonica-1.74.3/prog: xtractprotos.o
    Only in leptonica-1.74.3/src: endianness.h
    Only in leptonica-1.74.3/src: xtractprotos

**Comment by DanBloomberg** [comment]
@stweil  Should I delete the old version of 1.74.3, and make a new one without these spurious files?

**Comment by stweil** [comment]
Maybe making a new 1.74.4 (or a 1.74.3.1, without changing the current 1.74.3) would be better.

**Comment by DanBloomberg** [comment]
ok, will do a 1.74.4

**Comment by DanBloomberg** [comment]
New 1.74.4 is out.  Noted the problem with the 1.74.3 release on the release page.

**Comment by egorpugin** [comment]
It's true that some people uses or wants to use the fourth tweak number like 1.74.3.1 or like in some packaging systems (1.74.3-1, 1.74.3-2). But my vote is also for strict 1.74.4.
