### ISSUE TITLE
leptonica site: Source Downloads

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#265]
Hi Dan!

http://www.leptonica.org/download.html

>**All the even-numbered releases from Version 1.42 through 1.60, and all subsequent releases through 1.69, are available for download at [github](https://github.com/DanBloomberg/leptonica).**

What about linking to
https://github.com/DanBloomberg/leptonica/releases
instead of
https://github.com/DanBloomberg/leptonica/
?

**Comment by DanBloomberg** [comment]
Yes, that makes sense.  Done.

**Comment by amitdo** [comment]
Dan, can you fix it again?

Also, github -> GitHub

**Comment by DanBloomberg** [comment]
I think I got it right now  :-)

Thanks for reminding me.
