### ISSUE TITLE
How to remove lines from bi-tonal images?

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#266]
The line removal sample works for gray scale images.  Is there a technique for doing that on bi-tonal images?

**Comment by DanBloomberg** [comment]
It's a bit harder.  What helps is if you have information about the lines that you want to remove, such as the orientation and thickness.

For example, suppose you want to remove the staff lines in a scan of a music score.  You would deskew and do a large enough horizontal opening.  Then a vertical closing can be used to reconnect the pieces of the notes and bar lines where the staff lines were lifted out.

**Comment by tdhintz** [comment]
Actually, I just want to remove the lines.  These are boxes (vertical and horizontal lines) around areas on a form that I want to drop out for OCR, so they don't intersect with text.  I don't want to drop lines that comprise characters.

**Comment by tdhintz** [comment]
Dan, can I bother you for a specific example set of API calls to achieve this?  There are so many functions exposed in leptonica I'm not clear where to start.  Thanks,

**Comment by DanBloomberg** [comment]
You can use functions in morph.c or morphseq.c to do the openings with block filters (filters that have w x h pixels).  For the examples I described above, for example you could take w = 100 and h = 1 for horizontal filters looking for 100 ON pixels adjacent horizontally.

The seedfill operations are in seedfill.c.

The function pixSubtract() does the set subtraction.

There are many programs in the prog directory that use these functions; just use grep to see examples of use.  Also, check out pageseg.c, which uses these functions extensively.

**Comment by tdhintz** [comment]
Pardon the delay. I've been working to understand.  I gather you mean do something like this?

/* remove horizontal lines from pixs*/
SEL *sel = selCreateBrick(100, 1, 0, 0, SEL_HIT);
PIX* horizLinesRemoved = pixOpen(null, pixs, sel);

**Comment by tdhintz** [comment]
The following seems close, but replaces large areas with black pixels.  Guidance?

/* remove horizontal lines from pixs*/
SEL sel = selCreateBrick(1, 100, 0, 0, SEL_HIT);
PIX *mask = pixOpen(null, pixs, sel);
PIX *result = pixSubtract(null, pixs, mask);

**Comment by tdhintz** [comment]
This seems pretty hacky, but mostly works.  It leaves a lot of noise where the document scanner left uneven edges.  I also need to repeat the operation for each width of the line, so iterating over the image from the widest to narrowest.  Disposal of memory omitted for clarity.

Is there a better way?

```
for (int i = 4; i >0; --i)
{
PIX *mask = pixCloseSafeBrick(null, pixs, i, 100);
pixXor(pixs, pixs, mask);
}
```

**Comment by DanBloomberg** [comment]
You can use pixOpenBrick(), and avoid having to generate the Sel, as you were doing with pixCloseSafeBrick().

Remember that the returned images from these functions is the address of the pix.

I believe in the brick functions the 3rd arg is the width and the 4th is the height.  So the iteration over pixCloseSafeBrick() doesn't make sense.  Also, this is generating a new pix each time, which needs to be cleaned up with pixDestroy().

I'm going to be unable to help for the next week or so, but if you send me an image and tell me exactly what you want to happen, I'll write come example code to do it for you in a bit over a week.

**Comment by tdhintz** [comment]
Thanks for looking.  I just want boxes to disappear from forms because they impact the quality of OCR.

**Comment by tdhintz** [comment]
Hi Dan,

I hope you had a good trip.  Can I impose on you to help me sort this out?  I'd like to extend Charles Weld's tesseract .Net project with a solution if that can be done.  Thanks for any pointers.

**Comment by DanBloomberg** [comment]
Hi TD,

Sorry for the delay.  I am back on line and will attempt to help you in the next few days with your line removal project.

**Comment by tdhintz** [comment]
This is interesting.

[Accurate, swift and noiseless image binarization](http://www.iapress.org/index.php/soic/article/download/20160304/226)

**Comment by tdhintz** [comment]
I was able to write an implementation using ImageMagick .Net that I'd like to translate into Leptonica.  The ImageMagick version is something like this:

```
maskImg = img.Clone();
maskImg.Negate();
maskImg.Morphology(MorphologyMethod.Erode, "rectangle:50x1");
maskImg.WriteMask = img;
maskImg.Morphology(MorphologyMethod.Dilate, "rectangle:50x1");
maskImg.WriteMask = null;
img.Composite(mask, CompositeOperator.Lighten);
```

So far I've been able to translate the following.  Any suggestion for the missing pieces?

```
mask = pixClone(img);
pixInvert(mask, mask);
 sel = selCreateBrick(1, 50, 0, 0, SEL_HIT);
pixErode(mask, mask, sel);
/* TODO: set mask from original, img */
pixDilate(mask, mask, sel);
selDestroy(sel);
/* TODO: img.Composite(mask, CompositeOperator.Lighten); */
```

**Comment by tdhintz** [comment]
This is pretty close, and its fast.  Kudos to Leptonica.  The lines are nearly removed but imperfections are left behind.

```
mask = pixCopy(null, img);
pixInvert(mask, mask);
sel = selCreateBrick(1, 50, 0, 0, SEL_HIT);
pixErode(mask, mask, sel);
pixDilate(mask, mask, sel);
selDestroy(sel);
cleanedImg = pixXor(null, img, mask);
```

**Comment by tdhintz** [comment]
Am I correct in thinking a single pixOpen is the same as the erode followed by dialate?

```
mask = pixCopy(null, img);
pixInvert(mask, mask);
sel = selCreateBrick(1, 50, 0, 0, SEL_HIT);
pixOpen(mask, mask, sel);
selDestroy(sel);
cleanedImg = pixXor(null, img, mask);
```

**Comment by DanBloomberg** [comment]
yes
