### ISSUE TITLE
Tesseract .Net color inverts bi-tonal images.

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#267]
Tesseract .Net has trouble using bi-tonal Bitmap objects.  A white page with black text is reversed such that it becomes a black page with white text.  Charles comments that this is a limitation of Leptonica.  I'm looking for suggestions to resolve this.  See link, below.

https://github.com/charlesw/tesseract/issues/72

**Comment by DanBloomberg** [comment]
1 bpp pix do not have colormaps.  This greatly simplifies all functions on 1 bpp pix.
(Of course, you could add a colormap to a 1 bpp pix, but all operations would ignore it.)

This is enforced when reading a pix from some image formatted file.  For example, png allows 1 bpp images to have colormaps, including transparency components, but when these images are read, they are converted to a pix that has a greater depth if necessary to preserve the value of the pixels, including transparency.

**Comment by tdhintz** [comment]
I'll review Charles' C# code then to see if I can spot the bug.  Most of the work is done there so it is probable that is where the bug lives.
