### ISSUE TITLE
Despeckle erode examples?

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#270]
I need to remove peppering from bi-tonal images like the one attached.  Is there a concrete example of this someone can point to?

![despeckle](https://user-images.githubusercontent.com/10895586/28483033-3b7c71f0-6e39-11e7-8758-75b2faf7a8e6.png)

**Comment by tdhintz** [comment]
The peppering looks like a single pixel, so I tried the following without success.  Why doesn't this remove the isolated pixels?

```
sel = selCreateFromString("ooooxoooo", 3, 3, null);
pix1 = pixCopy(null, pix);
pixInvert(pix1, pix1);
pix2 = pixHMT(null, pix1, sel);
cleanPix = pixXor(null, pix, pix2);
```

**Comment by tdhintz** [comment]
```
sel = selCreateFromString("ooooXoooo", 3, 3, null);
pixMask = pixHMT(null, pix, sel);
pixResult = pixSubtract(null, pix, pixMask);
```

Or (I assume),

```
sel = selCreateFromString("ooooXoooo", 3, 3, null);
pixMask = pixHMT(null, pix, sel);
pixSubtract(pix, pix, pixMask);
```

**Comment by DanBloomberg** [comment]
The code above looks correct for removing the isolated fg (black) pixels, with the result either in a new image or subtracted from the input image.

Has this been satisfactorily resolved?

**Comment by tdhintz** [comment]
Yes, thank you!  I'm curious... does it make sense to pursue a DWA implementation?

**Comment by DanBloomberg** [comment]
DWA is usually not called for.  It makes sense to use DWA in situations where (1) speed is critical and (2) the morphological operations take a significant part of the overall time.
