### ISSUE TITLE
pixLocateBarcodes doesn't support QR code

### ISSUE THREAD

**Issue by favpdf** [DanBloomberg/leptonica#271]
It seems that two dimensions barcodes like QR aren't supported in leptonica. Is there any plan to support them? Thanks!

**Comment by DanBloomberg** [comment]
No.  In fact, the barcode reading utility is in a very primitive and poorly-functioning state.  I'm hoping to get around to cleaning it up sometime in the next year or two ...

**Comment by favpdf** [comment]
Got it. Thanks for the update.
