### ISSUE TITLE
lept.pc is Copied to Wrong Folder

### ISSUE THREAD

**Issue by fifothekid** [DanBloomberg/leptonica#274]
I built using autobuild. After making make and make install it copies all the files to the right places except the lept.pc which is used by pkg-config. It is copied to /usr/local/lib/pkgconfig while it should be in /usr/share/pkgconfig. That was the main reason why I couldn't build Tesseract 4

**Comment by chewi** [comment]
Although some projects install pkg-config files to /usr/share/pkgconfig, the vast majority install to /usr/lib/pkgconfig.

```
$ ls /usr/share/pkgconfig | wc -l
46
$ ls /usr/lib/pkgconfig | wc -l
852
```

Whether it puts them under local or not probably depends on --prefix but this is just the same as all the other files. I'll see later whether other projects ignore --prefix in this case but I very much doubt it. Note what it says in the pkg-config man page.

> On most systems, pkg-config looks in /usr/lib/pkgconfig, /usr/share/pkgconfig, /usr/local/lib/pkgconfig and /usr/local/share/pkgconfig for these files. It will additionally look in the colon-separated list of directories specified by the PKG_CONFIG_PATH environment variable.

I don't know why your system isn't looking in /usr/local/lib/pkgconfig but you could try setting PKG_CONFIG_PATH.

**Comment by Mosely** [comment]
I have the same issue.  Setting PKG_CONFIG_PATH to /usr/local/lib/pkgconfig did allow me to build Tesseract 4, though.

If it helps, I'm running CentOS Linux release 7.4.1708 (Core) and the version of pkg-config is 0.27.1

**Comment by fifothekid** [comment]
yes, that worked for me too
