### ISSUE TITLE
Erode, Dilate, and HMT shift image.

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#277]
Using 1.72.1 and 1.74.4 the use of the following calls shifts bi-tonal images either toward the upper left corner, or down toward the lower right corner as if an extra bit was inserted or removed from the upper left.  Am I using this wrong?

Platform is Win64.

```
                    sel = selCreateFromString("ooooxoooo", 3, 3, null);
                    pix2 = pixErode(null,  pix1, sel);
```

**Comment by DanBloomberg** [comment]
You need to indicate where the center of the Sel is located. To avoid translation, put the center at the location of the hit.
To indicate the center, use a capital X for the hit.
I probably should emit a warning in selCreateFromString() if no center is indicated.

**Comment by tdhintz** [comment]
Thanks!  I was wondering how the center was specified.
