### ISSUE TITLE
pixAnd and pixOr do the opposite?

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#278]
I'm masking patterns off images.  When I pixAnd what I want masked it behaves like an OR.  pixOr behaves like I expected from pixAnd.  How am I misunderstanding these methods?

```
sel = selCreateFromString("xxxxOxxxx", 3, 3, null);
pixMask = pixHMT(null, pix, sel);
pixResult = pixAnd(null, pix, pixMask); /* result is black */


sel = selCreateFromString("xxxxOxxxx", 3, 3, null);
pixMask = pixHMT(null, pix, sel);
pixResult = pixOr(null, pix, pixMask); /* result is cleaned  */
```

**Comment by DanBloomberg** [comment]
Remember, you're operating on 1 bpp images, so black is 1 and white is 0.  (with grayscale images, black is 0 and white is max)

You are doing these operations photometrically inverted from the usual way with 1 bpp images, because you're matching a background pixel surrounded by foreground pixels.

The sel matches a white pixel surrounded by 8 black pixels, and results in a black pixel where the white plixel was.  Is that what you want to do?

Then the AND gives all white pixels, and the OR gives all black pixels.

**Comment by tdhintz** [comment]
I'm attempting to clean images like that described in #270.  More generally I want to understand the API.  I've read more papers on the subject than you can shake a stick at.  The implementation I thought I needed was the following but it didn't clean the image.

```
sel = selCreateFromString("ooooXoooo", 3, 3, null);
pixMask = pixHMT(null, pix, sel);
pixResult = pixAnd(null, pix, pixMask);
```

**Comment by DanBloomberg** [comment]
pixMask has all those single pixels that you want to remove.  So you need to use either pixXor() or pixSubtract() in the third line.

**Comment by DanBloomberg** [comment]
also, if you do:

   pixXor(pixMask, pix, pixMask);

the result you want will end up in pixMask, rather than creating another pix.

**Comment by tdhintz** [comment]
Attached are two images for the two different SELs I used with pixHMT.  In other words, these are the output of the pixHMT().  I've clipped a part of the image using MS Paint with grid lines so the pixels are easier to identify.  The two pictures are not exactly to scale, but what is important is that "ooooXoooo" did not match a hit.  The source image is #270 

![hmt](https://user-images.githubusercontent.com/10895586/29848951-c9bda714-8cf1-11e7-8c18-8f385728874d.jpg)


The first HMT output was from this.
selCreateFromString("ooooXoooo", 3, 3, null);

The second is from this.
selCreateFromString("xxxxOXXXX", 3, 3, null);

This is the source image description:

DIRECTORY, TAG, VALUE
Exif IFD1, New Subfile Type, Single page of multi-page image
Exif IFD1, Image Width, 636 pixels
Exif IFD1, Image Height, 824 pixels
Exif IFD1, Bits Per Sample, 1 bits/component/pixel
Exif IFD1, Compression, T6/Group 4 Fax
Exif IFD1, Photometric Interpretation, WhiteIsZero
Exif IFD1, Fill Order, Normal
Exif IFD1, Strip Offsets, 258
Exif IFD1, Orientation, Top, left side (Horizontal / normal)
Exif IFD1, Samples Per Pixel, 1 samples/pixel
Exif IFD1, Rows Per Strip, 824 rows/strip
Exif IFD1, Strip Byte Counts, 23812 bytes
Exif IFD1, X Resolution, 75 dots per inch
Exif IFD1, Y Resolution, 75 dots per inch
Exif IFD1, Planar Configuration, Chunky (contiguous for each subsampling pixel)
Exif IFD1, Unknown tag (0x0124), 0
Exif IFD1, Unknown tag (0x0125), 0
Exif IFD1, Resolution Unit, Inch
Exif IFD1, Page Number, 0 0

**Comment by tdhintz** [comment]
I see the problem.  I was burned by #267.

```
sel = selCreateFromString("ooooXoooo", 3, 3, null);
pixMask = pixHMT(null, pix, sel);
pixResult = pixAnd(null, pix, pixMask);
```

Or (I assume),

```
sel = selCreateFromString("ooooXoooo", 3, 3, null);
pixMask = pixHMT(null, pix, sel);
pixAnd(pix, pix, pixMask);
```
