### ISSUE TITLE
leptonica\src\leptprotos.h(1042): error C2955: 'std::allocator': use of class template requires template argument list

### ISSUE THREAD

**Issue by estekitaly** [DanBloomberg/leptonica#280]
I'm trying to build tesseract 3.02 using leptonica 1.68 I get the following error:
leptonica\src\leptprotos.h(1042): error C2955: 'std::allocator': use of class template requires template argument list

this is the line that the error refers to inside leptprotos

`LEPT_DLL extern void setPixMemoryManager ( void * ( allocator ( size_t ) ), void  ( deallocator ( void * ) ) );`

how do I solve this?

**Comment by DanBloomberg** [comment]
1.68 is at least 5 years old,  This problem was addressed many years ago.

Please use cmake with  1.74.4.
