### ISSUE TITLE
README - Visual Studio

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#281]
>http://www.leptonica.org/source/README.html

>3. Building on Windows
>
>   (a) Building with Visual Studio

Looks outdated.

What about cppan info?

**Comment by egorpugin** [comment]
Short form:
1. Download the latest CPPAN (C++ Archive Network https://cppan.org/) client from https://cppan.org/client/.
2. Run
git clone https://github.com/DanBloomberg/leptonica
cd leptonica
cppan
mkdir build && cd build
cmake ..
3. Build a solution (leptonica.sln) in your Visual Studio version.
```

FYI: I'm working on cppan v2 with very major changes. ETA by the end of the year/early months of 2018. Then we can add more information on building. v2 fixes drawbacks of current version and won't change in future (with near 100% prob.). So, building instructions will be pretty stable at that time.

**Comment by DanBloomberg** [comment]
README is updated.   Thanks, Egor!

**Comment by amitdo** [comment]
Dan, what about your site? 
http://www.leptonica.org/source/README.html

I don't see the update there.

**Comment by DanBloomberg** [comment]
yes, that's a bit more work, and I've been reluctant to remove Tom's
distribution.  However, it's at least 5 years out of date, so ...  this
weekend it gets cleaned up.

**Comment by amitdo** [comment]
Dan, your site is still not updated.

**Comment by DanBloomberg** [comment]
Ah, thank you for reminding me!

And I see that you were asking me to update leptonica.org with the new README.html, which is trivial. I was thinking of cleaning up the major pages on the site, including Tom's unsupported distribution, which I have now done.  Mostly reformatting to make it look better.

Looking forward to Egor's new cppan.  Anything else you'd like, just let me know.
