### ISSUE TITLE
does pixWrite change 1bpp to 8bpp?

### ISSUE THREAD

**Issue by drgottjr** [DanBloomberg/leptonica#284]
working with leptonica through javacpp on android.  so far, so good.  many thanks.  i have found a problem, and i don't know whether it's occurring up the line or down the line from pixConvertto1().

this is the flow:  
1) take picture with device camera
2) save as full color jpg
3) load image (pixRead) from device
4) preprocess image and hand off to tesseract for ocr.
5) return text (if any) to user

preprocessing involves converting the color image to grayscale, binarizing, deskewing and rotating.
maybe some dilation and erosion, but, for the most part and for my purposes, the above operations give me very good results.

the problem i encountered involved saving an image which had been "convertedto1" for some debugging.   after saving the image (pixWrite()) and reading it back later, its depth was reported as 8bpp.  this caused some operations (notably deskewing to fail, since it requires 1bpp).   under normal circumstances the flow described above starts with a 32bpp image and does not involve saving intermediate images along the way.  and convertto1() does, in fact, return a 1bpp image.  something appears to happen between pixWrite() and later with pixRead()

my question is: are you aware of pixWrite()'s saving a 1bpp image as 8bpp?  or is there, perhaps, something pixRead() does that i should know about and which i can prevent?  i also realize there could be some manipulation occurring on the android side.  but it would help to eliminate suspects.

many thanks in advance
-go

**Comment by DanBloomberg** [comment]
Everything you describe seems reasonable except for this last part.
I should have a chance to look at the issue on Monday.  The only thing that comes to mind without looking at the code is the issue of whether something is saved with a colormap.  leptonica deliberately does not handle 1 bpp cmap images or produce 1 bpp cmap png files.  Are you saving such an image?

**Comment by drgottjr** [comment]
the short answer is i don't know.  that is to say, i'm not doing anything that i'm aware of to save images with a colormap (also, i use the .jpg format).  since i am only interested in black and white images in order to extract text, i was trying to ignore any mention relating to color maps in the documentation.
i'll go over the functions i use to see where i should have paid more attention.  

i do note that the documentation for pixConvertTo1() says that if the input has a colormap, it's removed.  so at least i know for sure that the returned image is 1bpp and no color map.  since i immediately pixWrite() the image, it would seem it's picking up a few more bpp on the way back from android.  the code posted for pixRead() seems pretty straightforward, but i didn't fully follow the trail started by filegetformat()...

in any case, unless you happen to see something to the contrary, i'll assume it's me who needs to check more closely the functions i use to see if one or more expect or don't expect a color map and what happens if they do or don't see one.  thanks again for your time.  and the project.

-go

**Comment by drgottjr** [comment]
.jpg apparently cannot be 1bpp.  it'll be 8bpp minimum.  if i want to save intermediate images for inspection i'll have to try a different format.  probably .bmp.  i apologize for the false alarm.
-go

**Comment by DanBloomberg** [comment]
Yes, that would do it.  Suggest png or tiff-g4 for saving 1 bpp images.  These have good compression, whereas bmp saved by leptonica is not compressed.
