### ISSUE TITLE
Conan package for Leptonica library

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [DanBloomberg/leptonica#285]
Hello
Do you know about Conan package manager? Can you add Conan package for leptonica and maintain it? Here you can find example of my conan recipe for libpng: https://github.com/ZaMaZaN4iK/conan-libpng

**Comment by DanBloomberg** [comment]
No, I didn't know about it.

Sorry, can't use this package manager on leptonica.

**Comment by amitdo** [comment]
Leptonica has cppan package.

https://github.com/cppan/cppan
https://github.com/DanBloomberg/leptonica/blob/master/cppan.yml

Also related: 
https://github.com/Microsoft/vcpkg/tree/master/ports/leptonica
and for Tesseract:
https://github.com/Microsoft/vcpkg/tree/master/ports/tesseract
