### ISSUE TITLE
Statically linking PNG, TIFF etc.

### ISSUE THREAD

**Issue by kivancguckiran** [DanBloomberg/leptonica#287]
Hello everyone and thanks for the library. If this is not the right place to post this issue please show me the way.

I've posted on Tesseract OCR google groups but got no answer yet. What I'm trying to achieve is statically linking Leptonica and Tesseract to a shared object. And this shared object will be linked to an executable.

I've compiled Leptonica, then Tesseract. Then linked the static libraries to the shared object. After that, when I try to link this shared object to the executable, I get undefined reference errors to Leptonica functions.

I've tried linking to shared object with whole-archive option. This time I got undefined reference errors to image libraries'(PNG, TIFF) functions.

I'm using Tesseract 3.05.01, Leptonica 1.74.4 and I can provide the code and the link commands if needed.

Thanks!

**Comment by egorpugin** [comment]
What is your OS?
How do you build libraries? From some guide or yourself?

**Comment by kivancguckiran** [comment]
Hi!

```
git clone --branch=3.05 https://github.com/tesseract-ocr/tesseract/
git clone --branch=1.74.4 https://github.com/DanBloomberg/leptonica/
```

Leptonica building:
```
./autobuild
./configure

make
sudo make install
```

Tesseract building:
```
cd tesseract

./autogen.sh
./configure

make
sudo make install
```

How I try to link to the shared object:
```
g++ -I. -I/usr/local/include/tesseract -I/usr/local/include/leptonica -std=gnu++11 wrap.cpp  /usr/local/lib/liblept.a /usr/local/lib/libtesseract.a -shared -o wrap.so -fPIC -Wl,-Bsymbolic
```

Linking of the executable:
```
gcc test.c -o test wrap.so
```

And this outputs these errors:
```
wrap.so: undefined reference to `sem_init'
wrap.so: undefined reference to `pixExpandReplicate'
wrap.so: undefined reference to `pixConvertTo8'
wrap.so: undefined reference to `pixGetWpl'
...
...
wrap.so: undefined reference to `pixConvertTo32'
wrap.so: undefined reference to `pixaCreate'
wrap.so: undefined reference to `sem_wait'
collect2: error: ld returned 1 exit status
```

The files:
[Code.zip](https://github.com/DanBloomberg/leptonica/files/1512750/Code.zip)

Platform is CentOS 7.2.

```
$uname -a
3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks in advance!

**Comment by kivancguckiran** [comment]
So, I've fixed it via whole archive option with other image libraries.

For anyone having trouble regarding this issue, it goes like this:

I've first tried using whole archive option with leptonica and tesseract.
```
g++ -I. -I/usr/local/include/tesseract -I/usr/local/include/leptonica -std=gnu++11 wrap.cpp  -Wl,--whole-archive /usr/local/lib/liblept.a /usr/local/lib/libtesseract.a -Wl,--no-whole-archive -shared -o wrap.so -fPIC -Wl,-Bsymbolic
```

But this time I got undefined reference errors for image libraries.

Then I've tried linking them too:
```
g++ -I. -I/usr/local/include/tesseract -I/usr/local/include/leptonica -std=gnu++11 wrap.cpp  -Wl,--whole-archive /usr/local/lib/liblept.a /usr/local/lib/libtesseract.a /usr/local/lib/libpng16.a /usr/local/lib/libtiff.a /usr/local/lib/libjpeg.a -Wl,--no-whole-archive -shared -o wrap.so -fPIC -Wl,-Bsymbolic
```

This worked. But the linked shared object was around ~40MB. I've tried stripping it:
```
g++ -fdata-sections -ffunction-sections -I. -I/usr/local/include/tesseract -I/usr/local/include/leptonica -std=gnu++11 wrap.cpp  -Wl,--whole-archive /usr/local/lib/liblept.a /usr/local/lib/libtesseract.a /usr/local/lib/libpng16.a /usr/local/lib/libtiff.a /usr/local/lib/libjpeg.a -Wl,--no-whole-archive -shared -o wrap.so -fPIC -Wl,-Bsymbolic -Wl,--gc-sections -Wl,--strip-all
```

Now, the shared object was around 6MB.

The linking commands might contain syntactic errors but the idea is correct. I don't recall the exact linking commands for them.

Hope this helps someone.

Thanks.

**Comment by sudhirkadamHJ** [comment]
@kivancguckiran I am trying to build tesseract.
My requirement is to compile tesseract in particular folder. Here's what I have done so far,

1. install zlib, libjpeg, libpng, libtiff to build folder
2. install leptonica to build folder and copy headers to include/leptonica folder in build directory
3. install tesseract in tesseract folder with paths to build folder for libraries and includes 

I am getting following error in tesseract 'make' command,

libtool: link: g++ -fPIC -I/home/sudhir/work/assignments/buildpack/build/include -I/home/sudhir/work/assignments/buildpack/build/include/libpng16 -I/home/sudhir/work/assignments/buildpack/build/include/leptonica -std=c++11 -o tesseract tesseract-tesseractmain.o  -L/home/sudhir/work/assignments/buildpack/build/lib ./.libs/libtesseract.a -llept -lrt -lpthread
./.libs/libtesseract.a(libtesseract_api_la-baseapi.o): **In function `tesseract::TessBaseAPI::ProcessPagesMultipageTiff(unsigned char const*, unsigned long, char const*, char const*, int, tesseract::TessResultRenderer*, int)':
baseapi.cpp:(.text+0x5cb6): undefined reference to `pixReadMemFromMultipageTiff'
baseapi.cpp:(.text+0x5d71): undefined reference to `pixReadFromMultipageTiff'
./.libs/libtesseract.a(libtesseract_api_la-pdfrenderer.o): In function `tesseract::TessPDFRenderer::imageToPDFObj(Pix*, char*, long, char**, long*)':
pdfrenderer.cpp:(.text+0x555): undefined reference to `l_generateCIDataForPdf'
pdfrenderer.cpp:(.text+0x80e): undefined reference to `l_CIDataDestroy'
pdfrenderer.cpp:(.text+0x86c): undefined reference to `l_CIDataDestroy'**
collect2: error: ld returned 1 exit status
make[2]: *** [tesseract] Error 1
make[2]: Leaving directory `/home/sudhir/work/assignments/buildpack/src/tesseract-3.05.01/api'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/sudhir/work/assignments/buildpack/src/tesseract-3.05.01'
make: *** [all] Error 2
ls: cannot access /home/sudhir/work/assignments/buildpack/tesseract/bin: No such file or directory
Tesseract build failed. Exiting.

I am building with following versions of libraries,
ZLIB - 1.2.11
JPEG - 9b
PNG - 1.6.27
TIFF - 4.0.9
LEPTONICA - 1.74.4
TESSERACT - 3.05.01

Could you point me in right direction as I am not sure what I am missing.

**Comment by kivancguckiran** [comment]
@sudhirkadamHJ Hi, is the question still valid? I did not have time to look for a couple of weeks.

**Comment by sudhirkadamHJ** [comment]
@kivancguckiran the question is still valid. I can share the build script if you want a look.

**Comment by kivancguckiran** [comment]
Please do. Reproducing the problem would probably help.

**Comment by sudhirkadamHJ** [comment]
@kivancguckiran  Here is the build script

#!/bin/bash
#
# Build Script for making standalone version of Tesseract
# Originally posted at:https://code.google.com/p/tesseract-ocr/issues/detail?id=1326
# Original pastebin source: http://pastebin.com/VnGLHfbr
# NOTE:
# you must set 2 environment variables to locate the runnable version of Tesseract:
#   TESSDATA_PREFIX - set to the parent folder for the tessdata folder
#   DYLD_LIBRARY_PATH - set to the path up to and including the lib folder
#
# the runnable version of Tesseract consists of the folder "tesseract" with the following content (comments in brackets):
#
#      bin (folder)
#            tesseract (the executable itself)
#      include (folder)
#            
#      lib (folder - pointed to by DYLD_LIBRARY_PATH)
#            
#      share (folder - pointed to by TESSDATA_PREFIX)
#            man (folder)
#            tessdata (folder)

BUILD_LIBJPEG=1
BUILD_ZLIB=1
BUILD_LIBPNG=1
BUILD_LIBTIFF=1
BUILD_LEPTONICA=1
BUILD_TESSERACT=1

# Get the base directory of where the script is
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BUILD_DIR="$BASE_DIR"/build
ARCHIVE_DIR="$BASE_DIR"/archives
SRC_DIR="$BASE_DIR"/src
TESSERACT_DIR="$BASE_DIR"/tesseract

LIBJPEG_VERSION=9b
ZLIB_VERSION=1.2.11
LIBPNG_VERSION=1.6.27
LIBTIFF_VERSION=4.0.9
LEPTONICA_VERSION=1.74.4
TESSERACT_VERSION=3.05.01


bail_out()
{
    echo
    echo "  Something went wrong, HALTING BUILD!" 
    echo
    exit 1
}

echo
echo
echo "STARTING BUILD"
echo 

if [ ! -d "$ARCHIVE_DIR" ]; then
	mkdir "$ARCHIVE_DIR"
fi

if [ ! -d "$SRC_DIR" ]; then
	mkdir "$SRC_DIR"
fi

if [ ! -d "$BUILD_DIR" ]; then
	mkdir "$BUILD_DIR"
fi

echo "Base Build Directory: "
echo "    -> $BUILD_DIR"

#fPIC flag for shared object error ('.rodata' can not be used when making a shared object)
# export CC="gcc -fPIC"
# export CXX="g++ -fPIC"

# FIRST - Build lib Libjpeg
if [[ "$BUILD_LIBJPEG" = 1 ]]
then
        echo
        echo "Building Lib Jpeg"

        # Clean up old files
        rm -rf $SRC_DIR/jpeg* $BUILD_DIR/jpeg*

        if [ ! -f $ARCHIVE_DIR/jpegsrc.v$LIBJPEG_VERSION.tar.gz ]; then
			#Download the file
			curl -o $ARCHIVE_DIR/jpeg.v$LIBJPEG_VERSION.tar.gz http://www.ijg.org/files/jpegsrc.v$LIBJPEG_VERSION.tar.gz
        fi

        echo "Extracting archive"
        tar -xzf $ARCHIVE_DIR/jpeg.v$LIBJPEG_VERSION.tar.gz -C $SRC_DIR

        cd $SRC_DIR/jpeg-$LIBJPEG_VERSION

		./autogen.sh

        echo "Configuring Lib Jpeg for Standalone"
        ./configure --disable-shared --prefix=$BUILD_DIR

        echo "Building LIBJPEG and deploying to "
        echo "    -> $BUILD_DIR"
        make install

        #Check if the build was successful
        if [ -f $BUILD_DIR/include/jpeglib.h ]; then 
			echo "LIB JPEG Build Successful"
        else
			echo "LIBJPEG build failed. Exiting."
			exit 1
        fi
else
        echo "Skipping LIBJPEG"
fi


export LDFLAGS="-L$BUILD_DIR/lib"
export CFLAGS="-I$BUILD_DIR/include"

echo "Exporting pkgconfig folder path to pkg_config_path"
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$BUILD_DIR/lib/pkgconfig

# SECOND - Build lib zlib 
if [[ $BUILD_ZLIB = 1 ]]
then
        echo
        echo "Building ZLIB"

        # Clean up old files
        rm -rf $SRC_DIR/zlib* $BUILD_DIR/zlib*

        if [ ! -f $ARCHIVE_DIR/zlib-$ZLIB_VERSION.tar.gz ]; then
			#Download the file
			curl -o $ARCHIVE_DIR/zlib-$ZLIB_VERSION.tar.gz http://zlib.net/fossils/zlib-$ZLIB_VERSION.tar.gz
        fi

        echo "Extracting archive"
        tar -xzf $ARCHIVE_DIR/zlib-$ZLIB_VERSION.tar.gz -C $SRC_DIR

        cd $SRC_DIR/zlib-$ZLIB_VERSION

        echo "Configuring ZLIB for Standalone"
        ./configure --solo --static
        echo "Building Zlib and deploying to "
        echo "    -> $BUILD_DIR"
        make install prefix=$BUILD_DIR

        #Check if the build was successful
        if [ -f $BUILD_DIR/include/zlib.h ]; then 
			echo "ZLIB Build Successful"
        else
			echo "ZLIB build failed. Exiting."
			exit 1
        fi
else
        echo "Skipping ZLib"
fi

# THIRD - Build Lib PNG
if [[ $BUILD_LIBPNG = 1 ]]
then
      	echo
        echo "Building Lib PNG"

        # Clean up old files
        rm -rf $SRC_DIR/libpng* $BUILD_DIR/libpng*

        if [ ! -f "$ARCHIVE_DIR/libpng-$LIBPNG_VERSION.tar.gz" ]; then
			#Download the file
			curl -L -o $ARCHIVE_DIR/libpng-$LIBPNG_VERSION.tar.gz http://downloads.sourceforge.net/project/libpng/libpng16/older-releases/$LIBPNG_VERSION/libpng-$LIBPNG_VERSION.tar.gz?use_mirror=excellmedia
        fi

        echo "Extracting archive"
        tar -xzf $ARCHIVE_DIR/libpng-$LIBPNG_VERSION.tar.gz -C $SRC_DIR

        cd "$SRC_DIR/libpng-$LIBPNG_VERSION"

		echo "Copying libz header files to libpng"
        cp $BUILD_DIR/include/zlib.h .
        cp $BUILD_DIR/include/zconf.h .

		./autogen.sh

        echo "Configuring Lib PNG for Standalone"
        ./configure --disable-shared --disable-static --prefix=$BUILD_DIR \
CXXFLAGS="-I$BUILD_DIR/include" \
CPPFLAGS="-I$BUILD_DIR/include"

        echo "Building LIBPNG and deploying to $BUILD_DIR"
        make check
        make install

        #Check if the build was successful
        if [ -f "$BUILD_DIR/include/libpng16/png.h" ]; then 
			echo "LIB PNG Build Successful"
        else
			echo "LIBPNG build failed. Exiting."
			exit 1
        fi

else
        echo "Skipping LIBPNG"
fi


# FOURTH - Build lib Libtiff
if [[ "$BUILD_LIBTIFF" = 1 ]]
then
        echo
        echo "Building Lib Tiff"

        # Clean up old files
        rm -rf $SRC_DIR/tiff* $BUILD_DIR/tiff*

        if [ ! -f $ARCHIVE_DIR/jpegsrc.v$LIBTIFF_VERSION.tar.gz ]; then
			#Download the file
			curl -o $ARCHIVE_DIR/tiff-$LIBTIFF_VERSION.tar.gz http://download.osgeo.org/libtiff/tiff-$LIBTIFF_VERSION.tar.gz
        fi

        echo "Extracting archive"
        tar -xzf $ARCHIVE_DIR/tiff-$LIBTIFF_VERSION.tar.gz -C $SRC_DIR

        cd $SRC_DIR/tiff-$LIBTIFF_VERSION

		./autogen.sh

        echo "Configuring Lib Tiff for Standalone"
        ./configure --disable-shared --disable-static --prefix=$BUILD_DIR \
CXXFLAGS="-I$BUILD_DIR/include" \
CPPFLAGS="-I$BUILD_DIR/include"

        echo "Building LIBTIFF and deploying to "
        echo "    -> $BUILD_DIR"
        make install

        #Check if the build was successful
        if [ -f $BUILD_DIR/include/tiff.h ]; then 
			echo "LIB TIFF Build Successful"
        else
			echo "LIBTIFF build failed. Exiting."
			exit 1
        fi
else
        echo "Skipping LIBTIFF"
fi

# FIFTH - Build Leptonica
if [[ $BUILD_LEPTONICA = 1 ]]
then
        echo
        echo "Building Leptonica"

        # Clean up old files
        rm -rf $SRC_DIR/leptonica* $BUILD_DIR/leptonica*

        if [ ! -f $ARCHIVE_DIR/leptonica-$LEPTONICA_VERSION.tar.gz ]; then
			#Download the file
			curl -o $ARCHIVE_DIR/leptonica-$LEPTONICA_VERSION.tar.gz http://www.leptonica.com/source/leptonica-$LEPTONICA_VERSION.tar.gz
        fi

        echo "Extracting archive"
        tar -xzf $ARCHIVE_DIR/leptonica-$LEPTONICA_VERSION.tar.gz -C $SRC_DIR

        cd $SRC_DIR/leptonica-$LEPTONICA_VERSION

		./autobuild
        
        echo "Configuring leptonica for standalone"
        ./configure --disable-shared --disable-static --prefix=$BUILD_DIR --without-giflib --without-libwebp --without-libopenjpeg \
LDFLAGS="-L$BUILD_DIR/lib" \
CXXFLAGS="-I$BUILD_DIR/include -I$BUILD_DIR/include/libpng16" \
CPPFLAGS="-I$BUILD_DIR/include -I$BUILD_DIR/include/libpng16"
		
        echo "Building LEPTONICA and deploying to "
        echo "    -> $BUILD_DIR"
		make


        #Check if the build was successful
        if [ -f $SRC_DIR/leptonica-$LEPTONICA_VERSION/src/.libs/liblept.a ]; then 
			echo "Leptonica Build Successful"
        else
			echo "LEPTONICA build failed. Exiting."
			exit 1
        fi

        echo "Copying files for Tesseract"
        # cp $SRC_DIR/leptonica-$LEPTONICA_VERSION/src/.libs/liblept.a $BUILD_DIR/lib

        if [ ! -f $BUILD_DIR/include/leptonica ]; then
			mkdir $BUILD_DIR/include/leptonica
        fi

        cp $SRC_DIR/leptonica-$LEPTONICA_VERSION/src/*.h $BUILD_DIR/include/leptonica

		echo "Copying lept.pc to pkgconfig"
		cp $SRC_DIR/leptonica-$LEPTONICA_VERSION/lept.pc $BUILD_DIR/lib/pkgconfig

		pkg-config --cflags lept
  		pkg-config --libs lept	

else
        echo "Skipping Leptonica"
fi

# FINALLY - Build Tesseract
if [[ $BUILD_TESSERACT = 1 ]]
then
        echo
        echo "Building Tesseract"
        
        rm -rf $SRC_DIR/tesseract*

        #Create Tesseract Build Directory
        if [ ! -d $TESSERACT_DIR ]; then
			mkdir $TESSERACT_DIR
        else
			rm -rf $TESSERACT_DIR/*
        fi

        if [ ! -f $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz ]; then
			#Download the file
			curl -L -o $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz https://github.com/tesseract-ocr/tesseract/archive/$TESSERACT_VERSION.tar.gz
       	fi
 
       	echo "Extracting archive"
    	tar -xzf $ARCHIVE_DIR/tesseract-$TESSERACT_VERSION.tar.gz -C $SRC_DIR
		      
        cd $SRC_DIR/tesseract-$TESSERACT_VERSION
        
        echo "Running autogen"
        ./autogen.sh || bail_out

		# export LIBLEPT_HEADERSDIR=$BUILD_DIR/include/leptonica
        
		echo "Configuring Tesseract"
        ./configure --disable-shared --disable-static --prefix=$TESSERACT_DIR --with-extra-libraries=$BUILD_DIR/lib \
CXXFLAGS="-I$BUILD_DIR/include -I$BUILD_DIR/include/libpng16 -I$BUILD_DIR/include/leptonica" \
CPPFLAGS="-I$BUILD_DIR/include -I$BUILD_DIR/include/libpng16 -I$BUILD_DIR/include/leptonica" \
LDFLAGS="-L$BUILD_DIR/lib" \
PKG_CONFIG_LIBDIR=$BUILD_DIR/lib/pkgconfig

        echo "Start Building Tesseract"
        make

        ls $TESSERACT_DIR/bin

        if [ -x $TESSERACT_DIR/bin/tesseract ]; then
			echo "Tesseract Build Successful"
        else
			echo "Tesseract build failed. Exiting."
			exit 1
        fi

        echo "Checking the language files"
        if [ ! -f "$ARCHIVE_DIR/eng.traineddata" ]; then
			#Download the file
			curl -L -o $ARCHIVE_DIR/eng.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/eng.traineddata
        fi

        echo "Checking OSD (Optical Script Detection) models"
        if [ ! -f "$ARCHIVE_DIR/osd.traineddata" ]; then
			#Download the file
			curl -L -o $ARCHIVE_DIR/osd.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/osd.traineddata
        fi

		echo "Checking MD (Math / equation detection) models"
		if [ ! -f "$ARCHIVE_DIR/eq.traineddata" ]; then
			#Download the file
			curl -L -o $ARCHIVE_DIR/eq.traineddata https://github.com/tesseract-ocr/tessdata/raw/3.04.00/equ.traineddata
        fi

        echo "Installing Languages, OSD and MD"
        cp $ARCHIVE_DIR/eng.traineddata -C $TESSERACT_DIR/bin
        cp $ARCHIVE_DIR/osd.traineddata -C $TESSERACT_DIR/bin
		cp $ARCHIVE_DIR/eq.traineddata -C $TESSERACT_DIR/bin

        cd $TESSERACT_DIR/bin
		
		export TESSDATA_PREFIX=$TESSERACT_DIR/share
        export DYLD_LIBRARY_PATH=$TESSERACT_DIR/lib

        echo "Tesseract is now built and can be found at: $BUILD_DIR"

else
        echo "Skipping Tesseract"
fi

**Comment by sudhirkadamHJ** [comment]
@kivancguckiran here is the build script

[install.zip](https://github.com/DanBloomberg/leptonica/files/1614914/install.zip)
