### ISSUE TITLE
[Question] how to remove black background from text image using leptonica

### ISSUE THREAD

**Issue by hoangtocdo90** [DanBloomberg/leptonica#290]
I need remove black area and convert white text to black.
Any ones can help me?
Thanks so much! 
Example : 
![untitled](https://user-images.githubusercontent.com/22963463/34031977-495dbd5a-e1b7-11e7-976d-d82ead8d12bf.png)

**Comment by zdenop** [comment]
It is called invert. There are plenty information on internet how to do it with plenty tools...
Or you can try this [image-processing-for-ocr-with-leptonica-inverse-color-text](https://stackoverflow.com/questions/11678542/image-processing-for-ocr-with-leptonica-inverse-color-text)
