### ISSUE TITLE
add the option to compile with -fPIC even when static library

### ISSUE THREAD

**Issue by lordadamson** [DanBloomberg/leptonica#292]
Hi, I'd like to compile leptonica as a static library that is compiled with the `fPIC` flag because I'll later incorporate it into a dynamic library of my own.

Currently I have to add the `-fPIC` flag myself into the Makefile but it would be super awesome if there was an argument that I could pass to the make file or maybe to a configure script or whatever. That would help a lot automating the build process in CI environments and such.

Thank you in advance.

**Comment by chewi** [comment]
You're probably better off using the autotools configure/make scripts, which respect CFLAGS and friends, rather than the static Makefile.

**Comment by DanBloomberg** [comment]
3 options: cmake, autotools, static (hand built) makefile.  See README.html.

For the static makefiles, you need to edit environ.h, depending on the external libraries you want to use, and you can change the compiler directives in src/makefile and prog/makefile.
