### ISSUE TITLE
Access Leptonica in Visual Basic 2017

### ISSUE THREAD

**Issue by wills2018** [DanBloomberg/leptonica#294]
Hi I’m using Emgu and OpenCV to do some image processing in VB. I need to use the Leptonica “Convert to Pix” function is there any way I can do this in VB?

**Comment by DanBloomberg** [comment]
I haven't investigated it, but I don't know any way to call leptonica from functions in visual basic.

Is VB even supported by Microsoft?. The last stable version was 20 years ago  :-)

**Comment by amitdo** [comment]
He probably means VB.Net.

**Comment by DanBloomberg** [comment]
Someone else may know if VB Net can link leptonica, or if it has functions that convert between OpenCV raster images and Pix.  Absent a conversion function, and assuming leptonica can be called from VB Net, you could write the pix out as a png from OpenCV, and then read it back from leptonica.

**Comment by amitdo** [comment]
https://github.com/emgucv/emgucv/

>Emgu CV is a cross platform .Net wrapper to the OpenCV image processing library. Allowing OpenCV functions to be called from .NET compatible languages such as C#, VB, VC++, IronPython etc. The wrapper can be compiled by Visual Studio, Xamarin Studio and Unity, it can run on Windows, Linux, Mac OS X, iOS, Android and Windows Phone.

https://github.com/emgucv/emgucv/blob/6147e01967fc/Emgu.CV.OCR/Pix.cs

http://www.emgu.com/forum/viewforum.php?f=9&sid=4764f76da9cb1a195605bd3fa619b9cb

**Comment by DanBloomberg** [comment]
If they wrap all of leptonica, unless openCV has a converter from its image format to Pix, you'll need to do your own.  It shouldn't be hard -- you need to pack the openCV image raster data in the format required for Pix, as described in pix.h.

**Comment by wills2018** [comment]
Gentlemen. Thank you for your help and I have a Pix! I would now like to create a searchable PDF and it seems like I need Tesseract v4 to do this. Before I set out on this adventure do you know if this will co-exist with Emgu 3.3.0.2824?

**Comment by amitdo** [comment]
They are using Tesseract 4.0 since emgucv 3.2.

http://www.emgu.com/wiki/index.php/Version_History
https://github.com/emgucv/tesseract/commits/master

**Comment by wills2018** [comment]
Thank you amitdo. I've written code that OCRs a document perfectly well. The reason for my confusion is that in trying to convert Charles example of "Creating a searchable PDF" Tesseract doesn't seem to expose the methods I require. See below. There doesn't appear to be much documentation or any examples I can refer to. Most frustrating. I don't know if you can help?
![ocr test](https://user-images.githubusercontent.com/34859224/35221212-41eeac50-ff71-11e7-9b15-d7a61b379fbe.jpg)

**Comment by DanBloomberg** [comment]
you may want to move this onto tesseract-ocr

**Comment by amitdo** [comment]
I don't have any experience with c#/vb, so I can't help, sorry.

Don't use the Tesseract 'issues', it's intended for bug reports.
For questions, you can try tesseract-ocr forum.
https://groups.google.com/d/forum/tesseract-ocr

I think you should try asking emgucv / carelsw first.

**Comment by amitdo** [comment]
I'm sorry, I meant charlesw.
https://github.com/charlesw/tesseract

I don't see that he has a forum, so open an issue with your question.
https://github.com/charlesw/tesseract/issues

Another possible place you can try is stackoverflow.com
Here is an example for a question:
https://stackoverflow.com/questions/26162169/tesseract-net-process-image-from-memory-object

**Comment by Phreak87** [comment]
i have written a wrapper for Leptonica: LeptonicaSharp.
with this you have the option PixToBitmap and PixFromBitmap

**Comment by amitdo** [comment]
https://github.com/Phreak87/LeptonicaSharp

It licensed under GPLV3.  I suggest to change it to the same [license of Leptonica](https://github.com/DanBloomberg/leptonica/blob/master/leptonica-license.txt) (2-Clause BSD) or another permissive license (MIT/Apache 2.0), so more developers can use it.
