### ISSUE TITLE
Documentation - I think it's out of date?

### ISSUE THREAD

**Issue by lwm** [DanBloomberg/leptonica#295]
In order to get things done, I had to:

```bash
$ ./autobuild
$ ./configure
$ make
$ make install
```

Which is not what is written on https://tpgit.github.io/UnOfficialLeptDocs/leptonica/README.html#building-on-linux-unix-macos. Assuming this is out of date, would it make sense to reduce these steps to these few steps, which are a bit easier to grok.

**Comment by stweil** [comment]
That unofficial documentation should be fine if you start with the tar file which is provided for each release. That tar file includes `configure` and other files made by `autobuild`, so it is not necessary to run that script.

For building from Git sources, using the official documentation (part of the distribution) would be better.

**Comment by lwm** [comment]
Ah, I see. There are different documentations, thanks!

**Comment by DanBloomberg** [comment]
I've been reluctant to do it, but the "unofficial" documentation went with 1.68 and is at least 5 years old, so perhaps I should just delete it because it's confusing?

Stefan, what's your take on that?

**Comment by stweil** [comment]
Maybe start with replacing the current text? Here is a possible variant:

Old:
- Tom Powers has built the Unofficial Leptonica Documentation. It covers much of the information in these pages and is more easily navigated. You are encouraged to use it.

New:
- Tom Powers has built the Unofficial Leptonica Documentation. It only covers the versions up to 1.68 (2011), but is more easily navigated. You can use it, but be aware that some information might be no longer valid.

I'd also move that information from the first position in the list down to a less prominent position.

**Comment by DanBloomberg** [comment]
Stefan, great suggestions.  Done.
