### ISSUE TITLE
restrict giflib to > 5.1.2

### ISSUE THREAD

**Issue by DanBloomberg** [DanBloomberg/leptonica#301]
@chewi 

Can we modify configure.ac to only use giflib libraries with version > 5.1.2?

At present, configure.ac will say that we have a giflib with old gif libraries, and anything older than 5.1 will fail in the compile phase because the interface changed going from 4.X --> 5.0, and then again from 5.0 --> 5.1.

One other modification needed is for openjpeg, to include the header file
   openjpeg-2.3/openjpeg.h
as a match.

**Comment by chewi** [comment]
I should be able to do a check for the new method signature but it should also be fairly easy to support both, which I think it worthwhile. I'll give this a shot.

**Comment by DanBloomberg** [comment]
leptonica no longer supports giflib before 5.1, and 5.1.2 doesn't work, which is why I indicated > 5.1.2.

However, if essentially nobody is using 5.1.2 (it was patched within a week to 5.1.3), then 5.1+ would be appropriate.

**Comment by chewi** [comment]
I was going to ask if you weren't supporting 4 simply because the method signature had changed but on closer inspection, I see you are making use of new features so fair enough. It's unfortunate that some distributions, notably CentOS/RHEL and Fedora (!?), are still lagging behind on 4 but I guess supporting it isn't worth the effort.

**Comment by amitdo** [comment]
@chewi , you might want read this: https://github.com/tesseract-ocr/tesseract/issues/1215

**Comment by DanBloomberg** [comment]
The fact that all those distributions are still at 4.X, and not even supporting 5.X, seems to be an example of one of the weaknesses of the open source ecosystem, which in some (hopefully rare) situations like this becomes mired down with issues of supporting bad old source versions with incompatible interfaces.

I can hope that this decision for leptonica to stop the nonsense with 4.x and 5.0 giflib helps spur others to clean this up.

**Comment by amitdo** [comment]
I'm really surprised about Fedora's giflib.

https://apps.fedoraproject.org/packages/giflib
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/KGF2P73NHDEH7GV34YI7WYCVABLMU7HK/

**Comment by amitdo** [comment]
An update:


https://bugzilla.redhat.com/show_bug.cgi?id=822844
https://fedoraproject.org/wiki/Changes/GifLib5?rd=User:Smani/Changes/GifLib5

Thanks to @manisandro

**Comment by amitdo** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=822844

Sandro Mani 2018-01-22 18:11:54 EST
>I can hope that this decision for leptonica to stop the nonsense with 4.x and 5.0 giflib helps spur others to clean this up.

>Since leptonica went giflib-5 only, I gave it a shot [1], overall does not look bad most build out of the box, a few need some minor patching.

**Comment by chewi** [comment]
See #304.

**Comment by egorpugin** [comment]
You can click on dependencies' versions on this page to check what leptonica uses.
https://cppan.org/pvt.cppan.demo.danbloomberg.leptonica/version/1.75.1
Currently it's openjpeg 2.3.0 and giflib 5.1.4.

**Comment by DanBloomberg** [comment]
This issue is settled.   No tesseract or leptonica support for giflib  before 5.1.

Thank you all for making this happen!
