### ISSUE TITLE
italic_reg depends on gnuplot?

### ISSUE THREAD

**Issue by chewi** [DanBloomberg/leptonica#305]
Seems like this needs to be added to the gnuplot list. The source doesn't seem to indicate that this would be required but it fails without it.

**Comment by DanBloomberg** [comment]
yes, I'll add it to the list.  The culprit is pixWordMaskByDilation() in debug mode.

Also, wordboxes_reg.c needs to be on the list, because it calls pixWordMaskByDilation.

**Comment by DanBloomberg** [comment]
fixed
