### ISSUE TITLE
Leptonica for OCR image preprocessing

### ISSUE THREAD

**Issue by Artgit** [DanBloomberg/leptonica#311]
Hello,

I need to preprocess scanned images in order to improve the following OCR quality. I already able to remove horizontal and vertical lines with Leptonica(Java lept4j) library.

I just wondering if there is a scripts written with Leptonica library in order to do the image preprocessing - for example, cleaning scanning artifacts, noise, etc. Thanks!

**Comment by DanBloomberg** [comment]
Once the image has been binarized (1 bpp), all you can do is remove speckle noise, which is small foreground components that you wish to be part of the background.

This can be done morphologically, e.g., using a hit-miss operator to identify small isolated foreground components.  See, e.g. livre_hmt.c, findpattern*.c, arabic_lines.c for what these operations can do.  What you want is something simpler yet; say, a square of don't-cares surrounded by a square of misses.  For example, to remove any components that fit into a 2x2 square, you could generate this hmt sel:

static const char *selstr = "oooo"
                                     "oC o"
                                     "o   o"
                                     "oooo";
Sel *sel1 = selCreateFromString(selstr, 4, 4, "some name");

Then 
Pix *pix2 = pixHMT(NULL, pix1, sel1);

This gives you a foreground pixel at "C" wherever you get a match with the square of misses.
You can then dilate the result with a 2x2 Sel

Sel *sel2 = selCreateBrick(2, 2, 0, 0, SEL_HIT);

to get a 2x2 square of fg pixels wherever there was a fg pixel:

Pix *pix3 = pixDilate(NULL, pix2, sel2);

Finally, set subtract the result from the original:

pixSubtract(pix1, pix1, pix3);

I can make a little program to demonstrate this.

**Comment by Artgit** [comment]
@DanBloomberg thank you very much for your answer! I'll really appreciate if you can create the program to demonstrate this. Thanks!

**Comment by DanBloomberg** [comment]
@Artgit 
The program is checked in:
   prog/speckle_reg.c
and I've added it to the regression test suite.
In it I showed how to remove speckle up to 2x2 and up to 3x3.
If you run the program with the argument generate
     speckle_reg generate
it will put some golden files in /tmp/lept/golden
If you run it with the argument display
    speckle_reg display
it will display the results on your screen. That image will be in
    /tmp/lept/regout/speckle.08.jpg

**Comment by Artgit** [comment]
@DanBloomberg thank You very much !!! Currently, I'm trying to port it to Java lept4j JNA wrapper - https://github.com/nguyenq/lept4j/issues/15 This is almost work except I'm still unable right now to port the last code block

**Comment by Artgit** [comment]
@DanBloomberg , could you please show the example how to remove the scanning artifacts from the following images(for example remove punch holes, invert the text on the black areas):
![cleanup-before-after](https://user-images.githubusercontent.com/2064812/36662842-631118f4-1ae8-11e8-825d-eb6d4ff02ee5.jpg)

or the scanning artifacts like the following:

![demo](https://user-images.githubusercontent.com/2064812/36663491-67b9f5cc-1aea-11e8-8b03-b4685710ce0a.png)

**Comment by DanBloomberg** [comment]
These are tough.  I'll leave them as an exercise for you  :-)

**Comment by Artgit** [comment]
yeah.. unfortunately, I have no idea how to solve it. Anyway, thanks for your previous help!

**Comment by DanBloomberg** [comment]
There are functions for automatic deskew that would be helpful for some of these images, and can be used before trying to run OCR..  (see skew.c)

Tesseract should do OK with handling some of the white text on black background.

The function I gave you will remove some of the speckle around the text in your example.

**Comment by Artgit** [comment]
Thanks, I have already implemented own deskew function. I need to clear the image noise as much as possible because I can have a few different scanned documents on the single page(image) under the different angles, and this way I'd like to extract all of them separately, deskew them and place back into canvas based on their previous coordinates. Otherwise OCR Engine unable to properly recognize them. This is why I'd like to clear the scanning noise(for example like presented on images above) because when I use Morphological Dilation and then Connected Components approaches, the noise connects these documents.

**Comment by DanBloomberg** [comment]
Your own deskew function?  Not using something in skew.c?

See:  http://leptonica.org/skew-measurement.html

**Comment by Artgit** [comment]
Thanks, I'll investigate this documentation. I mean I already use some implementation based on Hough Transform(not from the Leptonica package) and I can fix the skew for a single document but right now I faced the issue described above with multiple scanned documents on the single page and I need to deskew them separately.

**Comment by DanBloomberg** [comment]
Read the papers I wrote that are referenced there.  Hough is poor for several reasons.

Variance of differential row pixel projections is the way to do it.

**Comment by Artgit** [comment]
Thanks @DanBloomberg ,  I read the articles, they look really interesting. Now, I understand much better how to deskew the images.  But I still don't undertand how to automatically divide the single image into the separated parts and to deskew them separately.

**Comment by DanBloomberg** [comment]
you can't do it in general.

If you know that the image may be composed of two different parts with different skew, you can divide the image into 2 or 3 parts, each with width 1/2 or 1/3 of the full width (using pixRasterop()), and perform the skew angle calculation on each part.

**Comment by Artgit** [comment]
What do you think about the following approach https://stackoverflow.com/questions/48630743/opencv-remove-background-noise-and-artifacts ? For example, erode, dilate, find contours, perform deskew for every contour. Can this approach potentially work in this case?

**Comment by DanBloomberg** [comment]
so much easier with leptonica  :-)

just use the leptonica skew finder.  It uses all the pixels, not just a selected subset, and the algorithm is much more robust.   (leptonica is also much faster than opencv, if that's of any importance)

**Comment by Artgit** [comment]
>>It uses all the pixels, not just a selected subset

this is exactly the issue I'd like to solve and this is why I need to find the contours(I may be wrong anyway). I can have several different documents under the different angles on the same image:

![example2](https://user-images.githubusercontent.com/2064812/36750369-0a7b718e-1c06-11e8-9abd-170d14ee3303.png)

and I need to deskew them on this image, to have something like the following image:

![example](https://user-images.githubusercontent.com/2064812/36750404-1c7d3372-1c06-11e8-881e-bdcc7e878522.png)

**Comment by DanBloomberg** [comment]
If you expect that the images can be in both landscape and portrait orientation, you can do a couple of things:

(1) rotate the image by 90 before attempting deskew -- the high confidence in the skew finder will indicate that the image was in landscape mode.

(2) for text, use the text orientation in flipdetect.c.

**Comment by Artgit** [comment]
Sorry, I think I was not clear in my previous post.  The issue is that both of these documents are placed on the same image. In the given example one of them is rotated under the 90 degree but I can also have the images where different parts can be rotated under the different(any) angles. This is why I need first to correct the skew of all parts(not the whole image but the parts inside of this image separately) of the same image before OCR.

In the given example I need to correct skew of the first(top part1) document on the image and leave the bottom one(Part2) unrotated(because the bottom part was given as properly rotated)

![image](https://user-images.githubusercontent.com/2064812/36776301-f8eedbdc-1c6d-11e8-9743-500628edf27d.png)

**Comment by Artgit** [comment]
This is what I have for now based on my OpenCV research https://stackoverflow.com/questions/49031247/java-opencv-deskew-matofpoint-and-place-into-new-canvas I still need to deskew these areas and extract them into the new canvas.

**Comment by data-man** [comment]
@Artgit, maybe [scantailor-advanced](https://github.com/4lex4/scantailor-advanced) will be useful for you.

**Comment by Artgit** [comment]
Thanks All for the help on this topic! I have the results for now so I will close this issue. If you don't mind I'll create another one with more specific issues.
