### ISSUE TITLE
[Question]How to put pix inside another pix with box 

### ISSUE THREAD

**Issue by hoangtocdo90** [DanBloomberg/leptonica#314]
Hi guys.
I crop a pix  by using pixClipRectangle and do some other image processing.
When finish i wan't to update cropped pix into original pix.
I'm do many search but no luck.
Thanks for help!
`
Pix* cropped = pixClipRectangle(original, abox, NULL);

Pix *dilate = pixDilateGray(cropped, 5, 5);
//need update dilate pix to original
origial = ???()
`

**Comment by DanBloomberg** [comment]
you have two choices:

(1) pixDestroy(original);
 original = dilate;

(2) pixTransferAllData(original, &dilate)

In both cases, be sure to pixDestroy(&cropped)

**Comment by hoangtocdo90** [comment]
@DanBloomberg 
thanks for reply. but actually i want put pix inside another pix with box.
![untitled](https://user-images.githubusercontent.com/22963463/36820393-f13112a2-1d30-11e8-97f3-7d1c04df49b3.png)

**Comment by DanBloomberg** [comment]
If you're not scaling pix1, then pixRasterop() is the way to do it.

If you're scaling pix1 to fit into the box before doing the rasterop, you can do that with pixScaleToSize(), where you get the size you want from the size of the box.

**Comment by hoangtocdo90** [comment]
It's work!
Thanks for help !
