### ISSUE TITLE
Improve scanned image quality

### ISSUE THREAD

**Issue by Artgit** [DanBloomberg/leptonica#316]
Is there anything in Leptonica library that can improve the following scanned image:

https://stackoverflow.com/questions/49048186/improve-the-ocr-quality-of-low-quality-scanned-image

or it is impossible to fix the quality of such images in the automatic mode? Thanks!

**Comment by DanBloomberg** [comment]
This is poor quality fax.

You can try experiments, such as doing small dilations (say, 2x2 or 1x3) to see if it improves the results on tesseract.  Otherwise, you're probably out of luck.

**Comment by Artgit** [comment]
Thanks
