### ISSUE TITLE
[Query] No resources to learn about Leptonica

### ISSUE THREAD

**Issue by rahulsharmaq2cs** [DanBloomberg/leptonica#317]
I haven't found any resources for getting an introduction about leptonica. I want to learn but all I find is advanced stuff and cannot find a point to jump right in. Going through leptonica's source code is not of benefit because I cannot understand most of it, if I don't know what the basics are. (Like what PIX is actually)
Please suggest a starting point to me.

Thanks
Rahul

**Comment by DanBloomberg** [comment]
After you look through the README.html, this is the important page for an overview:

   http://leptonica.org/highlevel.html

It groups the files by categories and gives you a 1-line accounting of what's in each file.

**Comment by Eugenij** [comment]
Study leptonica, but can't figure out how to binarying such image:
![shot03584](https://user-images.githubusercontent.com/1322560/37059978-20048c80-21b9-11e8-8f69-10b651788cbb.jpg)
I need something like this: 
![shot03584-need](https://user-images.githubusercontent.com/1322560/37060023-42ef1594-21b9-11e8-8576-2de3136f57ba.jpg)
help please.

**Comment by DanBloomberg** [comment]
Here's a trivial program to do the job:

Pix *pix1 = pixRead("/tmp/samers.jpg");
pixInvert(pix1, pix1);
Pix *pix2 = pixConvertTo8(pix1, 0);
Pix * pix3 = pixThresholdToBinary(pix2, 160);
pixWrite("/tmp/samers.png", pix3, IFF_PNG

Again, I suggest that you look at the highlevel.html file to get an idea of the operations that are available, and browse around in the prog directory.

![samers](https://user-images.githubusercontent.com/16688684/37061848-983951b0-2149-11e8-8ccc-c180f96b3183.png)
);

**Comment by Eugenij** [comment]
thank you very much, but can I extract one channel from the image? for example green

**Comment by DanBloomberg** [comment]
pixGetRGBComponent()
