### ISSUE TITLE
Do we need to continue to support pixDisplayWrite, pixDisplayWriteFormat and pixDisplayMultiple

### ISSUE THREAD

**Issue by DanBloomberg** [DanBloomberg/leptonica#319]
@stweil 
@amitdo 

These three are at the end of writefile.c.  They are deprecated legacy functions that were needed for some early versions of tesseract 3, and are no longer in use in prog/

It would be nice to remove them from the library.  Can we do this now?

**Comment by stweil** [comment]
They seem to be unused since more than a year: https://github.com/tesseract-ocr/tesseract/commit/a1c22fb0d0f6bde165ec7b7c3125420b0ba1d541.

Nevertheless all Linux distributions with Tesseract 3.05 still need them.

**Comment by DanBloomberg** [comment]
That's fine.  I can wait a couple of years and ask again  :-)

**Comment by amitdo** [comment]
You can make pixDisplayWrite a stub.

I don't think that tesseract used the other two.

**Comment by stweil** [comment]
Tesseract 3.05 does indeed not use `pixDisplayWriteFormat` or `pixDisplayMultiple`.

**Comment by DanBloomberg** [comment]
OK. Removed those two.  Still have pixDisplayWrite(), which we can keep indefinitely.

**Comment by DanBloomberg** [comment]
checking this again.

(1) are we still supporting tesseract 3.05?
(2) even if we are, would making the function a non-functional stub, as Amit suggested, be ok?

**Comment by zdenop** [comment]
1. From time to time pop up some people using tesseract 3.04  ;-)
2. I would suggest to mark it as depreciated (with message during compiling process) for next release and then remove it or make it as  a non-functional stub in following release...

**Comment by DanBloomberg** [comment]
OK, for 1.79, this will say it become non-functional in 1.80.

**Comment by DanBloomberg** [comment]
1.80 is not yet released, but pixDisplayWrite() is now a stub at the master.

**Comment by DanBloomberg** [comment]
1.80 is released.  pixDisplayWrite() is now a stub.
