### ISSUE TITLE
travis failing for 32 bit with giflib-5.1.4

### ISSUE THREAD

**Issue by DanBloomberg** [DanBloomberg/leptonica#322]
@egorpugin 

travis seems to be having trouble un-taring giflib.  Claims it's not a bzip2.

No problem with 64 bits however.

**Comment by egorpugin** [comment]
Changed url, let's see how it goes.

**Comment by egorpugin** [comment]
Looks like fixed.
On travis we have linux+macos, not 32+64 bits.
