### ISSUE TITLE
pixReadMemBmp read BMP file Bugs?

### ISSUE THREAD

**Issue by wyy** [DanBloomberg/leptonica#323]
1. BMP files with negative bitmap height are not supported.

2. The BMP color order (b,g,r,a) is not changed to PIX(r,g,b,a) if depth==32.

  (Line241 - line246)
 if (depth != 24) {  /* typ. 1 or 8 bpp */
        data = (l_uint8 *)pixdata + pixBpl * (height - 1);
        for (i = 0; i < height; i++) {
            memcpy(data, fdata, fdatabpl);
            fdata += fdatabpl;
            data -= pixBpl;
        }

**Comment by DanBloomberg** [comment]
please zip up some standard rgb bmp files so I can check them

**Comment by DanBloomberg** [comment]
and ... negative image dimensions are invalid

**Comment by DanBloomberg** [comment]
Please also note in selecting the bmp rgb files, use the old standard BITMAPINFOHEADER file format. From https://en.wikipedia.org/wiki/BMP_file_format   :
"For compatibility reasons, most applications use the older DIB headers for saving files. With OS/2 no longer supported after Windows 2000, for now the common Windows format is the BITMAPINFOHEADER header."

**Comment by wyy** [comment]
From https://en.wikipedia.org/wiki/BMP_file_format :
“ Unless BITMAPCOREHEADER is used, uncompressed Windows bitmaps also can be stored from the top to bottom, when the Image Height value is negative.”

**Comment by DanBloomberg** [comment]
Didn't realize that.  Can probably be accommodated with little effort.

Still need some standard RGB bmp files to do experiments on.  Please supply.  You can put them in here as a zip file.

Also, look at the comments in bmpio.c, l. 249-283.  Is that correct?  If so, we should be handling the color components correctly.

**Comment by wyy** [comment]
I think the else block is correct. Line 249-295.bmpio.c.
 But sorry, I’m outside now, and I can upload bmp file after some days.

**Comment by wyy** [comment]
[capture.zip](https://github.com/DanBloomberg/leptonica/files/1825660/capture.zip)
the bmp file Height value is negative.

**Comment by DanBloomberg** [comment]
thanks!  I'll see what we can do.

**Comment by DanBloomberg** [comment]
fixed.  Enabled bmp reading to handle bmp files with height < 0.

The colors are correct, so no changes will be made to the color components.
