### ISSUE TITLE
Makefile:476: recipe for target 'all-recursive' failed

### ISSUE THREAD

**Issue by serrrgggeee** [DanBloomberg/leptonica#326]
Hello. I need leptonica, because it's depend for tesseract but it show error "Makefile:476: recipe for target 'all-recursive' failed". My os is ubuntu. is it actual virsionf?

**Comment by LubieWarzywa** [comment]
Hello, I have the same problem. I am working on AWS with Ubuntu (16.04.4 LTS (Xenial Xerus)).
I made following steps according to instruction from readme file. I've tried all of the proposed methods.

Below what I got following option (3):
```
git clone https://github.com/DanBloomberg/leptonica.git
cd leptonica
mkdir build
cd build
cmake ..
make
cmake ..
```
and at third moment I got:
```
~/leptonica/build$ cmake ..
-- Could NOT find GIF (missing:  GIF_LIBRARY GIF_INCLUDE_DIR)
-- Checking for module 'libopenjp2'
--   No package 'libopenjp2' found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/leptonica/build 
```

While using option (2) I've got (using following instruction from video: https://www.youtube.com/watch?v=vOdnt2h1U8U ):
```
wget http://www.leptonica.org/source/leptonica-1.75.3.tar.gz
gunzip leptonica-1.75.3.tar.gz 
tar -xvf leptonica-1.75.3.tar 
cd leptonica-1.75.3
./autobuild
./configure
```
Output:
```
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking for gawk... gawk
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking for gawk... (cached) gawk
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking how to run the C preprocessor... gcc -E
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for cos in -lm... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZLIB... yes
checking for LIBPNG... yes
checking for JPEG... yes
checking for DGifOpenFileHandle in -lgif... no
checking gif_lib.h usability... no
checking gif_lib.h presence... no
checking for gif_lib.h... no
checking for LIBTIFF... yes
checking for LIBWEBP... yes
checking for LIBJP2K... no
checking for opj_create_decompress in -lopenjp2... no
checking openjpeg-2.3/openjpeg.h usability... no
checking openjpeg-2.3/openjpeg.h presence... no
checking for openjpeg-2.3/openjpeg.h... no
checking openjpeg-2.2/openjpeg.h usability... no
checking openjpeg-2.2/openjpeg.h presence... no
checking for openjpeg-2.2/openjpeg.h... no
checking openjpeg-2.1/openjpeg.h usability... no
checking openjpeg-2.1/openjpeg.h presence... no
checking for openjpeg-2.1/openjpeg.h... no
checking openjpeg-2.0/openjpeg.h usability... no
checking openjpeg-2.0/openjpeg.h presence... no
checking for openjpeg-2.0/openjpeg.h... no
checking whether make supports nested variables... (cached) yes
checking for size_t... yes
checking whether byte ordering is bigendian... no
checking whether compiler supports -Wl,--as-needed... yes
checking for fmemopen... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/endianness.h
config.status: creating src/Makefile
config.status: creating prog/Makefile
config.status: creating lept.pc
config.status: creating config_auto.h
config.status: executing libtool commands
config.status: executing depfiles commands
```

```
./make-for-auto
```
(I've changed 
mv src/makefile src/makefile.static
mv prog/makefile prog/makefile.static
to capital letters: 
mv src/Makefile src/makefile.static
mv prog/Makefile prog/makefile.static )

And after using sudo make I've got the following error:

```
make  all-recursive
make[1]: Entering directory '/home/ubuntu/leptonica-1.75.3'
Making all in src
make[2]: Entering directory '/home/ubuntu/leptonica-1.75.3/src'
make[2]: *** No rule to make target 'all'.  Stop.
make[2]: Leaving directory '/home/ubuntu/leptonica-1.75.3/src'
Makefile:476: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/ubuntu/leptonica-1.75.3'
Makefile:385: recipe for target 'all' failed
make: *** [all] Error 2 
```

Following two options I got the error. Do you have any ideas why it happens?
I would be grateful for tips.

**Comment by egorpugin** [comment]
Please, use autotools build on linux.
CMake is not well tested there.

**Comment by DanBloomberg** [comment]
and run make-for-auto to remove "makefile" in each directory

**Comment by mironkraft** [comment]
> Hello, I have the same problem. I am working on AWS with Ubuntu (16.04.4 LTS (Xenial Xerus)).
> I made following steps according to instruction from readme file. I've tried all of the proposed methods.
> 
> Below what I got following option (3):
> 
> ```
> git clone https://github.com/DanBloomberg/leptonica.git
> cd leptonica
> mkdir build
> cd build
> cmake ..
> make
> cmake ..
> ```
> 
> and at third moment I got:
> 
> ```
> ~/leptonica/build$ cmake ..
> -- Could NOT find GIF (missing:  GIF_LIBRARY GIF_INCLUDE_DIR)
> -- Checking for module 'libopenjp2'
> --   No package 'libopenjp2' found
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/ubuntu/leptonica/build 
> ```
> 
> While using option (2) I've got (using following instruction from video: https://www.youtube.com/watch?v=vOdnt2h1U8U ):
> 
> ```
> wget http://www.leptonica.org/source/leptonica-1.75.3.tar.gz
> gunzip leptonica-1.75.3.tar.gz 
> tar -xvf leptonica-1.75.3.tar 
> cd leptonica-1.75.3
> ./autobuild
> ./configure
> ```
> 
> Output:
> 
> ```
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking how to print strings... printf
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking for a sed that does not truncate output... /bin/sed
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for fgrep... /bin/grep -F
> checking for ld used by gcc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking whether ln -s works... yes
> checking the maximum length of command line arguments... 1572864
> checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
> checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for ar... ar
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking for gawk... gawk
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for a working dd... /bin/dd
> checking how to truncate binary pipes... /bin/dd bs=4096 count=1
> checking for mt... mt
> checking if mt is a manifest tool... no
> checking how to run the C preprocessor... gcc -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -fPIC -DPIC
> checking if gcc PIC flag -fPIC -DPIC works... yes
> checking if gcc static flag -static works... yes
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... yes
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /bin/mkdir -p
> checking whether make sets $(MAKE)... yes
> checking for style of include used by make... GNU
> checking whether make supports nested variables... yes
> checking dependency style of gcc... gcc3
> checking for gawk... (cached) gawk
> checking for gcc... (cached) gcc
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether gcc accepts -g... (cached) yes
> checking for gcc option to accept ISO C89... (cached) none needed
> checking whether gcc understands -c and -o together... (cached) yes
> checking how to run the C preprocessor... gcc -E
> checking whether ln -s works... yes
> checking whether make sets $(MAKE)... (cached) yes
> checking for cos in -lm... yes
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.9.0... yes
> checking for ZLIB... yes
> checking for LIBPNG... yes
> checking for JPEG... yes
> checking for DGifOpenFileHandle in -lgif... no
> checking gif_lib.h usability... no
> checking gif_lib.h presence... no
> checking for gif_lib.h... no
> checking for LIBTIFF... yes
> checking for LIBWEBP... yes
> checking for LIBJP2K... no
> checking for opj_create_decompress in -lopenjp2... no
> checking openjpeg-2.3/openjpeg.h usability... no
> checking openjpeg-2.3/openjpeg.h presence... no
> checking for openjpeg-2.3/openjpeg.h... no
> checking openjpeg-2.2/openjpeg.h usability... no
> checking openjpeg-2.2/openjpeg.h presence... no
> checking for openjpeg-2.2/openjpeg.h... no
> checking openjpeg-2.1/openjpeg.h usability... no
> checking openjpeg-2.1/openjpeg.h presence... no
> checking for openjpeg-2.1/openjpeg.h... no
> checking openjpeg-2.0/openjpeg.h usability... no
> checking openjpeg-2.0/openjpeg.h presence... no
> checking for openjpeg-2.0/openjpeg.h... no
> checking whether make supports nested variables... (cached) yes
> checking for size_t... yes
> checking whether byte ordering is bigendian... no
> checking whether compiler supports -Wl,--as-needed... yes
> checking for fmemopen... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating src/endianness.h
> config.status: creating src/Makefile
> config.status: creating prog/Makefile
> config.status: creating lept.pc
> config.status: creating config_auto.h
> config.status: executing libtool commands
> config.status: executing depfiles commands
> ```
> 
> ```
> ./make-for-auto
> ```
> 
> (I've changed
> mv src/makefile src/makefile.static
> mv prog/makefile prog/makefile.static
> to capital letters:
> mv src/Makefile src/makefile.static
> mv prog/Makefile prog/makefile.static )
> 
> And after using sudo make I've got the following error:
> 
> ```
> make  all-recursive
> make[1]: Entering directory '/home/ubuntu/leptonica-1.75.3'
> Making all in src
> make[2]: Entering directory '/home/ubuntu/leptonica-1.75.3/src'
> make[2]: *** No rule to make target 'all'.  Stop.
> make[2]: Leaving directory '/home/ubuntu/leptonica-1.75.3/src'
> Makefile:476: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/ubuntu/leptonica-1.75.3'
> Makefile:385: recipe for target 'all' failed
> make: *** [all] Error 2 
> ```
> 
> Following two options I got the error. Do you have any ideas why it happens?
> I would be grateful for tips.

Hi there, how you solved your last problem? The one that you had at MAKE? I am facing same issue:
`Making all in src
make[1]: Entering directory '/home/asus/XxxxxxXxxx/src'
make[2]: Entering directory '/home/asus/XxxxxxXxxx/src'
make[2]: *** No rule to make target 'XxxxxxXxxxd.cpp', needed by 'XxxxxxXxxx-XxxxxxXxxx.o'.  Stop.
make[2]: Leaving directory '/home/asus/XxxxxxXxxx/src'
make[1]: *** [Makefile:15180: all-recursive] Error 1
make[1]: Leaving directory '/home/asus/XxxxxxXxxx/src'
make: *** [Makefile:808: all-recursive] Error 1
`

**Comment by DanBloomberg** [comment]
1.75.3 is 3 years old.  Suggest you use a more recent release, or clone from the current tree.

Dan

**Comment by mironkraft** [comment]
> 1.75.3 is 3 years old. Suggest you use a more recent release, or clone from the current tree.
> 
> Dan

Hi Dan, i just used main bitcoin from 3 days ago

it is up to date my release, but the problem i guess is the same as this old one

**Comment by DanBloomberg** [comment]
I just followed the prescription with 1.75.3

```
wget http://www.leptonica.org/source/leptonica-1.75.3.tar.gz
gunzip leptonica-1.75.3.tar.gz 
tar -xvf leptonica-1.75.3.tar 
cd leptonica-1.75.3
./autobuild
./configure
```

and then with 'make' got this result:

```...
tmp/git1/leptonica-1.75.3$ make
make  all-recursive
make[1]: Entering directory '/tmp/git1/leptonica-1.75.3'
Making all in src
make[2]: Entering directory '/tmp/git1/leptonica-1.75.3/src'
  CC       adaptmap.lo
  CC       affine.lo
  CC       affinecompose.lo
  CC       arrayaccess.lo
  CC       bardecode.lo
...
```

**Comment by ZeclintrYzath** [comment]
I have an output error: 

    make[1]: Entering directory '/home/user/apr-util-1.6.1'
    /bin/bash /usr/share/apr-1.0/build/libtool --no-silent --mode=compile x86_64-linux-gnu-gcc -pthread  -g -O2 -fdebug-prefix map=/build/apr-Defb06/apr-1.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE  -Wdate-time -D_FORTIFY_SOURCE=2 -I/home/user/apr-util-1.6.1/include -I/home/user/apr-util-1.6.1/include/private  -I/usr/include/apr-1.0  -I/usr/include  -o xml/apr_xml.lo -c xml/apr_xml.c && touch xml/apr_xml.lo
    libtool: compile:  x86_64-linux-gnu-gcc -pthread -g -O2 -fdebug-prefix-map=/build/apr-Defb06/apr-1.6.3=. -fstack-protector-strong -Wformat -Werror=format-security -DHAVE_CONFIG_H -DLINUX -D_REENTRANT -D_GNU_SOURCE -Wdate-time -D_FORTIFY_SOURCE=2 -I/home/user/apr-util-1.6.1/include -I/home/user/apr-util-1.6.1/include/private -I/usr/include/apr-1.0 -I/usr/include -c xml/apr_xml.c  -fPIC -DPIC -o xml/.libs/apr_xml.o
    xml/apr_xml.c:35:10: fatal error: expat.h: No such file or directory
     #include <expat.h>
              ^~~~~~~~~
    compilation terminated.
    /home/user/apr-util-1.6.1/build/rules.mk:206: recipe for target 'xml/apr_xml.lo' failed
    make[1]: *** [xml/apr_xml.lo] Error 1
    make[1]: Leaving directory '/home/user/apr-util-1.6.1'
    /home/user/apr-util-1.6.1/build/rules.mk:118: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

    Note that the <expat.h> package is missing. Try specifying ^ ~ in the #include <expat.h> line. It is because of him that the error occurs 
    'all-recursive'.

 I used expat:

     sudo apt-get install libexpat1 libexpat1-dev

I installed them, this hack `^ ~~~~~~~~` works and after that something like `Libraries have been installed in:`.
