### ISSUE TITLE
Denial of service vulnerability because values in the input are not correctly validated

### ISSUE THREAD

**Issue by wigsaparelli** [DanBloomberg/leptonica#331]
While inspecting the code we've found an easy denial of service vulnerability because values in the input are not correctly validated, actually aren’t validated at all.
o	kernelReadStream, line 558, values are read from file, never validated
o	kernelReadStream, line 562, calls kernelCreate with sy
o	kernelCreate, line 116 calls create2dFloatArray with sy (now called height)
o	Create2dFloatArray, line 494 calls LEPT_CALLOC (which is just a call to calloc) with height (again called sy) and a size of a pointer
o	Many calloc implementations, e.g. GCC’s just multiply the two parameters without checking for any possible overflow
o	So, put a value of 0xC000…0 in for sy and the result of the multiplication (on a four byte pointer system) is going to be 0, which gives you a crash or possibly a memory overwrite on line 498.

**Comment by DanBloomberg** [comment]
Thank you for noticing this, and for making a constructive comment on the issue (here).

The same issue came up many years ago with calloc for the Pix, when we were fuzzing jpeg, bmp and png images. It was solved by doing the 64-bit arithmetic checking that you'll find in pixCreateHeader().  We will do the same thing here for Fpix and Dpix, which, unlike Pix (for which there are many serialized image formats), can only be read from data serialized by leptonica itself.  But we agree it should be fuzz-proof as well.

**Comment by wigsaparelli** [comment]
Many thanks

Cheers, Rich

**Comment by DanBloomberg** [comment]
fixed with commit 649:

   https://github.com/DanBloomberg/leptonica/commit/6541dbed93a4529d70d36eb3ccb1a35aa60b38ce

thanks again!
