### ISSUE TITLE
 undefined macros and syntax error with configure.ac

### ISSUE THREAD

**Issue by DanBloomberg** [DanBloomberg/leptonica#334]
@chewi 

I've installed the latest version of automake (etc).  Now, when running my autobuild file, I am getting errors:

libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:38: error: possibly undefined macro: AS_IF
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:44: error: possibly undefined macro: AC_DEFINE
configure.ac:46: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:47: error: possibly undefined macro: AC_CHECK_HEADER
configure.ac:50: error: possibly undefined macro: AC_SUBST
configure.ac:52: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:178: error: possibly undefined macro: AC_CHECK_HEADERS
configure.ac:179: error: possibly undefined macro: AC_DEFINE_UNQUOTED
configure.ac:8: installing 'config/compile'
configure.ac:10: installing 'config/missing'
prog/Makefile.am: installing 'config/depcomp'

Has something been deprecated?

I could suppress the error messages using m4_pattern_allow([AS_IF])  etc., but could not fix the problem, because when running ./configure, I get this error, and no Makefile is made:

./configure: line 13070: syntax error near unexpected token `ZLIB,'
./configure: line 13070: `  PKG_CHECK_MODULES(ZLIB, zlib,'

**Comment by chewi** [comment]
Did get your earlier message, will look tonight.

**Comment by DanBloomberg** [comment]
Thanks.  Here's some more info.

Running each command in autobuild, the error messages happen in autoconf, which returns failure (1).

Here are the versions:
> dpkg -l autoconf
autoconf       2.69-11  
> dpkg -l libtool
libtool        2.4.6-2

And running ./configure dies with the syntax error on ZLIB.

Jeff has the same versions of these tools, but he can build from head without errors.

**Comment by DanBloomberg** [comment]
Running autoreconf -fvi:

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
configure.ac:38: error: possibly undefined macro: AS_IF
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:44: error: possibly undefined macro: AC_DEFINE
configure.ac:46: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:47: error: possibly undefined macro: AC_CHECK_HEADER
configure.ac:50: error: possibly undefined macro: AC_SUBST
configure.ac:52: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:178: error: possibly undefined macro: AC_CHECK_HEADERS
configure.ac:179: error: possibly undefined macro: AC_DEFINE_UNQUOTED
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by chewi** [comment]
Works fine for me too.

```
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal --force -I m4
aclocal-1.15: warning: couldn't open directory 'm4': No such file or directory
autoreconf-2.69: configure.ac: tracing
autoreconf-2.69: configure.ac: creating directory config
autoreconf-2.69: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf-2.69: running: /usr/bin/autoconf-2.69 --force
autoreconf-2.69: running: /usr/bin/autoheader-2.69 --force
autoreconf-2.69: running: automake --add-missing --copy --force-missing
configure.ac:8: installing 'config/compile'
configure.ac:8: installing 'config/config.guess'
configure.ac:8: installing 'config/config.sub'
configure.ac:10: installing 'config/install-sh'
configure.ac:10: installing 'config/missing'
prog/Makefile.am: installing 'config/depcomp'
parallel-tests: installing 'config/test-driver'
autoreconf-2.69: Leaving directory `.'
```


You should ensure you don't have junk sitting in your repository. `git clean -fxd` will delete everything that isn't committed but make sure you move anything you actually want to keep out of the way first!

**Comment by DanBloomberg** [comment]
The m4sh.m4 file is there.

I removed autoconf:

The following packages will be REMOVED:
  autoconf automake
0 upgraded, 0 newly installed, 2 to remove and 1 not upgraded.
After this operation, 3,664 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 308416 files and directories currently installed.)
Removing automake (1:1.15.1-3) ...
Removing autoconf (2.69-11) ...
Processing triggers for install-info (6.5.0.dfsg.1-1) ...
Processing triggers for man-db (2.7.6.1-4) ...

Then re-installed it:

The following additional packages will be installed:
  automake
Suggested packages:
  autoconf-archive gnu-standards autoconf-doc
The following NEW packages will be installed:
  autoconf automake
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/1,112 kB of archives.
After this operation, 3,664 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Selecting previously unselected package autoconf.
(Reading database ... 308211 files and directories currently installed.)
Preparing to unpack .../autoconf_2.69-11_all.deb ...
Unpacking autoconf (2.69-11) ...
Selecting previously unselected package automake.
Preparing to unpack .../automake_1%3a1.15.1-3_all.deb ...
Unpacking automake (1:1.15.1-3) ...
Processing triggers for install-info (6.5.0.dfsg.1-1) ...
Setting up autoconf (2.69-11) ...
Setting up automake (1:1.15.1-3) ...
update-alternatives: using /usr/bin/automake-1.15 to provide /usr/bin/automake (automake) in auto mode
Processing triggers for man-db (2.7.6.1-4) ...

Same problem when running autoconf.

**Comment by DanBloomberg** [comment]
I am building directly from a clone of the repository head:
   git clone https://github.com/DanBloomberg/leptonica.git .

**Comment by stweil** [comment]
Try `autoconf -d -v`. Are there problems writing to `/tmp`? Disk full? Missing rights?

Running `strace -f autoconf -d -v` would give even more information, but is more difficult to evaluate.

**Comment by chewi** [comment]
Searching around, I think you need to install `autoconf-archive`, which is mentioned in your output above as being suggested.

**Comment by amitdo** [comment]
>./configure: line 13070: syntax error near unexpected token ZLIB,' ./configure: line 13070: PKG_CHECK_MODULES(ZLIB, zlib,'

This one means you didn't install pkg-config.

**Comment by amitdo** [comment]
@stwell, maybe you should port the related checks from Tesseract's autogen.sh to Leptonica?

**Comment by DanBloomberg** [comment]
@amitdo 
That fixed it!    (I wonder why it wasn't installed on my machine in the distro, as it was on Jeff's)

Thank you!

I'll leave the issue open for a while, anyway.

**Comment by DanBloomberg** [comment]
@chewi 

We have a file, autobuild, that is currently provided from the git repository and can be used to run the autotools code.

I also have a shell script that just runs autoreconf.  It has 2 lines:
  #!/bin/sh -e
  exec autoreconf -fi

What is the best way to let people build with autotools from a git clone?  And what should we provide?

**Comment by stweil** [comment]
> @stweil, maybe you want to port the related checks from Tesseract's autogen.sh to Leptonica?

Done with pull request #335.

**Comment by egorpugin** [comment]
Maybe it's time to think about switching to cmake?

**Comment by chewi** [comment]
@DanBloomberg, I'm not sure what you're asking as I think the autobuild script is sufficient. I tend to assume that people building from source have some idea what they're doing and have the usual build tools available. In Gentoo, we don't use the autobuild script because we have our own scripts for calling autoconf and friends.

Although I've invested a lot of time in the Autotools stuff, I don't really mind if you want to drop it as it's still been a valuable learning experience for me. The tests still need to be added to CMake and while I'm not a CMake expert, I gather it is a very good idea to make use of `GNUInstallDirs`. As things stand, I think the library destination is hardcoded as `${prefix}/lib`.

The new kid on the block that everyone is talking about is Meson. It's very easy to use and does a good job of pleasing everyone. I haven't tried it yet but I have read parts of the manual. Adding this to Leptonica would be an interesting exercise at least.

**Comment by DanBloomberg** [comment]
@chewi 

Someone suggested using autoreconf, etc.  I was just asking the experts.  I like the autobuild approach, where we are explicitly calling the different tools.

I have no intention of removing autotools support for leptonica.  You have done a great job with these difficult tools, and as you noted, with 'make check', we can verify that all the regression tests run to completion and are idempotent.  There is an outstanding issue for implementing that in cppan.

I like the fact that we have multiple ways to build leptonica.  I use the static makefiles; they're fast and trivial to maintain.  Jeff, our Debian maintainer, uses autotools.  cppan provides cross-platform portability for builds, so it's critical for windows.  And if you want to add meson to the list, I'd welcome it.  At each stage, it seems that the generic tools have become easier to support.

**Comment by stweil** [comment]
I see no need to replace the autotools based build and use that also on Windows with Mingw-w64. cmake and cppan are a good choice for builds with Visual Studio.

**Comment by chewi** [comment]
Good to know. Don't know if I'll find time for Meson but if I want to try it out, I know where to start. :smile:

**Comment by DanBloomberg** [comment]
Closing this.  @amitdo figured out the problem, which was a bit difficult to figure out from the error messages, and @stweil fixed autobuild (now, autogen.sh) so that this shouldn't happen again.

**Comment by archuletacarla6-netizen** [comment]
> [@chewi](https://github.com/chewi)
> 
> I've installed the latest version of automake (etc). Now, when running my autobuild file, I am getting errors:
> 
> libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'. libtoolize: copying file 'config/ltmain.sh' libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'. libtoolize: copying file 'm4/libtool.m4' libtoolize: copying file 'm4/ltoptions.m4' libtoolize: copying file 'm4/ltsugar.m4' libtoolize: copying file 'm4/ltversion.m4' libtoolize: copying file 'm4/lt~obsolete.m4' configure.ac:38: error: possibly undefined macro: AS_IF If this token and others are legitimate, please use m4_pattern_allow. See the Autoconf documentation. configure.ac:44: error: possibly undefined macro: AC_DEFINE configure.ac:46: error: possibly undefined macro: AC_CHECK_LIB configure.ac:47: error: possibly undefined macro: AC_CHECK_HEADER configure.ac:50: error: possibly undefined macro: AC_SUBST configure.ac:52: error: possibly undefined macro: AC_MSG_ERROR configure.ac:178: error: possibly undefined macro: AC_CHECK_HEADERS configure.ac:179: error: possibly undefined macro: AC_DEFINE_UNQUOTED configure.ac:8: installing 'config/compile' configure.ac:10: installing 'config/missing' prog/Makefile.am: installing 'config/depcomp'
> 
> Has something been deprecated?
> 
> I could suppress the error messages using m4_pattern_allow([AS_IF]) etc., but could not fix the problem, because when running ./configure, I get this error, and no Makefile is made:
> 
> ./configure: line 13070: syntax error near unexpected token `ZLIB,' ./configure: line 13070: ` PKG_CHECK_MODULES(ZLIB, zlib,'

**Comment by zdenop** [comment]
@archuletacarla6-netizen :  did you installed pkg-config package?
