### ISSUE TITLE
Rename autobuild to autogen.sh

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#337]
I would suggest to rename `autobuild` to common name of such script: `autogen.sh`.
See e.g. FAQ of [automake](https://www.gnu.org/software/automake/faq/autotools-faq.html#What-does-_002e_002fbootstrap-or-_002e_002fautogen_002esh-do_003f). or google for "autogen.sh".

**Comment by zdenop** [comment]
I did not see bootstrap for a long time ;-) I did not make deep investigation but most of packages I used have autogen.sh...

**Comment by DanBloomberg** [comment]
Seems reasonable to 'standardize' on autogen.sh

**Comment by DanBloomberg** [comment]
renamed autobuild --> autogen.sh
