### ISSUE TITLE
FYI: Marriage of Leptonica and Lua

### ISSUE THREAD

**Issue by pullmoll** [DanBloomberg/leptonica#343]
Hey Dan and contributors,

I wanted to let you know that I'm working on a marriage of Leptonica and [Lua](http://www.lua.org/). There's still a lot to do while some things are working fine already.
You can follow my progress at ~~[my fork's branch lua](https://github.com/pullmoll/leptonica/tree/lua)~~ [lualept](https://github.com/pullmoll/lualept).
All you need to do is have a lua53-dev (or similar named) package installed.

I managed to modify the `configure.ac` and `src/Makefile.am` files such that building `leptlua.a` and `leptlua.so.5.0.3` depends on Lua >= 5.3.0 being found and not disabled with the `--without-lua` switch.

There's also a tiny command line tool `prog/llua` which can be used to run a script file for testing. In `lua/script.lua` you'll find some code which I use to test the interface.

I did not yet take care of the CMake way to build things because that's not my strong side.

I'm also undecided whether perhaps Lua (5.3.4) itself, which is tiny, should be shipped as `src/3rdparty/lua` and be built along with Leptonica, if there is no conifgure option `--with-system-lua` or `--without-lua` specified.

Whenever the several hundred more mappings of Leptonica functions to Lua C-function wrappers are done, it should become possible to do almost anything you can do with Leptonica and your own C code by simply running a Lua script from your application.

**Comment by amitdo** [comment]
Hi,

Why not make this wrapper an external project that depend on Leptonica?

**Comment by pullmoll** [comment]
@amitdo Sure, that's always possible. I thought that perhaps integrating Lua could make creating (additional?) reg tests for Leptonica itself easier. And in any case it would be optional and perhaps default disabled.

**Comment by DanBloomberg** [comment]
Actually, the reg tests are quite easy to make.  Early on, there was some iteration on the design of the functions in regutils.c, but that stabilized about 5 years ago.  There are presently 114 reg tests, run by alltests_reg, and I've been adding them and converting non-reg progs at about 20/year.

**Comment by pullmoll** [comment]
Thanks Dan for the advice!
I see your point and I'll go and make `leptlua` a separate project then.

**Comment by data-man** [comment]
@pullmoll 
Maybe ```lualept```?
Most often, the names of Lua-wrappers starts with ```lua```.

**Comment by pullmoll** [comment]
Ok, separated out and renamend @data-man https://github.com/pullmoll/lualept
It's still WIP of course.

**Comment by DanBloomberg** [comment]
One small thing.  You're using the typedefs for leptonica structs.  C++ allows use without the 'struct' keyword, so in C++, you would ignore the typedef and say, e.g.,
   Box *box = ...
whereas in C (e.g., the library) you need to say
   BOX *box = ...
I think it's nicer to use the struct names if possible, rather than the typedef.

**Comment by pullmoll** [comment]
I'd have to rename the source files to `*.cpp` then to make my editor (QtCreator) recognize they are C++ and not complain about the missing `struct` before the names. I tried to keep the code C89 until now while that's probably not needed.

**Comment by DanBloomberg** [comment]
Right.  Please ignore my dumb suggestion  :-)

**Comment by pullmoll** [comment]
Actually I followed it :-) I doubt there are too many systems which have nothing but a C89 capable compiler available. Many things are easier to manage or cleaner when using a C++ compiler. I can see warnings in QtCreator because it parses the code on the fly, while I type it in. The exported functions are still inside `extern "C" { }` so all should be fine.

**Comment by pullmoll** [comment]
Closing as lualept is a separate project now.
