### ISSUE TITLE
Punch hole removal

### ISSUE THREAD

**Issue by suman-pan** [DanBloomberg/leptonica#351]
Hello ,

I am processing with BW 1bpp TIFF images, in case of processing or filtering of some images I need to remove the punch holes from those images. it's like

![image](https://user-images.githubusercontent.com/40057690/41151052-43a0c178-6b2d-11e8-879c-b1ccc95e5339.png)

From the above image to this...

![image](https://user-images.githubusercontent.com/40057690/41151097-6999c7a8-6b2d-11e8-8347-70cfd4d15617.png)

Is there any way to do this using Leptonica functionalities?

Thanks..

**Comment by DanBloomberg** [comment]
If you don't have any other big blobs on the images, you can generate a structuring element from one of the examples.  See selgen.c, and examples of the use of those functions in prog/findpattern*.c and findpattern_reg.c.

Doing a HMT with one of those structuring elements gives you some pixels near the center of the blob you're trying to remove, but nowhere else.

You then have 2 ways to proceed:
(1) fill from those pixels as a seed, using the original as a clipping mask, and xor the result with the original.
(2) dilate those pixels enough to cover the blob, and set subtract the result from the original

**Comment by suman-pan** [comment]
Thanks for your valuable response, I am trying on it.

**Comment by Marcopt98** [comment]
Did you manage to get any results? @suman-pan

**Comment by Marcopt98** [comment]
@DanBloomberg I wonder if it's possible to achieve something similar but with some user input like a bezier path?

**Comment by DanBloomberg** [comment]
I have an open issue on this problem
   https://github.com/DanBloomberg/leptonica/issues/597

and a new way to approach it, but haven't had the time to try it yet.
