### ISSUE TITLE
wrong lept.pc generated by cmake (OUTPUT_NAME-NOTFOUND)

### ISSUE THREAD

**Issue by agilmor** [DanBloomberg/leptonica#357]
Building the tag `1.74.4` with cmake I've ended with this `lept.pc` file:
```
prefix=/usr/local/opt/leptonica-1.74
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: leptonica
Description: An open source C library for efficient image processing and image analysis operations
Version: 1.74.4
Libs: -L${libdir} -lleptonica_OUTPUT_NAME-NOTFOUND
Libs.private:
Cflags: -I${includedir} -I${includedir}/leptonica
```

**Comment by DanBloomberg** [comment]
please try building with 1.76.0 or from the current head.

what platform are you using?

**Comment by agilmor** [comment]
Hi!

We've tried it before posting, but I got an error like this:
```
src/gifio.c:191:16: error: too many arguments to function ‘DGifOpen’
```

As we're installing Leptonica as a dependence of Tesseract 4.0.0, the version `1.74.4` is good enough for us, and is the newest version without the `DGifOpen` error in our Debian Jessie based infrastructure.

Right now we are still on Debian Jessie, but we plan to move to Ubuntu 18.04 this summer.
So, we don't really need any patch from Leptonica at all.
We've just fixed manually the `lept.pc` file in our current setup and we expecte that moving to Ubuntu 18.04, will probably solve the `DGifOpen` error.

Posting JFYI!
Thanks!

**Comment by DanBloomberg** [comment]
Thanks!  We decided with 1.75 to go ahead and stop supporting all the old gif versions with incompatible interfaces.  Some distros were even still using 4.6.  Sorry this has limited your options, but if it helps get the distros in better shape I guess it's worth it.

**Comment by phetmsn0075** [comment]
prefix=/usr/local/opt/leptonica-1.74
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: leptonica
Description: An open source C library for efficient image processing and image analysis operations
Version: 1.74.4
Libs: -L${libdir} -lleptonica_OUTPUT_NAME-NOTFOUND
Libs.private:
Cflags: -I${includedir} -I${includedir}/

**Comment by zdenop** [comment]
IMO this should be closed - posting issue for old leptonica version without testing the latest release is wrong approach.
The latest code produce correct lept.pc for me:
```
prefix=/usr/local
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: leptonica
Description: An open source C library for efficient image processing and image analysis operations
Version: 1.79.0
Libs: -L${libdir} -lleptonica
Libs.private:
Cflags: -I${includedir} -I${includedir}/leptonica
```

**Comment by DanBloomberg** [comment]
thank you for checking.  Happy to close it.
