### ISSUE TITLE
Feature request: Wolf's binarization

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#359]
https://perso.liris.cnrs.fr/cwolf/software/binarize/

And maybe also Niblack?

**Comment by DanBloomberg** [comment]
I can have a look at the 2002 paper.

**Comment by amitdo** [comment]
I discovered that [opencv_contrib](https://github.com/opencv/opencv_contrib), which is [licensed](https://github.com/opencv/opencv_contrib/blob/master/LICENSE) under the 3-Clause license, [implements](https://github.com/opencv/opencv_contrib/blob/0f5d6ae1942870bb1fc4bec9fa086a13f68c48d5/modules/ximgproc/src/niblack_thresholding.cpp) Wolf's algorithm.

**Comment by amitdo** [comment]
Dan,

Do you plan to implement it? Otherwise, you can close this issue.

**Comment by DanBloomberg** [comment]
Probably not, but let's leave it open for a while to nag me ...
