### ISSUE TITLE
pixaReadMultipageTiff consumes too much memory.

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#362]
pixaReadMultipageTiff loads all pages immediately.  Larger multipage color TIFFs will quickly consume all available memory causing a loss of performance.

A scale-able solution would be to use lazy loading and release.

**Comment by amitdo** [comment]
https://github.com/DanBloomberg/leptonica/blob/a7aa5d866ba320c60e7aaa426a145f791535838a/src/tiffio.c#L1146

https://github.com/tesseract-ocr/tesseract/blob/621a8cd29d6d11edfe6c92eb9f4ebf282d6fe321/src/api/baseapi.cpp#L1042

**Comment by DanBloomberg** [comment]
Sorry I didn't get around to this earlier.

The intent of pixaReadFromMultipageTiff() is to generate a pixa as efficiently as possible. The pixa has all the images uncompressed in raster format. If this will use too much memory, don't call it.
If you only want a small subset of these images, call pixReadFromMultipageTiff() instead on the pages that you want.  The directory reading overhead will likely not be significant.

**Comment by DanBloomberg** [comment]
@tdhintz 

I believe that the functions pixReadFromMultipageTiff() and pixReadMemFromMultipageTiff() will do what you want.  See prog/mtiff_reg.c for their use.

**Comment by tdhintz** [comment]
Github Tesseract/charlesw is based on the other implementation.  I’ll lobby them for a less memory intensive solution.  Thank you,

**Comment by amitdo** [comment]
@DanBloomberg,

I think you can close this issue.

**Comment by tdhintz** [comment]
I’ll close it once a solution has been tested.

**Comment by tdhintz** [comment]
I noticed that BigTiff format isn’t supported because offset is of type size_t.  Is that right?

**Comment by DanBloomberg** [comment]
Hadn't considered support of BigTiff.  Requires libtiff-4.0, apparently.  Could be tricky supporting both.  Tesseract page images are not expected to be anywhere near 4 GB in Tiff serialized format.

**Comment by tdhintz** [comment]
The tiffs can contain enough small pages to exceed the limit, but I've never seen one in real life.
