### ISSUE TITLE
multiple processing with tesseract 4.00 and leptonica greater 1.74.1 poor performance

### ISSUE THREAD

**Issue by evkremer** [DanBloomberg/leptonica#365]
System: centos 7
imagetype to process: png
tesseract -v:
tesseract 4.00.00alpha
 leptonica-1.74.4
  libgif 4.1.6(?) : libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7 : libwebp 0.3.0 : libopenjp2 2.3.0
 Found AVX
 Found SSE

I experience crazy performance drop down with calling tesseract from a java application running on a wildfly 11. Tesseract is called 20 times from java the runtime, so i can get more and faster imageprocessing. This is done because my cpu got 20 cores. 
So my problem epears after i did an update of tesseract from version 4.00alpha to 4.00beta-3 and leptonica 1.74.1 to 1.76. Before the update there were no problems and the processingtime for 1 page was around 8 seconds. Now i get processingtimes around 8 min for 1 page.

First i thought, that i have broken something during the build process. 
I used following command to compile leptonica + tesseract.
------------------ leptonica------------
./autobuild
./configure
make 
make install
export LD_LIBRARY_PATH=/usr/local/lib

----------------- tesseract --------------
./autogen.sh
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig LIBLEPT_HEADERSDIR=/usr/local/include ./configure --with-extra-includes=/usr/local/include --with-extra-libraries=/usr/local/lib
LDFLAGS="-L/usr/local/lib" CFLAGS="-I/usr/local/include" make
make install
ldconfig

Later on i installed the repository package from: https://download.opensuse.org/repositories/home:/Alexander_Pozdnyakov/ScientificLinux_7/. Here i got the same problem as mentioned before.

Have anyone any assumtions?

**Comment by DanBloomberg** [comment]
Whatever is causing this, it does not seem to be related to leptonica.

**Comment by stweil** [comment]
That's correct. You have 20 cores and run 20 instances of Tesseract? Then each Tesseract instance creates 4 threads, so you get a total of 80 threads, and your cores will spend a lot of time with scheduling.

Results should be better if you run 5 Tesseract instances, so up to 20 threads can be handled by the 20 cores.

I expect best results for your scenario with 20 Tesseract instances which must be told to use a single thread per instance. Either set envirnment variable `OMP_THREAD_LIMIT=1` or do it programmatically using the OpenMP API (sorry, I have no own experience with that 2nd alternative).

**Comment by evkremer** [comment]
Paying around with thread_limit and process number leads me to a solution.
Im using now 12 processes with 4 threads and the processing time per page reduced radicaly.

thx guys
