### ISSUE TITLE
pixWriteMemJpeg() should extract Jpeg stream directly when PIX has original JPEG stream

### ISSUE THREAD

**Issue by favpdf** [DanBloomberg/leptonica#367]
Currently, pixWriteMemJpeg() re-compress PIX to memory JPEG stream even when PIX was generated by opening a JPEG file. It causes worse image quality for one more JPEG compression.

**Comment by DanBloomberg** [comment]
The pix is a raster image.  It is not compressed.  pixWriteMemJpeg() compress the raster image and writes to memory.

**Comment by favpdf** [comment]
The problem is that the pix was created by opening a jpeg file. JPEG->raster image->JPEG. Because JPEG algorithm is a loss compression method,  one more compression downgrades image's quality. Could we create a function to load JPEG stream from JPEG file to memory directly?

**Comment by amitdo** [comment]
>JPEG->raster image->JPEG

You can convert the raster image (PIX) to a compressed but lossless format like PNG.
