### ISSUE TITLE
Thoughts on natvis file?

### ISSUE THREAD

**Issue by fdncred** [DanBloomberg/leptonica#370]
If you use Visual Studio for imaging you should use the [ImageWatch ](https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.ImageWatch2017)extension. The ImageWatch extension is a life saver with [OpenCV ](https://docs.opencv.org/2.4/doc/tutorials/introduction/windows_visual_studio_image_watch/windows_visual_studio_image_watch.html)but I'd like to see if anyone can get it to work with Leptonica.  The ImageWatch [documentation](https://imagewatch.azurewebsites.net/ImageWatchHelp/ImageWatchHelp.htm) says it could work so I've started a natvis file based on one found here on [GitHub ](https://github.com/aleksey-nikolaev/natvis-collection)and it nearly works but it's not quite there, mostly due to my ignorance.

I was hoping that another Leptonica user would help finish this natvis file below so the people using Visual Studio could have an excellent debugger visualizer.

```
<?xml version="1.0" encoding="utf-8"?>
<AutoVisualizer xmlns="http://schemas.microsoft.com/vstudio/debugger/natvis/2010">
    <UIVisualizer ServiceId="{A452AFEA-3DF6-46BB-9177-C0B08F318025}" Id="1" MenuName="Add to Image Watch"/>

    <!-- Leptonica Pix Format -->
    <Type Name="Pix">
        <UIVisualizer ServiceId="{A452AFEA-3DF6-46BB-9177-C0B08F318025}" Id="1" />
    </Type>

    <Type Name="Pix">
        <DisplayString>{{{spp}({(d+7)/8}-BPP) x {w} x {h} {xres}x{yres}}}</DisplayString>
        <Expand>
            <!--struct Pix
                  {
                      l_uint32             w;         /*!< width in pixels                   */
                      l_uint32             h;         /*!< height in pixels                  */
                      l_uint32             d;         /*!< depth in bits (bpp)               */
                      l_uint32             spp;       /*!< number of samples per pixel       */
                      l_uint32             wpl;       /*!< 32-bit words/line                 */
                      l_uint32             refcount;  /*!< reference count (1 if no clones)  */
                      l_int32              xres;      /*!< image res (ppi) in x direction    */
                                                      /*!< (use 0 if unknown)                */
                      l_int32              yres;      /*!< image res (ppi) in y direction    */
                                                      /*!< (use 0 if unknown)                */
                      l_int32              informat;  /*!< input file format, IFF_*          */
                      l_int32              special;   /*!< special instructions for I/O, etc */
                      char                *text;      /*!< text string associated with pix   */
                      struct PixColormap  *colormap;  /*!< colormap (may be null)            */
                      l_uint32            *data;      /*!< the image data                    */
                  };-->

            <Synthetic Name="[type]">
                <DisplayString>UINT8</DisplayString>
            </Synthetic>
            <Synthetic Name="[channels]">
                <DisplayString Condition="d&lt;=8">1</DisplayString>
                <DisplayString Condition="d==24">3</DisplayString>
                <DisplayString Condition="d==32">4</DisplayString>
                <DisplayString>{d/8}</DisplayString>
            </Synthetic>
            <Synthetic Name="[width]">
                <DisplayString Condition="d&lt;=8">{(w * d + 7) / 8}</DisplayString>
                <!--<DisplayString Condition="d==8">{(w * d + 7) / 8}</DisplayString>
                <DisplayString Condition="d&lt;=8">{(w * (d + 7)) / 8}</DisplayString>
                <DisplayString Condition="d&lt;=8">{4 *((w * (d + 7) / 8) + 3) / 4}</DisplayString>
                <DisplayString Condition="d&lt;=8">{w/8}</DisplayString>-->
                <DisplayString>{w}</DisplayString>
            </Synthetic>
            <!--<Item Name="[width]">w</Item>-->
            <Item Name="[height]">h</Item>
            <Item Name="[depth]">d</Item>
            <Item Name="[bpp]">d</Item>
            <Item Name="[spp]">spp</Item>
            <Item Name="[wpl]">wpl</Item>
            <Item Name="[xres]">xres</Item>
            <Item Name="[yres]">yres</Item>
            <!--<Item Name="[formatnum]">informat</Item>-->
            <Synthetic Name="[format]">
                <DisplayString Condition="informat==0">IFF_UNKNOWN</DisplayString>
                <DisplayString Condition="informat==1">IFF_BMP</DisplayString>
                <DisplayString Condition="informat==2">IFF_JFIF_JPEG</DisplayString>
                <DisplayString Condition="informat==3">IFF_PNG</DisplayString>
                <DisplayString Condition="informat==4">IFF_TIFF</DisplayString>
                <DisplayString Condition="informat==5">IFF_TIFF_PACKBITS</DisplayString>
                <DisplayString Condition="informat==6">IFF_TIFF_RLE</DisplayString>
                <DisplayString Condition="informat==7">IFF_TIFF_G3</DisplayString>
                <DisplayString Condition="informat==8">IFF_TIFF_G4</DisplayString>
                <DisplayString Condition="informat==9">IFF_TIFF_LZW</DisplayString>
                <DisplayString Condition="informat==10">IFF_TIFF_ZIP</DisplayString>
                <DisplayString Condition="informat==11">IFF_PNM</DisplayString>
                <DisplayString Condition="informat==12">IFF_PS</DisplayString>
                <DisplayString Condition="informat==13">IFF_GIF</DisplayString>
                <DisplayString Condition="informat==14">IFF_JP2</DisplayString>
                <DisplayString Condition="informat==15">IFF_WEBP</DisplayString>
                <DisplayString Condition="informat==16">IFF_LPDF</DisplayString>
                <DisplayString Condition="informat==17">IFF_DEFAULT</DisplayString>
                <DisplayString Condition="informat==18">IFF_SPIX</DisplayString>
            </Synthetic>
            <Item Name="[stride]">wpl * 4</Item>
            <Item Name="[bstride]">(w * d + 7) / 8</Item>
            <Item Name="[cstride]">((((w * d + 7) / 8) + 3) / 4) * 4</Item>
            <Item Name="[dstride]">((((w * d) + 31) &amp;~31)>>3)</Item>
            <Item Name="[estride]">((w * d) - 1) / 4 * 4 + 4</Item>
            <Item Name="[fstride]">((((w * d) + 31) / 32) * 4)</Item>
            <Item Name="[refcount]">refcount</Item>
            <Item Name="[data]">data</Item>
        </Expand>
    </Type>

    <Type Name="Pixa">
        <DisplayString>{{{n} blocks}}</DisplayString>
        <Expand>
            <CustomListItems>
                <Variable Name="i" InitialValue="0" />
                <Loop>
                    <If Condition="i &gt;= n">
                        <Break />
                    </If>
                    <Item Name="[pix {i}]">pix[i]</Item>
                    <Item Name="[box array {i}]">boxa[i]</Item>
                    <Exec>i++</Exec>
                </Loop>
            </CustomListItems>
        </Expand>
    </Type>
</AutoVisualizer>
```
Thanks,
Darren

**Comment by DanBloomberg** [comment]
Thank you for the query.  I don't know anything about this, but let's leave this issue open for a while to see if we get some feedback.

  -- Dan

**Comment by fdncred** [comment]
@DanBloomberg,
I've studied the requirements of ImageWatch and maybe you can help me without knowing about ImageWatch. [Here ](https://imagewatch.azurewebsites.net/ImageWatchHelp/ImageWatchHelp.htm#_Toc345074361)are the requirements.

With your Pix format, I'm not sure how to tell 1-channel type, 2-number of channels, or 7-stride. Would you have any insight into how to determine this?

1. channel types: (represented as [type] in natvis)
    * INT8, UINT8
    * INT16, UINT16
    * INT32
    * FLOAT16
    * FLOAT32
    * FLOAT64
2. channel format denotes number of channels (max 512), optionally a format string like RGB, BGR, RGBA, etc. ([channel] in natvis)
3. image width in pixels (r[width] in natvis)
4. image height in pixels ([height] in natvis)
5. the number of planes ([planes] in natvis) optional
6. the image data ([data] in natvis) pointer to the beginning of the pixel data. For packed images, this is a single address.
7. stride ([stride] in natvis) number of bytes per pixel row.

Thanks for your time,
Darren

**Comment by DanBloomberg** [comment]
There are a lot of terms in use for the number of planes of data (e.g., the red plane for RGB).
Others are "samples", "components", "channels", etc.  In leptonica, we use "samples" and "components".

1. pix data is uint32.
  fpix data is float32
  dpix data is float64

2. channel format in leptonica for 3 and 4 sample images is RGB and RGBA.  Details of sample order are in pix.h.

5. number of planes may in leptonica be the number of samples per pixel.  1 for grayscale and colormap; 3 for rgb, etc.

7. pixGetWpl() gets the stride in 32 bit (4 byte) units.  In leptonica, each raster line is padded to 32 bits.

**Comment by fdncred** [comment]
Thanks for the info. 

I'm guessing that ImageWatch doesn't support UINT32 because the image below demonstrates as close as I can get, and to get here I have to set:
1. [type] to UINT8
2. [width] to (w *d + 7) / 8, which is 316 for the feyn.tif sample image - I realize this is wrong but this is the only setting produces any type of viewable image.
3. [stride] to wpl * 4, also 316.

All other settings that I've tried make the image "invalid" in ImageWatch. Maybe someday Microsoft will open source ImageWatch and we can really see what's happening. Until that time, I'll have to make due with saving files out, or writing a completely separate debugger visualizer.

![devenv_2018-09-20_15-58-07](https://user-images.githubusercontent.com/343840/45846767-5e971c80-bcee-11e8-9616-d9391d8ebd95.png)

**Comment by DanBloomberg** [comment]
yes, (2) is wrong.  The image width (in pixels) is 2528, which is 316 * 8.

**Comment by DanBloomberg** [comment]
No action on this for > 1 year, with issue of ImageWatch not supporting basic uint32 type.

Closing.
