### ISSUE TITLE
No pdf file created via c/invoke

### ISSUE THREAD

**Issue by Phreak87** [DanBloomberg/leptonica#371]
for a VB.Net wrapper i try to write a pdf-file and get no error and no file.
(Create PDF from files work)

My Code:

     Dim PIX32 As New Pix("Test.jpg") ' Default Pix - Created and OK, 32 BPP
     Dim C1 As New L_Pdf_Data ' L_PTRA, WH and XY via ___create created.
     pixConvertToPdf(PIX32, L_ENCODE.L_FLATE_ENCODE, "C:/Test.pdf", C1, L_T_IMAGE.L_LAST_IMAGE)
     ' Quality, x, y and Res are set to 0. Title is null.

The internal function:

     Public Shared Function pixConvertToPdf(
     ByVal pix As Pix,
     ByVal type As Integer,
     ByVal fileout As String,
     ByRef plpd As L_Pdf_Data,
     ByVal position As Integer,
     Optional ByVal quality As Integer = 0,
     Optional ByVal x As Integer = 0,
     Optional ByVal y As Integer = 0,
     Optional ByVal res As Integer = 0,
     Optional ByVal title As String = Nothing) As Integer

     Dim _Result As Integer = LeptonicaSharp.Natives.pixConvertToPdf(pix.Pointer, type, quality, fileout, x, y, res, title, plpd.Pointer, position)
     Return _Result
     End Function

and the native call

    <DllImport(DllPath, CallingConvention:=CConv, EntryPoint:="pixConvertToPdf")> _
    Friend Shared Function pixConvertToPdf(
    ByVal pix As IntPtr,
    ByVal type As Integer,
    ByVal quality As Integer,
    ByVal fileout As String,
    ByVal x As Integer,
    ByVal y As Integer,
    ByVal res As Integer,
    ByVal title As String,
    ByRef plpd As IntPtr,
    ByVal position As Integer) As Integer
    End Function

You can give it a try here: https://github.com/Phreak87/LeptonicaSharp.

**Comment by fdncred** [comment]
It looks to me like  your enum L_T_IMAGE is wrong. The c code checks for L_LAST_IMAGE == 3 and if true writes the pdf, assuming the other data is right.

Your code:
```vb
Public Enum L_T_IMAGE
''' <summary>smaller  first image to be used</summary>
L_FIRST_IMAGE
''' <summary>smaller  intermediate image; not first or last</summary>
L_NEXT_IMAGE
''' <summary>smaller  last image to be used</summary>
L_LAST_IMAGE
```
Leptonica C code:
```c
/*! Pdf multi image flags */
enum {
    L_FIRST_IMAGE   = 1,    /*!< first image to be used                      */
    L_NEXT_IMAGE    = 2,    /*!< intermediate image; not first or last       */
    L_LAST_IMAGE    = 3     /*!< last image to be used                       */
};
```

**Comment by Phreak87** [comment]
Hey Darren,

you are great!. thats it! 
with this information i think i have to double check the other enums too.
Thank you!
