### ISSUE TITLE
Leptonica pixSubtract

### ISSUE THREAD

**Issue by hkyselov** [DanBloomberg/leptonica#374]
Hello,

I have a problem with understanding the boolean subtract function and whether I can replace it with combinations of boolean operations. I'm using java wrapper for Leptonica.

pix1 is the image with the small dot in the right bottom corner
[pix1.png](https://i.stack.imgur.com/6QLnr.png)

pix2 is mask
[pix2.png](https://i.stack.imgur.com/DwhmJ.png)
When I do subtraction, the dot is removed from the image(result.png)

// pseudo code
pix1 = pix1.png;
pix2 = pix2.png;
result = Leptonica1.pixSubtract(null, pix1, pix2); // result.png
[result.png](https://i.stack.imgur.com/hD1J2.png)

It's not clear why the dot is removed.
Could please somebody explain how subtraction is working?

**Comment by DanBloomberg** [comment]
Suggestions:

* do a Google search for "binary image set subtraction"
* look at, for example, http://www.sci.utah.edu/~gerig/CS6640-F2010/B-Morse-morph1.pdf
* binary set subtraction is logically A - B == A and not-B   (convince yourself of this with a venn diagram example
* if all else fails, see the notes at the top of the source code for pixSubtract() in pix3.c

**Comment by hkyselov** [comment]
@DanBloomberg Thank you

**Comment by DanBloomberg** [comment]
you're welcome.  Bit logical operations are fun!
