### ISSUE TITLE
Process for reporting security bugs

### ISSUE THREAD

**Issue by Google-Autofuzz** [DanBloomberg/leptonica#376]
Hi Leptonica team,
As part of our fuzzing efforts at Google, we are interested in understanding the process for reporting potential security issues to your project in a private manner. Could you please advise us if there is a private tracker for these kinds of bugs, or if you prefer them filed in a publicly visible way?

Thanks!

**Comment by DanBloomberg** [comment]
It's fine to report them publicly here on github, but it doesn't seem necessary since we have an internal filing for each report.  I have no objection either way.

  -- Dan
