### ISSUE TITLE
UnpackBinary?

### ISSUE THREAD

**Issue by fdncred** [DanBloomberg/leptonica#379]
@DanBloomberg,
Shouldn't there be an pixUnpackBinary somewhere around here in order to make the red and green boxes actually red and green on the pixadb?
https://github.com/DanBloomberg/leptonica/blob/73ade46c75e6c2b44bcd07ab53d1c35e6139297e/src/jbclass.c#L1632
Perhaps something like this?
```c
    if (pixadb) {
        pix2 = pixUnpackBinary(pixs, 32, 1);
        //pix2 = pixCopy(NULL, pixs);
        pixRenderBoxaArb(pix2, boxa1, 2, 255, 0, 0);
        pixaAddPix(pixadb, pix2, L_INSERT);
        //pix2 = pixCopy(NULL, pixs);
        pix2 = pixUnpackBinary(pixs, 32, 1);
        pixRenderBoxaArb(pix2, boxa2, 2, 0, 255, 0);
        pixaAddPix(pixadb, pix2, L_INSERT);
    }
```
Thanks,
Darren

**Comment by DanBloomberg** [comment]
Thanks again, Darren.

  -- Dan
