### ISSUE TITLE
1Bpp pixWriteMemBmp

### ISSUE THREAD

**Issue by Phreak87** [DanBloomberg/leptonica#380]
Hello,

my c# wrapper supports the conversion from pix to bitmap via the pixWriteMemBmp function.
this works for all depths except 1Bpp. i don´t know if this is a Bitmap issue or a Leptonica issue.
any Idea why exactly 1Bpp doesn´t work?

    Public Function ToBitmap() As Image
        Dim Size As Integer = 0
        Dim Bytes As Byte() = Nothing
        Dim PixU As Pix = Me' (me = Pix with Pointer)

        If Me.d = 1 Then PixU = Me.pixConvertTo2
        _All.pixWriteMemBmp(Bytes, Size, Me)
        Dim MemStrm As New IO.MemoryStream(Bytes)
        Return New Bitmap(MemStrm, True)

    End Function

**Comment by DanBloomberg** [comment]
Hi Markus,

I have no way to debug your wrapper.  As far as I know, there are no problems with bmp I/O. You can run the regression tests in leptonica/prog, such as ioformats_reg, which test all formats with all different types of images.  Or you can write a little C program to read the 1 bpp image that you're having trouble with.

**Comment by Phreak87** [comment]
Hi Dan,

I will run the regression tests and check the binary output awaited from the stream function with the given bytes from leptonica. Maybe the colormaps are not transferred. Bitmap in c# is only 1bppindexed. 
And maybe if you like - add a link to the wrapper to your page too. This allows c# and vb.net users to work with your great library.

**Comment by Phreak87** [comment]
Hi Dan,

i don´t no why but now it works
my try was to save the 1bpp-file via leptonica,
read the file from fs as byte() and compare
with the bytes from memstream. All the same
and no loading problems. now it looks fine.
if this problem occurs with specific other files 
i let you know and reopen this issue.

thank you for your help.
