### ISSUE TITLE
getRGBFromOctcube in allheaders.h?

### ISSUE THREAD

**Issue by fdncred** [DanBloomberg/leptonica#385]
@DanBloomberg,
I'm confused. Is getRGBFromOctcube() supposed to be in allheaders.h? I was trying to call it from a wrapper and it doesn't seem to be available. Maybe these helper functions aren't supposed to be exported and callable. Just seeking some clarification.
Thanks,
Darren

**Comment by DanBloomberg** [comment]
It's static, which means it is only callable from inside the file colorquant1.c in which it is defined.  It is not visible globally.

**Comment by fdncred** [comment]
Thanks for the help. Please excuse my ignorance.

I'm trying to simulate k-means with your octcube functions. Is there a way to get all the colors that are represented by the output of pixOctcubeHistogram()? 

What I'm really trying to do is quantize the colors down to 7 colors plus a background color for 8 in total. My current code is based on [this ](https://github.com/mzucker/noteshrink), since it gives such great results, but I'm trying to make it more leptonica-ish.

Thanks,
Darren

**Comment by fdncred** [comment]
I can probably live with this which approximates what I'm looking for. Although, I may try to increase the saturation.
```cs
var px = pixs.pixOctcubeQuantMixedWithGray(8, 2, 36);
```
