### ISSUE TITLE
Missing openjpeg in .pc file

### ISSUE THREAD

**Issue by jeroen** [DanBloomberg/leptonica#386]
Static linking fails because `liblept.a` depends on openjpeg but this is missing from the pkg-config info:
https://github.com/DanBloomberg/leptonica/blob/ed2d7c6370bbeea2d2f843392b62239560566528/lept.pc.in#L10

**Comment by zdenop** [comment]
This is solved with PR #429

**Comment by DanBloomberg** [comment]
yes
