### ISSUE TITLE
Runtime redirection of stderr?

### ISSUE THREAD

**Issue by jbarlow83** [DanBloomberg/leptonica#388]
While Leptonica has the `-DNOCONSOLE_IO` option, it seems that most OS distributions that ship Leptonica don't set this define. It's really only useful for static linkage.

Even then, I wouldn't want to switch that off, since the error messages Leptonica reports to stderr are sometimes useful at runtime. I'd just prefer to keep Leptonica's messages out of my application's stderr output. I currently redirect stderr externally before each Leptonica call which is a bit elaborate:

https://github.com/jbarlow83/OCRmyPDF/blob/a873278c2a27808a164ae5d852b20061d920efc2/src/ocrmypdf/leptonica.py#L47

Since `fprint(stderr...)` appears many times in the code base, I suggest replacing all uses of stderr with a global variable `FILE* lepterrstream` which defaults to `stderr`.

**Comment by DanBloomberg** [comment]
By design, all the fprintf(stderr ...) calls should be in debug sections.  If you find any that are not, please let me know.

That leaves the L_INFO, L_WARNING and L_ERROR calls that are under message control. I'm sure you looked at the discussion in environ.h.  You can set things up, for example, so that you only see the error messages in stderr, and I'd guess that you won't have many of them but you might want to see them when they occur.  There is a lot of flexibility in the choice of messages going to stderr, both at compile and runtime.  Can you work within those constraints?

**Comment by jbarlow83** [comment]
It's definitely an issue that I'd end up suppressing useful error cases. For example in something as basic as `pixRead()` I would like to be able to tell the difference between two equally interesting situations at runtime: "image file not found" and "pix not read". Suppressing the errors leaves with me a NULL and no information about what went wrong.

It's not which messages are sent that I'm not looking to control, but where they are sent.

I use multiple processes not threads, so I can get away with stream redirection. But redirection won't work for a multithreaded program, unless every application access to stderr is protected by an external lock. (Or else another thread could write into the redirected stderr, corrupting it.) So I suspect there's other reasonable use cases of Leptonica in which control of where messages are sent would help

Most C libraries either don't write to stdout/err at all, or have an API that allows one to either change the output streams. Some provide a hook, e.g. `(*lept_error_handler)(msg,...)` where the default handler send the message to `fprintf(stderr)`.

Really appreciate your work on Leptonica by the way... I seem to keep finding more APIs I want to use.

**Comment by DanBloomberg** [comment]
You can always redirect stderr (as you mention); e.g., from the command line

    `anyprogram` >2 msg.txt    (overwrites any old msg.txt file)
     anyprogram >>2 msg.txt  (appends)`

Leptonica isn't designed to be run multithreaded.  Cloning can cause race conditions because functions that change the ref count aren't locked. And there are a few globals that can be reset that would affect all threads.

Can you send me a simple example of an API from a library that lets you change output streams at runtime?

**Comment by jbarlow83** [comment]
I can work around the issue, it's just not ideal.

Looking at Leptonica's dependencies:

• libpng prints messages to stderr by default, but provides an API to replace this behavior with a user callback function.
http://www.libpng.org/pub/png/libpng-1.2.5-manual.html#section-5.1

• libtiff does the same as libpng.
http://www.libtiff.org/man/TIFFError.3t.html

• libjpeg exposes method pointers for error callback functions in a context structure that the user is allowed to change. Same idea, slightly different implementation.
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/libjpeg.txt#L1434

Thinking more about, a callback API is the better way to go than an API that changes the target output stream. A callback API lets the caller do whatever it wants to handle an error, which might not be writing to an output stream.

**Comment by DanBloomberg** [comment]
Thank you.  I'll see how those libraries handle the callbacks.

My other concern with output to arbitrary files is security vulnerabilities.  I'll run this by Google's security operations to see if it introduces any obvious issues.

**Comment by jbarlow83** [comment]
I am now trying to get Leptonica working with a Windows application and have again run into issue.

To clarify, Leptonica would not write to arbitrary files if this were implemented.

Leptonica should provide a single new API call that takes a callback function as a parameter and saves the callback function in a Leptonica global variable. Then, instead of using `fprintf` for example, Leptonica could call a new function like `lept_fprintf` which would first check if a callback is registered and call it with the formatted message as a parameter, or failing that, call `fprintf` as usual.

This is the standard practice in high security-concern libraries like libjpeg and libpng. This change would also *improve* security. In its current form, Leptonica current leaks error handling information to stdout and stderr.

Libraries like Leptonica that write to stdout/stderr are usually disparaged for doing so:
* https://stackoverflow.com/questions/37122208/shared-library-is-outputting-into-stdout
* https://stackoverflow.com/questions/22941756/how-do-i-prevent-a-library-to-print-to-stdout-in-linux-c
* https://www.reddit.com/r/C_Programming/comments/97ebfj/redirect_stdout_and_stderr_to_a_buffer/e47n9kh/
* https://git.kernel.org/pub/scm/linux/kernel/git/kay/libabc.git/plain/README

**Comment by DanBloomberg** [comment]
Thank you for your patience!

Your first suggestion was this:

Since fprint(stderr...) appears many times in the code base, I suggest replacing all uses of stderr with a global variable FILE* lepterrstream which defaults to stderr.

This seems doable, and we would include a function that can change the value of lepterrstream at runtime.   And it solves your problem.  Note that there are 450 calls for output to stderr.

You've now suggested another method for controlling output to stderr, using a wrapper to fprintf() with a callback.  What are the pros and cons of the two methods?

Note that few of these writes to stderr are debug routines and *Info() functions, which wouldn't be called in a production environment.  Should they be altered as well?

If you prefer the wrapper/callback approach, can you provide sample code for lept_fprintf() and an example of a registered callback.  Am I correct in assuming that you would want a callback function that sends to an arbitrary stream?

  Dan

**Comment by jbarlow83** [comment]
I think the wrapper/callback method is definitely superior because it's more convenient for languages other than C and C++. Pretty much every language supports callbacks from C, but obtaining a FILE* can be inconvenient in managed languages. A callback is infinitely more flexible. (I only suggested the global variable, at first, it seemed like it would be an easier change to make. I would not bother with this method.)

I'd also suggesting making it the policy that the Leptonica library never writes to stdout or stderr, except through the default callback handler it supplies. (`prog/*` of course can write directly). Even for debug and Info*() - I think it's easy to make it a policy. It means a naked printf/fprintf is a bug. After all, when implemented Leptonica behave exactly as before because the default handler would write to stderr.

It could look something like this. Then all instances of `fprintf(stderr, ...)` would be replaced with `lept_stderr(...)` or similar.

```c

static void lept_default_stderr_handler(const char *formatted_msg)
{
    if (formatted_msg)
        fputs(formatted_msg, stderr);
}

/* The handler is private to leptonica */
void (*stderr_handler)(const char *) = lept_default_stderr_handler;

LEPT_DLL
void leptSetStderrHandler(void (*handler)(const char *))
{
    if (handler)
        stderr_handler = handler;
    else
        stderr_handler = lept_default_stderr_handler;
}

#define MAX_DEBUG_MESSAGE 1000

LEPT_DLL
void lept_stderr(const char *fmt, ...) __attribute__ ((format (printf, 1, 2))
{
    va_list args; 
    char msg[MAX_DEBUG_MESSAGE];
    int n;

    va_start(args);
    n = vsnprintf(msg, sizeof(msg), fmt, args);
    va_end(args);
    if (n < 0)
        return;
    (*stderr_handler)(msg);
}

```

(The `__attribute__` syntax tells gcc to treat the first argument as printf-style string and raise warnings/errors if the variable arguments do not match the string, to prevent undefined behavior. It can be wrapped in a GCC-only macro.)

Example usage - let's say we want to route Leptonica errors to the Linux/POSIX system logger:

```c

void send_to_syslog(const char *msg)
{
    syslog(1, msg);
}    

void main() 
{
    leptSetStderrHandler(send_to_syslog);
    (void)pixRead("does_not_exist.png");  /* will call lept_stderr */
}

**Comment by DanBloomberg** [comment]
Thank you!  All looks great.

A couple of questions:
(1) what is the GCC-only macro that could be used to include the printf template?

(2) LEPT_DLL is added to all public functions by xtractprotos, which generates allheaders.h.  So lept_stderr() and leptSetStderrHandler() would have their prototypes in allheaders.h, and we don't need it here.

I'll put this in utils1.c.

**Comment by jbarlow83** [comment]
(1) Should look like this - the `__attribute__` must go with the function declaration, not the definition, so that external modules known to apply those checks. It does not go on the definition

```c
#if __GNUC__ >= 4
#define PRINTF_ARGUMENT_CHECKS __attribute__ ((format (printf, 1, 2)))
#else
#define PRINTF_ARGUMENT_CHECKS
#endif

void lept_stderr(const char *fmt, ...) PRINTF_ARGUMENT_CHECKS;
```

When used you get errors like:
```
lept.c:49:34: warning: format specifies type 'char *' but the argument has type
      'int' [-Wformat]
int main(){ lept_stderr("hi %s", 42);}
                            ~~   ^~
                            %d
1 warning generated.
```

(2) Sounds good.

**Comment by DanBloomberg** [comment]
Using the attribute is too complicated, because my prototypes are auto generated by xtractprotos, which uses the function definition to pull out the prototypes.

Also,  lept_stderr("hi %s", 42) seg faults, and when  I put the attribute in by hand in allheaders.h, it still seg faults.

**Comment by jbarlow83** [comment]
fprintf(stderr, "hi %s", 42); will segfault too.

The attribute is just a convenience that should trigger a compiler warning.
It's not essential.

**Comment by DanBloomberg** [comment]
I still have 450 subs to do.  Will do this in conjunction with another widespread change, adding an include of config_auto.h.

**Comment by DanBloomberg** [comment]
@jbarlow83 

I believe we're finally ready to close this.  Do you agree?

**Comment by jbarlow83** [comment]
I believe so. If there are any issue related I'll open them separately.

Thanks and happy $holiday_of_choice.
