### ISSUE TITLE
Byte Array Join bug?

### ISSUE THREAD

**Issue by fdncred** [DanBloomberg/leptonica#391]
@DanBloomberg, I'm confused over this [line ](https://github.com/DanBloomberg/leptonica/blob/d8e8d2d1e983502b36e4ab052849452b19bb5ea3/src/bytearray.c#L483)of code.

It appears that parameter 2, pba2, is an [in,out] variable, however right before returning you are deleting pba2. Should that perhaps be ba2, as the comments indicate, or have I just misunderstood the code?
Code:
```c
/*---------------------------------------------------------------------*
 *                        String join/split                            *
 *---------------------------------------------------------------------*/
/*!
 * \brief   l_byteaJoin()
 *
 * \param[in]       ba1
 * \param[in,out]   pba2 data array is added to the one in ba1, and
 *                       then ba2 is destroyed
 * \return  0 if OK, 1 on error
 *
 * <pre>
 * Notes:
 *      (1) It is a no-op, not an error, for %ba2 to be null.
 * </pre>
 */
l_ok
l_byteaJoin(L_BYTEA   *ba1,
            L_BYTEA  **pba2)
{
l_uint8  *data2;
size_t    nbytes2;
L_BYTEA  *ba2;

    PROCNAME("l_byteaJoin");

    if (!ba1)
        return ERROR_INT("ba1 not defined", procName, 1);
    if (!pba2)
        return ERROR_INT("&ba2 not defined", procName, 1);
    if ((ba2 = *pba2) == NULL) return 0;

    data2 = l_byteaGetData(ba2, &nbytes2);
    l_byteaAppendData(ba1, data2, nbytes2);

    l_byteaDestroy(pba2);
    return 0;
}
```

**Comment by fdncred** [comment]
Hey Dan,
Thanks for the explanation. This entire thing was my ignorance. Even after reading the code, I was thinking the return value was in pba2 when it's actually ba1 that is appended to. Usually when one has an out variable the data for the function is returned in that out variable. My mistake for misunderstanding your code.

Darren

**Comment by DanBloomberg** [comment]
Glad to help.  I am modifying the description to make it a bit clearer.

  -- Dan
