### ISSUE TITLE
byteatest.c suggestion - accomodate windows line endings in tests

### ISSUE THREAD

**Issue by fdncred** [DanBloomberg/leptonica#392]
@DanBloomberg,
While running byteatest.c I noticed that one test always failed. I tracked it down because I'm on windows.  In the following [code](https://github.com/DanBloomberg/leptonica/blob/b40e02de21823270969934190f2331ebef7812e3/prog/byteatest.c#L97), perhaps it should look something like this since windows has crlf as line endings. Perhaps there should also be a `#elseif _MACOS` with `\r` as well - Not sure on that one.
```c
    for (i = 0; i < n; i++)
    {
        str = sarrayGetString(sa, i, L_NOCOPY);
        l_byteaAppendString(lba1, str);
#ifdef _WIN32
        l_byteaAppendString(lba1, "\r\n");
#else
        l_byteaAppendString(lba1, "\n");
#endif
    }
```
This way when it comes time to do the `filesAreIdentical()` test, it works on windows too.
Thanks,
Darren

**Comment by amitdo** [comment]
>should also be a #elseif _MACOS with \r as well - Not sure on that one.

Only if you want to support 'classic' Mac OS, before OSX, last version was 9.2.2, released on December 5, 2001. 

OSX (now macOS) always used '\n' for line break.

**Comment by fdncred** [comment]
I can understand your reluctance however, the code is not opening a file in text mode. It calls `l_binaryRead()` which of course does this at a lower level `fp = fopen(fname, "rb");`.  So, the SO reference may not apply. I'm not sure how windows could be convinced read a file in binary mode any other way.

Maybe if there were a `l_binaryReadAsText()` where it passes the `_O_TEXT` mode to fopen, as described [here](https://docs.microsoft.com/en-us/cpp/c-runtime-library/text-and-binary-mode-file-i-o?view=vs-2017), it would be translated to `\n` from it's current `\r\n`, but I haven't tested that. I'm not even sure this makes sense, binary as text is just weird. ;)

**Comment by DanBloomberg** [comment]
OK, I'll fix it.  Will also convert byteatest to a proper regression test (bytea_reg).

**Comment by DanBloomberg** [comment]
Fixed.

**Comment by DanBloomberg** [comment]
Unfixed and fixed again.  The issue can remain closed.
