### ISSUE TITLE
pixOtsuAdaptiveThreshold return 1

### ISSUE THREAD

**Issue by hedonis** [DanBloomberg/leptonica#393]
Hello,
I'm using Leptonica.net 1.75.06 in C# VS2017

Pix p1,p2;
Pix pix = Pix1.pixReadFromMemoryStream(File.Open(openFileDialog1.FileName, FileMode.Open));
int y=pix.pixOtsuAdaptiveThreshold(20,20,0,0,0,out p1,out p2);

pixOtsuAdaptiveThreshold function return 1 (error) and I don't why

**Comment by DanBloomberg** [comment]
I can't debug your C# wrapper code.

Nearly every function in the leptonica library will emit error messages when it returns due to an error condition.  You need to look at the messages.  If your C# wrapper doesn't give error messages, that makes it harder to debug problems.

**Comment by hedonis** [comment]
Thank You for quick response. My wrapper doesn't produce any message. Only function return 1. Can You explain me what for are out arguments in this function and are they nessesery?

**Comment by DanBloomberg** [comment]
From the function header documentation, the last of the output arguments is the binarized image, which is the raison d'etre for this function.

``/*!
 * \brief   pixOtsuAdaptiveThreshold()
 *
 * \param[in]    pixs 8 bpp
 * \param[in]    sx, sy desired tile dimensions; actual size may vary
 * \param[in]    smoothx, smoothy half-width of convolution kernel applied to
 *                                threshold array: use 0 for no smoothing
 * \param[in]    scorefract fraction of the max Otsu score; typ. 0.1;
 *                          use 0.0 for standard Otsu
 * \param[out]   ppixth [optional] array of threshold values
 *                      found for each tile
 * \param[out]   ppixd [optional] thresholded input pixs, based on
 *                     the threshold array
 * \return  0 if OK, 1 on error
 *
``

**Comment by hedonis** [comment]
Image must be in gray scele :)

**Comment by hedonis** [comment]
Thank's for explanation.
