### ISSUE TITLE
Error on Sel s = Sel1.selCreateBrick(1, 50, 0, 0, 0);

### ISSUE THREAD

**Issue by hedonis** [DanBloomberg/leptonica#396]
Hi,
When i running my app i get error :
System.NotImplementedException
  HResult=0x80004001
  Message=method or operation is not implemented
  Source=leptonica.net

 Sel s = Sel1.selCreateBrick(1, 50, 0, 0, 0);

i'm using vs2017 and leptonica.net tvn-cosine 1.75.0.6.
Any idea's? :)

**Comment by Phreak87** [comment]
Leptonica supports this but tvns version does not wrap this function.
You can use LeptonicaSharp instead of

**Comment by hedonis** [comment]
When try
PM> Install-Package LeptonicaSharp -Version 1.77.0.1

I get : 
       Install failed. Rolling back...
       Package 'leptonicaSharp.1.77.0.1' does not exist in project 'WindowsFormsApp3'
       Package 'leptonicaSharp.1.77.0.1' does not exist in folder 
       'C:\Users\seba\source\repos\WindowsFormsApp3\packages'
       Executing nuget actions took 867,98 ms
        Install-Package : Could not install package 'leptonicaSharp 1.77.0.1'. You are trying to install this 
       package into a project that targets '.NETFramework,Version=v4.6.
       1', but the package does not contain any assembly references or content files that are compatible 
       with that framework. For more information, contact the package autho
       r.
      At line:1 char:16
         + Install-Package <<<<  LeptonicaSharp -Version 1.77.0.1
         + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
         + FullyQualifiedErrorId : 
 NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by Phreak87** [comment]
Please close this issue (it's not a leptonica issue) and post the issues to the library's issue list. For LeptonicaSharp I can help, but not in this issue
