### ISSUE TITLE
'getcwd' is deprecated (windows&clang with msvc compatibility)

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#398]
I got this:

> warning: 'getcwd' is deprecated: The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _getcwd. See online help for details.

regarding following code:
https://github.com/DanBloomberg/leptonica/blob/7dac4b18eab74e44dd4b03f0539352acbc986f1a/src/utils2.c#L2894

**Comment by stweil** [comment]
Linux and macOS still need `getcwd`, so Windows requires separate code to fix the warning.

**Comment by zdenop** [comment]
Maybe there is [other problem related to getcwd](https://stackoverflow.com/questions/2868680/what-is-a-cross-platform-way-to-get-the-current-directory):
> If  buf is a null pointer, the behavior of getcwd() is unspecified.
