### ISSUE TITLE
Warnings from clan on windows

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#399]
FYI:
I tried to build leptonica with clan 8 (msvc compatibility) on windows and I got of warnings:
*  'register' storage class specifier is deprecated and incompatible with C++17 [-Wdeprecated-register]
*  unused variable... - but I just build leptonica with zlib and png

More details are in [build.log.gz](https://github.com/DanBloomberg/leptonica/files/2717376/build.log.gz).

**Comment by DanBloomberg** [comment]
Removed the register declarations and the unused variables that are really unused.  The variables in tiff routines are required if linking the tiff library.
