### ISSUE TITLE
pixDeskew produce more blurry image with text

### ISSUE THREAD

**Issue by andrew-vandenbrink** [DanBloomberg/leptonica#401]
![image](https://user-images.githubusercontent.com/12871379/51842041-496f7180-2310-11e9-9600-67a24f4c184a.png)

Left is original, right is the result

is this expected?

**Comment by DanBloomberg** [comment]
It is possible.  Deskew uses linear interpolation (equivalent to area mapping) for the destination pixels (see rotateam.c).  If you repeatedly rotate by a small amount, blur will accumulate.  See prog/rotate1_reg.c

You can compensate for this by doing a sharpening operation after the deskew:
    pixUnsharpMasking()

  -- Dan

**Comment by andrew-vandenbrink** [comment]
Thanks, this function is quite important on our pipeline, i tried with pixUnsharpMasking, still it does not match the original document

**Comment by DanBloomberg** [comment]
Sorry this is causing you problems.

Higher order (than linear) interpolation functions can be used, but they're complicated and considerably more compute intensive, and I haven't tried to implement them.

**Comment by DanBloomberg** [comment]
An alternative is to use a winner-take-all approach to the area calculation.  Much slower than a linear or polynomial combination, but it should produce sharp edges.

**Comment by andrew-vandenbrink** [comment]
Thanks, I could try to get the angle from leptonica and then rotate it with opencv...

**Comment by DanBloomberg** [comment]
I did some experiments.  Winner-take-all doesn't work -- it has all the usual sampling artifacts.

However, doing unsharp masking after an area mapping rotation has the desired effect of reducing the blur that was introduced with the rotation.  A small amount of sharpening will do the trick; e.g.,
    pix2 = pixUnsharpMasking(pix1, 1, 0.3);

I've added some discussion of this to the comments in the header of rotateam.c.

**Comment by andrew-vandenbrink** [comment]
Sorry to close the issue early, thank you for you suggestion seems it produce better result, but still not close to original

![image](https://user-images.githubusercontent.com/12871379/52040148-cd0aa780-2536-11e9-8f08-4142c9c60334.png)

From bottom to top, original -> deskew only -> deskew+unsharp mask

**Comment by DanBloomberg** [comment]
A bit of extra noise on the edge is visible due to the sharpening, but but blur has been significantly reduced so it looks pretty good to me.  Was this with parameters 1 and 0.3 for sharpening?

If you can do better by some other method, please let me know.  Otherwise, I'll close this in a month or so.

**Comment by andrew-vandenbrink** [comment]
Hmm the first image is the one with unsharp mask.
Yes it is with parameters 1 and 0.3

Ill see what I can do, its ok to close it, ill update once i find the solution...
