### ISSUE TITLE
Include within function callSystemDebug.

### ISSUE THREAD

**Issue by marcosjom** [DanBloomberg/leptonica#405]
Hi, I'm compiling leptonica using XCode 10 (OSX 10.13.6), and the compiler is complaining about an include within the function. Just wanted to share this issue.

Issue: leptonica/src/utils2.c:2491:3: Import of module 'Darwin.TargetConditionals' appears within function 'callSystemDebug'

To solve it:

(1) Remove from _callSystemDebug_'s body:
 _#include "TargetConditionals.h"_

(2) Add before _callSystemDebug_:
_#if defined (__APPLE__)  /* iOS 11 does not support system() */
#include "TargetConditionals.h"
#endif_

**Comment by DanBloomberg** [comment]
You're using some old version of leptonica, and I suspect this problem has been fixed.

Try using version 1.77, or github at head.

**Comment by marcosjom** [comment]
I'm using 1.77, and the #include I'm refering to is at HEAD in the file "utils2.c" (last modified a month ago).

**Comment by DanBloomberg** [comment]
I see the Target Conditionals include at l. 2646, not l. 2491.

But I see what you're saying.  I'll make the change.

**Comment by marcosjom** [comment]
Thanks!

**Comment by DanBloomberg** [comment]
Fixed.  Thank you for raising the issue.

  -- Dan
