### ISSUE TITLE
Make failed Missing zlib.h, zconf.h in the src

### ISSUE THREAD

**Issue by geyungjen** [DanBloomberg/leptonica#408]
make failed.

/home/megan/lept/leptonica/src/libversions.c:66:10: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
          ^~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/leptonica.dir/libversions.c.o] Error 1
make[1]: *** [src/CMakeFiles/leptonica.dir/all] Error 2
make: *** [all] Error 2

Bacause of import "zlib.h", this assume it is in the same src dir where the c code is.

So I copied zlib.h and zconf.h to the src to continue make

(base) [megan@localhost build]$ cp /usr/include/zlib.h /home/megan/lept/leptonica/src/
(base) [megan@localhost build]$ cp /usr/include/"zconf.h" /home/megan/lept/leptonica/src/

It compiled all to object files.

Then linking failed

[ 53%] Building C object src/CMakeFiles/leptonica.dir/zlibmemstub.c.o
[ 54%] Linking C shared library libleptonica.so
/home/megan/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[2]: *** [src/libleptonica.so.1.78.0] Error 1
make[1]: *** [src/CMakeFiles/leptonica.dir/all] Error 2
make: *** [all] Error 2

Any work around? Thanks!

**Comment by DanBloomberg** [comment]
Sorry, I don't know what you are doing, or whether you're using cmake or autoconf, or what platform (hardware, software) you're trying to build on.

Traditionally, library header files go in /usr/include or /usr/local/include.  You certainly do not want to put them in a leptonica source directory.

**Comment by geyungjen** [comment]
Thanks for the reply.

I have centos 7

(base) [megan@localhost build]$ cat /etc/*release*
CentOS Linux release 7.6.1810 (Core)
Derived from Red Hat Enterprise Linux 7.6 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.6.1810 (Core)
CentOS Linux release 7.6.1810 (Core)
cpe:/o:centos:centos:7

1. I git clone this
2. cd /home/megan/lept/leptonica/src/build after mkdir /home/megan/lept/leptonica/src
3. cmake ../../

(base) [megan@localhost build]$ cmake ../../
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /home/megan/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc
-- Check for working C compiler: /home/megan/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/megan/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++
-- Check for working CXX compiler: /home/megan/anaconda3/bin/x86_64-conda_cos6-linux-gnu-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find GIF (missing: GIF_LIBRARY GIF_INCLUDE_DIR)
-- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- Checking for module 'libwebp'
--   No package 'libwebp' found
-- Checking for module 'libopenjp2'
--   No package 'libopenjp2' found
-- Looking for WEBP
-- Looking for include file dlfcn.h
-- Looking for include file dlfcn.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file strings.h
-- Looking for include file strings.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file openjpeg-2.0/openjpeg.h
-- Looking for include file openjpeg-2.0/openjpeg.h - not found
-- Looking for include file openjpeg-2.1/openjpeg.h
-- Looking for include file openjpeg-2.1/openjpeg.h - not found
-- Looking for include file openjpeg-2.2/openjpeg.h
-- Looking for include file openjpeg-2.2/openjpeg.h - not found
-- Looking for include file openjpeg-2.3/openjpeg.h
-- Looking for include file openjpeg-2.3/openjpeg.h - not found
-- Looking for fmemopen
-- Looking for fmemopen - found
-- Looking for fstatat
-- Looking for fstatat - found
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Configuring done
-- Generating done
-- Build files have been written to: /home/megan/lept/leptonica/src/build


4. make

(base) [megan@localhost build]$ make
Scanning dependencies of target leptonica
[  0%] Building C object src/CMakeFiles/leptonica.dir/adaptmap.c.o
[  1%] Building C object src/CMakeFiles/leptonica.dir/affine.c.o
[  1%] Building C object src/CMakeFiles/leptonica.dir/affinecompose.c.o
[  2%] Building C object src/CMakeFiles/leptonica.dir/arrayaccess.c.o
[  2%] Building C object src/CMakeFiles/leptonica.dir/bardecode.c.o
[  3%] Building C object src/CMakeFiles/leptonica.dir/baseline.c.o
[  4%] Building C object src/CMakeFiles/leptonica.dir/bbuffer.c.o
[  4%] Building C object src/CMakeFiles/leptonica.dir/bilateral.c.o
[  5%] Building C object src/CMakeFiles/leptonica.dir/bilinear.c.o
[  5%] Building C object src/CMakeFiles/leptonica.dir/binarize.c.o
[  6%] Building C object src/CMakeFiles/leptonica.dir/binexpand.c.o
[  6%] Building C object src/CMakeFiles/leptonica.dir/binreduce.c.o
[  7%] Building C object src/CMakeFiles/leptonica.dir/blend.c.o
[  8%] Building C object src/CMakeFiles/leptonica.dir/bmf.c.o
...

[ 47%] Building C object src/CMakeFiles/leptonica.dir/libversions.c.o
/home/megan/lept/leptonica/src/libversions.c:66:10: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
          ^~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/leptonica.dir/libversions.c.o] Error 1
make[1]: *** [src/CMakeFiles/leptonica.dir/all] Error 2
make: *** [all] Error 2

5. If I copy /usr/local/include/zlib.h and zconf.h

Compile will complete, but linking will throw error

 53%] Building C object src/CMakeFiles/leptonica.dir/zlibmemstub.c.o
[ 54%] Linking C shared library libleptonica.so
/home/megan/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[2]: *** [src/libleptonica.so.1.78.0] Error 1
make[1]: *** [src/CMakeFiles/leptonica.dir/all] Error 2
make: *** [all] Error 2

Hope these info are helpful to find what I did wrong.

Thanks again

**Comment by geyungjen** [comment]
If there are some environmental variables needed to be set? But I did not find any in readme

**Comment by geyungjen** [comment]
By the way, my hardware is:

Intel 8th gen 8700T, 64GB RAM, 1 128GB SSD for OS, 2 6TB HDD for non OS.

(base) [megan@localhost build]$ sudo cat /proc/cpuinfo | grep processor
[sudo] password for megan:
processor       : 0
processor       : 1
processor       : 2
processor       : 3
processor       : 4
processor       : 5
processor       : 6
processor       : 7
processor       : 8
processor       : 9
processor       : 10
processor       : 11
(base) [megan@localhost build]$ free
              total        used        free      shared  buff/cache   available
Mem:       65671528     1530280    22337272       39772    41803976    62534072
Swap:      12505084           0    12505084

(base) [megan@localhost build]$ df -k
Filesystem               1K-blocks     Used  Available Use% Mounted on
/dev/mapper/centos-root   52403200 33387248   19015952  64% /
devtmpfs                  32818412        0   32818412   0% /dev
tmpfs                     32835764        0   32835764   0% /dev/shm
tmpfs                     32835764    18400   32817364   1% /run
tmpfs                     32835764        0   32835764   0% /sys/fs/cgroup
/dev/sdb1               5814184472   507216 5520634824   1% /data/disk1
/dev/sdc1               5814184472    90136 5521051904   1% /data/disk2
/dev/sda2                  1038336   226408     811928  22% /boot
/dev/mapper/centos-home   58814404 41419708   17394696  71% /home
/dev/sda1                   204580    11512     193068   6% /boot/efi
tmpfs                      6567156       12    6567144   1% /run/user/42
tmpfs                      6567156        0    6567156   0% /run/user/1000
tmpfs                      6567156        0    6567156   0% /run/user/0

**Comment by geyungjen** [comment]
Never mind, I fix it.

Just log in as root and cmake, make, make install.

Done.

It was the anacounda cc and ld caused the issue.

Thanks
