### ISSUE TITLE
Unable to build Leptonica 1.78.0

### ISSUE THREAD

**Issue by SteveKlinko** [DanBloomberg/leptonica#409]
First error is a link error: alpha_dec.obj module machine type 'x86' conflicts with target machine type 'x64' in cppan-d-b-d project. Then 10 more errors saying: missing type specifier in tiff.h in the leptonica project

**Comment by zdenop** [comment]
Please post all details e.g. how to configure build, build tools version configure log, build log...

**Comment by SteveKlinko** [comment]
I forgot to say that I am trying to build for x64. I used CPPAN to create the Visual Studio solution. I configure the VS solution for x64. Here is the Build output from VS:

1>------ Rebuild All started: Project: ZERO_CHECK, Configuration: Release x64 ------
1>Checking Build System
1>CMake does not need to re-run because C:/WORKSPACES_MISC/ApplicationController64/leptonica-1.78.0/build/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/WORKSPACES_MISC/ApplicationController64/leptonica-1.78.0/build/.cppan/CMakeFiles/generate.stamp is up-to-date.
1>CMake does not need to re-run because C:/WORKSPACES_MISC/ApplicationController64/leptonica-1.78.0/build/src/CMakeFiles/generate.stamp is up-to-date.
2>------ Rebuild All started: Project: cppan-d-b-d, Configuration: Release x64 ------
2>Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
2>Copyright (C) Microsoft Corporation. All rights reserved.
2>
2>338b7ef3.dir\Release\alpha_dec.obj : fatal error LNK1112: module machine type 'x86' conflicts with target machine type 'x64' [C:\Users\steve\.cppan\storage\obj\33\8b\7ef3\build\9dda6c96\cppan\338b7ef3\338b7ef3.vcxproj]
2>CMake Error at C:/Users/steve/.cppan/storage/etc/static/functions.cmake:689 (message):
2>CUSTOMBUILD : Last execute_process() with message '' failed with error : 1
2>Call Stack (most recent call first):
2>  C:/Users/steve/.cppan/storage/etc/static/build.cmake:203 (check_result_variable)
2>  C:/Users/steve/.cppan/storage/obj/33/8b/7ef3/build.cmake:34 (include)
2>
2>
2>Done building project "cppan-d-b-d.vcxproj" -- FAILED.
3>------ Rebuild All started: Project: build-dependencies, Configuration: Release x64 ------
3>Building Custom Rule C:/WORKSPACES_MISC/ApplicationController64/leptonica-1.78.0/.cppan/CMakeLists.txt
3>CMake does not need to re-run because C:/WORKSPACES_MISC/ApplicationController64/leptonica-1.78.0/build/.cppan/CMakeFiles/generate.stamp is up-to-date.
4>------ Rebuild All started: Project: leptonica, Configuration: Release x64 ------
4>Building Custom Rule C:/WORKSPACES_MISC/ApplicationController64/leptonica-1.78.0/src/CMakeLists.txt
4>CMake does not need to re-run because C:/WORKSPACES_MISC/ApplicationController64/leptonica-1.78.0/build/src/CMakeFiles/generate.stamp is up-to-date.
4>adaptmap.c
4>affine.c
4>affinecompose.c
4>arrayaccess.c
4>bardecode.c
4>baseline.c
4>bbuffer.c
4>bilateral.c
4>bilinear.c
4>binarize.c
4>binexpand.c
4>binreduce.c
4>blend.c
4>bmf.c
4>bmpio.c
4>bmpiostub.c
4>bootnumgen1.c
4>bootnumgen2.c
4>bootnumgen3.c
4>bootnumgen4.c
4>boxbasic.c
4>boxfunc1.c
4>boxfunc2.c
4>boxfunc3.c
4>boxfunc4.c
4>boxfunc5.c
4>bytearray.c
4>ccbord.c
4>ccthin.c
4>classapp.c
4>colorcontent.c
4>coloring.c
4>colormap.c
4>colormorph.c
4>colorquant1.c
4>colorquant2.c
4>colorseg.c
4>colorspace.c
4>compare.c
4>conncomp.c
4>convertfiles.c
4>convolve.c
4>correlscore.c
4>dewarp1.c
4>dewarp2.c
4>dewarp3.c
4>dewarp4.c
4>dnabasic.c
4>dnafunc1.c
4>dnahash.c
4>dwacomb.2.c
4>dwacomblow.2.c
4>edge.c
4>encoding.c
4>enhance.c
4>fhmtauto.c
4>fhmtgen.1.c
4>fhmtgenlow.1.c
4>finditalic.c
4>flipdetect.c
4>fliphmtgen.c
4>fmorphauto.c
4>fmorphgen.1.c
4>fmorphgenlow.1.c
4>fpix1.c
4>fpix2.c
4>gifio.c
4>gifiostub.c
4>gplot.c
4>graphics.c
4>graymorph.c
4>grayquant.c
4>heap.c
4>jbclass.c
4>jp2kheader.c
4>jp2kheaderstub.c
4>jp2kio.c
4>jp2kiostub.c
4>jpegio.c
4>jpegiostub.c
4>kernel.c
4>leptwin.c
4>libversions.c
4>list.c
4>map.c
4>maze.c
4>morph.c
4>morphapp.c
4>c:\users\steve\.cppan\storage\src\1f\16\f783\libtiff\tiff.h(74): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\WORKSPACES_MISC\ApplicationController64\leptonica-1.78.0\src\libversions.c)
4>c:\users\steve\.cppan\storage\src\1f\16\f783\libtiff\tiff.h(75): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\WORKSPACES_MISC\ApplicationController64\leptonica-1.78.0\src\libversions.c)
4>c:\users\steve\.cppan\storage\src\1f\16\f783\libtiff\tiff.h(77): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\WORKSPACES_MISC\ApplicationController64\leptonica-1.78.0\src\libversions.c)
4>c:\users\steve\.cppan\storage\src\1f\16\f783\libtiff\tiff.h(78): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\WORKSPACES_MISC\ApplicationController64\leptonica-1.78.0\src\libversions.c)
4>morphdwa.c
4>morphseq.c
4>numabasic.c
4>numafunc1.c
4>numafunc2.c
4>pageseg.c
4>paintcmap.c
4>parseprotos.c
4>partition.c
4>pdfio1.c
4>pdfio1stub.c
4>pdfio2.c
4>pdfio2stub.c
4>pix1.c
4>pix2.c
4>pix3.c
4>pix4.c
4>pix5.c
4>pixabasic.c
4>pixacc.c
4>pixafunc1.c
4>pixafunc2.c
4>pixalloc.c
4>pixarith.c
4>pixcomp.c
4>pixconv.c
4>pixlabel.c
4>pixtiling.c
4>pngio.c
4>pngiostub.c
4>pnmio.c
4>pnmiostub.c
4>projective.c
4>psio1.c
4>psio1stub.c
4>psio2.c
4>psio2stub.c
4>ptabasic.c
4>ptafunc1.c
4>ptafunc2.c
4>ptra.c
4>quadtree.c
4>queue.c
4>rank.c
4>rbtree.c
4>readbarcode.c
4>readfile.c
4>recogbasic.c
4>recogdid.c
4>recogident.c
4>recogtrain.c
4>regutils.c
4>rop.c
4>roplow.c
4>rotate.c
4>rotateam.c
4>rotateorth.c
4>rotateshear.c
4>runlength.c
4>sarray1.c
4>sarray2.c
4>scale1.c
4>scale2.c
4>seedfill.c
4>sel1.c
4>sel2.c
4>selgen.c
4>shear.c
4>skew.c
4>spixio.c
4>stack.c
4>stringcode.c
4>strokes.c
4>sudoku.c
4>textops.c
4>tiffio.c
4>tiffiostub.c
4>utils1.c
4>utils2.c
4>warper.c
4>watershed.c
4>C:\Users\steve\.cppan\storage\src\1f\16\f783\libtiff\tiff.h(74): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\WORKSPACES_MISC\ApplicationController64\leptonica-1.78.0\src\tiffio.c)
4>C:\Users\steve\.cppan\storage\src\1f\16\f783\libtiff\tiff.h(75): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\WORKSPACES_MISC\ApplicationController64\leptonica-1.78.0\src\tiffio.c)
4>C:\Users\steve\.cppan\storage\src\1f\16\f783\libtiff\tiff.h(77): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\WORKSPACES_MISC\ApplicationController64\leptonica-1.78.0\src\tiffio.c)
4>C:\Users\steve\.cppan\storage\src\1f\16\f783\libtiff\tiff.h(78): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\WORKSPACES_MISC\ApplicationController64\leptonica-1.78.0\src\tiffio.c)
4>webpio.c
4>webpiostub.c
4>writefile.c
4>zlibmem.c
4>zlibmemstub.c
4>Done building project "leptonica.vcxproj" -- FAILED.
========== Rebuild All: 2 succeeded, 2 failed, 0 skipped ==========

Thank You

**Comment by zdenop** [comment]
Once again please provide all details how you configure build - you just give only build log. From that it looks like you tried to build it fox x86 first and than 'x64' ...

I just build fresh leptonica x64 build from git master with cppan and it was without problem.  So there should be problem how you configure leptonica (or run the build)

**Comment by SteveKlinko** [comment]
When I run cppan I get:

Initializing Storage
Packages Database not found
Downloading Database

Then it downloads a bunch of things.
But I am skeptical about the Packages database not found statement.

What could this be?

**Comment by egorpugin** [comment]
Hi,

Could you use SW instead of cppan?
SW is cppan v2.

See
https://software-network.org/
https://github.com/SoftwareNetwork/sw

Download sw, put to PATH and run `sw generate` in leptonica folder.

**Comment by bleze** [comment]
Reviving this since I encountered same problem...

I ran sw generate to get Visual Studio solution. Opened it and changed toolset to v141 (2017) and made a RelWithDebInfoDLL x64 build, however the linker is looking for a lib that is missing;
LINK : fatal error LNK1104: cannot open file 'C:\Users\xyz\.sw\storage\pkg\89\dc\64e7\obj\bld\c4dc85\lib\org.sw.demo.gif-5.2.1.lib'.

Don't need GIF support - basically only TIFF I think. Not sure where to go next...

**Comment by egorpugin** [comment]
Post `sw --version` here.
Anyways sw does not generate VS solutions properly yet.
You should generate specific single config to run without errors.
Run `sw -config rwdi generate` - for rel with deb info.
d - debug
r - release
msr - min size rel

**Comment by bleze** [comment]
Thanks for quick response!

sw.client.sw version 0.3.1.

Tried with sw -config rwdi generate, however building that solution gives me same linker error :(

**Comment by egorpugin** [comment]
Oh, 0.3.1 does not have working VS gen yet.
0.3.0 works for single-config solutions.

**Comment by bleze** [comment]
Unable to find windows binary for 0.3.0?

**Comment by egorpugin** [comment]
I've added it to https://software-network.org/client/

**Comment by bleze** [comment]
Thanks for 0.3.0, however that does not work either. I changed toolset from 142 to 141 (VS2017);

```LNK1104	cannot open file; 'C:\Users\xyz\.sw\storage\pkg\25\78\4a4d\obj\bld\b1588c\lib\org.sw.demo.mgk25.jbig.jbig-2.1.0.lib'	danbloomberg.leptonica-1.79.0```

```MSB3073	The command "sw1 @C:/Development/leptonica-master/.sw/sln/leptonica-master/msvc/vs/16/projects/i/1f06c0/4833e0/24ab6f.rsp
:VCEnd" exited with code 9009.	BUILD_DEPENDENCIES	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	128```

**Comment by egorpugin** [comment]
How did you generate sln?

**Comment by bleze** [comment]
`sw -config rwdi generate`

**Comment by egorpugin** [comment]
I see. Please, wait then. I'll try to improve vs builds in the latest sw client.

**Comment by bleze** [comment]
Thanks :)

**Comment by bleze** [comment]
Got something built using CMAKE, so no rush

**Comment by egorpugin** [comment]
@bleze @zdenop and others
I've added VS generator to current sw version.
Try it out! (re-download client or `sw --self-upgrade`)

`sw generate` - to make a solution.

Feel free to provide feedback.

**Comment by zdenop** [comment]
I tried:
```
mkdir msbuild && cd msbuild
sw generate ..
```
and it created vs solution.

PS: when I trid to run `sw generate .` (I forgot one dot) I got error message that was not very clear for me:
```
Downloading database from origin remote
Exception in file D:\dev\cppan2\client2\src\sw\driver\driver.cpp:106, function canLoadInput: TODO: unimplemented
```

**Comment by egorpugin** [comment]
Unimplemented things are just have to be reported.
Thanks for the report. :)

Error string contains file, line, function, error message - error's origin.
In your case the message is `TODO: unimplemented`.

**Comment by egorpugin** [comment]
Also I've fixed that error message. Will be available with the next update.
It did not find spec file (sw.cpp) and tried to load current directory with heuristics, but that was not implemented yet.

**Comment by egorpugin** [comment]
Closing as fixed.
Feel free to report any new issues.
