### ISSUE TITLE
Problem with large (huge) Pix* in pixCreateHeader?

### ISSUE THREAD

**Issue by pullmoll** [DanBloomberg/leptonica#413]
I have a rather large 600 dpi scan image of 11338 x 9212 pixels with depth 32.
I can rotate it using Linux on x86_64 but it fails on Windows when Leptonica and the application are built for 32 bit.

The raw data is a total of 389.42 MiB (417,782,624) and calling pixRotate() fails with this error:
```
pixCreateNoInit: pix_malloc fail for data.
pixCreateTemplateNoInit: pixd not made
pixCreateTemplate: pixd not made
pixHShear: pixd not made
pixRotate2Shear: pix1 not made
```

I think that pixCreateHeader() is working right because it does not print an error for these parameters, yet the call to pix_malloc() obviously returns NULL.

It should be possible to have several Pix* of that size in memory AFAICT, even with 32 bit limited memory, because more than 1GiB should be free at that time, but perhaps I'm hitting a hard limit due to temporary Pix* created while doing the shear rotation?

Before I go and try to debug that failing pix_malloc() call, is there perhaps some signed/unsigned issue when implicitly casting the `pix_malloc(4LL * wpl * height)` parameter in line `pix1.c:343` to `size_t`?

The same expression is in `pix1.c:467` where it is assigned to an `l_uint64 bignum` and should probably read `4ULL * wpl * height`.

**Comment by DanBloomberg** [comment]
I agree that pixCreateHeader() should have no trouble with those images.

I can change the 4LL --> 4ULL, but don't see how we get into trouble unless the 4LL number is negative!

How are you calling pixRotate()?  Are you requesting embedding?  Rotating by shear, sampling or area mapping?

**Comment by DanBloomberg** [comment]
Seems worth doing some experiments on Windows to see if the failure can be prevented:
   LL --> ULL
   different methods of rotation

**Comment by pullmoll** [comment]
I use `L_ROTATE_AREA_MAP`, `width==0` and `height==0`, i.e. no embedding.
Just before that call to pixRotate() with the huge Pix* I used the same parameters with a 1bpp mask image to later on fill the corner edges  with `pixSetMasked()` and an average border color. That call succeeds thus It's definitely memory related.

I will do some experiments and print some debug info on my side for the WIN32 case. Currently looking for the useful API calls, perhaps `GetProcessWorkingSetSize()` or some such function. I fear we just hit a hard to come by limit here for 32 bit.

**Comment by pullmoll** [comment]
Here are some numbers from just before calling the pixRotate() from my code:
```
[19:56:49.695] deskew: GlobalMemoryStatus() returned:
[19:56:49.695]  dwMemoryLoad     : 78 %
[19:56:49.695]  ullTotalPhys     : 4294500352 (4193848 KiB)
[19:56:49.695]  ullAvailPhys     : 922697728 (901072 KiB)
[19:56:49.695]  ullTotalPageFile : 8587055104 (8385796 KiB)
[19:56:49.695]  ullAvailPageFile : 4377718784 (4275116 KiB)
[19:56:49.695]  ullTotalVirtual  : 2147352576 (2097024 KiB)
[19:56:49.695]  ullAvailVirtual  : 939773952 (917748 KiB)
[19:56:49.695] deskew: GetProcessWorkingSetSize() min=204800 (200 KiB), max=1413120 (1380 KiB)
```
So, if I interpret these numbers right, there should be ~900MB of virtual memory available for the process (ullAvailVirtual), and that would be roughly 2 more copies of the Pix* data but not 3.

After all it looks like this is our own problem and not something that Leptonica can or should deal with and thus I close this issue.

**Comment by DanBloomberg** [comment]
good luck with it ..
