### ISSUE TITLE
Support for webp anim needed in cmake and automake

### ISSUE THREAD

**Issue by DanBloomberg** [DanBloomberg/leptonica#414]
I've added code to generate animated webp into the library.  There are two nw files in the library:
    webpanimio.c   (the real one, which requires HAVE_LIBWEBP_ANIM == 1)
    webpanimiostub.c  (the stub, which should be linked if HAVE_LIBWEBP_ANIM == 0)

The code can be compiled with the static makefile, and the results have been tested using the new regression test prog/webpanimio_reg.  In README.html, I discussed what you need to do on the ./configure line when building webp to include the mux library required for animated webp.  After the webp libraries are installed, one makes this change by hand to environ.h:
 * set HAVE_LIBWEBP and HAVE_LIBWEBP_ANIM both to 1
and changes the set of libraries to be linked in the static makefile prog/makefile, to include libwebp and libwebpmux.

So it all works fine building that way.

@egorpugin 
However, I did not add the regression test to the lists for cmake:
     prog/CmakeLists.txt
    sw.cpp
because this requires modifying CMakeLists.txt to search for the library libwebpmux.
Without that modification, the stub file is linked into the library.

@chewi 
Also, under autools, I did not add webpanimio_reg.c to  prog/Makefile.am, because I don't know how to set up configure.ac to search for libwebpmux.  As a result, the stub file gets linked into the library.

**Comment by egorpugin** [comment]
I've added this to sw https://github.com/DanBloomberg/leptonica/commit/c3e2afd6937b1cc2105a87e9c6c74af2e9041513

I can't check cmake build correctness right now, so someone should do this. Also it would be better if someone else took maintaining cmake scripts, because I'm focused on sw.

**Comment by egorpugin** [comment]
Added to cmake https://github.com/DanBloomberg/leptonica/commit/28cfba8c48fa0e4246e9232701824f64acfd144a

**Comment by zdenop** [comment]
see: PR #415

**Comment by zdenop** [comment]
I just check it on windows with following results:
```
f:\Project-Personal\clang_shared\leptonica\prog>f:\win64_llvm\bin\webpanimio_reg.exe

////////////////////////////////////////////////
////////////////   webpanimio_reg   ///////////////
////////////////////////////////////////////////
leptonica-1.79.0 (Apr  6 2019, 14:37:54) [MSC v.1915 LIB Release x64] : libgif 5.1.2 : libjpeg 6b (libjpeg-turbo 2.0.2) : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.0
Info in pixaWriteMemWebPAnim: data size = 46858
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in webpanimio_reg, index 0: comparing /tmp/lept/webp/margeanim.webp with /tmp/lept/golden/webpanimio_golden.00.webp
Time:   0.063 sec
```

**Comment by egorpugin** [comment]
With sw build I have (see https://github.com/DanBloomberg/leptonica/commit/28cfba8c48fa0e4246e9232701824f64acfd144a#commitcomment-33057823)
```
d:\dev\leptonica\prog>..\.sw\windows_x86_64_msvc_19.20_shared_Release\danbloomberg.leptonica.progs.webpanimio_reg-1.79.0.exe generate

////////////////////////////////////////////////
////////////////   danbloomberg.leptonica.progs.webpanimio_reg-1._reg   ///////////////
////////////////////////////////////////////////
leptonica-1.79.0 (Apr  6 2019, 17:27:33) [MSC v.1920 LIB Release x64] : libgif 5.1.7 : libjpeg 9c : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.0
Info in pixaWriteMemWebPAnim: data size = 47298
Time:   0.078 sec

d:\dev\leptonica\prog>..\.sw\windows_x86_64_msvc_19.20_shared_Release\danbloomberg.leptonica.progs.webpanimio_reg-1.79.0.exe compare

////////////////////////////////////////////////
////////////////   danbloomberg.leptonica.progs.webpanimio_reg-1._reg   ///////////////
////////////////////////////////////////////////
leptonica-1.79.0 (Apr  6 2019, 17:27:33) [MSC v.1920 LIB Release x64] : libgif 5.1.7 : libjpeg 9c : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 1.0.2 : libopenjp2 2.3.0
Info in pixaWriteMemWebPAnim: data size = 47298
Time:   0.078 sec
```

**Comment by DanBloomberg** [comment]
The sizes look about right -- I got something closer to zdenop's result, I believe.

You can check the output file: chrome browser can display animated webp (others likely also do, but I haven't tested).   It should be a cat that reverses itself in a loop 5 times, with 1/4 second for each image (total: 10 images in 2.5 sec)

If you have webpinfo, it should say there are 2 images, the loop count is 5, and the duration is 250.

@zdenop: looking at the error message -- did you run the program twice, once with 'generate' and the second time with either nothing or with 'compare'?

Egor's output header is wrong -- it should just have the name of the test, as with zdenop's.

**Comment by zdenop** [comment]
I make a cmake build on linux and  run:
```
/usr/src/leptonica/prog> ../build64/bin/webpanimio_reg

////////////////////////////////////////////////
////////////////   webpanimio_reg   ///////////////
////////////////////////////////////////////////
leptonica-1.79.0 : libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.5.0 : libopenjp2 2.3.0
Info in pixaWriteMemWebPAnim: data size = 46354
Error in fopenReadStream: file not found
Error in nbytesInFile: stream not opened
Failure in webpanimio_reg, index 0: comparing /tmp/lept/webp/margeanim.webp with /tmp/lept/golden/webpanimio_golden.00.webp
Time:   0.225 sec
```
I run it several times with the same result => /tmp/lept/golden/webpanimio_golden.00.webp does not exists...

**Comment by egorpugin** [comment]
> You can check the output file: chrome browser can display animated webp 

Works for me (sw case).

> Egor's output header is wrong -- it should just have the name of the test, as with zdenop's.

It's just a name of sw produced executable.

**Comment by zdenop** [comment]
autotools part should be solve with PR#417

**Comment by DanBloomberg** [comment]
@zdenop
Did you run it first with
   webpanimio_reg generate
which makes the golden file, and then with
   webpanimio_reg compare
?

**Comment by zdenop** [comment]
I am sorry I did not user argument.  With arguments result is correct (Linux Opensuse cmake build):
```
>  ./webpanimio_reg generate

////////////////////////////////////////////////
////////////////   webpanimio_reg   ///////////////
////////////////////////////////////////////////
leptonica-1.79.0 : libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.5.0 : libopenjp2 2.3.0
Info in pixaWriteMemWebPAnim: data size = 46354
Time:   0.225 sec

> ./webpanimio_reg compare

////////////////////////////////////////////////
////////////////   webpanimio_reg   ///////////////
////////////////////////////////////////////////
leptonica-1.79.0 : libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.3) : libpng 1.6.34 : libtiff 4.0.9 : zlib 1.2.11 : libwebp 0.5.0 : libopenjp2 2.3.0
Info in pixaWriteMemWebPAnim: data size = 46354
Time:   0.218 sec

```

**Comment by zdenop** [comment]
should be solved with #419

**Comment by zdenop** [comment]
IMO this could be closed.

**Comment by DanBloomberg** [comment]
yes
