### ISSUE TITLE
VS2019 build warnings

### ISSUE THREAD

**Issue by egorpugin** [DanBloomberg/leptonica#420]
%zu was appeared in C99 I guess.
Does leptonica use c89 or c99?

```
2>D:\dev\leptonica\src\webpanimio.c(267): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'size_t'
2>D:\dev\leptonica\src\webpanimio.c(267): note: consider using '%zu' in the format string

2>D:\dev\leptonica\src\utils1.c(532): warning C4477: 'fprintf' : format string '%lu' requires an argument of type 'unsigned long', but variadic argument 2 has type 'size_t'
2>D:\dev\leptonica\src\utils1.c(532): note: consider using '%zu' in the format string```

**Comment by DanBloomberg** [comment]
This has been a source of frustration.  About 10 years ago I put this in pixalloc.c:

*      (3) size_t is %lu on 64 bit platforms and %u on 32 bit platforms.
 *          The C99 platform-independent format specifier for size_t is %zu,
 *          but windows hasn't conformed, so we are forced to go back to
 *          C89, use %lu, and cast to get platform-independence.  Ugh.

and have used %lu throughout, trying to remember to cast to (unsigned long) -- but sometimes forgetting.

Can I now change all these %lu to %zu?

**Comment by stweil** [comment]
According to the [Microsoft documentation](https://docs.microsoft.com/de-de/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2015), `%zu` is supported at least in VC-2015 and newer versions. So yes, it is possible to change that (that implies removing the type casts, too).

**Comment by DanBloomberg** [comment]
Thanks.  I'll do it.

**Comment by DanBloomberg** [comment]
done
