### ISSUE TITLE
Question: Does rotate support alpha channel?

### ISSUE THREAD

**Issue by t246246** [DanBloomberg/leptonica#423]
I'm new to leptonica. I compiled 1.78.0 in MSYS2 and tired to make a routine to rotate 90 for png and do the following:

```
#include "allheaders.h"

int main(int argc, char *argv[]) {
  char *in, *out;
  PIX *pixs, *pixd;

  in = argv[1];
  out = argv[2];

  if ((pixs = pixRead(in)) == NULL)
    exit(1);
	 
  pixd = pixRotate90(pixs, 1);

  if((pixWrite(out, pixd, IFF_PNG)) != 0)	 
    exit(2);

  pixDestroy(&pixs);
  pixDestroy(&pixd);

  exit(0);
}
```
It works fine for 24 bit PNG but if the input image has alpha, the output lost it.
As I read https://github.com/DanBloomberg/leptonica/issues/82 , I think 32bit is supported.

Are there any way to accomplish this by adding something the code above?

Best Wishes,

**Comment by DanBloomberg** [comment]
Thank you for reporting this bug.

You could patch your application code by adding
pixSetSpp(pixs, 4) 
after rotating, but it's better to fix the library function.
If you want to see how that works:

in pixRotate90() in rotateorth.c, after pixCopyInputFormat(...),
add this:
pixCopySpp(pixd, pixs);

That should do it, and I'll fix it at head tomorrow.

FYI, the leptonica program fileinfo is often useful for checking on file header data.
The gimp program
     identify -verbose
is also a good resource.

  -- Dan
