### ISSUE TITLE
Correction in `boxaSort2d` documentation

### ISSUE THREAD

**Issue by vidiecan** [DanBloomberg/leptonica#427]
https://github.com/DanBloomberg/leptonica/blob/master/src/boxfunc2.c#L893

` If delta1 < 0,` should be ` If delta1 > 0,`

See 
https://github.com/DanBloomberg/leptonica/blob/master/src/boxfunc2.c#L1922

**Comment by DanBloomberg** [comment]
thank you for reporting this error.

The business of negative overlaps (which are really positive separations) tends to be confusing. I fixed the comments.
