### ISSUE TITLE
fileinfo failed to read some tiff file.

### ISSUE THREAD

**Issue by t246246** [DanBloomberg/leptonica#428]
I create simple image with ImageMagick and convert it to tile format with tiffcp:
```
$ magick convert \( -size 320x240 xc:red -size 320x240 xc:blue -append \) \( -size 320x240 xc:green -size 320x240 xc:yellow -append \) +append -type Palette x1.tif
$ tiffcp -l 128 x1.tif x2.tif
```

[x2.zip](https://github.com/DanBloomberg/leptonica/files/3134582/x2.zip)
Then try to check the format:

```
$ tiffinfo x2.tif 
TIFF Directory at offset 0x18008 (98312)
  Image Width: 640 Image Length: 480
  Tile Width: 256 Tile Length: 128
  Bits/Sample: 2
  Compression Scheme: None
  Photometric Interpretation: palette color (RGB from colormap)
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Planar Configuration: single image plane
  Page Number: 0-1
  Color Map: (present)
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000
```
```
$ fileinfo x2.tif 
===============================================
Reading the header:
  input image format type: tif
  w = 640, h = 480, bps = 2, spp = 1, iscmap = 1
===============================================
Reading the full image:
Error in pixReadFromTiffStream: line read fail
Error in pixReadStream: tiff: no pix returned
Error in pixRead: pix not read
Error in writeImageFileInfo: failure to read full image of x2.tif
```

**Comment by DanBloomberg** [comment]
Do you have a simple way the reader can check if there are tiles and then modify the line reading, or convert the data programmatically to strips so that the current reading works?

**Comment by t246246** [comment]
Checking seems to be easy. libtiff has TIFFIsTiled().  But reading is not so simple.
Reading the source of tiffcp.c is best.  https://gitlab.com/libtiff/libtiff/blob/master/tools/tiffcp.c#L1353 or https://gitlab.com/libtiff/libtiff/blob/master/tools/tiffcp.c#L1407 depending on planer configuration.

**Comment by DanBloomberg** [comment]
Thank you.  This was very helpful  At this point we are checking, but have no plans to attempt to read these images.  If someone has a tiled image, they can generate a strip image with:
    tiffcp -s <tiled.tif> <normal.tif>
