### ISSUE TITLE
Wrong library name in the lept.pc

### ISSUE THREAD

**Issue by aleksey-nikolaev** [DanBloomberg/leptonica#433]
This commit https://github.com/DanBloomberg/leptonica/commit/0fefa7e55b27c1cc76e79f755a12a00c5aa3ef7d makes it impossible to use pkg-config.
So, it is ok to use a name `leptonca` here https://github.com/DanBloomberg/leptonica/commit/0fefa7e55b27c1cc76e79f755a12a00c5aa3ef7d#diff-afaa716feb616ef56fe0428c098a59abR45 because it is not a library name - it is a target name, but here https://github.com/DanBloomberg/leptonica/commit/0fefa7e55b27c1cc76e79f755a12a00c5aa3ef7d#diff-96c54e0786cbda272167018ac7bfd833R9 should be a file name.

**Comment by zdenop** [comment]
Please provide details (what is your OS, build tool etc.) How looks lept.pc after configuration/build on your system?

**Comment by aleksey-nikolaev** [comment]
Qt 5.12 + mingw73_64
for leptonica 1.78.0  lept.pc was:
```
prefix=C:/Projects/proof-mingw-depends/install
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: leptonica
Description: An open source C library for efficient image processing and image analysis operations
Version: 1.78.0
Libs: -L${libdir} -lleptonica-1.78.0
Libs.private:
Cflags: -I${includedir} -I${includedir}/leptonica
```

for current version 

```
.....
Version: 1.79.0
Libs: -L${libdir} -lleptonica
.....
```

Lib name is `libleptonica-1.79.0.dll.a` (and `libleptonica-1.78.0.dll.a` for previous version)

**Comment by zdenop** [comment]
How did you configured leptonica?
I just tried it and I got:

```
prefix=F:/win64_llvm
exec_prefix=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

Name: leptonica
Description: An open source C library for efficient image processing and image analysis operations
Version: 1.79.0
Libs: -L${libdir} -lleptonica-1.79.0
Libs.private:
Cflags: -I${includedir} -I${includedir}/leptonica
```

**Comment by aleksey-nikolaev** [comment]
Ok, I am trying to find how to get `leptonica-1.79.0` name from  [`leptonica_NAME`](https://github.com/DanBloomberg/leptonica/blob/master/lept.pc.cmake#L9) 
I used a last commit: ![image](https://user-images.githubusercontent.com/12497264/58004200-5c8a9500-7aeb-11e9-8477-9004a9f1e76e.png)

I added some message output:
![image](https://user-images.githubusercontent.com/12497264/58004279-9196e780-7aeb-11e9-8798-9cf0134dec4c.png)
Maybe the problem is that you use autotools instead of cmake? Sorry, I forgot that you have to maintain a secondary build system

**Comment by zdenop** [comment]
No I use cmake on windows.

**Comment by zdenop** [comment]
...the problem is that my repository use [`Libs: -L${libdir} -l@leptonica_OUTPUT_NAME@`](https://github.com/zdenop/leptonica/blob/3faf9ed989fddc54aea2bd6184e64595717b5242/lept.pc.cmake#L9)
while official repository use:
https://github.com/DanBloomberg/leptonica/blob/d910be87d6f904374e2050e389aabefb56eb59e1/lept.pc.cmake#L9

I am not use how this happen and also github does not show nothing for PR  (no differences???)  ;-):
![image](https://user-images.githubusercontent.com/574156/58042966-5244b700-7b3c-11e9-95ca-cafd63c3ec29.png)

I try to fork leptonica once again and re-test everything...
