### ISSUE TITLE
overflow in pixSauvolaGetThreshold

### ISSUE THREAD

**Issue by vidiecan** [DanBloomberg/leptonica#435]
There is a "number overflow" in 
https://github.com/DanBloomberg/leptonica/blob/master/src/binarize.c#L766
with e.g.,
```
ms = 65024
mv = 255
ms - mv * mv = -1
```
and the `-1` is used as a negative index in 
```sd = tab[var];```

The problem is very likely here
https://github.com/DanBloomberg/leptonica/blob/master/src/convolve.c#L1245
```
ival = (l_uint32)(norm * val)
```
which should be a rounding operation instead of a cast.
In the particular case, the ```norm * val = 65024.996337283206```

**Comment by DanBloomberg** [comment]
Thank you for finding this and pointing out the source of the error.
Adding 0.5 before casting in convolve.c should indeed solve the problem.

**Comment by vidiecan** [comment]
PR: https://github.com/DanBloomberg/leptonica/pull/437
