### ISSUE TITLE
Failed to create symlink (cross-build, install step)

### ISSUE THREAD

**Issue by Bleach665** [DanBloomberg/leptonica#436]
Winsows 10 x64, CMake gui 3.13.4, MinGW 530_32 (from Qt lib), Android NDK r16b toolchain, rev b0519a1c6fef192cac23829daa27c621a3d4489d.

Leptonica was configured with CMake GUI and Android toolchain and built with MinGW.
Received error:
```
[ 99%] Building C object src/CMakeFiles/leptonica.dir/zlibmemstub.c.o
[100%] Linking C static library libleptonica.a
[100%] Built target leptonica
Scanning dependencies of target lept
[100%] Creating lept symlink
CMake Error: failed to create symbolic link 'liblept.so': operation not permitted
src\CMakeFiles\lept.dir\build.make:56: recipe for target 'src/CMakeFiles/lept' failed
mingw32-make.exe[2]: *** [src/CMakeFiles/lept] Error 1
CMakeFiles\Makefile2:123: recipe for target 'src/CMakeFiles/lept.dir/all' failed
mingw32-make.exe[1]: *** [src/CMakeFiles/lept.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```
The last revision which I used and which was provided successful configuring and build in this way is ad35f07eebd165580938fc1ba4c7037a43a7d2ba.

**Comment by zdenop** [comment]
Thanks for report. IMO this is cmake issue: AFAIK [from this commit](https://gitlab.kitware.com/crondog/cmake/commit/afb7f6e4ff8a0c1a68c8d8cf2d6cf72401cfb8ff ) (11 moth ago) cmake should support symlinks also on windows...  Anyway I suggest to turn it off by default.

**Comment by zdenop** [comment]
IMO this could closed.

**Comment by DanBloomberg** [comment]
done
