### ISSUE TITLE
iomisc_reg test 38 error in centos aarch64 with libtiff 4.0.3 

### ISSUE THREAD

**Issue by Nymeriawolf** [DanBloomberg/leptonica#440]
we need  151885.000000, but get file size is 2 151953.000000, and  delta 0.0
diff=68
and try libtiff 4.0.10, failure test more and more ,like 15, and large value

**Comment by Nymeriawolf** [comment]
I guess the value of tiffsize about libtiff version.

**Comment by DanBloomberg** [comment]
Yes, that is likely.  There were some fairly significant changes with libtiff 4.0.

What are the exact sizes of those 8 files with 4.0.10?

**Comment by DanBloomberg** [comment]
I've changed #38 to have a delta of 100, which is > 68.
Closing the bug.  If there are other deltas that should be increased, let me know.
