### ISSUE TITLE
Build problems with version 79 Windows

### ISSUE THREAD

**Issue by tathams** [DanBloomberg/leptonica#441]
So. I follow instruction on my windows 7 laptop and git clone the source,
I run cppan as stuff is pulled to my machine. I run CMAKE and it builds for VS2010 which is on my system, All goes well and then I open the .sln
when I try to build I get an error
*Cannot open include file: 'stdbool.h': No such file or directory [C:\Users\user\.cppan\storage\obj\17\af\df2a\build\577b439c\cppan\17afdf2a\17afdf2a.vcxproj]	C:\Users\user\.cppan\storage\obj\17\af\df2a\build\577b439c\cppan\17afdf2a\cppan_private\config.h	2	1	cppan-d-b-d*
If I copy a stdbool.h file from elsewhere in the .cppan tree I then get inttypes.h missing.

So what have I done wrong

**Comment by zdenop** [comment]
IMO VS2010 is tool old. Try to use at least VS2015, but VS2017 is strongly suggested. 
Next this is not leptonica error, but cppan. You can try to build leptonica without cppan. Just try something like this:

```
mkdir build && cd build
cmake .. -G "Visual Studio 14 2015"
cmake --build .
```

**Comment by tathams** [comment]
zdenop. Thanks for your suggestions. I will try them

If anyone builds leptonica libraries for windows would you share them with me, As there always seem to be problems with Windows building and Visual Stdio. I just want to learn to use the library not become a CMAKE expert.

**Comment by zdenop** [comment]
This has nothing to do with cmake or leptonica.
Your compiler is too old => does not support C99. Microsoft start to support it [from Visual Studio 2013](https://devblogs.microsoft.com/cppblog/c99-library-support-in-visual-studio-2013/).

**Comment by egorpugin** [comment]
Try to use sw to build lept or generate solutions.
