### ISSUE TITLE
Add a note to `pixOrientDetect*` documentation

### ISSUE THREAD

**Issue by vidiecan** [DanBloomberg/leptonica#446]
The algorithm works well but it is easily fooled with mostly uppercase characters with narrow word gaps that have commas, brackets and single character words (mostly numbers). This is not that uncommon in documents with tables.

Example:
- `pixUpDownDetectGeneralDwa()` returns conf = -18
- without small cc-s (e.g., commas) returns = -9
- without small ccs-s and single characters returns = 9

Example picture (part of it, probably required zooming):

![t](https://user-images.githubusercontent.com/332350/61452277-b8429480-a95b-11e9-96fd-47fd2b2e6014.png)

**Comment by DanBloomberg** [comment]
Thank you.  This is indeed a problem with tables, where the number of ascenders and descenders may be biased by a low signal from repeated words.   A possible work-around would be to run the table detector and give a low confidence if there is a table.  Will add comments to the function, as you suggest.

**Comment by DanBloomberg** [comment]
Thanks.  Added a note.
