### ISSUE TITLE
Feature request: autoinvert 

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#447]
tesseract 4.x+ requires black letters on white background for correct OCR. 
IMO kind of "autoinvert" image function would help. Something like:

1. binarize image (or require binarized image)
2. calculate black/white ratio
3. if black/white ratio is higher than threshold parameter => invert image.

**Comment by DanBloomberg** [comment]
This is easy to implement following your algorithm.  I should be able to do it within a week.

**Comment by tdhintz** [comment]
I agree this is useful.  I assume you mean find regions of high ratios and invert just those regions.  For example, the columns of a report might have a header row in inverted text so you have to find the rectangle.  The whole document is rarely white on black.

**Comment by zdenop** [comment]
Any plans for this?

**Comment by OblackatO** [comment]
Are there any updates on this issue?

**Comment by DanBloomberg** [comment]
sorry, it keeps getting pushed down the stack.
I'll try to have an implementation by Jan 10, 2020  (there, an exact date).

**Comment by OblackatO** [comment]
> sorry, it keeps getting pushed down the stack.
> I'll try to have an implementation by Jan 10, 2020 (there, an exact date).

Thank you ! I will try to implement it my self, but so far I have already spent many time reading the API and documentation, to little results. In the mid time I find a solution using "convert":

_convert sr_img.png -threshold 75% thres_colored.png && convert -negate thres_colored.png dst.png_

This binarizes the image with a threshold of 75%, and then replaces every pixel with its complementary color.

**Comment by OblackatO** [comment]
Thank you !

**Comment by amitdo** [comment]
Dan already added the requested feature to Leptonica. Someone should close this issue.

**Comment by amitdo** [comment]
Dan,

Maybe you can mention `pixAutoPhotoinvert()` in the version notes (1.79) ?

**Comment by DanBloomberg** [comment]
Done.

**Comment by amitdo** [comment]
ping

**Comment by DanBloomberg** [comment]
It's in; last entry in 1.79:

* Added pixAutoPhotoinvert() for tesseract, to automatically photo-
          invert text regions where the background is black and text is white.

**Comment by amitdo** [comment]
Thanks! See https://github.com/DanBloomberg/leptonica/issues/527#issuecomment-669524466
