### ISSUE TITLE
pixSetPadBits clears wring bits in Windows

### ISSUE THREAD

**Issue by OpaitSoftware** [DanBloomberg/leptonica#448]
I have a Pix of Width 1913 and color depth of 8 with no color map. Initially, the scan line end looks like this:
data[1911] = 255
data[1912] = 255
data[1913] = 255
data[1914] = 255
data[1915] = 255
data[1916] = 255

If I save this Pix as a PNG file, The buffer is altered as follows:
data[1911] = 255
data[1912] = 0
data[1913] = 0
data[1914] = 0
data[1915] = 255
data[1916] = 255

I was expecting:
data[1911] = 255
data[1912] = 255
data[1913] = 0
data[1914] = 0
data[1915] = 0
data[1916] = 255

I am running under Windows (using PInvoke) and am suspecting that function pixSetPadBits (pix2.c, line 1307) is clearing the wrong end of the final DWORD on a scan line, or it fails to reshuffle the same word after applying a bit mask.

**Comment by DanBloomberg** [comment]
THanks for the report.  I will look into this in the next week.

Dan

**Comment by OpaitSoftware** [comment]
Dan, 
Thanks for your comment. I believe this was due to my misunderstanding of the internal image data storage format within the library. If I swap the little-endian bytes, everything should be fine. Sorry about that.

Farhad

**Comment by DanBloomberg** [comment]
No problem.  I appreciate that you reported the 'issue'.
