### ISSUE TITLE
Reading Mono8 RAW format images from camera stream

### ISSUE THREAD

**Issue by syberarall** [DanBloomberg/leptonica#451]
Hello,

I want to do image processing RAW format images provided from a camera stream (BASLER). The RAW format is typically Mono8, or BAYER12. Is this possible with LEPTONICA, since I have seen only file format processing. It would be great to have some sample, how to do it.

Best regards, Juergen

**Comment by DanBloomberg** [comment]
Sorry, but the RAW camera formats are not supported on leptonica.
Check out free converters, eg, irfanview
     https://www.telegraph.co.uk/technology/advice/10234288/How-can-I-convert-RAW-files-to-JPEG.html

Good luck,
  -- Dan
