### ISSUE TITLE
Determine if the document image is skewed or distorted

### ISSUE THREAD

**Issue by LinnaWang76** [DanBloomberg/leptonica#452]
I have no idea about this condition. Thx

**Comment by zdenop** [comment]
Please provide example image and what you try to reach. Make sure you read doc and example programs (e.g. https://github.com/DanBloomberg/leptonica/blob/master/prog/deskew_it.c, https://github.com/DanBloomberg/leptonica/blob/master/prog/skewtest.c)

**Comment by LinnaWang76** [comment]
First of all, Thx you for answering.
I want to create a classifier if the document image needs correction before text recognition.
mainly for skew and warp correction. For all the camera images with text.
![310001172](https://user-images.githubusercontent.com/31330445/65314480-03319000-dbc9-11e9-8cca-a0f9cda13575.jpg)
Thx

**Comment by zdenop** [comment]
I suggest to close, because there is no real issue, just you forget to have a look at available examples (progs) and docs on http://www.leptonica.org.

**Comment by LinnaWang76** [comment]
OK  you are right, I shouldn't take shortcuts
