### ISSUE TITLE
Photometric tag setting problem in image saving

### ISSUE THREAD

**Issue by suman-pan** [DanBloomberg/leptonica#465]
Hello sir
I have tried to open a BW 1bpp image having colormap data , and then saved it,
Now in savetiff it is setting photometric tag MinIsWhite, if image depth is 1.
After observation if we remove colormap before saving the image then this photometric tag setting is correct, but if we save the image without removing colormap then in image saving if the PIX contains colormap data ,the photometric tag setting should be MinIsBlack, as in colormap removal it inverts the image for 1bpp.
[Dummy_BW.zip](https://github.com/DanBloomberg/leptonica/files/3889508/Dummy_BW.zip)

I have attached a image for testing, please check through it.

**Comment by suman-pan** [comment]
Check this

**Comment by DanBloomberg** [comment]
Can you tell me exactly what you're doing?

Specifically:
 * how are you removing the colormap?
 * what is savetiff?
 * how are you saving the image?

Do you have some leptonica code that you're running?

Here's some that I just ran, and it all looks fine.  Your image is bw.tif.

    pix1 = pixRead("bw.tif");
    pixWrite("/tmp/bw2.tif", pix1, IFF_PNG);
    pix2 = pixRead("/tmp/bw2.tif");
    pixWrite("/tmp/bw2.png", pix1, IFF_PNG);
    pix3 = pixRead("/tmp/bw2.png");
    pixDisplay(pix2, 100, 100);
    pixDisplay(pix3, 100, 100);

pixReadStreamPng() removes the colormap on reading, but reading the tiff preserves the colormap.

**Comment by suman-pan** [comment]
I am doing some operation using leptonica, 
I have downloaded the leptonica code and build it's library and working with it.
You can repo the issue by doing this only..
Do pixread() that Tiff image
Then pixwrite() that image in Tiff_LZW or G4 compression..
Then check the outpot image photometric tag and also it's view (you will get an inverted image)

By the way savetiff actually pixwrite () or pixwritetiffcustom().
I am removing colormap using leptonica function pixremovecmap().

**Comment by suman-pan** [comment]
Hello sir
Have you understood the issue , either I will explain more elaborately about it..
Please respond.
Thanks

**Comment by DanBloomberg** [comment]
Fixed.  Thank you  for the bug report.

  -- Dan

**Comment by suman-pan** [comment]
Can you please provide the release link or the bug fixes, I need the changes for some testing , as I am using your incremental release

**Comment by DanBloomberg** [comment]
The commits were on Nov 29 and Nov 30.

The master has these, so you can use it.
