### ISSUE TITLE
The master branch does not compile on Windows

### ISSUE THREAD

**Issue by Soruk** [DanBloomberg/leptonica#466]
Hi,

When I try to compile the master branch on Windows, using the command (as described [here]());
`cmake .. -G "Visual Studio 16 2019" -A Win32 -DCMAKE_TOOLCHAIN_FILE=%VCPKG_HOME%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_INSTALL_PREFIX=..\..\build\x86
`
I have the following output: 

> -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
> -- The C compiler identification is MSVC 19.23.28107.0
> -- The CXX compiler identification is MSVC 19.23.28107.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x86/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x86/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x86/cl.exe
> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x86/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at F:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
>   By not providing "FindSW.cmake" in CMAKE_MODULE_PATH this project has asked
>   CMake to find a package configuration file provided by "SW", but CMake did
>   not find one.
> 
>   Could not find a package configuration file provided by "SW" with any of
>   the following names:
> 
>     SWConfig.cmake
>     sw-config.cmake
> 
>   Add the installation prefix of "SW" to CMAKE_PREFIX_PATH or set "SW_DIR" to
>   a directory containing one of the above files.  If "SW" provides a separate
>   development package or SDK, be sure it has been installed.
> Call Stack (most recent call first):
>   CMakeLists.txt:109 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/Temp/leptonica/vs16-x86/CMakeFiles/CMakeOutput.log".
The log file:
[CMakeOutput.log](https://github.com/DanBloomberg/leptonica/files/3895660/CMakeOutput.log)

When I compile the 1.78.0 tag, there is no issue.
Do you know what is missing here on master branch ?

Someone else have the same [issue](https://stackoverflow.com/questions/59060779/building-opencv-with-tesseract-with-git-bash)

**Comment by zdenop** [comment]
Using git master expect you are familiar with project and you are able to solve compiling problems.

> Could not find a package configuration file provided by "SW" with any of
> the following names:
> 
> SWConfig.cmake
> sw-config.cmake

Did you installed `[sw](https://software-network.org/)`?

**Comment by Soruk** [comment]
Yes, I installed "sw" but with no success.
For time being I disabled the SW_BUILD (i.e. by adding -DSW_BUILD=OFF to the cmake command line).
Credit: [microsoft/vcpkg#8991](https://github.com/microsoft/vcpkg/issues/8991)

**Comment by zdenop** [comment]
According instruction you should run `sw build` at main leptonica directory.

@egorpugin: This problem with cmake&sw start to popup quite often. Can you create instruction how to solve it? SWConfig.cmake and sw-config.cmake are not part of client distribution.

**Comment by Soruk** [comment]
I run the `sw build` at main directory (local folder of *leptionica*), but when trying to cmake for given platform (according to [wiki](https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Libleptonica-(using-vcpkg)) the error persists.
I will wait for instructions from @egorpugin

**Comment by zdenop** [comment]
it seems that cmake and sw build does not work together...

**Comment by egorpugin** [comment]
> it seems that cmake and sw build does not work together...

They does.
Currently cmake uses sw on windows by default.
@Soruk pass -DSW_BUILD=0 to cmake to disable it if you want to use vcpkg.

Otherwise, with sw you should do:
1. Download sw, add to PATH.
1. Call `sw setup` - this performs cmake integration.
1. Run cmake as usual for leptonica (`mkdir build && cd build && cmake ..`).

**Comment by Soruk** [comment]
Yes, I'm using the `-DSW_BUILD=0` / `-DSW_BUILD=OFF` option for time being..
Thanks.

**Comment by DanBloomberg** [comment]
@egorpugin 
Should I modify the README with instructions about compiling on windows with sw and cmake?

**Comment by egorpugin** [comment]
Yes, please.
Where are they?

**Comment by DanBloomberg** [comment]
in README.html

Section 3 (a)
Lines 323-332 are for visual studio.

Please modify with whatever level of detail you wish.

**Comment by egorpugin** [comment]
Oh, ok.
I've updated those docs.
