### ISSUE TITLE
pixDisplayWrite() deprecated warning

### ISSUE THREAD

**Issue by mujinbao** [DanBloomberg/leptonica#470]
@DanBloomberg 
The warning details are as follows：

######################################################
Notice:
pixDisplayWrite() has been deprecated in leptonica
since version 1.74. It will become a non-functioning
stub in 1.80.
######################################################

My current version is 1.78.
I need recognize OCR text from an image, so I use a python wrapper of name is  **[``tesserocr``](https://github.com/sirfz/tesserocr)**  to call ``tesseract-ocr``.

I hope you can give me some tips on how to stop this output.
My log file is fulling of these warnings now, it about to boom...

**Comment by DanBloomberg** [comment]
What version of tesseract are you using?  I thought pixDisplayWrite() has been removed from recent versions.

You can simply comment out the warning in the function and recompile.

Alternatively, you can compile with
   -DMINIMUM_SEVERITY=5
to turn off all warnings.
