### ISSUE TITLE
Guidance on bounding box code

### ISSUE THREAD

**Issue by tathams** [DanBloomberg/leptonica#473]
I am slowly reading doxygen documentation on 1.68 but have the 1.79 runtime and source.
As a learning project I want to read electronic schematic images which are normally black and some background colour. To gather all the smallest boxes of text and symbols of diodes, resistors, capacitors etc. Similar to OCR but I will have to discover and build a symbol table of similar font/pixel box entities.

Are there any sample testing progs or specific source c modules I should read for somewhere to start.
I am using a Prolog backend to do the heavy listing but Leptonica to read images.

If there is another forum to post this question. Please advise.

**Comment by DanBloomberg** [comment]
There are things in leptonica that will help, but your project is very open-ended and certainly non-trivial.

Modules in leptonica that would be helpful are:
* finding connected components
* looking for color and if finding it, doing color segmentation or at least identifying the typical colors
* using the jbig classifier on 1 bpp connected components to put them in similarity classes
* morphology to extract lines and to separate components that are connected by thin lines.

For further guidance, generate doxygen on 1.79, and also see 
      http://www.leptonica.org/highlevel.html

**Comment by tathams** [comment]
Thank you. I shall follow your suggestions
