### ISSUE TITLE
Cppan

### ISSUE THREAD

**Issue by Moldoteck** [DanBloomberg/leptonica#474]
Do I need to download/use cppan when building with sw?
i'm asking this because when i do 
******************
sw build(in main leptonica directory)
mkdir build && cd build
cmake ..
******************
first line of LeptonicaTargets.cmake contains include(C:/Program Files (x86)/leptonica/build/cppan.cmake)
So, when i do in my project
find_package(Leptonica REQUIRED)
I get:
```
CMake Error at C:/Program Files (x86)/leptonica/build/LeptonicaTargets.cmake:1 (include):
  include called with wrong number of arguments.  include() only takes one
  file.
Call Stack (most recent call first):
  C:/Program Files (x86)/leptonica/build/LeptonicaConfig.cmake:23 (include)
  C:/Program Files (x86)/tesseract/build/TesseractConfig.cmake:24 (find_package)
  sources/OCR/CMakeLists.txt:6 (find_package)
```
This is because cppan.cmake does not exist

**Comment by egorpugin** [comment]
Hi, 

Such workflow is not supported.
If you want to include leptonica with `find_package(Leptonica REQUIRED)` you can't use cppan or sw build there.

**Comment by amitdo** [comment]
@egorpugin,

Can you close this old issue?
