### ISSUE TITLE
Static linking for leptonica for Windows is not working

### ISSUE THREAD

**Issue by Moldoteck** [DanBloomberg/leptonica#477]
If i create static lib with Sw_build_shared_libs=0 and apply find_package(Leptonica) for my project, i get thi error: 
 Error LNK1104 cannot open file 'org.sw.demo.gif-5.2.1.lib' 
![image](https://user-images.githubusercontent.com/9899064/74470305-f7f83d00-4ea6-11ea-90a3-39da8e0adcaa.png)

Steps for leptonica:
Download sw, add it to path, run sw setup
Extract leptonica to c:\leptonica
Run cmake with  sw_build_shared_libs=0
Build the Install project with vs 2019  with debug x64
Needed files are generated in c:\Program Files(x86)\leptonica
![image](https://user-images.githubusercontent.com/9899064/74472021-e6646480-4ea9-11ea-9b2a-346edef76f5c.png)

**Comment by egorpugin** [comment]
See https://github.com/DanBloomberg/leptonica/issues/477
`find_package(Leptonica)` is incompatible with sw.
