### ISSUE TITLE
 Disable pixRead error messages

### ISSUE THREAD

**Issue by Tanya58** [DanBloomberg/leptonica#479]
I want to distinguish whether it is a text file or an image file through the pixRead function.
If it is a text file, I just print the text. otherwise, I extracts the text from the image and print it.

However, an error message is displayed when I use pixRead function to the text file.

I want to disable the pixRead function's error messages.
but I want to able the other function's error messages.

**Comment by DanBloomberg** [comment]
You can disable error messages for this pixRead() function call in this way:

   setMsgSeverity(L_SEVERITY_NONE);
   pix = pixRead();
   setMsgSeverity(L_SEVERITY_INFO);

**Comment by Tanya58** [comment]
Solved. Thank you!
