### ISSUE TITLE
Compatibility with out-of-date C compiler

### ISSUE THREAD

**Issue by le-sigwal** [DanBloomberg/leptonica#482]
Little and useful correction for old-fashion C compiler (gcc-2.95 for example)

Variables have to be declared at the beginning of a memspace{} before any call to a function() to avoid "parse error" :
  - ./src/compare.c @ line 3591
  - ./src/finditalic.c @ line  172
  - ./src/map.c @ line 119 & 195
  - ./src/rbtree.c @ line 143 & 165
  - ./src/readbarcode.c @ line 740 & 879
  - ./src/recogident.c @ line 837
  - ./src/utils2.c @ line 2277
  - ./prog/recogtest1.c @ line 127

**Comment by DanBloomberg** [comment]
Thank you for reporting this.  I've actually tried to avoid making this error, but have evidently not been entirely successful   :-)

I will fix this within the next day or so.

Dan

**Comment by le-sigwal** [comment]
Oh you have done a good job!
Thank you! &#128591;

**Comment by DanBloomberg** [comment]
done
