### ISSUE TITLE
IFF_TIFF_JPEG is missing from pixWriteMem.

### ISSUE THREAD

**Issue by pixel27** [DanBloomberg/leptonica#493]
https://github.com/DanBloomberg/leptonica/blob/8c68f749d42ad8be11561aa456d1df338dffa1c9/src/writefile.c#L741-L749
The pixWriteStream method DOES handle IFF_TIFF_JPEG so this appears to be an oversight.

**Comment by DanBloomberg** [comment]
Looking at pixWriteMem(), if you request IFF_JFIF_JPEG it will write a jpeg file, as one would expect, rather than a tiff file with jpeg compression.

If you want a jpeg compressed tiff file, use pixWriteMemTiff().

**Comment by pixel27** [comment]
I think there was a mix-up. I wasn't asking about IFF_JFIF_JPEG.

In pixWriteStream it has the lines:
https://github.com/DanBloomberg/leptonica/blob/e72584b0e3da7b38c568bff6908f236ca17795f8/src/writefile.c#L431-L439
So if IFF_TIFF_JPEG is passed into pixWriteStream a tiff with JPEG compression will be created.  The same cannot be said for pixWriteMem, if you pass in IFF_TIFF_JPEG you will get "unknown format".

**Comment by DanBloomberg** [comment]
.Yes, you are correct.  Thank you for pointing this out.  It is now fixed.

Regards,

Dan

**Comment by pixel27** [comment]
No problem  Truthfully I'm using the library to more load files to pass into Tesseract, but it has the ability to save images so I was playing around that functionality when I ran across this behavior and dug in to investigate.
