### ISSUE TITLE
Are there functions which support NGC or NCC (Nomalized Grey Compare) for pattern finding?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DanBloomberg/leptonica#50]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `jerry...@gmail.com` on 30 Jan 2011 at 3:43

**Comment by amitdo** [comment]
>Original issue reported on code.google.com by jerry...@gmail.com on **30 Jan 2011** at 3:43

Maybe it's time to close this issue?

**Comment by DanBloomberg** [comment]
Yeah, I'll close it.  It's based on a 2007 paper that I haven't read (yet) and am not likely to.
