### ISSUE TITLE
A calculation bug found in numaMakeDelta function in numfunc1.c file.

### ISSUE THREAD

**Issue by perlawk** [DanBloomberg/leptonica#511]
the function numaMakeDelta in numfunc1.c is suspected a bug:
with some numa test:
[3, 5] after numaMakeDelta , expect [2],   but gives [5],
original:
     prev = 0; 
my solution:
    numaGetIValue(nas, 0, &prev); 
Thanks for attention.

**Comment by DanBloomberg** [comment]
Thank you for bringing this to my attention.
You are correct -- it gets the first element of the delta array wrong!
Will be fixed today.

Dan
