### ISSUE TITLE
LNK2001 unresolved external symbol Leptonica 1.78.0 in VS2019 

### ISSUE THREAD

**Issue by AxellLim00** [DanBloomberg/leptonica#520]
Hi I'm new at using Tesseract and Leptonica, I'm using visual studio 2019 with a release x64 build, i have linked opencv2, Tesseract and Leptonica x64 static and have encountered some Linker issues. I got the files from vcpkg.

So far there seem to be 98 errors that all correspond on the file Leptonica-1.78.0.lib that all start with:
" LNK2001 unresolved external symbol .... "

can someone help me with this issue and tell me how to solve it?

**Comment by amitdo** [comment]
This is an old question regarding an old version of Leptonica.

Nobody replied. Maybe it time to close it.

**Comment by DanBloomberg** [comment]
yes
