### ISSUE TITLE
Unable to detect orientation by calling pixOrientDetect(Dwa)

### ISSUE THREAD

**Issue by bleze** [DanBloomberg/leptonica#525]
I'm trying to get pixOrientDetect(Dwa) to work, but it does not detect the rotation in my example.

I have binarized the image and tried to deskew or not deskew before calling pixOrientDetect(Dwa). Regardless I get incorrect 0 degree rotation.

`
l_float32 upconf = 0.0;
l_float32 leftconf = 0.0;
//if (pixOrientDetect(pix, &upconf, &leftconf, 0, false) == 0) // 1 bpp, deskewed, English text, 150 - 300 ppi
if (pixOrientDetectDwa(pix, &upconf, &leftconf, 0, false) == 0) // 1 bpp, deskewed, English text. 2.5 times faster than pixOrientDetect
{
	if (upconf > 1 && abs(upconf) > abs(leftconf))
		angle = 0;
	else if (leftconf > 1 && abs(leftconf) > abs(upconf))
		angle = 90;
	else if (upconf < -1 && abs(upconf) > abs(leftconf))
		angle = 180;
	else if (leftconf < -1 && abs(leftconf) > abs(upconf))
		angle = 270;
}
`

Can anyone spot my error?

My example TIFF image can found here; https://www.dropbox.com/s/lfn6jhrztpommb6/Rotated.tiff?dl=0

**Comment by bleze** [comment]
Tried another more complex example and here it works. So perhaps the example is just too simple or can Leptonica be improved to work on this too?

**Comment by DanBloomberg** [comment]
There was not enough content on your first image.   You got angle = 0 because that's what it gives when it can't make a decision.

**Comment by bleze** [comment]
As I figured. Thanks for confirming this and for a great library :)
