### ISSUE TITLE
A typo in the version notes

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#527]
Another issue with the version notes, this time for 1.80:

> Make **md** subdirectory and add ax_split_version.**md** there
 
md -> m4

https://github.com/DanBloomberg/leptonica/tree/master/m4

**Comment by DanBloomberg** [comment]
thanks!
fixed (not yet committed)

**Comment by amitdo** [comment]
Fixed in https://github.com/DanBloomberg/leptonica/commit/ff5fc9445243db. Thanks.

What about importing the changes to http://www.leptonica.org/source/version-notes.html ?

**Comment by DanBloomberg** [comment]
done!

**Comment by DanBloomberg** [comment]
fixed and done!
