### ISSUE TITLE
JPEG TIFF not readable via pixReadFromMultipageTiff.

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#528]
pixReadFromMultipageTiff returns null for the attached TIFF.  I thought maybe this might be due to the specific build of libtiff used by Leptonica but I was unable to create one that worked using turbojpeg.lib.  I was able to read this file with an older Leptonica (I think 1.78) but not 1.80.  Tiffinfo says this about the document.  Any advice?

D:\Petri\tiff-4.1.0\tiff-4.1.0\buildx86\tools\Release>tiffinfo show.tif
show.tif: Warning, Nonstandard tile width 636, convert file.
show.tif: Warning, Nonstandard tile length 824, convert file.
TIFFReadDirectory: Warning, Unknown field with tag 512 (0x200) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 513 (0x201) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 514 (0x202) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 515 (0x203) encountered.
TIFF Directory at offset 0x8 (8)
  Subfile Type: multi-page document (2 = 0x2)
  Image Width: 636 Image Length: 824
  Tile Width: 636 Tile Length: 824
  Resolution: 75, 75 pixels/inch
  Bits/Sample: 8
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  YCbCr Subsampling: 1, 1
  YCbCr Positioning: cosited
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Page Number: 0-0
  Reference Black/White:
     0:     0   255
     1:   128   255
     2:   128   255

[Show.zip](https://github.com/DanBloomberg/leptonica/files/4995394/Show.zip)

**Comment by DanBloomberg** [comment]
This is working as intended.  We were having trouble with fuzzing on tiled tifs, and made the decision not to support them.

See l. 508 in tiffio.c.  The tiles can easily be removed before processing, using tiffcp.

**Comment by tdhintz** [comment]
"Oof dah."   We can use ImageMagick to load them but we need to use BMP to get a Pix object if we want to keep things in memory.  Tesseract recognition quality is poor through that path for some reason.  We can push it back to disk in a compatible TIFF format but then we have to encrypt and track yet another temp file.  Life just got complicated.

**Comment by DanBloomberg** [comment]
Sorry about that.

You should be able to use PNG and keep everything in memory.

Have you submitted a comparison to tesseract that shows poorer quality through one path than another?
leptonica has some good image compare functions in compare.c that might be helpful.
