### ISSUE TITLE
Info in dewarpaSetValidModels: no model successfully built

### ISSUE THREAD

**Issue by mattsliv** [DanBloomberg/leptonica#531]
Greetings,

I am currently attempting to use Leptonica to dewarp scanned phone book images (e.g., see below).

![RI_1975_1_copy](https://user-images.githubusercontent.com/22246473/90794685-110cfb00-e2db-11ea-9c65-914e2cec7071.png)

I wrote a program using the example program `prog/dewarp1.c` as a template where a model can't successfully be built.

```
Info in dewarpGetTextlineCenters: finding text line centers
Warning in dewarpRemoveShortLines: lines are relatively short
Warning in dewarpBuildPageModel: linecount 3 < min req'd number of lines (10) for model
Info in dewarpaSetValidModels: page 0: no model successfully built
Info in dewarpaApplyInit: no valid dew model for page 0
Error in dewarpaApplyDisparity: no model available
Info in pixWriteStreamJpeg: converting from 1 to 8 bpp
Error in fopenReadStream: file not found
Error in pixRead: image file not found: /tmp/lept/dewmod/0060.png
Error in pixWrite: pix not defined
Error in fopenReadStream: file not found
Error in pixRead: image file not found: /tmp/lept/dewmod/0070.png
Error in pixWrite: pix not defined
Error in fopenReadStream: file not found
Error in pixRead: image file not found: /tmp/lept/dewapply/002.png
Error in pixWrite: pix not defined
Error in fopenReadStream: file not found
Error in pixRead: image file not found: /tmp/lept/dewapply/003.png
Error in pixWrite: pix not defined

concatenating ... done
pdf file made: /tmp/lept/model/dewarptest1.pdf
```

 Here is a summary of the changes:

- The input image `pixs` contains the image above
- Excluded converting from RGB to Gray using `pixConvertRGBToGray` since the image is already in grayscale
- Set the number of dewarp pages from 2 to 1 in `dewarpaCreate`
- Since the page I'm processing doesn't have a page number, I set the page number from 35 to 0 in `dewarpCreate` and `dewarpaApplyDisparity`
- Removed normalizing another image

[Here](https://github.com/DanBloomberg/leptonica/files/5104192/cus_dewarp_page.zip) is the full program and image to be processed.

Any help would be greatly appreciated!

**Comment by DanBloomberg** [comment]
Hi Matt,

The software requires longer lines to determine the transformation required for dewarping.  The typical page would just have text lines the full width, or possibly two columns with a small distance between them.  The lines in your image are too short.

The reason for this is there is always a risk when trying to fix harder cases that you'll just make things worse.  The algorithms here were designed, as with the Hippocratic oath, to first do no harm.

Dan

**Comment by mattsliv** [comment]
I see. Would you know of any pre-processing that would work with algorithms used?

**Comment by DanBloomberg** [comment]
No, not with the leptonica dewarping code.

**Comment by mattsliv** [comment]
Ah, interesting. I'll test this against some other warped images I have later on in the week.  

Thank you for your help!

**Comment by mattsliv** [comment]
As a side issue, my original images are `.tif` files instead of `.png` where I wasn't able to write an image if the read image is a `.tif`.

For example, this will not write:
```
pix_in = pixRead("/tmp/RI_1975_1.tif");
pix_thresh = pixThresholdToBinary(pix_in, 160);
pix_deskew = pixDeskewLocal(pix_thresh, 10, 0, 0, 0.0, 0.0, 0.0);
pixWrite("/tmp/test_deskew.tif", pix_deskew, IFF_TIFF_G4);
```

I was, however, able to read the image as a `.png` and write the de-skewed image as a `.tif`. For example, this will write:
```
pix_in = pixRead("/tmp/RI_1975_1.png");
pix_thresh = pixThresholdToBinary(pix_in, 160);
pix_deskew = pixDeskewLocal(pix_thresh, 10, 0, 0, 0.0, 0.0, 0.0);
pixWrite("/tmp/test_deskew.tif", pix_deskew, IFF_TIFF_G4);
```
 I'm not sure why there's issues with reading `.tif` images versus `.png` images (I have tried both `pixRead` and `pixReadTiff`).

**Comment by DanBloomberg** [comment]
can include the input tiff image RI_1975_1.tif?  what error messages did you get?

**Comment by mattsliv** [comment]
[Here](https://github.com/DanBloomberg/leptonica/files/5143473/RI_1975_1.tif.zip) is the `.tif` image. The strange thing is, there are no error messages...

**Comment by DanBloomberg** [comment]
Actually, it's a png.

/tmp$ fileinfo matt-image.png
===============================================
Reading the header:
  input image format type: png
  w = 3345, h = 4872, bps = 8, spp = 1, iscmap = 0
  xres = 600, yres = 600
===============================================
Reading the full image:
  input image format type: png
  w = 3345, h = 4872, d = 8, spp = 1, wpl = 837
  xres = 600, yres = 600
  text: <x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="XMP Core 5.4.0">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:tiff="http://ns.adobe.com/tiff/1.0/">
         <tiff:Orientation>1</tiff:Orientation>
         <tiff:PhotometricInterpretation>0</tiff:PhotometricInterpretation>
         <tiff:ResolutionUnit>2</tiff:ResolutionUnit>
         <tiff:Compression>5</tiff:Compression>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>

  colormap does not exist

**Comment by mattsliv** [comment]
Did you run `fileinfo` on the image in the `.zip` file? The image in there is not a `.png` file.

**Comment by DanBloomberg** [comment]
How strange.  So it now is.  But before it was a png.

Anyway, it's 1 bpp, and pixThresholdToBinary fails.  You should have seen error messages if you allow them to be sent to stderr.

**Comment by mattsliv** [comment]
Ah okay. It's now fixed by removing `pixThresholdToBinary`.

**Comment by PradeepNalluri** [comment]
@mattsliv are you able to dewarp the image? I am also facing a similar issue and the data in my image is much more sparse and distant than the image with which you are trying to dewarp. Any suggestion to solve this is much appreciated.
Thanks
PN

**Comment by DanBloomberg** [comment]
see my suggestion on Aug 21 for an alternative to the fancy dewarping approach.

**Comment by mattsliv** [comment]
@PradeepNalluri Unfortunately, the above solution proposed by @DanBloomberg does not fully dewarp the images that I'm dealing with alone.

The above code mostly fixes the third-dimensional skew of the images, where there is still a shear left that needs to be fixed. To fully dewarp most of my images, what I do is deskew using Leptonica then deshear using OpenCV.

**Comment by DanBloomberg** [comment]
Did OpenCV compute the remaining shear angle, or did you enter it by hand?

**Comment by mattsliv** [comment]
I found the corner points for OpenCV to compute the shear angle.

**Comment by DanBloomberg** [comment]
closing this issue

**Comment by Marcopt98** [comment]
![final](https://github.com/DanBloomberg/leptonica/assets/42810792/b58bcbaf-8c25-4801-848f-f151fb893f18)
Hey, I have a similar issue with this image example. I get the following logs:

> Info in dewarpGetTextlineCenters: finding text line centers
> Warning in dewarpBuildPageModel: linecount 2 < min req'd number of lines (10) for model
> Info in dewarpaSetValidModels: page 35: no model successfully built
> Info in dewarpaApplyInit: no valid dew model for page 35
> Error in dewarpaApplyDisparity: no model available
> Error in getFilenamesInDirectory: pdir not opened
> Error in getSortedPathnamesInDirectory: sa not made
> Error in convertFilesToPdf: sa not made

I tried to deskew but without any success. Do you think it might be because it's to curved?
Here's my code, do you have any suggestion?

```
var pixn = pixBackgroundNormSimple(pixs, nil, nil);
        var pixg = pixConvertRGBToGray(pixn, 0.5, 0.3, 0.2);
        var pixb = pixThresholdToBinary(pixg, 130);
        let dewa = dewarpaCreate(2, 30, 1, 10, 90);
       dewarpaUseBothArrays(dewa, 1);
let dew1 = dewarpCreate(pixb, 35);
        dewarpaInsertDewarp(dewa, dew1);
        dewarpBuildPageModel(dew1, modelPath.relativePath);
        dewarpaApplyDisparity(dewa, 35, pixg, 200, 0, 0, &pixd, disparityPath.relativePath);
```
