### ISSUE TITLE
make -j8   error

### ISSUE THREAD

**Issue by Yunpentium** [DanBloomberg/leptonica#536]
wsl  ubuntu 18.04
gcc version 7.4
cmake version 3.10.2

when I make -j8 to compile, have the following error..

Linking C static library libleptonica.a
/usr/bin/ar: unable to rename 'libleptonica.a'; reason: Permission denied
src/CMakeFiles/leptonica.dir/build.make:4722: recipe for target 'src/libleptonica.a' failed
make[2]: *** [src/libleptonica.a] Error 1
make[2]: *** Deleting file 'src/libleptonica.a'
CMakeFiles/Makefile2:117: recipe for target 'src/CMakeFiles/leptonica.dir/all' failed
make[1]: *** [src/CMakeFiles/leptonica.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zdenop** [comment]
**reason: Permission denied**
this is user problem and not leptonica

**Comment by Yunpentium** [comment]
I use root user,  and use chmod -R  777  ./leptonica/*

But  the problem can't be fixed,  I'm confused.

**Comment by Yunpentium** [comment]
Finally I  am tryingto make .. -DBUILD_SHARED_LIBS=ON,  and generate libleptonica.so successfully 


[ 99%] Building C object src/CMakeFiles/leptonica.dir/zlibmemstub.c.o
[100%] Linking C shared library libleptonica.so
[100%] Built target leptonica
