### ISSUE TITLE
pixAutoPhotoinvert: invert not applied on whole image

### ISSUE THREAD

**Issue by zdenop** [DanBloomberg/leptonica#541]
I tried to test pixAutoPhotoinvert function on following image:
![comics](https://user-images.githubusercontent.com/574156/94268790-f82ce080-ff3d-11ea-9cdc-b5744f7315be.png)
but invert is not applied on whole image:
![result](https://user-images.githubusercontent.com/574156/94268818-01b64880-ff3e-11ea-9862-7cb8f08e6804.png)
I understand this could be useful in some scenarios, but is it possible to force autoinvert whole image instead of individual regions?

**Comment by DanBloomberg** [comment]
Thank you.  That is an interesting failure.
I'll have a look at the situation.

**Comment by DanBloomberg** [comment]
Fixed the immediate problem.  Added some conditional hole-filling in the inversion mask.  Closing.
