### ISSUE TITLE
Unable to build Leptonica in RHEL7,4

### ISSUE THREAD

**Issue by oakolawole** [DanBloomberg/leptonica#542]
Greetings All,

I am trying to build letponica for use in Tessaract. 

After untar the tar file, I have executed the following

1. `./autogen.sh' -- completes
2. ./configure -- completes
3 make DEBUG=yes debug  -- completes

As stated, my goal is to run Leptonica for Tessaract and as such, I believe I need to build library files so I executed the
4. make SHARED=yes shared -- this fails with the following 
-----------------------------------------------------------------------------------------------
mv ../lib/shared/liblept.so ../lib/shared/liblept.so.1.80.0
cd ../lib/shared; rm liblept.so.1; \
  ln -s lblept..so.1.80.0 liblept.so.1
rm: cannot remove ‘liblept.so.1’: No such file or directory
cd ../lib/shared; rm liblept.so; \
  ln -s liblept.so.1 liblept.so
rm: cannot remove ‘liblept.so’: No such file or directory
-------------------------------------------------------------------------------------------------

When I try to run the sample files in prog folder. The instruction says

        To make the programs in the prog directory, first make liblept
         in src.  Then in prog you can customize the makefile for linking
         the external libraries:
         Finally, do 'make' in the prog directory

5. When I try to make liblept in the prog directory, nothing happens. 
6. Similarly when I attempt, in the src folder, 

   [root@localhost src]# make liblept
   make: *** No rule to make target `liblept'.  Stop.

Thank You.  Please help

**Comment by DanBloomberg** [comment]
Section 2 of README.html gives 3 ways to build leptonica. You used method (2): autoconf.  After you ran configure, you typed:
   make DEBUG=yes debug
This should fail in method 2. (!)  That command only works with method (1), which you did not enable by running
   make-for-local.

If you want to make a debug library, I suggest using method (3):  cmake.
Follow the instructions there.

**Comment by oakolawole** [comment]
My goal was to use Method 1.  I will delete and retry. 

Thank You

**Comment by oakolawole** [comment]
When I attempt to do make, I get a succesful build. 

When I attempt to make SHARED=yes shared, IT FAILS with below message

mv ../lib/shared/liblept.so ../lib/shared/liblept.so.1.80.0
cd ../lib/shared; rm liblept.so.1; \
  ln -s lblept..so.1.80.0 liblept.so.1
rm: cannot remove ‘liblept.so.1’: No such file or directory
cd ../lib/shared; rm liblept.so; \
  ln -s liblept.so.1 liblept.so
rm: cannot remove ‘liblept.so’: No such file or directory

**Comment by DanBloomberg** [comment]
According to the instructions:
   make-for-local
   cd src
   make DEBUG=yes debug   (for debug library)
    (or make SHARED=yes shared   (for shared library))
  cd ../prog
  make DEBUG=yes     (for debug programs)
    (or make SHARED=yes     (for shared programs))

If you're using shared libraries, you must also do this from your prog directory:
   export LD_LIBRARY_PATH=../lib/shared:$LD_LIBRARY_PATH
so the programs can find the leptonica shared library.

I agree with you that the documentation in the README.html is a bit terse
for building with static makefiles (method 1), so I have cleaned it up a bit.
The new version is attached here.
[README.html.gz](https://github.com/DanBloomberg/leptonica/files/5336829/README.html.gz)

**Comment by oakolawole** [comment]
Building Method 2 does not work for me. 

[root@localhost leptonica1]# make
make  all-recursive
make[1]: Entering directory `/root/dev/leptonica1'
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/dev/leptonica1'
make: *** [all] Error 2
[root@localhost leptonica1]#

**Comment by DanBloomberg** [comment]
I suggest you either try method 1, according to what I wrote above, or try method 3 with cmake.

**Comment by oakolawole** [comment]
when  do a make after doing a cmake .. -DBUILD_PROG=1, I get the following compile errors

/root/Downloads/leptonica-1.80.0/src/gifio.c: In function ‘pixReadMemGif’:
/root/Downloads/leptonica-1.80.0/src/gifio.c:180:5: error: too many arguments to function ‘DGifOpen’
     if ((gif = DGifOpen((void*)&buffer, gifReadFunc, NULL)) == NULL)
     ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:188:14: note: declared here
 GifFileType *DGifOpen(void *userPtr, InputFunc readFunc);    /* new one
              ^
/root/Downloads/leptonica-1.80.0/src/gifio.c: In function ‘gifToPix’:
/root/Downloads/leptonica-1.80.0/src/gifio.c:241:9: error: too many arguments to function ‘DGifCloseFile’
         DGifCloseFile(gif, &giferr);
         ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:246:9: error: too many arguments to function ‘DGifCloseFile’
         DGifCloseFile(gif, &giferr);
         ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:254:9: error: too many arguments to function ‘DGifCloseFile’
         DGifCloseFile(gif, &giferr);
         ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:259:9: error: too many arguments to function ‘DGifCloseFile’
         DGifCloseFile(gif, &giferr);
         ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:271:9: error: too many arguments to function ‘DGifCloseFile’
         DGifCloseFile(gif, &giferr);
         ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:277:9: error: too many arguments to function ‘DGifCloseFile’
         DGifCloseFile(gif, &giferr);
         ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:297:9: error: too many arguments to function ‘DGifCloseFile’
         DGifCloseFile(gif, &giferr);
         ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:305:9: error: too many arguments to function ‘DGifCloseFile’
         DGifCloseFile(gif, &giferr);
         ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:341:5: error: too many arguments to function ‘DGifCloseFile’
     DGifCloseFile(gif, &giferr);
     ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:203:5: note: declared here
 int DGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c: In function ‘pixWriteMemGif’:
/root/Downloads/leptonica-1.80.0/src/gifio.c:439:5: error: too many arguments to function ‘EGifOpen’
     if ((gif = EGifOpen((void*)buffer, gifWriteFunc, NULL)) == NULL) {
     ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:139:14: note: declared here
 GifFileType *EGifOpen(void *userPtr, OutputFunc writeFunc);
              ^
/root/Downloads/leptonica-1.80.0/src/gifio.c:445:5: error: too many arguments to function ‘EGifCloseFile’
     EGifCloseFile(gif, &giferr);
     ^
In file included from /root/Downloads/leptonica-1.80.0/src/gifio.c:80:0:
/usr/include/gif_lib.h:166:5: note: declared here
 int EGifCloseFile(GifFileType * GifFile);
     ^
/root/Downloads/leptonica-1.80.0/src/gifio.c: In function ‘pixToGif’:
/root/Downloads/leptonica-1.80.0/src/gifio.c:551:19: warning: assignment makes pointer from integer without a cast [enabled by default]
     if ((gif_cmap = GifMakeMapObject(gif_ncolor, NULL)) == NULL) {
                   ^
make[2]: *** [src/CMakeFiles/leptonica.dir/gifio.c.o] Error 1
make[1]: *** [src/CMakeFiles/leptonica.dir/all] Error 2
make: *** [all] Error 2
[root@localhost build]#

**Comment by DanBloomberg** [comment]
along with #547
