### ISSUE TITLE
Build Method 2 Fails

### ISSUE THREAD

**Issue by oakolawole** [DanBloomberg/leptonica#543]
After executing a ./configure
I attempt to do a Make but that fails
----------------------------------------------------------------------------------------
make  all-recursive
make[1]: Entering directory `/root/dev/leptonica-1.80.0'
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/dev/leptonica-1.80.0'
make: *** [all] Error 2
-------------------------------------------------------------------------------------------------

**Comment by DanBloomberg** [comment]
closing; all comments on this issue go to #542
