### ISSUE TITLE
Upsample factor?

### ISSUE THREAD

**Issue by zvezdochiot** [DanBloomberg/leptonica#552]
Interested in using upsample as preprocessing, with subsequent correction of the result to the original scale.

**Comment by DanBloomberg** [comment]
Sure.  You can upsample in a variety of ways.  See functions in scale1.c, and also pixExpandReplicate() in scale2.c.

**Comment by zvezdochiot** [comment]
But at the same time, I also have to scale the coordinates myself. And what kind of general system of work with the scale is not provided?

**Comment by DanBloomberg** [comment]
I don't understand the question..  The coords are always just the pixels.  If you upscale by 4x, the coords in the new image are 4x larger.  You can always divide by 4 to get the coords relative to the original.

**Comment by zvezdochiot** [comment]
This means that there are no structures that keep the scale. Got it. That was the question. Thanks.
