### ISSUE TITLE
genPathname corrupts filenames with backslashes in them via convertStepCharsInPath

### ISSUE THREAD

**Issue by MerlijnWajer** [DanBloomberg/leptonica#558]
Noticed as a problem in Tesseract initially: https://github.com/tesseract-ocr/tesseract/issues/3178

It looks like `genPathname` does not like backslashes in filenames on UNIX, even though this is valid:

```
$ wc -c /tmp/test\\.jp2
455359 /tmp/test\.jp2
merlijn@gentoo-x230 /tmp $ tesseract /tmp/test\\.jp2 -
Error in fopenReadStream: file not found
Error in findFileFormat: image file not found
Error during processing.
```

```
Breakpoint 1, 0x00007ffff7aa53b0 in fopenReadStream () from /usr/lib64/liblept.so.5
(gdb) print (char*)$rdi
$9 = 0x7fffffffd094 "/tmp/example/427527-\\nagripracharni Patrika Year 60 Vol 2 Ac 2610_0000.jp2"
(gdb) c
Continuing.Breakpoint 4, 0x00007ffff7aa50b0 in genPathname () from /usr/lib64/liblept.so.5
(gdb) print (char*)$rdi
$10 = 0x7fffffffd094 "/tmp/example/427527-\\nagripracharni Patrika Year 60 Vol 2 Ac 2610_0000.jp2"
(gdb) step
Single stepping until exit from function genPathname,
which has no line number information.
(gdb) print (char*)$rax
$19 = 0x5555555b0570 "/tmp/example/427527-/nagripracharni Patrika Year 60 Vol 2 Ac 2610_0000.jp2"
```

It looks like `convertStepCharsInPath` is causing this problem, it's  converting `'\\'` to `/` even on UNIX, which is not what it should be doing, as far as I can tell.

**Comment by stweil** [comment]
Yes, I can confirm this problem. The replacement should not be done for Linux, MacOS and others which only use `/` as path separator.

**Comment by DanBloomberg** [comment]
Question:  are there valid path names in unix that have these double back-slashes?  How would such a path, as you show above, be interpreted by the file system?

Also, are there valid path names in unix with a single back-slash?

**Comment by DanBloomberg** [comment]
And finally, is that a valid path name in Windows?

**Comment by MerlijnWajer** [comment]
> Question: are there valid path names in unix that have these double back-slashes? How would such a path, as you show above, be interpreted by the file system?

Yes, those exist, every backslash just needs to be escaped with another backslash from the shell, but the string (in bytes) would just contain one backslash for each backslash.

```
merlijn@gentoo-x230 ~ $ touch /tmp/test\\\\test2\\\\\\\\
merlijn@gentoo-x230 ~ $ ls -lsh /tmp/test\\\\test2\\\\\\\\
0 -rw-r--r-- 1 merlijn merlijn 0 Dec 10 23:18 '/tmp/test\\test2\\\\'
```

Quick test in Python (every backslash is also escaped with a backslash):

```
>>> s = '/tmp/test\\\\test2\\\\\\\\'
>>> s.count('\\')
6
>>> open(s, 'rb').read()
b''
```

The `s.count('\\')` shows that six backslashes are in the path in total (the `'\\'` is a *single* backslash). Two after `test`, four after `test2`. The `open(s, 'rb')` call shows that the open succeeds.

> Also, are there valid path names in unix with a single back-slash?

Yes, the example I showed actually had just a single back slash in the actual file name, it's just that I (and gdb) had to escape the back slashes for the string literals and in the shell itself.

**Comment by MerlijnWajer** [comment]
> And finally, is that a valid path name in Windows?

My windows-fu isn't that strong, but I know that both `/` and `\` are not allowed in *file* names, but can both be part of a path in Windows. If a forward slash actually works outside of Windows APIs is something I do not know.

**Comment by DanBloomberg** [comment]
Thank you!   From what you have said, on unix systems all backslashes must be preserved.  (Which is what you said in your initial posting.  I will fix this.

**Comment by MerlijnWajer** [comment]
Thank you!

**Comment by MerlijnWajer** [comment]
I can confirm that this solves the problem for me, by the way. Applied the patch it on top of Ubuntu 20.04's `liblept5` and the problem in Tesseract is gone. So I guess the issue can be closed?

**Comment by DanBloomberg** [comment]
Thank you for confirming we're ok.
