### ISSUE TITLE
cmake usage seems somewhat out-of-date

### ISSUE THREAD

**Issue by john-forrest** [DanBloomberg/leptonica#559]
First of all I should say I am no cmake guru. Also the version of Leptonica we are using is actually a slightly patched version of the one from the hunter package manager (see https://github.com/hunter-packages/leptonica), the most up to date version of which is 1.74.2. Nevertheless the gist of what I am seeing still seems to be true: that the cmake scripts are using traditional cmake of a flavour predating the target-orientated "modern" style of cmake 3.0.

The min cmake entry in our version is 2.8.11. The very latest cmake (3.19) has deprecated support for features pre-dating 2.8.12 (basically AKA 3.0). The script should report a warning not fail, but actually for me it fails at that point, which might be something to do with hunter.

Now that is our (old) leptonica version, but although the latest version in this repo says the 3.1.3, the actual cmake-style used seems hardly to have changed. It is still referring to things like TIFF_LIBRARIES (not tiff::libtiff or whatever it is) and it is not using the PRIVATE/PUBLIC/INTERFACE keywords in target_link_libraries(). 

I am wondering whether to do a catchup on Leptonica in our own area and then completely scrap the existing build scripts, but I was wondering if there was a reason for the current usage?

**Comment by DanBloomberg** [comment]
My suggestion is to build and install from the current release or the current master.
You are likely to have no difficulties.

Dan

**Comment by john-forrest** [comment]
Thanks for the reply. I think it is more complex than that as we are using the hunter package manager and that needs some fixes. Also looking again somebody has added some target use into the CMakeLists.txt, see:

https://github.com/hunter-packages/leptonica/blob/hunter/src/CMakeLists.txt#L38

I tried just updating the minimum cmake version for this version and it is now complaining that:

  CMake Error at src/CMakeLists.txt:38 (target_link_libraries):
    The plain signature for target_link_libraries has already been used with
    the target "leptonica".  All uses of target_link_libraries with a target
    must be either all-keyword or all-plain.
    
This is because you cannot mix use of PUBLIC/PRIVATE/INTERFACE with not using them. Reality is that you should not now be using the non-keyword form. Equally most of the entries like:

target_include_directories  (leptonica PUBLIC ${JPEG_INCLUDE_DIR})

should not be there - it should be a proper use of target_link_libraries().

I don't know why the latest version is coming up with this new error, but I will try and make some further changes and see how I go.

**Comment by john-forrest** [comment]
OK. What seems to have happened in our version (1.74.2) is that the line "pkg_check_modules(WEBP libwebp)", in the top-level CMakeLists.txt, is suddenly finding something when it did not before - possibly that for libopenjp2 too, difficult to tell. I've commented out those lines and it proceeds. Note that these builds are in docker container environments, so I know what is installed. The only think different about the cmake 3.19.1 is the cmake itself - one or other of the updates is making this behavve differently, even though nothing is obvious.

Just before that I tried adding "PUBLIC" to the associated target_link_libraries() calls in src/CMakeLists.txt. That got further - mixing no-keyword and keyword uses of target_link_libraries() has been illegal for sometime, so any change would have been those lines were called. With just the additional PUBLIC the error was a missing include file related to webp. That is not surprising as this version does not contain the target_include_directories() calls in CMakeLists.txt you have subsequently added (PR #273 ) 

I suspect we will stick with disabling the packages we don't want, so we know more specifically what we do, and not rely on optional stuff here. However should I decide to try to keep that, I still think the problem is lack of targets. In our own code we exclusively use find_package rather than pkg_check_modules, not least because it does relate to targets. However I note there is now an IMPORTED_TARGET parameter for pkg_check_modules, which would define PkgConfig::WEBP etc. This apparently came in with cmake 3.6. I suspect that would be the approach to use.

**Comment by egorpugin** [comment]
Hi,

Cmake is not the official build system. I contributed it for windows only usage to be used in tesseract-ocr.
After that cmake scripts were touched rarely just to keep very basic cmake level and ability to build leptonica with it.

**Comment by john-forrest** [comment]
OK fine. I will stick with the statement that the cmake usage is looking out-of-date, but short term this is probably more of an issue with the hunter version - where somebody has mixed modern and old-fashioned usage when they patched it. Longer term I suspect you will need to update to use targets properly (it would actually be less script lines) and (I would suggestion) have flags as to which third-party libraries you wish to use (rather than having optional ones). Shorter term, it seems this is my problem! I will close the ticket.
