### ISSUE TITLE
pixReadFromMultipageTiff leak reading Tiled image?

### ISSUE THREAD

**Issue by tdhintz** [DanBloomberg/leptonica#566]
If an attempt is made to read a Tiled TIFF using pixReadFromMultipageTiff, the file handle seems to be left open.  Tiled images are not compatible with leptonica so the expected behavior is to return null and leave the file in a closed state.

**Comment by DanBloomberg** [comment]
In l. 1367 of tiffio.c, please change TIFFCleanup() to TIFFClose().
Does that fix the problem?

**Comment by tdhintz** [comment]
Hey, Dan.  Its been busy so I can't go through the build right now.  We disabled the leptonica I/O for the moment because the leak had a rather serious impact on some people.  I'll get back to you when I get the chance to diagnose the problem further.

**Comment by tdhintz** [comment]
Dan, I tried to build this morning but our VS2019 instructions are based on cppan.  Can you save me some time and point me to the current build instructions for Windows?  Thanks,

**Comment by tdhintz** [comment]
I built as follows, but the VS2019 solution no longer links with Additional Dependencies set to anything, thus the dependencies are no longer bundled.  Is there a setting to also bundle dependencies?

mkdir build && cd build
cmake -DBUILD_SHARED_LIBS=1 -DSW_BUILD_SHARED_LIBS=0 ..
cmake --build . --config Release

**Comment by DanBloomberg** [comment]
Egor is the expert in this.
We're now recommending you build using sw.
The instructions are in README.html,   Section 3 (a).

**Comment by tdhintz** [comment]
Ah, right.  I have a hard time remembering that.  There is a build placeholder on the wiki I think.  Maybe mention that there?

**Comment by tdhintz** [comment]
Yes, that change does fix the file close problem.  Thank you!

**Comment by DanBloomberg** [comment]
Thank you for checking.  l'll make the change there (and a couple other places, I think).

Dan

**Comment by DanBloomberg** [comment]
Fix is in.
