### ISSUE TITLE
pixDeskew not working

### ISSUE THREAD

**Issue by youngsys** [DanBloomberg/leptonica#570]
Hi
test.png deskews nicely, but test2.png remains unchanged. Any ideas/pointers?
![test](https://user-images.githubusercontent.com/20759387/112010423-338c1e80-8b1f-11eb-9637-f51266af59a4.png)
![test2](https://user-images.githubusercontent.com/20759387/112010428-3424b500-8b1f-11eb-8b2e-62a2dd494297.png)

    Pix pix1 = Leptonica1.pixRead("c:/temp/test2.png");
    Leptonica1.pixSetResolution(pix1, 300, 300);
    Pix pix2 = Leptonica1.pixDeskew(pix1,0);
    Leptonica1.pixWrite("c:/temp/test3.png", pix2, IFF_PNG);

Both were created from a Word doc saved as pdf, rendered B&W with pdfBox, converted to pix and saved to disk. Test.png was oriented as here. Test2 was 200+ degrees, so was pixRotate90'd twice before attempting the deskew. Can anyone assist with why test2.png will not deskew?

Thanks.

**Comment by DanBloomberg** [comment]
I assume you are using pixDeskew() with default parameters.

The default value for DefaultSweepRange is 7 degrees.
If you expect skews larger than 7 degrees, use pixDeskewGeneral() with appropriate parameters.

**Comment by youngsys** [comment]
Doh! That was too easy. Thanks.
I was considering checking Tesseract confidence levels and then increasing the range, but it's so fast, I'm not sure I need to.
Thanks again.
