### ISSUE TITLE
Background normalization followed by Sauvola binarization

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#576]
https://github.com/DanBloomberg/leptonica/blob/5aaf1c187deeef7f/prog/binarize_set.c

```
*   Method 4.  Background normalization followed by Sauvola binarization.
```
```
    /* 4. Background normalization followed by Sauvola binarization */
```

but it calls `pixContrastNorm()`, not `pixBackgroundNorm()`.

Another thing, why methods 4 and 5 are not provided as functions call in `binarize.c`?

**Comment by DanBloomberg** [comment]
Thank you for noticing.  I agree that methods 4 and 5 could be added to binarize.c.
They are, in fact, much better than the first 3 for difficult images.
Will take a look.

Dan

**Comment by amitdo** [comment]
Fixed in commit 4378784233ebcf.

Thanks!

**Comment by amitdo** [comment]
https://github.com/DanBloomberg/leptonica/blob/4378784233ebcf8d3b7245a2c0d56f05d87f80af/src/binarize.c

```
 *      Sauvola binarization on adaptive background normalization
      
      
         *          PIX          *pixSauvolaOnBackgroundNorm()  8 bpp
```

It does not match to what you actually implemented.

**Comment by DanBloomberg** [comment]
Thank you for noticing.  I agree that methods 4 and 5 could be added to binarize.c.
They are, in fact, much better than the first 3 for difficult images.
Have added them as you suggested.

Dan

**Comment by DanBloomberg** [comment]
thanks!   I'll fix it.
