### ISSUE TITLE
Binarization methods for Tesseract

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#578]
Hi Dan,

Until a few days ago, Tesseract suppored only one binarization method. This is a custom non-adaptive Otsu. I added two methods from Leptonica: Adaptive Otsu and Tiled Sauvola. Currently, the parameters are fixed. The tiles size is 300x300.

I want to know your opinion. What binarization methods from Leptonica should be supported in Tesseract? I can add them all... What should be the default method?

**Comment by DanBloomberg** [comment]
As you can see, there are lots of ways to do it.  Best to couple some normalization operation (gray --> gray),
such as adaptive or contrast, followed by binarization (a global value, via Otsu, or a more adaptive value via Sauvola).

I don't have a particular favorite.  However if you run
     binarize_set w91frag.jpg
the last two in the output mosaic are pretty good.
They are, in fact, just the two that I added yesterday, so if you want to add any, I'd suggest those, and that they may be better than the others for difficult images like w91frag.jpg.  
Another advantage for using them is that they only have one adjustable parameter, the contrast normalization parameter 'mindiff'.

As you can see from the regression test binarize_reg, the tiling with Sauvola doesn't make any difference to the result -- it is just available to allow the image to be processed in parallel.  (Someone needed it years ago; can't remember why)

**Comment by amitdo** [comment]
Another question. Tessract needs not just the thresholded pix, but also a pix with thresholds values. It is used together with the greyscale image to find blobs outlines.

Some of Leptonica's binarization functions do provide this requirement. Others do not.

I think it should be possible to calculate the thresholds (for the original greyscale, not for a normalized version) from the combined pixel info of the greyscale I have and the thresholded image I get from these functions. Am I correct? Do you have a built in function for this task?

I hope my question is clear.

**Comment by DanBloomberg** [comment]
The thresholding as I've said is a sequence of operations.

What you want is easily calculated from the original and the result, which are at the same resolution.
Consider one pixel, say 153 in the original and 0 (white) in the 1 bpp result.
Then you can choose any value less than 153 for the corresponding pixel in the image of thresholds.
If the 1 bpp result is 1 (black), choose any value larger than the original gray value.

Is that what you want?  If so, I'll write a function to put the threshold value half way between the gray input
value and either 0 (for 0 output) or 255 (for 1 output).

**Comment by amitdo** [comment]
Yes, this is exactly what I want.

**Comment by DanBloomberg** [comment]
I've implemented it.  Let me know if it's what you need.

Dan

**Comment by amitdo** [comment]
Thanks a lot Dan. Yes, it's what I need. I'll try to use it in Tesseract and let you know how it worked out.

>the tiling with Sauvola doesn't make any difference to the result

I'm aware of that.

>it is just available to allow the image to be processed in parallel. (Someone needed it years ago; can't remember why)

You explained why here:

https://github.com/DanBloomberg/leptonica/blob/9d6265f796b769/src/binarize.c

```
 *      (3) Why a tiled version?
 *          (a) Because the mean value accumulator is a uint32, overflow
 *              can occur for an image with more than 16M pixels.
 *          (b) The mean value accumulator array for 16M pixels is 64 MB.
 *              The mean square accumulator array for 16M pixels is 128 MB.
 *              Using tiles reduces the size of these arrays.
 *          (c) Each tile can be processed independently, in parallel,
 *              on a multicore processor.
 *      
```

So maybe sauvola should be used with tiles in the new `pixSauvolaOnContrastNorm()`.

Currently, you use this code:
`pixSauvolaBinarizeTiled(pix1, 25, 0.40, 1, 1, NULL, &pixd);`

**Comment by DanBloomberg** [comment]
Tiling in pixSauvolaOnContrastNorm:  I'll set the number of tiles so that their size is about 250 x 250.

As for this latest function that I added, I can't believe it will be useful.  Here's why:
(1) I chose the threshold to be as close as possible to the input gray image. It is 1 larger if the binary output was 1 (black) and 1 smaller if the output was 0.  How can that be useful?
(2) I could have computed a threshold array just from the output binary image:
  0 (binary) --> 0 (threshold)
  1 (binary) --> 255 (threshold)

Dan

**Comment by amitdo** [comment]
>As for this latest function that I added

Here is what Tesseract does with the thresholds array:
https://github.com/tesseract-ocr/tesseract/blob/03435adca06348/src/ccstruct/coutln.cpp#L723

https://github.com/tesseract-ocr/tesseract/blob/63f446302878ad38f9b76732280cc6a9811cdc88/src/ccstruct/coutln.h#L49

If only the binary image is available it use it instead of the thresholds array. This method is less precise.
https://github.com/tesseract-ocr/tesseract/blob/03435adca063480/src/ccstruct/coutln.cpp#L821

**Comment by amitdo** [comment]
Note: This message replaces an earlier message I deleted. This one is more detailed. 

>As for this latest function that I added, I can't believe it will be useful

Here is what Tesseract does with the thresholds array:

* [`void TO_BLOCK::ComputeEdgeOffsets(Image thresholds, Image grey)`](https://github.com/tesseract-ocr/tesseract/blob/f77b1c68814b15/src/ccstruct/blobbox.cpp#L1034)
  * [`void BLOBNBOX::ComputeEdgeOffsets(Image thresholds, Image grey, BLOBNBOX_LIST *blobs)`](https://github.com/tesseract-ocr/tesseract/blob/f77b1c68814b15/src/ccstruct/blobbox.cpp#L387)
    * [`void C_BLOB::ComputeEdgeOffsets(int threshold, Image pix)`](https://github.com/tesseract-ocr/tesseract/blob/03435adca06348/src/ccstruct/stepblob.cpp#L405)
      * [`static void ComputeEdgeOffsetsOutlineList(int threshold, Image pix, C_OUTLINE_LIST *list)`](https://github.com/tesseract-ocr/tesseract/blob/03435adca0634/src/ccstruct/stepblob.cpp#L388)
        * If the thresholds array is available.  
[`void C_OUTLINE::ComputeEdgeOffsets(int threshold, Image pix)`](https://github.com/tesseract-ocr/tesseract/blob/03435adca06348/src/ccstruct/coutln.cpp#L723)
        * If only the binary image is available, Tesseract will use it instead of the thresholds array. This method is less precise.  
[`void C_OUTLINE::ComputeBinaryOffsets()`](https://github.com/tesseract-ocr/tesseract/blob/03435adca063480/src/ccstruct/coutln.cpp#L821)



See also [here](https://github.com/tesseract-ocr/tesseract/blob/63f446302878ad38f9b76732280cc6a9811cdc88/src/ccstruct/coutln.h#L49).

**Comment by DanBloomberg** [comment]
I don't know what's happening there.    But given the impreciseness of this
threshold array (any value between the gray input value and either 0 or
255, depending on if the binary pixel is 0 or 1), I can't see how it can be
useful.  And if *any value *would do, then I would suggest using the method
I mentioned to convert the binary image to 8 bpp, rather than going through
pixel-by-pixel as in the function provided.

**Comment by DanBloomberg** [comment]
I have added tiling to the normalized sauvola binarization, and also optionally
return the threshold array.
So using this, you can get a reasonable set of local threshold values that were used.

Let me know, and if that works, I'll delete the function I made 2 days ago.

**Comment by amitdo** [comment]
I tested this on w91frag.jpg using 
`pixSauvolaOnContrastNorm()`.

Tesseract need a the original image, a grayscale image, a binary image and optionally a thresholds array.

I tried these options:

1)  Use the thresholds array returned from `pixSauvolaOnContrastNorm()`.
2) Use the  thresholds array returned from pixThresholdArrayFromResult().
3) Similar to 2, but with this pre-step: convert the binary to grayscale.  `pix_binary2 = pixConvertTo8(pix_binary, false)`. 
4) `thresholds_arr = nullptr` Tesseract will use `ComputeBinaryOffsets()`instead of `ComputeEdgeOffsets()`.

All 4 variants give me 100% the same OCR output on this image.

**Comment by DanBloomberg** [comment]
and there is the trivial 5th method for making a threshold array:
     pix1 = pixInvert(NULL, pix_binary);
     pix_array = pixConvertTo8(pix1, 0);
which as mentioned above converts 0 --> 0 and 1 --> 255.

Do we agree that we don't need the function pixThresholdArrayFromResult() ?

**Comment by DanBloomberg** [comment]
Also, note that the threshold you get from the Sauvola step when you do contrast normalization first
is for the contrast normalized image, not for the original input.  It would not work if applied to the
input image.

**Comment by amitdo** [comment]
> Do we agree that we don't need the function pixThresholdArrayFromResult() ?

Yes. 

> Also, note that the threshold you get from the Sauvola step when you do contrast normalization first
> is for the contrast normalized image

I'm aware of that.

>It would not work if applied to the
> input image.

I also thought it won't work (and wondered why you don't return as out parameter the normalized grayscale), but somehow it does work - I get a useful OCR output on the mentioned image with option 1.

The image I provide to pixSauvolaOnContrastNorm() and to other Leptonica's binarization functions is grayscale (not the original color image).

**Comment by DanBloomberg** [comment]
Good, I'll remove that function.

And ... I'll set up pixSauvolaOnContrastNorm() to optionally also return the normalized intermediate image.

**Comment by amitdo** [comment]
Thanks again.
