### ISSUE TITLE
Bug reading PNM from stdin

### ISSUE THREAD

**Issue by giuliolunati** [DanBloomberg/leptonica#580]
# HOW TO REPRODUCE:

     #Create test.pnm
     cat << EOF > test.pnm
     P5
     12  1
     255
     123456789012
     EOF

     #Create test.c
     cat << EOF > test.c
     #include <leptonica/allheaders.h>
     int main(int argc, char **args) {
          PIX *p= pixReadStreamPnm(stdin);
          pixPrintStreamInfo(stderr, p, NULL);
     }
     EOF

     #Compile test:
     gcc -o test test.c -llept -ljpeg -lpng -ltiff

     #Read test.pnm from stdin
     cat test.pnm | ./test

     #The output says width=2 instead of width=12

# DIAGNOSIS:
The 1st char "1" in "12" is eaten away in `pnmSkipCommentLines()`, because `fseek(fp, -1L, SEEK_CUR)` can't work with `stdin`

**Comment by giuliolunati** [comment]
Should be fixed by #581

**Comment by DanBloomberg** [comment]
Fixed by #581
