### ISSUE TITLE
1.81.0: hash_reg test failure on armv7hl, aarch64, pcc64le, s390x

### ISSUE THREAD

**Issue by manisandro** [DanBloomberg/leptonica#582]
The `has_reg` test failes on armv7hl, aarch64, pcc64le, s390x with output as below, see https://koji.fedoraproject.org/koji/taskinfo?taskID=69492800 for the full build.

    FAIL: hash_reg
    ==============
    ////////////////////////////////////////////////
    ////////////////   hash_reg   ///////////////
    ////////////////////////////////////////////////
    leptonica-1.81.0 : libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.1.0) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.0
    Failure in hash_reg: value comparison for index 20
    difference = 47999.000000 but allowed delta = 0.000000
    Failure in hash_reg: value comparison for index 21
    difference = 47999.000000 but allowed delta = 0.000000
    Failure in hash_reg: value comparison for index 22
    difference = 16000.000000 but allowed delta = 0.000000
    Failure in hash_reg: value comparison for index 23
    difference = 79999.000000 but allowed delta = 0.000000
    Time:   1.994 sec
    ////////////////////////////////////////////////
    ////////////////   hash_reg   ///////////////
    ////////////////////////////////////////////////
    leptonica-1.81.0 : libgif 5.2.1 : libjpeg 6b (libjpeg-turbo 2.1.0) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 1.2.0
    Failure in hash_reg: value comparison for index 20
    difference = 47999.000000 but allowed delta = 0.000000
    Failure in hash_reg: value comparison for index 21
    difference = 47999.000000 but allowed delta = 0.000000
    Failure in hash_reg: value comparison for index 22
    difference = 16000.000000 but allowed delta = 0.000000
    Failure in hash_reg: value comparison for index 23
    difference = 79999.000000 but allowed delta = 0.000000
    Time:   1.990 sec
    FAIL hash_reg (exit status: 1)

**Comment by DanBloomberg** [comment]
Thank you for the report.  Those are the 4 tests of dna hashing with the hashmap.
Is this the only test that failed on these architectures?

**Comment by manisandro** [comment]
Yes

**Comment by DanBloomberg** [comment]
Are error messages turned off?  

 (default is to have all messages -- info, warning, error -- turned on)

**Comment by manisandro** [comment]
Don't believe any defaults in this regard are changed, configure call is

    ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-static --program-prefix=leptonica-

and output is

    checking build system type... x86_64-redhat-linux-gnu
    checking host system type... x86_64-redhat-linux-gnu
    checking how to print strings... printf
    checking for x86_64-redhat-linux-gnu-gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert x86_64-redhat-linux-gnu file names to x86_64-redhat-linux-gnu format... func_convert_file_noop
    checking how to convert x86_64-redhat-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for x86_64-redhat-linux-gnu-objdump... no
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for x86_64-redhat-linux-gnu-dlltool... no
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for x86_64-redhat-linux-gnu-ar... no
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for x86_64-redhat-linux-gnu-strip... no
    checking for strip... strip
    checking for x86_64-redhat-linux-gnu-ranlib... no
    checking for ranlib... ranlib
    checking for gawk... gawk
    checking command to parse /usr/bin/nm -B output from gcc object... ./configure: line 5395:  -e 's/^T .* \(.*\)$/extern int \1();/p' -e 's/^[ABCDGIRSTW][ABCDGIRSTW]* .* \(.*\)$/extern char \1;/p': No such file or directory
    ok
    checking for sysroot... no
    checking for a working dd... /usr/bin/dd
    checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
    checking for x86_64-redhat-linux-gnu-mt... no
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... no
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking whether make sets $(MAKE)... yes
    checking whether make supports the include directive... yes (GNU style)
    checking whether make supports nested variables... yes
    checking dependency style of gcc... none
    checking for gawk... (cached) gawk
    checking for x86_64-redhat-linux-gnu-gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking whether gcc understands -c and -o together... (cached) yes
    checking how to run the C preprocessor... gcc -E
    checking whether ln -s works... yes
    checking whether make sets $(MAKE)... (cached) yes
    checking for cos in -lm... yes
    checking for x86_64-redhat-linux-gnu-pkg-config... /usr/bin/x86_64-redhat-linux-gnu-pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for ZLIB... yes
    checking for LIBPNG... yes
    checking for JPEG... yes
    checking for DGifOpenFileHandle in -lgif... yes
    checking gif_lib.h usability... yes
    checking gif_lib.h presence... yes
    checking for gif_lib.h... yes
    checking giflib is at least version 5.1 (but not 5.1.2)... yes
    checking for LIBTIFF... yes
    checking for LIBWEBP... yes
    checking for LIBWEBPMUX... yes
    checking for LIBJP2K... no
    checking for opj_create_decompress in -lopenjp2... no
    checking openjpeg-2.3/openjpeg.h usability... no
    checking openjpeg-2.3/openjpeg.h presence... no
    checking for openjpeg-2.3/openjpeg.h... no
    checking openjpeg-2.2/openjpeg.h usability... no
    checking openjpeg-2.2/openjpeg.h presence... no
    checking for openjpeg-2.2/openjpeg.h... no
    checking openjpeg-2.1/openjpeg.h usability... no
    checking openjpeg-2.1/openjpeg.h presence... no
    checking for openjpeg-2.1/openjpeg.h... no
    checking openjpeg-2.0/openjpeg.h usability... no
    checking openjpeg-2.0/openjpeg.h presence... no
    checking for openjpeg-2.0/openjpeg.h... no
    checking whether to enable debugging... 
    checking whether make supports nested variables... (cached) yes
    checking for size_t... yes
    checking whether byte ordering is bigendian... no
    checking whether compiler supports -Wl,--as-needed... yes
    checking for fmemopen... yes
    checking for fstatat... yes
    checking Major version... 1
    checking Minor version... 81
    checking Point version... 0
    checking whether ln -s works... yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating src/endianness.h
    config.status: creating src/Makefile
    config.status: creating prog/Makefile
    config.status: creating lept.pc
    config.status: creating cmake/templates/LeptonicaConfig.cmake
    config.status: creating cmake/templates/LeptonicaConfig-version.cmake
    config.status: creating config_auto.h
    config.status: executing libtool commands
    config.status: executing depfiles commands

**Comment by DanBloomberg** [comment]
Thanks.  You showed the configure output for x86, which succeeded.  What does it look like for one of the failures?

**Comment by DanBloomberg** [comment]
Are the failures all on big endian processors?

**Comment by manisandro** [comment]
The one below i.e. is ppc64le. Actually no, ppc64le at least is little-endian, not sure about aarch64 and armv7hl as I believe they support both.

    ./configure --build=ppc64le-redhat-linux-gnu --host=ppc64le-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-static --program-prefix=leptonica-
    checking build system type... powerpc64le-redhat-linux-gnu
    checking host system type... powerpc64le-redhat-linux-gnu
    checking how to print strings... printf
    checking for ppc64le-redhat-linux-gnu-gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking for a sed that does not truncate output... /usr/bin/sed
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for fgrep... /usr/bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert powerpc64le-redhat-linux-gnu file names to powerpc64le-redhat-linux-gnu format... func_convert_file_noop
    checking how to convert powerpc64le-redhat-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for ppc64le-redhat-linux-gnu-objdump... no
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for ppc64le-redhat-linux-gnu-dlltool... no
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ppc64le-redhat-linux-gnu-ar... no
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for ppc64le-redhat-linux-gnu-strip... no
    checking for strip... strip
    checking for ppc64le-redhat-linux-gnu-ranlib... no
    checking for ranlib... ranlib
    checking for gawk... gawk
    checking command to parse /usr/bin/nm -B output from gcc object... ./configure: line 5395:  -e 's/^T .* \(.*\)$/extern int \1();/p' -e 's/^[ABCDGIRSTW][ABCDGIRSTW]* .* \(.*\)$/extern char \1;/p': No such file or directory
    ok
    checking for sysroot... no
    checking for a working dd... /usr/bin/dd
    checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
    checking for ppc64le-redhat-linux-gnu-mt... no
    checking for mt... no
    checking if : is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... no
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
    checking whether make sets $(MAKE)... yes
    checking whether make supports the include directive... yes (GNU style)
    checking whether make supports nested variables... yes
    checking dependency style of gcc... none
    checking for gawk... (cached) gawk
    checking for ppc64le-redhat-linux-gnu-gcc... (cached) gcc
    checking whether we are using the GNU C compiler... (cached) yes
    checking whether gcc accepts -g... (cached) yes
    checking for gcc option to accept ISO C89... (cached) none needed
    checking whether gcc understands -c and -o together... (cached) yes
    checking how to run the C preprocessor... gcc -E
    checking whether ln -s works... yes
    checking whether make sets $(MAKE)... (cached) yes
    checking for cos in -lm... yes
    checking for ppc64le-redhat-linux-gnu-pkg-config... /usr/bin/ppc64le-redhat-linux-gnu-pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for ZLIB... yes
    checking for LIBPNG... yes
    checking for JPEG... yes
    checking for DGifOpenFileHandle in -lgif... yes
    checking gif_lib.h usability... yes
    checking gif_lib.h presence... yes
    checking for gif_lib.h... yes
    checking giflib is at least version 5.1 (but not 5.1.2)... yes
    checking for LIBTIFF... yes
    checking for LIBWEBP... yes
    checking for LIBWEBPMUX... yes
    checking for LIBJP2K... no
    checking for opj_create_decompress in -lopenjp2... no
    checking openjpeg-2.3/openjpeg.h usability... no
    checking openjpeg-2.3/openjpeg.h presence... no
    checking for openjpeg-2.3/openjpeg.h... no
    checking openjpeg-2.2/openjpeg.h usability... no
    checking openjpeg-2.2/openjpeg.h presence... no
    checking for openjpeg-2.2/openjpeg.h... no
    checking openjpeg-2.1/openjpeg.h usability... no
    checking openjpeg-2.1/openjpeg.h presence... no
    checking for openjpeg-2.1/openjpeg.h... no
    checking openjpeg-2.0/openjpeg.h usability... no
    checking openjpeg-2.0/openjpeg.h presence... no
    checking for openjpeg-2.0/openjpeg.h... no
    checking whether to enable debugging... 
    checking whether make supports nested variables... (cached) yes
    checking for size_t... yes
    checking whether byte ordering is bigendian... no
    checking whether compiler supports -Wl,--as-needed... yes
    checking for fmemopen... yes
    checking for fstatat... yes
    checking Major version... 1
    checking Minor version... 81
    checking Point version... 0
    checking whether ln -s works... yes
    checking that generated files are newer than configure... done
    configure: creating ./config.status
    config.status: creating Makefile
    config.status: creating src/endianness.h
    config.status: creating src/Makefile
    config.status: creating prog/Makefile
    config.status: creating lept.pc
    config.status: creating cmake/templates/LeptonicaConfig.cmake
    config.status: creating cmake/templates/LeptonicaConfig-version.cmake
    config.status: creating config_auto.h
    config.status: executing libtool commands
    config.status: executing depfiles commands

**Comment by DanBloomberg** [comment]
I may have fixed the problem with the latest commit to head.
Please let me know if the test now succeeds.

**Comment by manisandro** [comment]
Thanks, builds and tests fine on all Fedora arches now!
