### ISSUE TITLE
*** [Makefile:666: all-recursive] Error 1

### ISSUE THREAD

**Issue by TufaaniMinhas** [DanBloomberg/leptonica#584]
Aoa, Hello all,

I am compiling GPG4win latest version on Ubuntu 20, from source code, but at make command following error occurs:

<Output written on gpg4win-compendium-de.pdf (155 pages, 3042581 bytes).
Transcript written on gpg4win-compendium-de.log.
/usr/bin/texi2dvi: pdflatex exited with bad status, quitting.
make[4]: *** [Makefile:1117: gpg4win-compendium-de.pdf] Error 1
make[4]: Leaving directory '/home/mmm/Downloads/gpg4win-3.1.16/doc/manual'
make[3]: *** [Makefile:811: all] Error 2
make[3]: Leaving directory '/home/mmm/Downloads/gpg4win-3.1.16/doc/manual'
make[2]: *** [Makefile:666: all-recursive] Error 1
make[2]: Leaving directory '/home/mmm/Downloads/gpg4win-3.1.16/doc'
make[1]: *** [Makefile:730: all-recursive] Error 1
make[1]: Leaving directory '/home/mmm/Downloads/gpg4win-3.1.16'
make: *** [Makefile:671: all] Error 2>

**Comment by amitdo** [comment]
>I am compiling GPG4win latest version on Ubuntu

This repo hosts Leptonica, an image processing library. You opened the issue in the wrong place.

**Comment by amitdo** [comment]
@DanBloomberg, @egorpugin, @stweil

Please close this issue.
