### ISSUE TITLE
invalid tiffbpl 

### ISSUE THREAD

**Issue by suman-pan** [DanBloomberg/leptonica#585]
Hello sir, 
I have tried to open some tiff images having jpeg compression with latest leptonica version 1.81.1(along with libtiff 4.2, libjpeg 9d) , got failed at pixReadFromTiffStream() due mismatch of tiffbpl and packedbpl. I have attached some of the data based on my observation ( some tifftag values, used for image dat validation), along with two sample images.
I have checked with some other application (like IrfanView) were able to process the image. 

Kindly check once

[SampleImageAndObservedData.zip](https://github.com/DanBloomberg/leptonica/files/6991272/SampleImageAndObservedData.zip)

**Comment by DanBloomberg** [comment]
Thank you for sending this bug.
The fix is straightforward, and it will be done when I can straighten out a situation with github.

**Comment by suman-pan** [comment]
Thanks for your respond.
Please Let me know about the changes, when done.

**Comment by DanBloomberg** [comment]
Try unzipping and replacing tiffio.c by this.  That should fix it.

[tiffio.c.gz](https://github.com/DanBloomberg/leptonica/files/6997205/tiffio.c.gz)

**Comment by suman-pan** [comment]
Thanks sir
The fix you have given worked properly, I have tested with a complete image set I have, it is working fine.
Thanks for your quick support.

**Comment by DanBloomberg** [comment]
glad to help.
