### ISSUE TITLE
FYI: Leptonica binary package in Debian and Ubuntu

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#594]
Dan,

On Debian and Ubuntu Leptonica is stuck in version 1.79.

FYI

**Comment by amitdo** [comment]
Pinging @jbreiden 

Any progress?

**Comment by amitdo** [comment]
@AlexanderP, maybe you can help with this task.

**Comment by jbreiden** [comment]
It's been in the back of my mind for a long time, and I'm still trying to
summon the energy.

**Comment by amitdo** [comment]
@jbreiden,

If you  won't able to find the energy for doing this task until the end of the year, consider sending a message to the Debian mailing list asking for help in maintaining Leptonica, or even announcing your retirement from Leptonica maintenance. If you go with this route, I suggest to mention Tesseract and its popularity [1][2] and the fact that it depends on Leptonica.

[1] [Overall rank (by stars) in GitHub](https://github.com/search?q=stars%3A%3E42860&2)
[2] [Rank for C++ projects in GitHub](https://github.com/search?q=stars%3A%3E42860+language%3Ac%2B%2B)

BTW, we finally released Tesseract 5.0.0 yesterday.

**Comment by jbreiden** [comment]
Leptonica 1.82 has been uploaded to Debian, it should show up on the
tracking webpage  within 24 hours.. Suggest keeping an eye on this, to see
and testing if Tesseract Debian package will need a recompile and re-upload
due to any accidental ABI compatibility issues.

https://tracker.debian.org/pkg/leptonlib

**Comment by amitdo** [comment]
@jbreiden, thank you!

**Comment by amitdo** [comment]
Hi @jbreiden,

It is now in sid but didn't move to testing.

Can you fix the issues raised in https://tracker.debian.org/pkg/leptonlib ?

What's the process to make Leptonica 1.82 also available in Ubuntu 22.04 ?

**Comment by DanBloomberg** [comment]
@jbreiden 

The two abi-compliance checker warnings are due README.html and version-notes.html grabbing data from the Creative Commons web site.

The suggestion is to copy to a local source, with some caveats.  Do you know how to do this properly?

**Comment by jbreiden** [comment]
That's interesting.

No release critical bugs have been filed  against leptonica as far as I can
tell.  The main complaint appears to  be a missing build for 32-bit Intel
architectures.  So far I'm not sure what would cause that.

There's also complaint related to multi-arch which I can probably do
something about.

If I remember correctly, Ubuntu will pull from Debian unstable.  So there
is a good chance that even if we do nothing, this will be part of the next
Ubuntu release.  That said, we do want this to promote to testing.

I'm not currently near a relevant computer but should be tomorrow. Thank
you for the heads up.

**Comment by amitdo** [comment]
The issue with the i386 build is a failed test.

```
///////////////   hash_reg   ///////////////
////////////////////////////////////////////////
leptonica-1.82.0 : libgif 5.1.9 : libjpeg 6b (libjpeg-turbo 2.1.2) : libpng 1.6.37 : libtiff 4.3.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.4.0
Failure in hash_reg: value comparison for index 10
difference = 1.000000 but allowed delta = 0.000000
Failure in hash_reg: value comparison for index 14
difference = 1.000000 but allowed delta = 0.000000
Failure in hash_reg: value comparison for index 18
difference = 1.000000 but allowed delta = 0.000000
Failure in hash_reg: value comparison for index 22
difference = 1.000000 but allowed delta = 0.000000
Time:   2.179 sec
FAIL: hash_reg
```

**Comment by amitdo** [comment]
[Fix flaky hash_reg test on i686](https://github.com/DanBloomberg/leptonica/commit/ea2bb8c9cf61d3eba258)

**Comment by DanBloomberg** [comment]
Correct: this was fixed on 14 Nov 2021.

Another simple fix to release 1.82.0 is to remove that test from prog/alltests_reg.c

**Comment by jbreiden** [comment]
I've uploaded Debian package 1.82.0-3 with the regression test fix, look
for it tomorrow in the usual location.

https://tracker.debian.org/pkg/leptonlib

Dan, you are referring to one of the many complaints from Debian's lint
system "lintian" complaining about a privacy violation. This is a very
minor issue and not blocking anything. What's going on is the
documentation, shipped with the package, includes an image from another
website. The image is a Creative Commons logo. Which means Lawrence Lessig
(or whoever has access to the logs from the Creative Commons website)
could know when someone is reading the Leptonica documentation. To get rid
of that warning, you would include the logo with Leptonica and link to it
locally, instead of using the one from the Creative Commons website. I
never bothered to mention this over the years because in the grand scheme
of things, I think it is unimportant. You are welcome to address it if you
wish.

**Comment by DanBloomberg** [comment]
Thanks, Jeff.  Your patch should allow the i386 build to go forward.

I'm happy to let Creative Commons continue to handle their logo image  :-)

**Comment by jbreiden** [comment]
- Migration status for leptonlib (1.79.0-1.1 to 1.82.0-3): BLOCKED:
   Rejected/violates migration policy/introduces a regression


I am not sure what broke.

**Comment by amitdo** [comment]
It looks better now,  the BLOCKED warning disappeared.

>Issues preventing migration:
∙ ∙ Too young, only 4 of 5 days old

Let's see if we'll move to testing tomorrow.

**Comment by amitdo** [comment]
https://tracker.debian.org/pkg/leptonlib

>news
>
>  [2022-01-07] leptonlib 1.82.0-3 MIGRATED to testing (Debian testing watch)

 @jbreiden, thanks again!

**Comment by amitdo** [comment]
Leptonica 1.82 is also available for Ubuntu Jammy 22.04:
https://packages.ubuntu.com/jammy/libleptonica-dev

**Comment by RobinFrcd** [comment]
Hi all,
leptonica is currently stuck on [1.79 on debian bullseye](https://packages.debian.org/bullseye/libleptonica-dev), the current stable release. Would it be possible to push the latest version for bullseye too ?

Thanks :pray:

**Comment by DanBloomberg** [comment]
@jbreiden 

1.79 is from Jan 2020.  What is the significance of it being 'stuck' on Debian with that release?

**Comment by jbreiden** [comment]
One web page says it got stuck due to a missing build on i386 architecture,
but this page says all is well for i386. Getting stuck is bad, because it
means the vast majority of people will not get the new version. I'm not
sure at the moment what to do about it.

https://packages.qa.debian.org/l/leptonlib.html
https://buildd.debian.org/status/package.php?p=leptonlib

**Comment by amitdo** [comment]
Everything is OK.

1.82.0-**2** was **BLOCKED**
 
but later version had had no issues:
1.82.0-**3** **MIGRATED** to testing

Ubuntu 22.04 was able to pick 1.82.

@RobinFrcd is talking about something else. He wants 1.82 to be backported to Debian stable.

**Comment by amitdo** [comment]
Half off-topic: @jbreiden, any chance for moving Tesseract from from 4.1 to 5.2 in Debian?

https://github.com/tesseract-ocr/tesseract/issues/3673#issuecomment-1048203258

**Comment by stweil** [comment]
For Debian bullseye it would be be better to simply apply commit 480f5e74c24fdc2003c42a4e15d1f24c9e6ea469 to get a fix for the FP exception.

**Comment by jbreiden** [comment]
Debian has two different tracking sites, and they disagree with each other.
I think one is just broken and stale.  Looking at the functioning one, both
Leptonica and Tesseract have modern versions in Debian Testing, which is
what we want. Other Debian colleagues have helped in this, and I think
overall things are in relatively good shape.

https://tracker.debian.org/pkg/tesseract

**Comment by jbreiden** [comment]
You are correct, Tesseract is still on 4.0 for buster
<https://packages.debian.org/fr/buster/tesseract-ocr> [a.k.a. Debian 10]
and 4.1 for bullseye
<https://packages.debian.org/fr/bullseye/tesseract-ocr> [a.k.a
Debian 11].  And it will remain that way forever; that is how Debian works.

Most importantly, Tesseract is at 5.1 in bookworm
<https://packages.debian.org/fr/bookworm/tesseract-ocr> [a.k.a. the
upcoming Debian 12 release] Which means the software releases are flowing
as expected and nothing is jammed up.

**Comment by amitdo** [comment]
>And it will remain that way forever; that is how Debian works.

In the Debian world, there is the [backports](https://backports.debian.org/) repo as a way to introduce new versions of software. This is only relevant to the current Debian stable and not to the 'old stable'.

It's a problem for us that we still get a lot of issues reports from people using Tesseract 4.x.
