### ISSUE TITLE
pixReadMemTiff returns other resolution than readHeaderMemTiff

### ISSUE THREAD

**Issue by maxfurioso** [DanBloomberg/leptonica#601]
I believe I have found an issue here. With some tiff files it happens that pixReadMemTiff() does not provide a resolution, xres and yres are both 0. But when I invoke readHeaderMemTiff() on the same file I get a resolution. 

I have added a screenshot from a debug state and a sample tiff file (tiff cannot be added directly, so I put it into a zip).
Do you have any idea?

![leptonica](https://user-images.githubusercontent.com/98384787/150945173-7490dc2a-2643-40bd-a942-0add2bb39fe3.png)
[zero.zip](https://github.com/DanBloomberg/leptonica/files/7932858/zero.zip)

**Comment by DanBloomberg** [comment]
You are correct!

readHeaderMemTiff() returns a default resolution of 300 if the resolution is not set in the tiff file.
But pixReadFromTiffStream() calls getTiffStreamResolution(), which returns 0 if not set in the file.

I believe they should both return 0 if the resolution is not known, and will modify tiffReadHeaderTiff() to do that.

**Comment by maxfurioso** [comment]
I agree. In the current situation, I find this confusing.

Besides that, I am wondering if it's possible to calculate the resolution. When I open this file with an image editor (for instance Paint.NET), it shows me a resolution of 96. So, I'm not sure if this is also a default value or if they do a trick.

**Comment by DanBloomberg** [comment]
That would likely be the screen resolution; i.e., the resolution of the display device.

The resolution in the file should be that of the file image relative to the 'object' (which if it were paper would be the scan resolution).  So if this were a document image, you could guess the size of the page being viewed and that would determine the resolution.

But if the original were a photograph of a natural scene, the resolution would depend on the number of pixels in the camera sensor and the physical size of the scene being photographed, which is something that might be interesting for a satellite image but not in general.

So the answer is application dependent.  These file-to-raster reading functions should not be making assumptions about the application.

**Comment by maxfurioso** [comment]
You made a good point. Thanks for sharing your thoughts.
