### ISSUE TITLE
Can't use sw

### ISSUE THREAD

**Issue by abcd3435** [DanBloomberg/leptonica#602]
I am trying to install this thing software network in order to compile, but it just gives errors over and over about missing api-ms-win-core dll's. I tried various versions, but still if not one, then another ws2_32 dll is missing, what to do then? Is thins sw thing only for windows 10?

**Comment by DanBloomberg** [comment]
@abcd3435 
We never responded to your query from early this year.
If you are still interesting in this, please explain in detail what you did, showing output.

**Comment by amitdo** [comment]
No reply from the OP.

Dan, please close this issue.
