### ISSUE TITLE
Leptonica reports IO errors

### ISSUE THREAD

**Issue by CSBVision** [DanBloomberg/leptonica#606]
Hello,

we are using Leptonica in combination with Tesseract as part of OpenCV. We compiled Leptonica and Tesseract as static libraries using Visual Studio that are linked inside OpenCV such that there is no explicit dependency on either Leptonica or Tesseract. In general everything works fine, however Leptonica reports the following errors:
```
Error in pixReadMemTiff: function not present
Error in pixReadMem: function not present
Error in pixaGenerateFontFromString: pix not made
Error in bmfCreate: font pixa not made
```
To my understanding these errors occur because Leptonica was compiled without libtiff, libpng and libjpeg to support the respective image files. Still, Leptonica and Tesseract work fine. I suspect the third-party libraries are necessary for file IO using Leptonica, however this is not needed and handled directly by OpenCV here. Leptonica/Tesseract are only used as libraries for OpenCV, not for any other application that relies on Leptonica for image IO.

If this is correct, these errors are irritating and misleading. So is there any option to disable them?

Checking Leptonica's source code leads to `environ.h` where defining `NO_CONSOLE_IO` to our understanding should disable these errors. Still, is this the best option or won't this also disable errors that should be kept?

Thanks for any support!

**Comment by stweil** [comment]
Please use the correct name "Tesseract". I suggest building Leptonica with `libtiff`. That should fix the error messages.

**Comment by CSBVision** [comment]
Thanks for pointing out (typo repeated by auto completion fixed, see edit). But for explained reasoning, I do not want any tiff/IO functionality in Leptonica - or is there any use of `libtiff` in Leptonica besides IO of tiff files?
If not and using Leptonica only as a sub-library of OpenCV that offers all IO functionality (including libtiff as a static lib), linking it against libtiff makes no real sense to me as it only complicates the compilation (i.e. configuring the dependencies) and extends the file size without any real reason.

**Comment by stweil** [comment]
If you already have libtiff as a static lib for OpenCV, using that for Leptonica, too, would not add much bytes to your binary. The error messages indicate that the related code is called, so either provide the necessary library or change the code for your special needs (remove message or remove caller).

**Comment by CSBVision** [comment]
Unluckily, it's not that simply. OpenCV builds libtiff as a static library if it does not find a system-wide installation. This is usually the case on Windows systems (on Linux systems with system-wide installations of dependencies, it's a completely different story; here also Leptonica and Tesseract can be used as system-wide shared libraries). To configure OpenCV with Tesseract support, at first both, Leptonica and Tesseract have to be compiled. Once they are correctly configured, you can configure OpenCV's CMake configuration to find the Leptonica and Tesseract headers and libraries. Only thereafter, OpenCV will be compiled and thus triggers the compilation of libtiff.

A solution would include to manually compile libtiff and configure it for Leptonica first. Still, I don't see any real benefit if Leptonica is not used for any image IO. But since your mentioning that related code might be called. Do you have any idea which libtiff code might be executed or required even though no image IO takes place?

**Comment by stweil** [comment]
No, but it should be easy to run your code in a debugger with a breakpoint on the error message. That should answer the question.

**Comment by CSBVision** [comment]
OK debugging is also not that easy as it requires the compilation of OpenCV debug binaries. So maybe an easier solution is to suppress the errors?

**Comment by DanBloomberg** [comment]
You ask if there is any use of libtiff in leptonica besides IO of tiff files.  Tesseract uses libtiff and leptonica to generate pdf files.

**Comment by CSBVision** [comment]
Thanks for this information! So if Leptonica and Tesseract are only used as libraries without IO, these should not be required at all. To the best of my knowledge, OpenCV only receives the detected text, but no image or PDF files are written. So is it the best option to set the define `NO_CONSOLE_IO` during compilation (i.e. adding `/DNO_CONSOLE_IO` to `CMAKE_CXX_FLAGS`)?

By the way: Why does Leptonica even report these errors when no IO takes place?

**Comment by DanBloomberg** [comment]
leptonica is instrumented to let you know, for many functions, if the function fails in some way.  If you don't supply libitff and a call is made that would require the library, unless you forbid output on error, an error message will be produced.  For I/O, if a library is missing, stubs for the functions are compiled instead, and these stubs generate an error message to stderr (unless redirected).

As you saw, leptonica gives you many ways to control the output to stderr, including redirecting the messages using custom error handlers.  If you don't want to see those messages, you will need to use one of those methods.  See environ.h and utils1.c.

**Comment by CSBVision** [comment]
Thanks for this clarification, then I will simply set this flag as mentioned before.
But can you think of any reason why there are these IO errors even without any IO (only API calls from OpenCV)? I don't really understand this... but as long everything works, I'm fine with that.

**Comment by DanBloomberg** [comment]
You are calling a function in Tesseract that requires libtiff.  If libtiff is not available, you will get the "function not present" message.

**Comment by CSBVision** [comment]
Yes of course, I agree with that. Still, the errors are already present by initializing Tesseract.
Initializing Tesseract using OpenCV calls `TessBaseAPI.Init()`, see [OpenCV initialization](https://github.com/opencv/opencv_contrib/blob/4.x/modules/text/src/ocr_tesseract.cpp#L147)
The respective code should only initialize the Tesseract library, I don't see any IO happening here, see [Tesseract Initialization](https://github.com/tesseract-ocr/tesseract/blob/main/src/api/baseapi.cpp#L378)
By inspecting the code, it's rather hard to find out where a libtiff function is used. I suspect it is also just an initialization step that prepares libtiff, even though the respective parts are not used by OpenCV as OCR thereafter works fine.
In case you might know whether this might be true or where this libtiff call might come from, I will have a closer look on it. If not, I'm fine with simply setting the `NO_CONSOLE_IO` flag as mentioned before.

**Comment by DanBloomberg** [comment]
I'm fine with your work-around.  Thank you for bringing this up and investigating it.

Dan

**Comment by CSBVision** [comment]
Alright, thanks for your time 👍

**Comment by stweil** [comment]
@CSBVision, you could try building Tesseract with `TESSERACT_DISABLE_DEBUG_FONTS` defined. Then the code no longer calls `bmfCreate` which triggers the TIFF related warnings.
