### ISSUE TITLE
How to build and install leptonicsa in Ubuntu from source?

### ISSUE THREAD

**Issue by shenw000** [DanBloomberg/leptonica#620]
I am new to the leptonica and need to build and install leptonica on Ubuntu 16.04. I have git cloned the leptonica source repo to my computer. But can't find the build and install Could you share with me the build and install instruction for leptonica on linux?

Thx!
shenw000

**Comment by DanBloomberg** [comment]
I suggest that you use one of the releases; say, 1.82.
They're set up for the usual "configure, make, make install" formula, that doesn't require installation of autotools.
See the README

If you want to build from the github master, you can do it easily either with autotools or cmake.
Again, the procedures are explained in the README.

**Comment by shenw000** [comment]
Thank you, DanBloomberg! I have successfully installed leptonica-1.82.0. After that, I run the command "make check",, and it shows that 117 pass and 25 skip. Does that look right?

**Comment by DanBloomberg** [comment]
Seems OK.  Which of these libraries do you have on your computer:
     jpeg, tiff, png

**Comment by shenw000** [comment]
OK, thanks! I have jpeg, tiff, and png plus some other image libraries on my computer.

**Comment by DanBloomberg** [comment]
Perhaps it's not finding one of those 3 libraries.
What is the first line of output when you run a function like numa3_reg?

**Comment by amitdo** [comment]
Dan, there was no reply to your last question.

I suggest to close this issue.
