### ISSUE TITLE
34 tests fail in "make check" after successful build

### ISSUE THREAD

**Issue by 36PopTarts** [DanBloomberg/leptonica#625]
### Environment

* **Commit Number**: [c59d31a](https://github.com/DanBloomberg/leptonica/commit/c59d31a2c6fb146594b8ece03d49af56153bc69f)
* **Platform**: `Linux hostname 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

### Current Behavior:

Using the autoconf build method, Leptonica succeeds building but fails to pass all of its tests on `make check` on only one of my VMs, which as far as I can tell is not different from any of the others which I have built it on and where all tests passed or skipped. It is an Ubuntu 20.04 VM. I wish I knew how to package builds on Linux myself so I could avoid this problem but here we are. I have attached the output from test-suite.log as well as the stderr and stdout from building Leptonica and running `make check`.
[test-suite.log](https://github.com/DanBloomberg/leptonica/files/8863039/test-suite.log)
[install.log](https://github.com/DanBloomberg/leptonica/files/8863040/install.log)

**Comment by 36PopTarts** [comment]
Update: I have tried building Tesseract on this VM on a whim, and it seems to work without issue. It seems the problem is specifically with the tests themselves and not Leptonica building on that VM.

**Comment by stweil** [comment]
`make check` is currently not robust and tries to run tests which should be skipped, so please make sure that for example all image formats are supported. The output indicates that PNG support is missing.

**Comment by 36PopTarts** [comment]
OK, I really thought I had included `sudo apt install libpng-dev` in my build script, but apparently I had not. That VM in particular didn't have it even though the others did. My apologies.
