### ISSUE TITLE
Animated GIF

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#626]
Hi Dan,

https://github.com/tesseract-ocr/tesseract/issues/3369#issuecomment-809680986

>I attempted to implement writing of gif anim about 4 years ago, but failed.
I left questions for the gif inventor/maintainer, but he did not engage. So I Implemented writing
of webp anim instead.
>
>Never tried reading animated gif into a pixa.
>
>And if someone shows me how to tell if a gif file is an animated gif, I'll use it in the gif reader to skip ("not supported") reading.
I believe that would mostly solve this issue.

Maybe this example from webp can help:

https://github.com/webmproject/libwebp/blob/36a6eea3bc2871c7f0166193a6fa42241af4a464/examples/gif2webp.c#L275

**Comment by amitdo** [comment]
I closed this issue because I got no feedback for 3 weeks.

**Comment by amitdo** [comment]
Hi Dan,

It turns out you found the way to detect animated gif back in May 2021.

https://github.com/DanBloomberg/leptonica/commit/9d6265f796b7692e93d6bdabde9f35932f758588.patch

https://github.com/DanBloomberg/leptonica/blob/6551f38d71e18f8647fd7f5ea9ed15890dc2289f/src/gifio.c#L242-L247

Leptonica warns the user if the given gif is animered gif, and process the first page only.

Maybe a better way to handle animated gif is to reject the whole gif file with a proper error message?

**Comment by DanBloomberg** [comment]
I agree.   Thanks Amit.
The change has been submitted.

**Comment by amitdo** [comment]
https://github.com/DanBloomberg/leptonica/commit/1a4ba7eebef8750912335cbab53080f9c1539e2d

Thanks!
