### ISSUE TITLE
Leptonica has any ECCN(Export Control Certification Number)

### ISSUE THREAD

**Issue by shq251** [DanBloomberg/leptonica#632]
Thank you for your support.
Kindly share the below information.
Doe Leptonica has any ECCN(Export Control Certification Number)  OR it does not require any ECCN as it is a open source?
Quick reply will be helpful for us as we are planning to use  it in our produce and release it.
Thanks in advance.

**Comment by stweil** [comment]
I am not aware of any Open Source software which provides a ECCN. Maybe this article helps: https://www.linuxfoundation.org/tools/understanding-us-export-controls-with-open-source-projects/.

**Comment by DanBloomberg** [comment]
@shq251 can reopen if the question is not answered.
