### ISSUE TITLE
leptonica malloc error coredump

### ISSUE THREAD

**Issue by wuyang-dl** [DanBloomberg/leptonica#633]
hi, here is a malloc error coredump.

blend.c:1786   
    pixd = pixCopy(NULL, pix1);  --------- malloc error, need check pixd is null or not.

if pixd is null, blend.c:1818( dval32 = *(lined + j + x);   cause coredump)

fix:
    pixd = pixCopy(NULL, pix1);
    pixDestroy(&pix1);
    if (!pixd)
        return (PIX *)ERROR_PTR("pixd not defined", procName, NULL);

![image](https://user-images.githubusercontent.com/55725716/181692856-452c70fb-d604-4651-ba5b-ae777261d61e.png)

**Comment by DanBloomberg** [comment]
If pix1 is valid, making a copy should succeed unless it is too large.

What are the dimensions of pix1?

Dan

**Comment by DanBloomberg** [comment]
Thank you for reporting this.  I put in a check as you suggested to make sure that pixd is valid.
