### ISSUE TITLE
Find the position of one graph in another graph

### ISSUE THREAD

**Issue by jueqing1015** [DanBloomberg/leptonica#634]
![aaa](https://user-images.githubusercontent.com/65677359/181726627-41c9e088-24e1-48cc-a1c6-2a7ad7acf98d.jpg)
![bbb](https://user-images.githubusercontent.com/65677359/181726634-93ab7494-9f72-4b7f-bc87-dae860f6ddf5.jpg)
For example, I want to use the above two pictures to find the position of the small picture in the large picture. How should I operate

**Comment by DanBloomberg** [comment]
This is fairly hard to do in a general way, if you have to include arbitrary rotation.

Without significant rotation, it is straightforward.  See prog/livre_hmt for how to produce a hit-miss template for locating your pattern in another image.

**Comment by jueqing1015** [comment]
> 如果您必须包含任意旋转，这通常很难做到。
> 
> 没有明显的旋转，它很简单。请参阅 prog/livre_hmt 以了解如何生成命中未命中模板以在另一个图像中定位您的模式。

At the beginning of learning this control, could you please make a small example, excluding rotation
thank you very much indeed

**Comment by DanBloomberg** [comment]
Make the hit-miss sel (selhm) in a way similar to what is done in prog/livre_htm.c.

Then do an HMT of your large image, using that structuring element (selhm), and test if there are any ON pixels with
    pixZero(pix, &empty)     [from pix3.c]

If the pattern is found in your larger image, you should get a tight cluster of hits (on pixels) in the HMT at the center location of the sel where the matches occur.  To do the HMT, you can use pixHMT() in morph.c.   
For example,
     pixHMT(NULL, pixbig, selhm);
where selhm is the hit-miss structuring element you generated from your small pattern.

**Comment by jueqing1015** [comment]
> 以类似于 prog/livre_htm.c 中所做的方式制作命中未命中 sel (selhm)。
> 
> 然后使用该结构元素 (selhm) 对大图像进行 HMT，并测试是否有任何 ON 像素与 pixZero(pix, &empty) [来自 pix3.c]
> 
> 如果在您的较大图像中找到该模式，您应该在 HMT 中匹配发生的 sel 的中心位置获得一个紧密的命中簇（在像素上）。要执行 HMT，您可以在 morph.c 中使用 pixHMT()。 例如 pixHMT(NULL, pixbig, selhm); 其中 selhm 是您从小模式生成的命中未命中结构元素。
I feel very much about your patient answer. I have made the basic effect according to your guidance, but now I need to cut down the area found from the large picture. Which part should x, y, width and height be obtained from

**Comment by jueqing1015** [comment]
> Make the hit-miss sel (selhm) in a way similar to what is done in prog/livre_htm.c.
> 
> Then do an HMT of your large image, using that structuring element (selhm), and test if there are any ON pixels with pixZero(pix, &empty) [from pix3.c]
> 
> If the pattern is found in your larger image, you should get a tight cluster of hits (on pixels) in the HMT at the center location of the sel where the matches occur. To do the HMT, you can use pixHMT() in morph.c. For example, pixHMT(NULL, pixbig, selhm); where selhm is the hit-miss structuring element you generated from your small pattern.

I feel very much about your patient answer. I have made the basic effect according to your guidance, but now I need to cut down the area found from the large picture. Which part should x, y, width and height be obtained from

**Comment by DanBloomberg** [comment]
When you do the HMT, using the selhm created from your pattern (the smaller image), you do it on the entire large image.  The result will be a 1 bpp image the same size as your large image, with foreground pixels at the center location of your selhm in all the places where the selhm matches your large image.

By "matches your large image", I mean that every hit and every miss in selhm has to be matched by hits and misses in the large image.

**Comment by jueqing1015** [comment]
> When you do the HMT, using the selhm created from your pattern (the smaller image), you do it on the entire large image. The result will be a 1 bpp image the same size as your large image, with foreground pixels at the center location of your selhm in all the places where the selhm matches your large image.
> 
> By "matches your large image", I mean that every hit and every miss in selhm has to be matched by hits and misses in the large image.

Sorry, my description is wrong. I need to cut the area I found

**Comment by DanBloomberg** [comment]
You need to remove the foreground pixels of the matched pattern from the large image?

If so, you can use pixRasterop():
   pixRasterop(pix, x, y, w, h, PIX_CLR, NULL, 0, 0);
where x,y is the upper-left corner of the pattern where it matches, and w,h are the pattern dimensions.
If the pattern matches at x1, y1, which is the center of the pattern where it matches, then
     x = x1 - w/2
     y = y1 - h/2
