### ISSUE TITLE
I want to perform several operations on images. What interfaces do I need to use? Thank you very much!

### ISSUE THREAD

**Issue by jueqing1015** [DanBloomberg/leptonica#637]
I want to perform several operations on images. What interfaces do I need to use? Thank you very much!

1. Fills the rectangular area specified by the image with color

2. Overlap one graph to another somewhere

3. The image is horizontally and vertically mirrored

**Comment by DanBloomberg** [comment]
1.  How does the image "specify" a rectangular area.
2.  What does that mean?
3. Not sure what you want.  See: pixMirroredTiling(), pixAddMirroredBorder()

**Comment by jueqing1015** [comment]
> 1. How does the image "specify" a rectangular area.
> 2. What does that mean?
> 3. Not sure what you want.  See: pixMirroredTiling(), pixAddMirroredBorder()
@DanBloomberg 
As shown in the following figure: the area in the figure is filled with red. How should this effect be operated?
![000](https://user-images.githubusercontent.com/65677359/184096110-3ef3310b-c6ac-4964-a27e-e82add42e559.jpg)


As shown in the following figure: how to merge the above two figures into the following one?
![00000](https://user-images.githubusercontent.com/65677359/184096128-4979a605-e19a-4633-98ba-cbb5a1469e06.jpg)

**Comment by DanBloomberg** [comment]
(1) If you specify a region as a Box, for 32 bpp use pixSetInRectArbitrary(pix, box, val), where val is a 32-bit RGB pixel.
See pixPaintBoxa() for a more general approach.

(2) pixRasterop() is your friend for putting arbitrary rectangular image regions on other images.

**Comment by DanBloomberg** [comment]
Issue appears to be resolved
