### ISSUE TITLE
Website states that Leptonica's license is CC BY 3.0 US, but it's actually the 2-clause BSD license?

### ISSUE THREAD

**Issue by mhmdanas** [DanBloomberg/leptonica#638]
If you scroll to the bottom of http://leptonica.org/ (or any other page of the website), it is stated that:

> Leptonica by [Dan Bloomberg](http://leptonica.org/www.leptonica.org) is licensed under a [Creative Commons Attribution 3.0 United States License](http://creativecommons.org/licenses/by/3.0/us/).

However, both http://leptonica.org/about-the-license.html (ignoring the footer) and https://github.com/DanBloomberg/leptonica/blob/master/leptonica-license.txt state that Leptonica is under the 2-clause BSD license.

**Comment by DanBloomberg** [comment]
I can see how this is confusing.

I applied the Creative Commons copyright to all the web pages of leptonica.org.
The source code is licensed under 2-clause BSD, which is specific for source code.

Does that help?

**Comment by mhmdanas** [comment]
Yeah, that makes sense. Could the statement prhaps be modified to clarift that CC BY 3.0 US is the license of the _website's contents_?

**Comment by DanBloomberg** [comment]
Probably even better, I should just remove the CC attributions on the web site pages.

**Comment by mhmdanas** [comment]
Does that mean the website would no longer be under that license?

Personally, I think just modifying the footers is sufficient. The footer could read something like "unless otherwise noted, the content of this page is licensed under the [CC BY 3.0 US](http://creativecommons.org/licenses/by/3.0/us/)." (I am not a lawyer though)

**Comment by stweil** [comment]
What about "This content is licensed by Dan Bloomberg under a [Creative Commons Attribution 3.0 United States License](http://creativecommons.org/licenses/by/3.0/us/)"?

Or "This documentation is licensed by Dan Bloomberg under a [Creative Commons Attribution 3.0 United States License](http://creativecommons.org/licenses/by/3.0/us/)"?

**Comment by mhmdanas** [comment]
The first one looks good to me, I would just use "this page's content" instead of "this content" for clarity.

**Comment by DanBloomberg** [comment]
Yes, that's better.  I'll go with "This documentation is ...".
Thanks.

**Comment by DanBloomberg** [comment]
Done.  Thanks for the suggestions.

**Comment by mhmdanas** [comment]
@DanBloomberg just a heads-up, you seem to have forgotten to update http://leptonica.org.

**Comment by DanBloomberg** [comment]
try shift-reload

**Comment by mhmdanas** [comment]
Haha, that worked, guess my browser cache was at fault. Thank you.
