### ISSUE TITLE
Outdated comments about fmemopen() and open_memstream()

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#641]
`fmemopen()` and `open_memstream(`) are supported on macOS (>10.12) and the BSDs.

https://github.com/DanBloomberg/leptonica/blob/21c6562346b449f9247d073203ff92bf476f9227/src/makefile.static#L48-L52

https://github.com/DanBloomberg/leptonica/blob/edcf1abe62bc7c0250f426e9beb936e261160aca/src/environ.h#L176-L183

**Comment by DanBloomberg** [comment]
Thanks Amit -- I'll fix this on Tuesday.

**Comment by stweil** [comment]
According to the documentation on MacOS, both functions conform to IEEE Std 1003.1-2008 (“POSIX.1”). So any OS which supports POSIX.1 should provide them.

**Comment by DanBloomberg** [comment]
Fixed.  Thank you for clarifying the use of these functions.
