### ISSUE TITLE
When trying to load TIFF images with pixRead it always fails

### ISSUE THREAD

**Issue by Sicos1977** [DanBloomberg/leptonica#657]
I build leptonica 1.83 with tiff support

![image](https://user-images.githubusercontent.com/6692947/210133209-ef80239f-0dbb-4231-bdc1-47f121e1958a.png)

But when trying to read a tiff with pixRead it always returns a null pointer (I'm using leptonica from a C# .NET project). When using version 1.82 it works without any problems.

![image](https://user-images.githubusercontent.com/6692947/210133267-066d9a79-6d65-4d23-8c08-0134dda9a6bc.png)

**Comment by zdenop** [comment]
Can you share also tiff file?

**Comment by Sicos1977** [comment]
You can use any of these tiff files, they all have the same problem --> https://github.com/Sicos1977/TesseractOCR/tree/master/TesseractOCR.Tests/Data/Conversion

**Comment by zdenop** [comment]
C code works for me without a problem:

```C
#include <leptonica/allheaders.h>

int main(int argc, char **argv) {
  char *filein;
  PIX *pixs;
  l_ok ret;
  l_int32  LeptMsgSeverity = 1;

  if (argc != 2)
     return fprintf(stderr," Syntax:  %s filein", argv[0]);

  filein = argv[1];

  if ((pixs = pixRead(filein)) == NULL) {
    ERROR_INT("pix not made", __func__, 1);
  } else {
    fprintf(stderr, "Leptonica loaded: %s\n", filein);
  }
 
  ret = pixWrite("pixs.png", pixs, IFF_PNG);
  if (ret > 0)
    ERROR_INT("ret of pixWrite: ", __func__, ret);
  pixDestroy(&pixs);
  return ret;
}
```

compiled with (MSVC 2019, Windows 10 64bit; libtiff 4.4.0):
```sh
cl test_tiff.c -I..\include ..\lib\leptonica-1.83.0.lib
```

e.g. `test_tiff.exe photo_palette_4bpp.tif` creates the correct png output...
Seems like a problem with wrapping leptonica in C# .NET...

**Comment by Sicos1977** [comment]
Weird because 1.82 works without any problems. Is there a way to see if the tif library is compiled into the output file?

**Comment by zdenop** [comment]
Well, you should see an error message (in the console/terminal) if you try to open unsupported image format.
Also, check the output of leptonica function `getImagelibVersions`.

You can also try to open an image with a format that does not need external lib (pbn, ppn, bmp) and save it as tiff...

**Comment by vsolominov** [comment]
Images are saved in `tiff` format correctly.
Versions of built-in libraries in `leptonica-1.83.0`:
- libgif 5.2.1
- libjpeg 6b (libjpeg-turbo 2.0.6)
- libpng 1.6.37
- libtiff 4.3.0
- zlib 1.2.11

I think this is due to the fact that the image format (e. g. [photo_rgb_32bpp.tif](https://github.com/Sicos1977/TesseractOCR/blob/master/TesseractOCR.Tests/Data/Conversion/photo_rgb_32bpp.tif) file) is not `tiff` but `bitmap`:

![image](https://user-images.githubusercontent.com/116663980/210151206-cdb4dd59-e3ce-4540-ade8-5a0ddaf4a8a6.png)

Looking at the commit [d4ab740f6c0d40fe12ddc15c9ceba1f614711665](https://github.com/DanBloomberg/leptonica/commit/d4ab740f6c0d40fe12ddc15c9ceba1f614711665) Leptonica does not support 32 bpp images.

**Comment by Sicos1977** [comment]
I check one of the filex with a hex editor and that seems like a tiff to me... as far as I know the first few bytes of a tiff image are always II

![image](https://user-images.githubusercontent.com/6692947/210151639-52d53421-fe4d-4341-9025-0eeb2b1f2e5f.png)

**Comment by vsolominov** [comment]
Yes, this is true for all files except what I wrote above ([photo_rgb_32bpp.tif](https://github.com/Sicos1977/TesseractOCR/blob/master/TesseractOCR.Tests/Data/Conversion/photo_rgb_32bpp.tif))

**Comment by zdenop** [comment]
When I run `>test_tiff.exe photo_rgb_32bpp.tif` I see this message:

```sh
Error in pixReadMemBmp: 32 bpp rgba input data is not supported
Error in pixReadStream: bmp: no pix returned
Error in pixRead: pix not read
Error in main: pix not made
Error in pixWrite: pix not defined

```

**Comment by Sicos1977** [comment]
The only thing I find weird is that all files seem to work when using version 1.82

**Comment by zdenop** [comment]
1. As already mentioned by vsolominov [photo_rgb_32bpp.tif](https://github.com/Sicos1977/TesseractOCR/blob/master/TesseractOCR.Tests/Data/Conversion/photo_rgb_32bpp.tif) is BMP file with wrong extensions. The same message you can get with [IrfanView ](https://www.irfanview.com/)
2. leptonica 1.82 reads it - but when you run my tests code, the output in PNG does not have correct colors 
3. leptonica 1.83 refuse to load it - reason is explain in this commit https://github.com/DanBloomberg/leptonica/commit/d4ab740f6c0d40fe12ddc15c9ceba1f614711665

**Comment by Sicos1977** [comment]
> 1. As already mentioned by vsolominov [photo_rgb_32bpp.tif](https://github.com/Sicos1977/TesseractOCR/blob/master/TesseractOCR.Tests/Data/Conversion/photo_rgb_32bpp.tif) is BMP file with wrong extensions. The same message you can get with [IrfanView ](https://www.irfanview.com/)
> 2. leptonica 1.82 reads it - but when you run my tests code, the output in PNG does not have correct colors
> 3. leptonica 1.83 refuse to load it - reason is explain in this commit [d4ab740](https://github.com/DanBloomberg/leptonica/commit/d4ab740f6c0d40fe12ddc15c9ceba1f614711665)

Okay, thinks missed that one.
