### ISSUE TITLE
Download old realeases

### ISSUE THREAD

**Issue by PasaOpasen** [DanBloomberg/leptonica#658]
Hello! I need a file with name `liblept-5.dll` which should be a part of leptonica 1.68, as I think. But I cannot find this old release version. Is there any old files storage with old leptonica versions?

**Comment by zdenop** [comment]
You can access older version via tags. E.g. https://github.com/DanBloomberg/leptonica/tree/v1.68 for web, download via https://codeload.github.com/DanBloomberg/leptonica/zip/refs/tags/v1.68 or with git: `git clone --depth 1 -c advice.detachedHead=false -b "v1.68" https://github.com/DanBloomberg/leptonica.git`

**Comment by PasaOpasen** [comment]
Thank u!
