### ISSUE TITLE
Evaluate library name change for autotools

### ISSUE THREAD

**Issue by DanBloomberg** [DanBloomberg/leptonica#663]
@stweil 
@amitdo 
@zdenop 
@jbreiden

I'm filing this issue (instead of Jeff) because Jeff presently has a 2-factor authentication problem with logging in to github.

For 1.83 I changed the autotools library name from liblept to libleptonica, so that it would be the same as with cmake.
This had been urged for several years.

We are opening this issue to decide if we should go ahead with the name change or revert to liblept.

Jeff has been the debian package maintainer for leptonica, as well as other libraries.
He looked at the direct dependency  list of Leptonica.  It has four different groups:

```
liblept5
  **Reverse Depends: ccextractor (0.94+ds1-1+b1)**
  **Reverse Depends: k2pdfopt (2.54+ds-1)**
  **Reverse Depends: kylin-scanner (1.0.0-1.1+b3)**
  Reverse Depends: leptonica-progs (1.82.0-3+b3)
  Reverse Depends: libleptonica-dev (= 1.82.0-3+b3)
  Reverse Depends: libtesseract5 (>= 5.3.0-2)
  **Reverse Depends: python3-tesserocr (2.5.2-2)**
  Reverse Depends: tesseract-ocr (>= 5.3.0-2)
```

To make the change, Jeff will need to coordinate it with all four of the groups and patch all the packages.
What do you think?

**Comment by jbreiden** [comment]
Let's start with "why was it important to synchronize" and "why did we
synchronize to libleptonica instead of libleft" ? Thanks.

**Comment by amitdo** [comment]
Previous discussions: #253, #598.

**Comment by amitdo** [comment]
Jeff, regarding your 2FA issue, maybe this [doc](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa/recovering-your-account-if-you-lose-your-2fa-credentials) can help you.

**Comment by zdenop** [comment]
Also I would like to point out that there is a change from 1.83 regarding moving internal part to pix_internal.h. So any sw using leptonica has to check version that is available during compilation.

**Comment by DanBloomberg** [comment]
With the interface changes, such as making fields of the structs "internal", we really did need to change the so version number for 1.83 to 6.0.0.   I made changing the library name for autotools to match that of cmake part of the cleanup for 1.83, because the library name should be the same on all platforms and it seemed reasonable to get all the pain (so number plus library name) over together.

**Comment by jbreiden** [comment]
I don't begrudge any of this. What I am is hopelessly behind on everything,
always. I'm starting to doubt that I'm going to be able to get this past
the finish line.

**Comment by zdenop** [comment]
I think also config for pkg-config should be changed: at the moment it is invoked with `pkg-config --cflags lept`
Not sure if there is a possibility to support for some time `lept` and `leptonica`  so developer/user has time to adapt. 
At least cmake installation [offer](https://github.com/DanBloomberg/leptonica/blob/0180cb11e405f766ce1429d6c7fd3acf1eb21f46/CMakeLists.txt#L56) to create [symlink for library](https://github.com/DanBloomberg/leptonica/blob/0180cb11e405f766ce1429d6c7fd3acf1eb21f46/src/CMakeLists.txt#L67-L73) on unix like systems...

**Comment by DanBloomberg** [comment]
The library name has been changed.   Jeff will hopefully be able to work through the dependencies and build a Debian release in time for Ubuntu 24-04.

@zdenop  In view of this, do you still think we need to consider your Mar 21 suggestion?  https://github.com/DanBloomberg/leptonica/issues/663#issuecomment-1478974571

**Comment by zdenop** [comment]
I would leave it as it is for now (AFAIK nobody complains about it and I am not using pkg-config, so I do not feel comfortable to change it)

**Comment by amitdo** [comment]
Debian testing has 1.84.1 with the soname change.

**Comment by amitdo** [comment]
@DanBloomberg,

I think you can close this issue.
