### ISSUE TITLE
RGB order changed when calling pixReadWithHint/pixWrite

### ISSUE THREAD

**Issue by sinall** [DanBloomberg/leptonica#675]
```
auto pix = pixReadWithHint("source.bmp", IFF_BMP);
auto ret = pixWrite("target.bmp", pix, IFF_BMP);
```

The `source.bmp` is captured by ATL CImage on Windows 11.

Testing images are attached.

![image](https://user-images.githubusercontent.com/1246382/223670543-b6600c40-a18c-42eb-89de-2ddc7443421b.png)
[images.zip](https://github.com/DanBloomberg/leptonica/files/10919028/images.zip)

**Comment by DanBloomberg** [comment]
pixReadWithHint() ignores the second arg if the input image format is not jpeg.  So there's no issue there.

I wrote the following test code, run on linux, and there are no issues with component order.  Try it, and let me know the results on Windows.

```
    pix1 = pixRead("source.bmp");
//    pix1 = pixReadWithHint("source.bmp", IFF_BMP);   // ignores 2nd arg
    pixWrite("/tmp/junk1.bmp", pix1, IFF_BMP);
    pixWrite("/tmp/junk1.png", pix1, IFF_PNG);
    pix2 = pixRead("/tmp/junk1.bmp");
    pix3 = pixRead("/tmp/junk1.png");
    pixEqual(pix2, pix1, &same);
    lept_stderr("same: %d\n", same);
    pixEqual(pix3, pix1, &same);
    lept_stderr("same: %d\n", same);
    pixDisplay(pix2, 300, 100);
    pixDisplay(pix3, 500, 100);
    pixWrite("/tmp/junk2.bmp", pix2, IFF_BMP);
    writeImageFileInfo("/tmp/junk1.bmp", stderr, 0);
    writeImageFileInfo("/tmp/junk2.bmp", stderr, 0);
```

**Comment by sinall** [comment]
> pixReadWithHint() ignores the second arg if the input image format is not jpeg. So there's no issue there.
> 
> I wrote the following test code, run on linux, and there are no issues with component order. Try it, and let me know the results on Windows.
> 
> ```
>     pix1 = pixRead("source.bmp");
> //    pix1 = pixReadWithHint("source.bmp", IFF_BMP);   // ignores 2nd arg
>     pixWrite("/tmp/junk1.bmp", pix1, IFF_BMP);
>     pixWrite("/tmp/junk1.png", pix1, IFF_PNG);
>     pix2 = pixRead("/tmp/junk1.bmp");
>     pix3 = pixRead("/tmp/junk1.png");
>     pixEqual(pix2, pix1, &same);
>     lept_stderr("same: %d\n", same);
>     pixEqual(pix3, pix1, &same);
>     lept_stderr("same: %d\n", same);
>     pixDisplay(pix2, 300, 100);
>     pixDisplay(pix3, 500, 100);
>     pixWrite("/tmp/junk2.bmp", pix2, IFF_BMP);
>     writeImageFileInfo("/tmp/junk1.bmp", stderr, 0);
>     writeImageFileInfo("/tmp/junk2.bmp", stderr, 0);
> ```

```
auto pix = pixRead(".\\test\\ths\\captcha-001.bmp");
auto ret = pixWrite("captcha-001.bmp", pix, IFF_BMP);
```

The same as previous, not working!

**Comment by DanBloomberg** [comment]
Please send all output from that test code, both to stderr and files written.

**Comment by DanBloomberg** [comment]
We are unable to find a problem on linux or Windows.
Will leave this open for a while in case @sinall has more information to share.

**Comment by DanBloomberg** [comment]
This problem is fixed on linux and Windows.
