### ISSUE TITLE
Please, help to upgrade leptonica for Capture2Text. 

### ISSUE THREAD

**Issue by Mirdgard** [DanBloomberg/leptonica#688]
Please, help to upgrade leptonica for Capture2Text. 
  Maybe, help me with some hints, how I can do it myself. I'm a noob.   
 Here is a link, that describes a problem -- 
https://sourceforge.net/p/capture2text/tickets/218/

**Comment by DanBloomberg** [comment]
Seems like a nice project, but I can't help you with it.
It appears you've been using leptonica 1.74, which is about 6 years old and not supported.
Suggest you upgrade to 1.83.

**Comment by Mirdgard** [comment]
Thank you for the information, good fellow!

**Comment by amitdo** [comment]
@DanBloomberg,

I think you can close this issue.
