### ISSUE TITLE
Please fix CMake for build Debug on linux

### ISSUE THREAD

**Issue by zappaz00** [DanBloomberg/leptonica#698]
CXX for project : without it check_cxx_compiler_flag undefined and debug version on linux configuring with errors "check_compiler_flag: CXX: needs to be enabled before use." Errors from 277 line of CMakeLists.txt

Way to fix:
![image](https://github.com/DanBloomberg/leptonica/assets/18219766/5ae0b5e5-47d6-42d3-9987-1540b815a06e)

**Comment by zdenop** [comment]
Leptonica is C project, so define it as CXX is misleading...
Can you please provide minimal example case for replicating problem?

**Comment by amitdo** [comment]
#697

!@zdenop,

You remoced `CXX` from the `project` command, but there are still some other `CXX` left.

```
CMAKE_CXX_COMPILER_ID

include(CheckCXXCompilerFlag)

check_cxx_compiler_flag

CMAKE_CXX_FLAGS
```
