### ISSUE TITLE
Build fails under Windows

### ISSUE THREAD

**Issue by Medalha** [DanBloomberg/leptonica#707]
Since some of the last modifications to the code, I am no longer able to build Leptonica under Windows 10 22H2. I am using cmake on the command line with Microsoft Visual Studio 2022. The build fails with the following error message:

-- sw: processing dependencies
CMake Error at C:/Users/Miguel/.sw/storage/etc/sw/static/SWConfig.cmake:148 (message):
  Compiler is not implemented: 'MSVC' or ''
Call Stack (most recent call first):
  CMakeLists.txt:213 (sw_execute)

Can someone please help with this issue? Thank you!

**Comment by Medalha** [comment]
Thank you!

**Comment by Medalha** [comment]
I commented these two lines and the problem persists:

# set(CMAKE_C_STANDARD 17)
# set(CMAKE_C_STANDARD_REQUIRED ON)

On the other end, the simple resetting of this line

  LANGUAGES C CXX

as it was before, enables the build without error.

**Comment by Medalha** [comment]
I don't have enough knowledge on these matters to evaluate this problem properly. All I know is that I used to build Leptonica (with sw) without any issue and suddenly I couldn't do it anymore, with the error I reported in my first message. It happened after the change in the "CMakeLists.txt" file.

**Comment by egorpugin** [comment]
Hi,

Please add CXX language in cmake project command.

**Comment by Medalha** [comment]
> Please add CXX language in cmake project command.

Do you mean the cmake command line? Do you remember the correct syntax? I can search for it, of course.

**Comment by rajeshja** [comment]
Has there been any change @egorpugin ? I'm trying to build leptonica and it's failing with the following errors:

```
[143/150] [pub.egorpugin.primitives.command-0.3.1]/src/command.cpp
Exception in file D:/dev/cppan2/client2/src/sw/builder/command.cpp:840, function execute1: When executing: [pub.egorpugin.primitives.command-0.3.1]/src/command.cpp
C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(142): error C2039: 'contains': is not a member of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(4871): note: see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'
C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): note: see reference to function template instantiation 'auto primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()<const char(&)[6]>(_T1) const' being compiled
        with
        [
            _T1=const char (&)[6]
        ]
C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C3487: 'bool': all return expressions must deduce to the same type: previously it was 'void'
C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(144): error C3487: 'bool': all return expressions must deduce to the same type: previously it was 'void'
C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(144): error C2562: 'primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()': 'void' function returning a value
C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): note: see declaration of 'primitives::Command::setProgram::<lambda_1>::()::<lambda_1>::operator ()'
C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C2296: '||': illegal, left operand has type 'void'
C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp(147): error C2297: '||': illegal, right operand has type 'void'
command failed: exit code = 2
Total errors: 1
```

I've tried changing `LANGUAGES C` to `LANGUAGES C CXX` and also tried adding the following:
```
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
but it seems to make no difference.

**Comment by egorpugin** [comment]
Hi,

You need the latest Visual Studio if you are building with SW tool.

**Comment by rajeshja** [comment]
Looks like the dependency with the error uses C++23, for which you need VS 2022.
Some changes I found in other forums:
1. Edit line 142 in `C:/Users/xxx/.sw/storage/pkg/9d/a6/8d0d/src/sdir/src/command/src/command.cpp` (look in the error for the exact location) and change it to `return s.find("4nt.exe") != std::string::npos;`
2. In `leptonica/CMakeLists.txt`, change the line `LANGUAGES C` to `LANGUAGES C CXX`
3. I'm not sure if this is strictly necessary, so if the above two don't work, additionally add the following lines:
```
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
after `set(CMAKE_C_STANDARD_REQUIRED ON)`

Once command.cpp is compiled, you can remove all these changes.

**Comment by Medalha** [comment]
When this issue first appeared, I was already using VS 2022.

 

The mere modification of leptonica/CMakeLists.txt from LANGUAGES C to LANGUAGES C CXX solved the problem.

 

The problem suddenly disappeared, even with LANGUAGES C only, I don’t know if due to subsequent updates of VS 2022 or due to changes in leptonica.

 

Anyway, there is no issue anymore. Thank you.

**Comment by rajeshja** [comment]
Once the dependency is compiled, the original code works. The above changes I have listed allow the code to be built with VS 2019.

**Comment by DanBloomberg** [comment]
@egorpugin @zdenop 

This looks to me like a documentation/maintenance issue worth fixing, because it is claimed to affect users who are building with versions of VS before 2022.

**Comment by zdenop** [comment]
@DanBloomberg : this is sw issue. There is not problem to build leptonica with VS2019 (and cmake without sw [-DSW_BUILD=OFF])

**Comment by DanBloomberg** [comment]
Thanks.  Is this documented, or if not, should it be?

**Comment by zdenop** [comment]
at least at https://github.com/DanBloomberg/leptonica/blob/master/.github/workflows/cmake-win64.yml ;-)

**Comment by zdenop** [comment]
I wrote some instructions to wiki ( https://github.com/DanBloomberg/leptonica/wiki) - feel free to improve it (especially grammar ;- ) )

**Comment by DanBloomberg** [comment]
Thank you!  I have modified it slightly, suggesting that one should load png, lz, jpeg and tiff libraries.
The other 3 image I/O libraries are not as important.

There are two other optional dependencies, which are not image I/O:
* gnuplot   (for plotting data)
* poppler   (for rendering pdf files as images)

I am in the process of putting code that uses poppler programs pdftoppm and pdfimages into the library, in a new file ```renderpdf.c```   (not yet added).
Right now, the code that uses them is only in several programs; e.g., cleanpdf, croppdf, compresspdf.

We should at some point include these two optional dependencies in the wiki.  You can see the information about gnuplot in gplot.c and about poppler in prog/cleanpdf.c, line 122 ff.

**Comment by DanBloomberg** [comment]
Yes, you're right.  gnuplot and the poppler programs are not dependencies of the library, and are not linked.

They're just programs that can be called, so best to leave them out of this BUILD wiki.

**Comment by DanBloomberg** [comment]
@zdenop 
Is this issue resolved?

**Comment by zdenop** [comment]
IMO yes

**Comment by Medalha** [comment]
I never met the issue  again. Than you.
