### ISSUE TITLE
Leptonica 1.84 release schedule

### ISSUE THREAD

**Issue by amitdo** [DanBloomberg/leptonica#721]
https://github.com/DanBloomberg/leptonica/issues/663#issuecomment-1789587445

>Jeff will hopefully be able to work through the dependencies and build a Debian release in time for Ubuntu 24-04.

Dan, do you plan to release 1.84 soon?

**Comment by DanBloomberg** [comment]
I would like to do it this month (November).
Do you have any concerns or suggestions?

**Comment by amitdo** [comment]
>Do you have any concerns or suggestions?

No. I just wanted to know what's your plan.

**Comment by DanBloomberg** [comment]
Thanks  :-)

I was just thinking about it today.  I'll try to do it tomorrow.

**Comment by DanBloomberg** [comment]
Thanks  :-)
Sigh.  A bunch of stuff came up.  New plan: 1.84.0 this weekend!

**Comment by DanBloomberg** [comment]
Finally done.  1.84.0 is released

**Comment by DanBloomberg** [comment]
had to delete it  (screwed up)

**Comment by DanBloomberg** [comment]
should be ok now

**Comment by stweil** [comment]
The GitHub release is still missing. Should I create it based on the tagged release?

**Comment by DanBloomberg** [comment]
I had to delete it again.  I forgot to commit some documentation changes (to README.html, version-notes.html) when I did the initial release.

So I committed them.  But when I tried to release with the same tag 1.84.0, it keeps using the old source from before the last commit.  Do I need to use a different tag, like 1.84.1?

**Comment by stweil** [comment]
Either tag 1.84.1, or delete the existing 1.84.0 and create a new 1.84.0 based on the latest commit.

**Comment by DanBloomberg** [comment]
how to delete the 1.84.0 tag?

**Comment by DanBloomberg** [comment]
ok, I figured it out  :-)

**Comment by DanBloomberg** [comment]
finally, I think 1.84.0 is now correct

**Comment by stweil** [comment]
Yes, it looks good. Merry Christmas!

**Comment by DanBloomberg** [comment]
And Merry Christmas and relaxing holidays to you.

**Comment by DanBloomberg** [comment]
Well, this is inconvenient.  Look at the win64-cmake failure in jp2kio.c:
     :\a\leptonica\leptonica\src\jp2kio.c(938,5): error C2198: 'opj_stream_set_user_data': too few arguments for call [D:\a\leptonica\leptonica\build\src\leptonica.vcxproj]

Can we get rid of that compiler conditional from years back and always use the 3 arg call to opj_stream_set_user_data()   ?

**Comment by DanBloomberg** [comment]
@stweil 
That conditional seems like a dangerous hack, anyway.  And I think the 2 arg version was changed to a 3 arg version at least 6 years ago, maybe more.

**Comment by stweil** [comment]
Yes, I also think it's time to remove that old code. But that's not urgent and can even wait until next year. :-)

**Comment by DanBloomberg** [comment]
Good to know.   It is rather funny that this just happened for the first time on the release master.

**Comment by amitdo** [comment]
Thanks Dan!

**Comment by amitdo** [comment]
>Jeff will hopefully be able to work through the dependencies and build a Debian release in time for Ubuntu 24-04.

CC: @jbreiden

**Comment by amitdo** [comment]
https://www.omgubuntu.co.uk/2023/10/ubuntu-24-04-release-date-set-for-april-25-2024

**Comment by amitdo** [comment]
>I had to delete it again. I forgot to commit some documentation changes (to README.html, version-notes.html) when I did the initial release.

Many projects document the release process including the files that need to be updated.

**Comment by DanBloomberg** [comment]
I haven't done it, but it seems like a good idea to list those files, and I'll do it in version-notes.html for the next release.

**Comment by stweil** [comment]
> Good to know. It is rather funny that this just happened for the first time on the release master.

That was simply bad luck. The old code always failed with OpenJPEG versions x.y.0 because checking for `OPJ_VERSION_MINOR == 0` always had been wrong (it should have checked the major version, too). So as soon as the build environment updated to OpenJPEG 2.5.0, it failed again (like it might have done for 2.1.0, 2.2.0, 2.3.0 and 2.4.0 in the past). It's good that this is fixed now.

**Comment by amitdo** [comment]
Right now, I don't see any progress going on in Debian:


https://tracker.debian.org/pkg/leptonlib

So unless things  change within the next 3 weeks, Ubuntu 24.04 will stay with Leptonica 1.82.

**Comment by DanBloomberg** [comment]
I have discussed this with Jeff, and due to a confluence of obligations over the next few months, he will not have time to make a new Debian release of leptonica.

I don't think it's a big deal, and he will do the upgrade if/when things get sufficiently less hectic.
