### ISSUE TITLE
pixRead() can't read png images

### ISSUE THREAD

**Issue by lazulkia** [DanBloomberg/leptonica#742]
I have been using leptonica1831.dll in my scripts.
Today I downloaded the latest dll generated by actions
https://github.com/DanBloomberg/leptonica/actions/runs/8591084071

I found that it can read jpg's normally but not png's, either pixRead() pixReadMem() pixReadMemPng().
Of course leptonica1831.dll can read png images normally.

May I ask what is causing this?

**Comment by DanBloomberg** [comment]
I have no idea.
Please send a complete log of your build, as well as the output to stderr of your runtime failures.

**Comment by zdenop** [comment]
Without detailed description & code (step by step to reproduce problem) nobody can tell you why your process fails.

**Comment by lazulkia** [comment]
Sorry, I'm a layman in programming, I just called it in a script and can't provide any more information.

If anyone wishes to reproduce it, they can test it with AutoHotkey-V2:

```
	DllCall("SetDllDirectoryW", "Str", "C:\Users\Administrator\Downloads\leptonica-1.84.1-45-g96ad9217-VS2019_win64\bin")
	DllCall("LoadLibraryW", "Str", "leptonica-1.84.1.dll", "Ptr")

	MsgBox hPix := DllCall("leptonica-1.84.1.dll\pixRead", "astr",  "D:\1.png"	, "Ptr")
```

**Comment by zdenop** [comment]
First of all Github Action (GA) artifacts MUST NOT to be used for any other reason than analyzing GA!
Next you should use (any) library properly e.g. to see output  messages. So you could see would see this: `Error in pixReadStreamPng: function not present`.
Which leads to log: https://github.com/DanBloomberg/leptonica/actions/runs/8591084071/job/23539423610 where is clear that png was not compiled (=>linked to leptonica).
GA should be fixed now.

**Comment by lazulkia** [comment]
Thank you. I didn't find the released version of leptonica.dll in this library, does that mean I have to compile it myself, which is very difficult for me.
