### ISSUE TITLE
Leptonica_FOUND not being set in exported cmake config

### ISSUE THREAD

**Issue by dr-matt** [DanBloomberg/leptonica#755]
I'm trying to build tesseract, which depends on leptonica. I built leptonica successfully via cmake, but when I try to build tesseract, cmake emits the following complaint and can't proceed:

```
CMake Error at CMakeLists.txt:8 (find_package):
  Found package configuration file:

    /tmp/leptonica/lib/cmake/leptonica/LeptonicaConfig.cmake

  but it set Leptonica_FOUND to FALSE so package "Leptonica" is considered to
  be NOT FOUND.
```

Note that this is not tesseract-specific. If I create a minimal cmake project with the line:
```cmake
find_package(Leptonica REQUIRED)
```
it fails in the same way.

From what I can tell, this is because `Leptonica_FOUND` is not explicitly set to `TRUE` or `FALSE` in leptonica's generated cmake configs. A workaround/fix is to simply add the following line at the end of `cmake/templates/LeptonicaConfig.cmake.in`:

```cmake
set(Leptonica_FOUND TRUE)
```

After doing so, tesseract is able to successfully find leptonica and all is well.

**Comment by zdenop** [comment]
Please provide information about OS and exact commands you use to build and install leptonica and tesseract. 

We run GA for cmake builds and they are working for windows, linux(ubuntu) and mac:
* https://github.com/tesseract-ocr/tesseract/actions/workflows/cmake-win64.yml
* https://github.com/tesseract-ocr/tesseract/actions/runs/11354377901

(MacOS macos-12-clang-14-cmake build fails for some reason at baseapi test, but rest macos build are ok)

**Comment by zdenop** [comment]
AFAIR `Leptonica_DIR` is the tesseract relic from a time when leptonica did not create files needed for `find_package`. 

Can you please try to use the standard cmake setting  `-DCMAKE_PREFIX_PATH=/tmp`?

**Comment by dr-matt** [comment]
It may be moot, as the error isn't reproducible if everything is done from a clean install. Closing this issue, thanks for the review.
