### ISSUE TITLE
VS2010 build issues (with patch)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DanBloomberg/leptonica#91]
```
I tried to build leptonica in Visulac studio 2010 based on VS2008 solution from 
leptonica 1.68.
I was quite successful, but I needed to patch a code a little bit. See 
attachment.


```

Original issue reported on code.google.com by `zde...@gmail.com` on 27 Jan 2014 at 7:11

Attachments:
* [leptonica-1.70_VS.patch](https://storage.googleapis.com/google-code-attachments/leptonica/issue-91/comment-0/leptonica-1.70_VS.patch)

**Comment by egorpugin** [comment]
Use cmake for generating VS projects and building windows binaries.
